### ISSUE TITLE
Nonlinear patterns do not work in java backend

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1]
Consider the following definition:

module TEST

syntax Foo ::= foo(Int, Int)

rule foo(I, I) => .

endmodule

When you kompile this definition and run:

krun -cPGM="foo(5, 6)"

it should not perform any rewrites. However, it rewrites to .K.

**Comment by radumereuta** [comment]
Can you explain why it shouldn't?

From my view, it should. And the current behavior is also the correct one.

**Comment by traiansf** [comment]
Radu, Dwight is right.  the rule is constrained to check that the arguments are equal before applying by the fact that both arguments are 'I'.

**Comment by grosu** [comment]
Why is this correct, Radu?  The rule has the same I in both of foo's
arguments, so it should not match foo(5,6).

**Comment by radumereuta** [comment]
Ah, right... I missed that.
