### ISSUE TITLE
Unification failed in Java backend because the sorts are too general

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#100]
For test generation purpose, I would like to unify a variable B:BExp with the LHS of the heating rule associated with the && operation, which looks like the following in the Java backend:
rule <generatedTop><T><k>'_&&_(__var__169:KItem,, __var__172:KItem) ~>
__var__171:K</k>__var__170:Bag</T></generatedTop> =>
<generatedTop><T><k>__var__169:KItem ~> (# '\_&&_(HOLE,,
__var__172:KItem))(.KList) ~>
__var__171:K</k>__var__170:Bag</T></generatedTop> when
['_=/=K_(isKResult(__var__169:KItem),, Bool(#"true"))]

However, I was not able to do that because the the KApp '_&&_(__var__169:KItem,, __var__172:KItem) has sort KItem rather than BExp. For test generation, I would always like to have the most concrete sort.

**Comment by yilongli** [comment]
Now there is a option --concrete-sort to kompile which generates the concrete sorts in heating/cooling rules. Therefore, I am closing this issue.

**Comment by grosu** [comment]
In case you have not done it already, please make sure you add the info about this option in "kompile --X".

**Comment by yilongli** [comment]
It has been done and the nice thing is that the current style of adding new option will force you to add description info. I just improved the info a bit and I will push the changes later.
