### ISSUE TITLE
[Java backend] name of the sort is effecting subsort calculations (and some other problems in subsort calculations)

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#1011]
Here's a demonstration:

```
➜  issue696 git:(master) ✗ cat test.k
module TEST
  syntax Sort ::= Int | Bool
  syntax KResult ::= Int | Bool
  syntax KItem ::= "test"
  rule test => isKResult(?S:Sort) ~> ?KR:KResult ==K ?S:Sort
endmodule
```

With Java 7:

```
➜  issue696 git:(master) ✗ java -version
java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b11)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)

➜  issue696 git:(master) ✗ rm -rf test-kompiled && kompile test.k --backend java && krun empty
<k>
    isKResult ( _33:Sort ) ~> _36:KResult ==K _33
</k>
```

With Java 8:

```
➜  issue696 git:(master) ✗ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

➜  issue696 git:(master) ✗ rm -rf test-kompiled && kompile test.k --backend java && krun empty
<k>
    true ~> _35:KResult ==K _36:Sort
</k>
```

The problem is with subsort calculations. `org.kframework.backend.java.util.Subsorts` is generating different subsorting graphs when I run it using Java 7 and Java 8.

Here's what it's generating when run with Java 7:

```
this.sorts:
[Bag, Bool, MInt, TCPError, #Bot, KResult, K, #Float, TCPAnswer, #String, #Int, Set, Int, List, #Bool, Float, Sort, Nat, KList, Map, Char, KItem, Stream, String, KLabel, BagItem, Id]

ordinal of KResult: 4
ordinal of Sort: 27

subsort graph:
[[false,false,false,false,true,false,false,true,true,true,true,true,true,true,true,true,false,false,true,false,false,true,true,true,true,true,true,true,true,true,true],[true,false,false,false,true,false,false,true,true,true,true,true,true,true,true,true,false,false,true,false,false,true,true,true,true,true,true,true,true,true,true],[true,true,false,false,true,false,false,true,true,true,true,true,true,true,true,true,false,false,true,false,false,true,true,true,true,true,true,true,true,true,true],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false],[false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]]
```

`subsort[KResult.ordinal][Sort.ordinal]` is false.

Now, with Java 8:

```
this.sorts:
[Nat, Set, MInt, K, String, KList, Int, Bool, Char, Sort, List, Stream, TCPAnswer, #Int, #String, #Bool, Bag, KResult, TCPError, KLabel, Float, BagItem, #Bot, Id, KItem, Map, #Float]

ordinal of KResult: 4
ordinal of Sort: 22

subsort:
[[false,false,false,false,true,false,false,true,true,true,true,true,true,true,true,true,false,false,true,false,false,true,true,true,true,true,true,true,true,true,true],[true,false,false,false,true,false,false,true,true,true,true,true,true,true,true,true,false,false,true,false,false,true,true,true,true,true,true,true,true,true,true],[true,true,false,false,true,false,false,true,true,true,true,true,true,true,true,true,false,false,true,false,false,true,true,true,true,true,true,true,true,true,true],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,false],[false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]]
```

`subsort[KResult.ordinal][Sort.ordinal]` is true.

Why I think that name of the sort is effecting subsort calculations? Because when I replace `Sort` with `MySort`, both versions work same.

```
➜  issue696 git:(master) ✗ cat test.k 
module TEST
  syntax MySort ::= Int | Bool
  syntax KResult ::= Int | Bool
  syntax KItem ::= "test"
  rule test => isKResult(?S:MySort) ~> ?KR:KResult ==K ?S:MySort
endmodule
```

Java 8:

```
➜  issue696 git:(master) ✗ rm -rf test-kompiled && kompile test.k --backend java && krun empty
<k>
    isKResult ( _35:MySort ) ~> _37:KResult ==K _35
</k>
```

Java 7:

```
➜  issue696 git:(master) ✗ rm -rf test-kompiled && kompile test.k --backend java && krun empty
<k>
    isKResult ( _33:MySort ) ~> _36:KResult ==K _33
</k>
```

---

Another thing that concerns me about subsort calculations is that even if we have 27 sorts, subsort graph is having 31 nodes. There may be other bugs too.

---

I already spent huge amount of time trying to figure all this and I'm hoping to fix this myself. @yilongli do you have any ideas about any of these?

**Comment by osa1** [comment]
Update: Another weird thing about subsorting calculations is that when run with Java 7, `subsort[27][4]` return true(which means `KResult` is subsort of `Sort`), while in Java 8 `subsort[22][4]` is false.

In summary:

Java 7: KResult < Sort
Java 8: Sort < KResult

I believe this is not a simple ordering preservation problem.(e.g. no linked data structure for fixed iteration order will solve this, we can only defer it)

**Comment by yilongli** [comment]
Thank you for tracking this down. `org.kframework.backend.java.util.Subsorts` is not the cause of the problem because it merely uses the subsorting information already computed during kompilation. Although we have only 27 subsorts in this definition, there are some other pre-defined sorts in `org.kframework.backend.java.kil.Sort` which makes the maximal ordinal number larger than 27. Since the ordinal number given to sort depends on when that `Sort` is cached, it's expected that the ord number will likely change between Java 7 and 8.

The root cause should be the pass `org.kframework.compile.transformers.CompleteSortLatice` which completes the subsorting relation. You have to somehow complete the subsorting relation that `KResult < Sort` and `Sort < KResult`.

**Comment by osa1** [comment]
@yilongli Are you sure I need to have `Sort < KResult` and `KResult < Sort`? In that case how would sort coercions work?

I found a suspicious line in sort lattice generator that prevents lattice generator to make `S1 < S2` if `S2 < S1` already. I'm not sure why it's doing that, but I think it's problematic because it makes lattice generation non-deterministic. e.g. what happens if, because of iteration order, it subsorts `S1` to `S2` first? Then it produces a different lattice.

On the other hand, if we make `S1 < S2` and `S2 < S1` then it's not a lattice anymore. Indeed, I'm getting this exception if I do that:

```
[Error] Critical: Circularity detected in subsorts: Sort < KResult < Sort
```

This is given by `computeSubsortTransitiveClosure`.

So I'm a bit confused here. I think lattice generator is wrong, but I don't know how to fix it. Basically, I need an answer to this:

Let's say I have:

```
syntax A ::= X | Y
syntax B ::= X | Y
```

If all we have in our lattice is subsorting relation, then we shouldn't generate anything in this example. Otherwise we'll have to have cycles.

Or maybe we can have `A = B` and then replace both `A` and `B` with some fresh `C` or something like that.

@andreistefanescu  @yilongli @grosu Any ideas?

**Comment by yilongli** [comment]
Yes, you are right. We can not simply add `Sort < KResult` and `KResult < Sort` right now. You have to deal with equivalent sort. There is a TODO item in `CompleteSortLatice` left by @andreistefanescu saying the same thing.

**Comment by osa1** [comment]
OK. I have this in mind:

`CompleteSortLattice` will work as before, except when it finds an equality between `A` and `B`, instead of adding `A < B` or `B < A`, I'll maintain a list of "equivalence classes" and add elements to right set in that list.

I'll annotate every `Sort` with an "equivalence class" field (or if we don't want to modify `Sort`, which we probably don't, add a map from `Sort` to `EqClass`). Algorithm then works as before, but when it finds two equal sorts:
- If both sorts have an equivalence class, it adds all elements in second one to first one(while updating moved sorts' fields).
- If only one of them has a class, then adds the other one to that.
- If none of them has a class, then creates a new class and adds both.

This shouldn't add anything to the complexity, since we already have a loop that detects equal sorts.

Now, once the algorithm is done, we'll have a list of equal sorts, and an incomplete lattice. Then I'll do something like this:

``` java
for (Set<Sort> eqSet : eqSets) {
  Iterator<Sort> iter = eqSet.iterator();
  Sort first = iter.next(); // we know every set has at least two elements
  do {
    Sort s = iter.next();
    for (Sort supersort : s.getSuperSorts()) {
      addSubsort(supersort, first);
    }
    // no need to do same thing for subsorts of s, beucase RHS of productions
    // are already the same, so they have same subsorts

    // remove s from context
  } while (iter.hasNext());
}
```

I also need to prevent adding same relation multiple times. e.g. we don't want to add `A < B` a more than once. (even if that doesn't effect correctness)

@yilongli  @andreistefanescu  do you see any problems with that? Any ideas about what should I do with productions? Can I just delete productions of deleted sorts?

**Comment by yilongli** [comment]
Your algorithm for maintaining equivalence classes is probably correct though I haven't proved it. However, I think it's a bit over-complicated. You don't have to compute the equivalence classes on-the-fly inside the existing nested loop. Just add another loop somewhere which iterates over the sorts that have only subsorting productions and put these sorts to a `Multimap<Set<Sort>, Sort>`, where the key is the set of subsorting productions. Once you compute the equivalent classes, just add another field in `Context` to store them and revise the `isSubsortedEq` accordingly. Removing sorts from context only makes the problem unnecessarily complex.

**Comment by osa1** [comment]
It's same either way. I'll either make this complex computation in `CompleteSortLattice` and leave all other code unchanged, or I don't do this computation, but handle equalities in other places. I prefer handling this in `CompleteSortLattice` and give rest of the program simplified and complete lattice to work on without extra considerations. As an example, if I do it your way I need to modify `transitiveClosure()` too. Since `Context` is used in all parts of the framework(including krun parts), I can't know which parts should I update. (my IDE finds 788 usages) I prefer not adding anything to `Context`, it's already complex enough to manage with all the state it holds.

**Comment by yilongli** [comment]
What I am saying is that you do the computation in `CompleteSortLattice` but you do it the simple way. On the other hand, do not remove any sorts from context because you will end up with modifying a lot of productions, predicates, configurations, search patterns, etc. Whether you add a new field in context to keep track of the equivalence classes and modify the `isSubsorted` method or modify the `Poset` class directly is just a matter of the implementation details.

**Comment by osa1** [comment]
I'm convinced that removing sorts is not a good way. The problem is that some of the sorts are hard-coded and if I remove those sorts, things are getting wrong again. Let's say the algorithm found that those sorts are equal: `KResult, A, B`. Now if it decides to keep `A` and remove others, we're having problems because `KResult` is hard-coded in some places so it's added again later (even if it's not added again, things go wrong, for example, heating/cooling rules are specifically looking for `KResult`s, we need to keep `isKResult` working even after removing `KResult`). We don't have list of "built-in" sorts so there's no way to change algorithm so that if there's a built-in sort in the set, it keeps it and removes others.

Also, I think it's possible for two built-in sorts to turn out to be equal. In that case it's not possible to remove any of them.

I still think that the right way of doing this is to implement `CompleteSortLattice` so that it just returns a simplified `Context` and `Module` without equalities or duplicate productions and leave rest of the code unchanged. But apparently this is not easily possible.

All other ways will leave lots of redundant/duplicate productions(and probably some other `ModuleItem`s)

@andreistefanescu  did you have anything in mind when you left this as TODO?

**Comment by andreistefanescu** [comment]
I think modifying the `Poset` in `Context` to keep track of equivalent sorts is not that complicated. A `HashSet` to rename each sort to the equivalent one should be enough.

**Comment by andreis** [comment]
Off-topic, but this thread just popped up in my notification feed. Must be a Github bug due to mine and @andreistefanescu's handles being so similar.
