### ISSUE TITLE
kframework.org website: "download" should be "Download"

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1033]
Talking about the left menu.

**Comment by pdaian** [comment]
Seems I already fixed this on August 25th: http://www.kframework.org/index.php?title=MediaWiki:Sidebar&action=history

This is the weirdest issue I've ever seen.  Whenever I put the link as "Download" it forces the d to lowercase, but if I use "Downloads" it shows up just fine as uppercase.  Can I put "Downloads" for now or should I keep investigating the bug?

**Comment by pdaian** [comment]
I've changed it to downloads, see if you like the way it looks.  If so close the issue, otherwise say no and I will keep investigating.

**Comment by grosu** [comment]
Strange, indeed.  Actually, Downloads is even better, because we have more things to be downloaded there.

Thanks!
Grigore

**Comment by pdaian** [comment]
Sounds good, I actually think it looks better also.  Closing, thanks!
