### ISSUE TITLE
Difference between Java backend and Maude backend in terms of Map

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#1042]
If I have the following definition:

```
module TEST

     syntax KItem ::= "start" | abc(String) | abd(String) | rem(String) | rem2(String)

     configuration <k> $PGM:K </k>
        <state> .Map </state>

     rule start => abc("f")

     rule <k>abc(S:String) => abd(S) ...</k>
    <state>... .Map => S |-> 1 ...</state>

     rule <k>abd(S:String) => rem(S) ...</k>
    <state>... .Map => S |-> 1 ...</state>

     rule <k>rem(S:String) => rem2(S) ...</k>
    <state>... S |-> _ => .Map </state>

     rule <k>rem2(S:String) => .K ...</k>
    <state>... S |-> _ => .Map </state>

endmodule
```

When i run the program "start" in Java backend, it will show the result of:

```
<k>
    rem2 ( "f" )
</k>
<state>
    .Map
</state>

```

However, if I run the program with Maude backend, it will show:

```
<k>
    .K
</k>
<state>
    .Map
</state>

```

The following of the definition can show the detail of the map execution in Maude:

```
module TEST

     syntax KItem ::= "start" | abc(String) | abd(String) | rem(String) | rem2(String)
            | addValue(String)

     configuration <k> $PGM:K </k>
        <state> .Map </state>

     rule start => abc("f")

     rule <k>abc(S:String) => abd(S) ...</k>
    <state>... .Map => S |-> 1 ...</state>

     rule <k>abd(S:String) => addValue(S) ...</k>
    <state>... .Map => S |-> 1 ...</state>

     rule <k>addValue(S) => .K ...</k>
    <state>... S |-> (1 => 2) ...</state>

     rule <k>rem(S:String) => rem2(S) ...</k>
    <state>... S |-> _ => .Map </state>

     rule <k>rem2(S:String) => .K ...</k>
    <state>... S |-> _ => .Map </state>

endmodule
```

Output is:

```
<k>
    .K
</k>
<state>
    "f" |-> 2
</state>

```

```
module TEST

     syntax KItem ::= "start" | abc(String) | abd(String) | rem(String) | rem2(String)
            | addValue(String)

     configuration <k> $PGM:K </k>
        <state> .Map </state>

     rule start => abc("f")

     rule <k>abc(S:String) => abd(S) ...</k>
    <state>... .Map => S |-> 1 ...</state>

     rule <k>abd(S:String) => addValue(S) ...</k>
    <state>... .Map => S |-> 1 ...</state>

     rule <k>addValue(S) => rem(S) ...</k>
    <state>... S |-> (1 => 2) ...</state>

     rule <k>rem(S:String) => .K ...</k>
    <state>... S |-> _ => .Map </state>

     rule <k>rem2(S:String) => .K ...</k>
    <state>... S |-> _ => .Map </state>

endmodule
```

Output is:

```
<k>
    .K
</k>
<state>
    "f" |-> 2
</state>

```

**Comment by yilongli** [comment]
This is actually a bug in the Maude backend as the map in Maude is modeled as a bag rather than a real map. So the following two rules

```
     rule <k>abc(S:String) => abd(S) ...</k>
    <state>... .Map => S |-> 1 ...</state>

     rule <k>abd(S:String) => rem(S) ...</k>
    <state>... .Map => S |-> 1 ...</state>
```

will result in two identical bindings`S |-> 1` in the Maude backend, which is incorrect.

**Comment by liyili2** [comment]
I am asking for solution not just a explanation of what is the responsibility here.

**Comment by liyili2** [comment]
Currently, the map in c semantics depends on this bug.

**Comment by grosu** [comment]
I think @yilongli 's answer was quite clear.  The definition is WRONG.  And so is the definition of C then, and therefore needs to be changed.  Your definition is equivalent to having a rule

```
rule true => false
```

If the semantics of C depended on such a rule, then it would be wrong.  So with the map.

You should be thankful to @yilongli that he found the problem for you in your C semantics,

**Comment by liyili2** [comment]
First, this problem is found by me and I didn't design the C semantics.

Second, this is not a bug originally, because it is very formalized in Maude backend. If you add n times of  an entry, then you can remove n times of the same entry, so I believe that the original guy who implements the Maude backend is intended to do that. Why I cannot ask what is the reason behind this and what they want to achieve because of the feature? Answering this question will help me to fix the problem in C semantics instead of wasting me two or three days to do it by myself. 

Third, suppose you are testing the C semantics of Maude version and find a problem in the C semantics and then you ask me, can I say that "this is a bug in C semantics, done."??? If you think it is OK. I am fine with that and next time I will only expect that I will get either a bug is being fixed here or someone tells me that this is a external bug. However, I will say that you will expect that the job of C semantics will be slower.

Liyi Li

**Comment by yilongli** [comment]
Gee... If you understand the problem, then say so in the problem description. Don't just tag it as a bug of the Java backend and assign it to me. I just spent 10mins reading your issue report and tried to debug the Java backend.

**Comment by grosu** [comment]
1) You found a bug in the C semantics.  Is this the first one?

2) It IS a BUG.  Period.  Do you understand the analogy with `rule true => false` ?  Actually, it is not even an analogy.  It is exactly the same thing.  If you take the C definition and mechanically translate it to Coq, you would be able to prove `true = false` with it.  Doesn't that bother you?  The problem with the C semantics is that it is wrong and needs to be fixed.  Now you understand the problem.  I don't understand what else you expected from @yilongli or anybody else.  It is like saying "I have an axiom true = false, and for some reason I can now prove that 3 = 5".

3) No, you cannot.  Because the C semantics is your project and it gets to be done properly.  Again, the C semantics is buggy, probably it has many many other bugs that need to be fixed.  When we'll have the Coq backend, we will discover tons of other errors.  Be prepared for that.

**Comment by liyili2** [comment]
The only probability to prove `true = false` by this is to have two variables t and f, and assign t to true and f to false. Then, we store the t in a map and store another t with the value f. At this point, the value of t will be equal to the value of f. I didn't think of the relation between this and `true = false` at that time.

I am seeing this as a feature is that I am suggesting that we can fix the problem in another way in order to have more powerful map. For example, when you put your key in a map, if there is a same key in the map, we can rename the variable and all its occurrence in its scope; then, we can allow the user to use our map two variables with same name appeared in two different places.

**Comment by andreistefanescu** [comment]
I don't know what the C semantics is doing in this case, but you can have a counter for how many times each value is in the map. You can have 2 rules for insert, one that created the entry with count 0, and another one that increases the counter.

**Comment by grosu** [comment]
Right, but that would be a different data-structure, a _multi-map_, which is effectively a binary relation (like a data-base).  I have no problem with adding such a structure to our builtins in the long run, but my feeling is that that was a bug in the C semantics.  Whoever introduced it probably expected to work differently, the proof being that you got different results with different engines.

Grigore

**Comment by liyili2** [comment]
OK. I satisfy with the explanation and Andrei's solution here. If @yilongli originally suggests that "this is a bug in Maude because you can prove true = false by this", it will take me shorter time to find the answer. Because this is a huge change in C semantics, if this were not a bug, it would be easier for me to deal with this. Anyway, sorry about wasting everybody's time and haven't thinking this very carefully in the first place. @yilongli, if you feel offensive about my message, sorry about that.

**Comment by grosu** [comment]
Before you make such a big change, it may be a good idea to talk to Chris about it, just to make sure that you are both on a same page with this.

Grigore

**Comment by chathhorn** [comment]
Yeah, we're talking. I don't think it'll be that big of a change. I was
aware of this behavior but I don't think the semantics should ever
intentionally rely on it. So yeah, this is likely a bug in the semantics.
