### ISSUE TITLE
kernelc program doesn't terminate when run with Java backend + proving

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#1046]
Steps to reproduce:
- Clone current master(61b45269b11257ec2cd193d868dc79f406ddbde8) and install as usual.
- Go to `k-distribution/samples/kernelc`
- Run `kompile --backend java kernelc.k`
- Run `krun tests/sorting/merge_sort.c --prove tests/sorting/merge_sort_spec.k --smt_prelude ../../include/z3/sorted_list.smt2` (also happens when `--z3-executable` is used)

What happens is that program runs for more than one hour(haven't waited to see if it will ever terminate), and at ~50 minute it starts printing stack traces. See my email to k-list to see stack traces it prints.

One weird thing is that I can't reproduce this on my laptop. Only happens on rvwork machine with Java 8. (haven't tried with Java 7 on rvwork)

**Comment by dwightguth** [comment]
You can also reproduce this error in @yilongli's branch regarding floating
points, if that is easier.
