### ISSUE TITLE
Weird command line argument parsing behavior

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#1047]
```
➜  ktest-bug-1 git:(ktest-bugfix) ✗ ktest config.xml --skip "" --dry           
[Error] Critical: Invalid value for --backend parameter. Allowed
values:[kompile, krun, pdf]
```

Several things are wrong about this:
- It's perfectly valid, no errors should be given.
- `--backend` is not used at all, but it thinks it's used.
- KTest doesn't even have `--backend` so I'm not sure why it's trying to parse `--backend`.
- `--backend` values are listed wrong. (it should be java, maude etc.)

**Comment by dwightguth** [comment]
Please assign this one to me, I will fix it this afternoon.
