### ISSUE TITLE
krun: output line length differs between linux and windows

### ISSUE THREAD

**Issue by traiansf** [kframework/k-legacy#105]
Apparently, when krun needs to wrap something on multiple lines it behaves differently on linux than on windows.  This is apparently inoffensive, but it breaks ktest for tests which check the configuration.
Example:
in /tests/regression/java-rewrite-engine/visitor

```
kompile --backend java imp
krun --backend java --smt none sum.imp 
```

The output should look like this:
On linux:

```
<k>
    int '_,_(n,, sum) ; (((n = 101 ;) (sum = 1 ;)) (while ( (! (n <= 1)) ) ({
       ((sum = (sum + n) ;) (n = (n + 0) ;)) })))
</k>
```

vs
On Windows:

```
<k>
    int '_,_(n,, sum) ; (((n = 101 ;) (sum = 1 ;)) (while ( (! (n <= 1)) ) (
      { ((sum = (sum + n) ;) (n = (n + 0) ;)) })))
</k>
```

I suspect it might be because on windows one needs two characters to break a line.  Regardless, we should not change behavior depending on that.

Can anybody take a look, please? I assigned Erik because he mention in an earlier issue he is in charge of krun now.

**Comment by ericmikida** [comment]
I'll take a look. The only windows machine I have is running XP though.
