### ISSUE TITLE
Should different backends use different temporary directories?

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#1059]
I'm currently working on improving KTest's parallelism. One problem that I'm currently having is when I run `kompile definition.k` and `kompile definition.k --backend pdf`at the same time, they're having a race, whichever terminates first is removing the `.k` directory and other one is failing.

This is not a PDF backend specific problem though. If Java backend also uses temporary directory then `kompile definition.k` and `kompile definition.k --backend java` should also be a problem.

I'd like to discuss what to do about this. I think one easy way to fix this is to make backends generate temp directories with different names.

We briefly discussed about a filesystem API in #1008 . Maybe we can implement that too. Using the API we can make sure that backends won't be able to read from/write to arbitrary files, they'll be restricted with their temporary directory, which is generated by filesystem API by reading some fields of backend(to decide on a directory name). This will also help cleaning up after backends are done.

Any ideas?

**Comment by radumereuta** [comment]
Well... the parsing is common for all backends, and it would be best if it's stored in the same place for caching reasons.
Maybe we should implement a mutex at the file level...

**Comment by dwightguth** [comment]
Since Grigore wants us to do something about the temp directory in the
first place, here's what I propose you do:
1. make the temp directory an actual temp directory, ie made via
   Files.createTempDirectory
2. If --debug is not passed, do the same thing as before and delete the
   temp directory.
3. If --debug is passed, do not delete the temp directory, but output the
   path to it on the command line.

**Comment by osa1** [comment]
> If --debug is passed, do not delete the temp directory, but output the
> path to it on the command line.

I don't have a better alternative but this part will lead to more verbose ktest output.
