### ISSUE TITLE
incorrect v3.4 tag

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#1067]
The commit tagged with v3.4 does not correspond to the latest stable release. Please fix this, to avoid confusion.

**Comment by dwightguth** [comment]
@traiansf can you take a look?

**Comment by traiansf** [comment]
It seems the released version is one commit (and a merge) ahead.  It was a fix of regex line endings for windows machines done by me and merged by @dwightguth .  Not sure what would be the best way to address this. I guess we should have tagged it as 3.4.1 or something.
On the other hand, there already exists a 3.4.1 tag which I don't even know what is about.

@dwightguth  - Any suggestions?

**Comment by dwightguth** [comment]
I don't really see a better solution than deleting and overwriting the tag.
It's not pretty, but it's the best we can do at this point.

The 3.4.1 tag was created to demarcate the point right before we deleted
stuff that we wanted to be made into external modules.

**Comment by traiansf** [comment]
Ok.  The v3.4 tag now points to the same commit as the released version. I'm closing this.

**Comment by denis-bogdanas** [comment]
Now it's fine, thank you.
Everybody, please run this to update the tags on your local machine: https://answers.atlassian.com/questions/141421/sourcetree-pull-all-tags
