### ISSUE TITLE
orElseBool doesn't work as expected

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#1090]
If I have the following definition:

```
module TEST

    syntax KItem ::= "start" | Int "xx" Int | "end"

    rule start => (1 xx 2) orElseBool true
    rule end => true orElseBool (1 xx 2)

endmodule
```

If I run both programs "start" and "end" the result will be similar to:

```
<k>
    true orElseBool (1 xx 2)
</k>

```

Which is not the expected result. I think the expected result should be true.

**Comment by andreistefanescu** [comment]
Try changing `KItem` to `Bool`, to make sure it's not a sort issue.
