### ISSUE TITLE
Undesirable behavior for DataStructureBuiltins in CopyOnWriteTransformer

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#11]
So in my work on the streams IO stuff, I end up creating the following term to put in the stdin cell in the initial configuration:

MyListItem(#buffer("")) $noIO:MyList MyListItem(#istream(0))

Then I use a CopyOnWriteTransformer to replace $noIO:MyList with .MyList. Of course this all happens after CompileDataStructures so we are working with a ListBuiltin object.

Unfortunately, the behavior of CopyOnWriteTransformer in this case is to put one ListBuiltin object inside the other as a base term, rather than the more reasonable behavior to distribute the elements of the inner ListBuiltin into the outer ListBuiltin. I have not tried it with Maps, Bags, or Sets, but it's possible something similar happens there as well.

This is a problem as you can imagine because then the base terms aren't the empty list and aren't a variable, and so the term is rejected when it is being converted to the java backend kil. I need this to work in order to be able to substitute the configuration parameters into the initial configuration in order to execute programs that use streams.

This is a quite urgent issue. Technically today is my last day and I am under no obligation to finish the diff I am working on for streams at all. However, I would like to use some of my own personal time to do so in the next couple days so that when I leave it will be with everything nice and tidy. But this can only happen if this bug and any others I run into afterwards are resolved immediately. So I am marking this priority_critical.

**Comment by grosu** [comment]
I would like to add that this is indeed very urgent!  Dwight is currently the only one working on krun and, once he leaves, it will take months until somebody can confidently claim proficiency over krun.  Therefore, please give Dwight's needs top priority.  Dwight, if you can also identify, based on the OWNERS file, who is responsible for the bugs, please let us know (so in case that person cannot work on it, we find an alternative).

Thanks,

Grigore

**Comment by dwightguth** [comment]
Yes I spoke to Andrei S and he suggested I assign this to Traian so that's what I did.

As far as knowledge of krun goes, I should reiterate at this point by the way that I am more than happy to continue to answer basic questions about krun code for as long as is needed after I leave. I simply will not do any further programming or debugging once I am done.

**Comment by traiansf** [comment]
I pushed a patch which should do what you want for lists. please let me
know whether there are problems with it.

best whises,
Traian

2013/8/15 dwightguth notifications@github.com
