### ISSUE TITLE
how to connect a definition to various builtin implementations

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#1104]
There are cases when the same definition or some of definitions has/have to be compiled with different implementations of the builtins. I know we discussed this in the past and we let it for a later development stage. I do not know if this is already implemented in the current version. If not, I guess that it can be implemented using the new modular approach. We really need it for the Maude-based symbolic backend and for other architecture-dependent definitions, therefore we will very appreciate any support in this direction.

**Comment by dwightguth** [comment]
Currently the framework has the capability of allowing each individual
backend to specify the file to be autoincluded by every definition, and the
capability to specify a different implementation per backend of each hook.
Is this sufficient for your needs, or are you saying that you need the
ability for the same hook in the same backend to change based on some
compiler flag?

**Comment by dwightguth** [comment]
Closing. Please reopen if you still need some kind of resolution to this.
