### ISSUE TITLE
debugger no longer active?

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#1105]
I didn't use the debugger for a while. I tried it today and it seems it does not longer work:

```
$ kompile bp.k --transition "computational"
Dorels-MacBook-Pro:v0 dlucanu$ krun tests/recp.bp --debug
<T>
    <k>
        .K
    </k>
    <env>
        main |-> 3 s |-> 1 x |-> 2
    </env>
    <genv>
        main |-> 3 s |-> 1 x |-> 2
    </genv>
    <store>
        1 |-> s :: lambda (  , if ( * ) skip ; else { (s (  )) ; x = (! x) ; }
           ) 2 |-> False 3 |-> main :: lambda (  , x = False ; (s (  )) ; 
          Final : skip ; )
    </store>
    <returning>
        false
    </returning>
    <strict>
        .K
    </strict>
</T>
Dorels-MacBook-Pro:v0 dlucanu$
```

**Comment by dwightguth** [comment]
The flag has been moved to --debugger to support the new --debug flag
reserved specifically for developers.

**Comment by grosu** [comment]
Is this also displayed by --help and put a note about in the manual?  I do not see it when I click on the Help button in the kweb interface at :http://www.kframework.org/tool/run/.

Grigore

**Comment by dwightguth** [comment]
It is documented by --help. Since we don't by any means have a complete
manual at this time, it is not documented there, but it will be very easy
to ensure that all the options to krun are documented in the manual once we
finally take the time to make a manual version.
