### ISSUE TITLE
the parser doesn't create the proper list terminator for my specification

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1110]
I wanted to get rid of the `.Exps` in my specification rule:
https://github.com/yilongli/c-semantics/blob/java_rewrite_engine/cil-semantics/tests/verification/sum_spec.k#L11

Without writing the `.Exps`, `tv(unsigned int, I32N:MInt{bitwidth(32)})` remained as a `TypedValue` after the parsing. I expected something like `tv(unsigned int, I32N:MInt{bitwidth(32)}), .Exps` because:
`cil-syntax.k:  syntax FunCall ::= Exp "(" Exps ")"   [klabel('call), strict(2)]`

And since `TypedValue` is not subsorted to `TypedValues` or `Exps`, unification failed and the ml prover got stuck.

A similar case is the following rule:
`cil-exp.k:  rule *tv(T:Type, va_list(tv(_:Type, V:Value))) => tv(downPtr(T), V)`
However, this rule became 
`rule * tv ( T:Type , va_list ( '_,_(tv ( _:Type , V:Value ) , .TypedValues) )  )   => tv ( downPtr ( T:Type )  , V:Value )  [ structural()]`.
Note that there is this `.TypedValues` after `tv(...)`, which is what I would like to have.

@radumereuta @andreistefanescu any idea?

**Comment by radumereuta** [comment]
I can answer this.
The step which tries to add the list terminators work only on TermConses, the classes which have direct access to he production. If you write a rule in the labeled format, I will consider that everything has the sort KItem, and do nothing.

Looking at your examples, I can only see abstract syntax.

**Comment by yilongli** [comment]
Awesome, many thanks! I realized that I had `'tv` in my spec and `tv` in the other rule when I was filing the issue. So I replaced `'tv` with `tv`, failed, and then gave up. Now I convert all abstract syntax to concrete syntax and it works great.
