### ISSUE TITLE
krun --- pretty printing

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#112]
For some reason, the lists are not pretty printed correctly anymore by krun.  For example, here is a snippet of a configuration (from KOOL static) returned by krun:

```
    <class>
        <extends>
            Object
        </extends>
        <private>
            '_,_(x,, .List{","})
        </private>
        <className>
            B
        </className>
        <extendsAll>
            SetItem(Object)
        </extendsAll>
        <ctenv>
            B |-> (void, .List{","}) -> void
            f |-> (void, .List{","}) -> int
            get |-> (void, .List{","}) -> int
            x |-> int
        </ctenv>
    </class>
```

It should be

```
    <class>
        <extends>
            Object
        </extends>
        <private>
            x
        </private>
        <className>
            B
        </className>
        <extendsAll>
            SetItem(Object)
        </extendsAll>
        <ctenv>
            B |-> void -> void
            f |-> void -> int
            get |-> void -> int
            x |-> int
        </ctenv>
    </class>
```

**Comment by ericmikida** [comment]
Can you give more detailed steps to reproduce the bug? ie What program is this output from? I can't seem to reproduce the bug, and after running a bunch of the programs using statically typed KOOL everything seems to work. I pulled all the changes from master immediately before running the tests.

Here is some sample output I get:

Directory: kframework/k/tutorial/2_languages/2_kool/2_typed/2_static
Command: krun ../programs/factorial.kool
Output:

```
<T>
    <out>
        ListItem(#ostream ( 1 ))
        ListItem(#buffer ( "" ))
    </out>
    <classes>
        <class>
            <extends>
                Object
            </extends>
            <className>
                Main
            </className>
            <extendsAll>
                SetItem(Object)
            </extendsAll>
            <ctenv>
                Main |-> void -> void
                f |-> int -> int
            </ctenv>
        </class>
    </classes>
</T>
```

**Comment by grosu** [comment]
Something strange happens ... I do not see the pretty printing problem in kool anymore.  Hm.  But I just noticed it in fun.  See, for example, the output of ktest on tuple-2.fun:

https://github.com/kframework/k/blob/master/tutorial/2_languages/3_fun/1_untyped/1_environment/tests/tuple-2.fun.out
