### ISSUE TITLE
==K and =/=K doesn't work in Java backend

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#1125]
If I have the following definition:

```
module TEST

     syntax KItem ::= "start"

     syntax Type ::= "fun" | "int"

     syntax Bool ::= isFunctionType(Type) [function]

     syntax Bool ::= #isFunction(Type) [function]

     rule #isFunction(fun) => true
     rule isFunctionType(T:Type) => #isFunction(T) ==K true
     rule start => isFunctionType(int)

endmodule
```

If I run the program "start", I will get the final configuration like:

```
<k>
    #isFunction ( int ) ==K true
</k>

```

The ==K and =/=K cannot compare true value with an arbitrary constructor. This problem actually affect every conditional rule in C semantics since Chris tends to define conditional guard in this way.

**Comment by andreistefanescu** [comment]
This is the expected behaviour in the java backend. You left a function undefined. You should either make the function total, possibly by using the [owise].

**Comment by liyili2** [comment]
When does it start to become expected behavior? Before Oct 17, I expect it will work.

**Comment by yilongli** [comment]
This is always the expected behavior. The reason it worked before was due to a long-lasting bug in the Java backend. I fixed it recently.

To be more specific, you may want to say:
`rule #isFunction(_) => false [owise]`

**Comment by grosu** [comment]
On a side, but related note, can you please add a note in the manual-to-be about owise, to make sure we do not forget about it?  I'm assuming it is hacked at this moment, right?  I mean, it is probably not using Cosmin's strategies, right?

Grigore

**Comment by yilongli** [comment]
@grosu yes, if (hack == not using Cosmin's strategies) then yes ;) I will add it to the manual-to-be.

**Comment by chathhorn** [comment]
Does [owise] only work on functions?

**Comment by yilongli** [comment]
@chathhorn for the Java backend, yes.
