### ISSUE TITLE
Both Java backend and Maude backend can't give a error message when the program doesn't exist

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#1126]
If I have the following definition:

```
module TEST

     syntax KItem ::= "start"

endmodule
```

If I don't have the program (let's say the program is a.test), and I try to run the command:

```
krun a.test
```

The output will be similar to execute a program without any output:

```
qangel@qangel-Satellite-S855:~/project/csemantics/bin$ krun a.test
qangel@qangel-Satellite-S855:~/project/csemantics/bin$ 

```

I mean the error message is missing.

**Comment by dwightguth** [comment]
Should be fixed in #1123. Please reopen if that is not the case.
