### ISSUE TITLE
guaranteed NullPointerException in ktest

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#113]
this line https://github.com/kframework/k/blob/master/src/javasources/KTool/src/org/kframework/ktest/tests/Test.java#L462 is guaranteed to throw a `NullPointerException` due to referencing `rootDir` variable.

**Comment by daejunpark** [comment]
@osa1, Could you explain it again? The line number was changed due to my recent commit. Thanks!

**Comment by osa1** [comment]
@daejunpark https://github.com/kframework/k/blob/master/src/javasources/KTool/src/org/kframework/ktest/tests/Test.java#L483 `rootDir` is null but it's used in next line.

**Comment by osa1** [comment]
https://github.com/kframework/k/blob/9ac00fe89116e725f5ea85b1969d7ea51ee63514/src/javasources/KTool/src/org/kframework/ktest/tests/Test.java#L475

**Comment by daejunpark** [comment]
Thanks @osa1. I didn't even notice that such code exists!
Although it has a buggy code, it does not lead to a null pointer exception, because a null pointer is just printed as the string "null".
But I'll make it have a better shape! Thanks again!
