### ISSUE TITLE
ktest --- krun-option : either error or should work for all programs

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#115]
This test works as expected:

```
  <test
      definition="fun-untyped.k"
      programs="../../../programs"
      extension="fun"
      results="." >
      <all-programs>
        <krun-option name="--pattern" value="&lt;k&gt; V:K &lt;/k&gt;" />
      </all-programs>
  </test>
```

but this one ignores all the krun options when executes the programs:

```
  <test
      definition="fun-untyped.k"
      programs="../../../programs"
      extension="fun"
      results="." >
      <krun-option name="--pattern" value="&lt;k&gt; V:K &lt;/k&gt;" />
  </test>
```

On the other hand, this one works as expected, that is, it considers the desired options of kompile:

```
  <test
      definition="tutorial/2_languages/3_fun/1_untyped/2_substitution/fun-untyp\
ed.k"
      programs="tutorial/2_languages/3_fun/programs"
      extension="fun"
      results="tutorial/2_languages/3_fun/programs"
      >
      <kompile-option name="-transition" value="otherwise"/>
  </test>
```

This non-uniformity confused me for the second time, in the sense that I spent 5 minutes or so trying to understand why the second case above didn't work.  If it confused me, it may confuse others as well.  I see two ways to deal with it:

1) Report an error message when the krun-options attribute is not under a program or an all-programs tag;
2) Allow, by default, krun-options at the top level to mean it applied to all-programs.  I think this is the only meaningful thing for a user to mean.

1 is probably simpler to take care of, but 2 is better.  Your call, Daejun.

**Comment by daejunpark** [comment]
@grosu What I have in mind is the input validation. (i.e., 1st way). This is also related with Issue #95. In this way, we can prevent a future problem. I'll fix it by this week.
