### ISSUE TITLE
fresh variable redundancy

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1159]
From the K-user list:

I didn't have a problem in the older version using the fresh function, but now using '!' like the following example gives the same value twice:

rule <k> iWantChildren </k>
(. => <thread> <tid> !NewId1:Int </tid> </thread>
        <thread> <tid> !NewId2:Int </tid> </thread>
)

this makes two threads with the same value. How should I do it?

Thank you
Omar Alzuhaibi

**Comment by yilongli** [comment]
It's reproducible only using the Maude backend.

test.k

```
module TEST
  imports MAP

  configuration
    <k> $PGM:K </k>
    <threads>
        <thread multiplicity="*">
            <id> .K </id>
        </thread>
    </threads>

  syntax KItem ::= "start"

  rule <k> start => .K </k>
       (. => <thread> <id> !X:Int </id> </thread> <thread> <id> !Y:Int </id> </thread>)

endmodule
```

program.test:

```
start
```
