### ISSUE TITLE
kompile syntax error from removing empty comment

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#116]
From this message on the K list, attachments uploaded here:
https://gist.github.com/bmmoore/7201048

From: Kevin Garton
Sent: Sunday, October 27, 2013 5:36 PM
To: Rosu, Grigore
Subject: kompile bug

Professor,

I (well, to be fair, the one that figured it out was Ryan Welsh) noticed an odd bug today while working on the homework. The attached file "no-error_kool-untyped.k" kompiles without any error; the file "error_kool-untyped.k" does not kompile, throwing this error:

[Error] Critical: Parse error: Syntax error near unexpected character 'r'
    File: /home/garton1/K/homework/HW4/ex1/kool-untyped.k
    Location: (535,3,535,3)

This error is reproduced both on EWS and the online interface. The only difference in these files is the empty comment on line 534. kompile's parser is apparently doing weird things with comments.

Kevin Garton

**Comment by radumereuta** [comment]
I managed to reduce it to this:

```
module TEST
  rule A => .K
/***** added this ****/
  rule B => .K

/*
  rule C => .K
*/
/***** added this ****/

  rule D => .K
endmodule
```

It's a problem in the BasicParser. There should be 3 StringSentences for this module: A, B and D (C is commented), but somehow the parser is tricked by the comments and it generates only one instance with the content of the entire module.
