### ISSUE TITLE
checkstyle is oversensitive

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1174]
checkstyle considers as an error a rather common, an ok in my view, white space scenario.

consider the code below, underscores are white spaces:

```
void foo() {
____int x;
____
____x = 10;
}
```

checkstyle says there shouldn't be any white spaces on the line between the declaration and initialization. IDEs very commonly generate those whitespace, and they are very useful when navigating code. You don't want the cursor to bounce back and forth when moving through a method. The level of whilespace should match the surrounding level of indentation in this case.

**Comment by andreistefanescu** [comment]
I'm not sure about eclipse, but intelij allows you to set the cursor anywhere, even if the isn't an actual whitespace there.

**Comment by dwightguth** [comment]
Eclipse also tracks the location of the cursor based on the last time you
moved it from left to right, not based on the current line. And when you
hit enter, it automatically inserts the indentation even if your IDE is
configured to remove it when you save.

Cosmin, the issue with changing this is it causes there to be muddy diffs
that only differ in terms of whitespace. That is the real advantage of a
no-trailing-whitespace rule. Unless  you can think of a way to enforce that
property automatically another way, I'm inclined to leave this as is.

On Wed, Nov 12, 2014 at 9:02 PM, Andrei Stefanescu <notifications@github.com
