### ISSUE TITLE
Use ground equality in pattern matching rewriter

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1177]
Currently ==K and =/=K use unification even if we are using --pattern-matching. It would be good to set things up so that the pattern matching rewriter performed equality on ground terms, to avoid contaminating the pattern matching rewriter with bugs in the prover.

This could be accomplished by abstracting an interface similar to BuiltinIOOperations and injecting a different implementation of the builtin function for kompile, the prover, and pattern matching.

**Comment by yilongli** [comment]
Pattern matching and ground term are orthogonal concepts. It would be wrong to have pattern matching rewriter performed equality only on ground terms. But I see what you are saying, I will try to come up with a better solution.
