### ISSUE TITLE
Singleton maps are ambiguously parsed

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#125]
The compilation of the following definition

```
module MAP
  syntax Id ::= "x"

  configuration
     <env> x |-> 10 </env>
endmodule
```

produce the following ambiguity:

```
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: MyMap ::= K "|->" K 
   x |-> 10
2: 
   x |-> 10
    File: /Users/dlucanu/teste-temp-k/singletonmap/map.k
    Location: (5,12,5,20)
    Compilation Phase: Ambiguity filter
```

The compilation works fine if .Map is added to the content of the cell. I see no reasons to report ambiguities for singleton maps.

**Comment by radumereuta** [comment]
The ambiguity is fair in this case. We are currently working on the new MyMap classes, which look exactly like the old ones. In this case, when you are writing a MapItem element in the configuration, I have no reason to choose one or the other. If you would write it in a rule, I would use the configuration information to disambiguate.

When you add the .Map element, you specify that you want to have the old maps, and not the new ones. Although they look exactly the same (terminal wise) the sorts are not related.

This would be fixed once Andrei S. and Andrei A. finish with the implementation of the new maps, and we remove one of the two.
