### ISSUE TITLE
Whitespace bug in the parser

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1258]
see TreeNodesToKORE on the new-parser-on-kore branch

**Comment by dwightguth** [comment]
@cos what was this? this is really not enough info to reproduce the error...

**Comment by cos** [comment]
we added a hack in the pipeline because there was a bug in the parser kernel. @radumereuta fixed it afaik. @radumereuta, please close the issue if it is fixed.

**Comment by radumereuta** [comment]
Should be fixed now.
