### ISSUE TITLE
strange error reported when the name of the file differs from that of the main module

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#126]
The following definition

```
module BLA
  syntax Id ::= "x"

  configuration
     <env> x |-> 10 </env>
endmodule
```

is included in the file map.k. Compiling it without mentioning the main module option, we get the following strange error:

```
$ kompile map.k 
[Error] Internal: Internal compiler error --- Cannot find configuration.
    File: File System
    Location: generated
```

I think that the error should be more suggestive.

**Comment by osa1** [comment]
Just a note: This problem is related with built-in map.k file. If you rename your file as `somethingElse.k`, you get more useful error message:

```
[Error] Compiler: Could not find main module 'TEST'. Use -l(ang) option to
specify another.
        File: /home/omer/K/test/test.k
        Location: File system.
```
