### ISSUE TITLE
After upgrading to 3.5, Undefined sort Error

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1277]
OK. First I want to ask something that confused me. When you ask about the version, should I say 3.5 or 3.6-SNAPSHOT?! because the former is what you call it but the latter is what kompile --version gives!

Now to my question. I had in my syntax module a nonterminal which I don't expand to any terminal. I expand it to terminals in the main module. It didn't cause any problems before 3.5, but now it gives an error:
[Error] Compiler: Undefined sort ISiteId

I did a temporary fix but I thought I should report it.

**Comment by dwightguth** [comment]
This is considered intended behavior. If you want to declare a nonterminal of a sort that is not otherwise declared in that module, you should use a forward reference:

```
syntax ISiteId
```
