### ISSUE TITLE
Assign default value to configuration variable

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1278]
Can I assign a default value to a configuration variable such that krun doesn't complain if I don't specify it in the command parameters?

**Comment by andreistefanescu** [comment]
Yes, you can. If you have configuration variable `$VAR` and you want to initialize it with the default value `v`, you can use `krun -cVAR=v`.

**Comment by omarzd** [comment]
I meant can I assign a default value to it inside the k file so that if I do only `krun`, it would use the default value, but if I do `krun -cVAR=v`, then `v` would overwrite the default value.

**Comment by andreistefanescu** [comment]
I don't think that is possible, but we may add support for it. @dwightguth what do you think?

**Comment by dlucanu** [comment]
We discussed in the past about this feature. It should be a (old) issue.

**Comment by grosu** [comment]
Yes, I remember that.  Can you please point us to that issue, so we can keep track of it?

Grigore

**Comment by omarzd** [comment]
Here is that issue, #754.

**Comment by grosu** [comment]
I think all we need for this is a way to assign a special value, say #undefined, to configuration variables that were not assigned a value using krun.  The rest can be done programmatically.

Grigore

**Comment by dwightguth** [comment]
Closing as duplicate of #754
