### ISSUE TITLE
Multiple fresh Ints in one rule

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1279]
This was an issue [here](http://lists.cs.uiuc.edu/pipermail/k-user/2014-November/000699.html). It hasn't been fixed yet.

**Comment by dwightguth** [comment]
This issue is being tracked here: #1159. It seems to be an issue only in the old implementation of fresh in K 3.5. If you determine you can't get your definition to work on K 3.6, we can fix this for you, but for the time being our resources are prioritized on the latest version of K.

**Comment by omarzd** [comment]
No I'm already using the workaround mentioned in the thread I linked. I just wanted to report this. Thank you.
