### ISSUE TITLE
ktest - badly formatted error message

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#128]
The following error message is quite useful, but it poorly formatted:

fslwork$ ktest ~/k/tutorial/2_languages/3_fun/1_untyped/1_environment/exercises/spawn-join/tests/config.xml
Buildfile: 

```
/home/grosu/k/tutorial/2_languages/3_fun/1_untyped/1_environment/exercises/spawn-join/tests/config.xml
[Error] Critical: There are multiple K definitions with different kompile
                  options where they share the same directory:

/home/grosu/k-private/tutorial/2_languages/3_fun/1_untyped/1_e
                  nvironment/exercises/spawn-join. Two different options are
                  <test

definition=/home/grosu/k-private/tutorial/2_languages/3_fun/1_
                  untyped/1_environment/exercises/spawn-join/fun-untyped.k;
                  kompile-option=--transition lookup assignment io  /> and
<test

definition=/home/grosu/k-private/tutorial/2_languages/3_fun/1_
                  untyped/1_environment/exercises/spawn-join/fun-untyped.k;
                  kompile-option= />.
    File: command line
    Location: System file.

fslwork$ 
```

**Comment by osa1** [comment]
This is related with my code. I can't reproduce this error message, can you please write what is your current directory while running this test config?

**Comment by grosu** [comment]
Go to

k/tutorial/2_languages/3_fun/1_untyped/1_environment/exercises/spawn-join/tests

and modify the options of one of the two tests, say for example remove io from the --transition option of the second test's kompile.

**Comment by daejunpark** [comment]
@grosu @osa1 
I can fix it. This is because my previous implementation of wrapping messages in 80-width is conflicting with Omer's newest implementation.

**Comment by daejunpark** [comment]
@osa1 

After getting rid of my implementation, I found your StringUtil.splitLine has some problem. It seems that you just return a whole string if it is exceed 80-width without an white space. But you should have considered the string has white spaces after 80-width. For example, the above case now prints as follows: (you have to create a fake 'fun-untyped.k' in order to run ktest.)

```
$ pwd
/Users/daejunpark/k/tutorial/2_languages/3_fun/1_untyped/1_environment/exercises/spawn-join/tests
$ touch fun-untyped.k
$ ~/k/bin/ktest config.xml 
Buildfile: config.xml
[Error] Critical: There are multiple K definitions with different kompile
options where they share the same directory:
/Users/daejunpark/Desktop/K/dev/k/tutorial/2_languages/3_fun/1_untyped/1_environment/exercises/spawn-join/tests. Two different options are <test definition=/Users/daejunpark/Desktop/K/dev/k/tutorial/2_languages/3_fun/1_untyped/1_environment/exercises/spawn-join/tests/fun-untyped.k; kompile-option= /> and <test definition=/Users/daejunpark/Desktop/K/dev/k/tutorial/2_languages/3_fun/1_untyped/1_environment/exercises/spawn-join/tests/fun-untyped.k; kompile-option=--transition lookup assignment io  />.
```

I think you can just use WordUtils.wrap.
http://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/text/WordUtils.html

On the other hand, I do not agree with the idea of preserving a long string such as a path name or a code snippet (like above). I think it does not matter to wrap such a long string. For example, my previous implementation prints our as follows:

```
[Error] Critical: There are multiple K definitions with different kompile
                  options where they share the same directory:
                  /Users/daejunpark/Desktop/K/dev/k/tutorial/2_languages/3_fun/1
                  _untyped/1_environment/exercises/spawn-join/tests. Two
                  different options are <test
                  definition=/Users/daejunpark/Desktop/K/dev/k/tutorial/2_langua
                  ges/3_fun/1_untyped/1_environment/exercises/spawn-join/tests/f
                  un-untyped.k; kompile-option= /> and <test
                  definition=/Users/daejunpark/Desktop/K/dev/k/tutorial/2_langua
                  ges/3_fun/1_untyped/1_environment/exercises/spawn-join/tests/f
                  un-untyped.k; kompile-option=--transition lookup assignment io
                   />.
    File: command line
    Location: System file.
```

Of course, I agree that the above is not that good, but I don't know how to make it better within 80-width.

Please let me know if there is a better solution.

**Comment by osa1** [comment]
@daejunpark , we had discussed this on mailing list and decided to ignore long words(without whitespace).

**Comment by daejunpark** [comment]
@osa1 Yes, I know. But I just want to discuss about it again.

Even if we didn't discuss it again, the current your implementation has a minor bug. Please scroll in the right direction, and you will find a white space which should be wrapped to the next line.

Thanks!

**Comment by daejunpark** [comment]
@osa1 Please never mind my previous opinion at least now. I can this very problem by myself. We can talk about the fundamental issue later on.
