### ISSUE TITLE
'in' operator for List of Lists

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1280]
I have the following list of lists:

```
ListItem (
    ListItem ( 1 )
    ListItem ( 6 ) )
ListItem (
    ListItem ( 1 )
    ListItem ( 4 ) )
ListItem (
    ListItem ( 2 )
    ListItem ( 5 ) )
```

I want to check if the list (2,5) is in that list. Using the 'in' operator doesn't return true nor false. It just gets stuck. The rule which has this condition never matches. I'm using the latest binaries released.

My intention was to make a list of coordinates. Perhaps there is a better representation for it. What do you think?

Thank you

**Comment by dwightguth** [comment]
The following expression evaluates to true for me: `ListItem(2) ListItem(5) in ListItem(ListItem(1) ListItem(6)) ListItem(ListItem(1) ListItem(4)) ListItem(ListItem(2) ListItem(5))`

Can you show me the exact rule in question which is causing you trouble so that I can attempt to debug further?

**Comment by omarzd** [comment]
Is this version 3.5?
Give me some time. I will debug first and see if everything is OK from my side.

**Comment by omarzd** [comment]
OK. Is it ok if I want to assign it directly in a map like so:

```
<mapCell> 
  "List1" |-> BS:List
  "ListofLists" |-> Obs:List
  "check" |-> (_ => BS in Obs)
</mapCell>
```

Because what I'm getting is this

```
  "check" |-> (
    ListItem ( 1 )
    ListItem ( 5 ) =K
    ListItem ( 1 )
    ListItem ( 6 )) orBool (
    ListItem ( 1 )
    ListItem ( 5 ) =K
    ListItem ( 1 )
    ListItem ( 4 ) orBool (
    ListItem ( 1 )
    ListItem ( 5 ) =K
    ListItem ( 2 )
    ListItem ( 5 ) orBool false))
```

**Comment by dwightguth** [comment]
Ah, okay. Yes, this is a bug in the standard library for the maude backend in K. The simplest solution for you to get past this is to write the following rule in your semantics:

```
rule L1:List =K L2:List => L1 ==K L2
```

**Comment by omarzd** [comment]
I don't know what that rule means but it worked! Thank you.
