### ISSUE TITLE
all links are broken on the K tutorial pages!

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1288]
Since we changed the structure of the github repo (for example, the tutorial files are under k-distribution), all the links to "All files" on all the Tutorial pages are broken!

@pdaian, if you are still available, can you please take a look and fix one of them, and then send a reply to this issue telling us what needs to be done to fix all of them?  Then, Shijiao can do the rest uniformly, making sure that everything works.

Also, for some reason, the webpages of the FUN lectures seem to have been moved.  Why?

Thanks,
Grigore

**Comment by pdaian** [comment]
I'll take care of fixing them all.  ETA <1 hour.  I'll get back to you on the FUN pages also.

On January 6, 2015 10:44:57 AM CST, Grigore Rosu notifications@github.com wrote:

> Since we changed the structure of the github repo (for example, the
> tutorial files are under k-distribution), all the links to "All files"
> on all the Tutorial pages are broken!
> 
> @pdaian, if you are still available, can you please take a look and fix
> one of them, and then send a reply to this issue telling us what needs
> to be done to fix all of them?  Then, Shijiao can do the rest
> uniformly, making sure that everything works.
> 
> Also, for some reason, the webpages of the FUN lectures seem to have
> been moved.  Why?
> 
> Thanks,
> Grigore
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kframework/k/issues/1288

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laurayuwen** [comment]
Thank you Philip!
Shijiao
