### ISSUE TITLE
--search --pattern

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1290]
Can you please point me to documentation on how to specify patterns to use with `--search --pattern`?

**Comment by dwightguth** [comment]
I am not entirely sure how up to date it still is, but there is still some material in the manual draft in the at  k-distribution/documentation/ref-manual.k that covers options to krun. I think it should still be accurate. But basically to summarize, you can write any term followed by a side condition and it will return those results which match that term and satisfy the side condition. So for example:

`krun --search --pattern '<k> I:Int </k> requires I >Int 0'`

would match all configurations whose K cell contains nothing but one positive integer.

**Comment by omarzd** [comment]
On Windows, it works only with double quotes. Also I got some errors. The following threw `NullPointerException`:

```
--pattern "<myList> _:List </myList>"
```

And the following should have returned one  solution but it didn't:

```
--pattern "<myList> ListItem(1) </myList>"
```

However, when I did it like this, it worked:

```
--pattern "<myList> L:List </myList> requires 1 in L"
```

I wonder what the difference is between the second and third examples.
To say: when there in anything at all in `L`, I did this and it worked:

```
--pattern "<myList> L:List </myList> requires size(L) >Int 0"
```

**Comment by omarzd** [comment]
OK. This only shows the contents of the list 'L'. But how do I show the whole configuration like what `--search` does by default?

**Comment by omarzd** [comment]
That's easy. Whenever you specify a variable, its contents are shown in the output. So just surround the pattern with your topmost cell, e.g. `<T>` and specify a variable like so: 

```
<T> B:Bag <myList> L:List </myList> </T> requires size(L) >Int 0
```

The contents of `B` is your whole configuration.
