### ISSUE TITLE
ktest -- default option should not be needed

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#131]
The following config.xml works:

```
<tests>

  <test
    definition="lambda.k"
    programs="."
    extension="lambda"
    results="." >
    <all-programs>
      <krun-option name="-output" value="pretty" />
    </all-programs>
  </test>

</tests>
```

But the following does not:

```
<tests>

  <test
    definition="lambda.k"
    programs="."
    extension="lambda"
    results="."
  />

</tests>
```

This makes no sense, because pretty is the default output mode anyway.

**Comment by osa1** [comment]
This is handled in new kompile. I'll try push new version as ktest2 this weekend.

**Comment by grosu** [comment]
Actually, I figured out what the problem was.  By default, ktest uses the option "--output none" for krun, so the "--output pretty" tells it to output the configuration.  This was very confusing.  Now I think that it would be better if ktest uses the same defaults for krun as krun itself ... The drawback is that we will have to explicitly say "--output none" when we want to ignore the configuration, but probably that is OK, because one would expect to do that anyway.

**Comment by daejunpark** [comment]
Ok, I'll do it soon.

**Comment by daejunpark** [comment]
I think the reason of the default krun option was that we cannot pass such options to ktest in a single job mode.

That being said, I dropped all default options: ce3b77b1da62c5f05fac9a92965ee7968054816b
