### ISSUE TITLE
Attributes misprinted in PDF poster

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1312]
If you kompile and then kdoc any of the 1_lambda definitions, you will see attributes misprinted as follows:

```
   ... [binder( binder())]
   ... [strict( strict())]
   ... [bracket( bracket())]
```

Can you please help with this asap?  In fact, from now on I'm going to report lots of minor problems like this one, because both I and Mark Hills teach classes using K.  I expect many such minor details to have escaped us.  It is very important to fix these asap.  This is also, indirectly, a reason why we want K to build from sources on all settings: most likely I'll ask students to download and use the latest version of K in class, because that's the only one in which the bugs they report get fixed quickly.

**Comment by dwightguth** [comment]
Fixed by #1315
