### ISSUE TITLE
ktest --- option names of tools should drop the dashes

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#132]
There is really no point in having to write

```
    <kompile-option name="--main-module" value="CALLCC"/>
```

instead of just

```
    <kompile-option name="main-module" value="CALLCC"/>
```

Besides, the -- is disallowed inside XML comments, so we cannot comment out such tests right now.

**Comment by adamsmd** [comment]
This suggestion assumes that all options start with "--" which may not 
always be the case.  For example someone might want to use the short 
form of an option (i.e. with only one "-" at the front).

Unfortunately, I don't know of a better solution.

**Comment by osa1** [comment]
Also, currently some kompile options are specified wrongly in config files, for example, we don't have `-backend`, we have `--backend` but in config files it's `-backend`, I'm currently handling this in an ad-hoc way.

Maybe we can adopt a convention like this: (arguments have to start with either `-` or `--`)

If there's a `-`, that this means it's a short argument with one dash, if there's no `-`, it means it's a long argument at two dashes should  be added.

**Comment by grosu** [comment]
Actually, to keep things simple, we can disallow the shortcuts in ktest's config files.

**Comment by daejunpark** [comment]
If it is not urgent, please let me implement this in the new ktest.

**Comment by osa1** [comment]
I'm closing, this was resolved a while ago. (we had decided to use long/full argument names all the time and received no complaints after that)
