### ISSUE TITLE
Build failure of the last version of the matster

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#1327]
I cannbot build the last version of the master:

$ mvn package
Error: Could not find or load main class “-XX:+TieredCompilation”
Dorels-MacBook-Pro:k-original dlucanu$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
Dorels-MacBook-Pro:k-original dlucanu$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

**Comment by grosu** [comment]
Radu, Cosmin, can you please look into this asap?  Note that besides us, students were asked to install K from sources, so we want to fix this before they see it.

Thanks,
Grigore

**Comment by radumereuta** [comment]
That is a flag which tells the JVM to precompile the code, and now apparently it tries to read it as the entry point for the execution.
@cos @andreistefanescu  any ideas? I haven't seen this before.

**Comment by cos** [comment]
I have no idea. It seems to be a problem with the classpath as it cannot find the class containing `main(..)`. @radumereuta, why do you think it is related to the `+TieredCompilation` flag?

Running `mvn` with the `-e` might help debug this also.

**Comment by radumereuta** [comment]
I cannot reproduce it.
@dlucanu have you tried `mvn clean` before running `mvn package`?
I also got some random errors, until I cleaned the project.

**Comment by dlucanu** [comment]
"mvn clean" produces the same error.
I cloned a fresh copy and the behaviour is the same.

**Comment by radumereuta** [comment]
I don't have other suggestions than what @cos suggested.
Please run maven with the `-e` command. We may get some more information about this error.

**Comment by dlucanu** [comment]
It seems to be related to maven. I updated it and it seems that the version 3.2.5 does not work with
MAVEN_OPTS=“-XX:+TieredCompilation”
I removed it from my .profile file and it compiles fine.
Thanks.

**Comment by radumereuta** [comment]
This is still weird, since I have the same setup on windows, and it works fine for me.
But at least you found a configuration that works.

**Comment by grosu** [comment]
Cos, Radu, can you please update the K pre-requisites page with minimal version number info for Maven, please?

Thanks,
Grigore

**Comment by radumereuta** [comment]
But we didn't find any such information.

**Comment by cos** [comment]
@grosu, it doesn't seem to be related to the mvn version. I have an older version, 3.1.1, and it works fine. From what we know so far, it seems to be specific to @dlucanu's mvn installation. Running it with `-e` or `-X` may help with debugging it, in case we still want to figure out what happened.
