### ISSUE TITLE
ktest --- generate results automatically

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#133]
It would be really great if ktest can be added an option, say --generate-results, which would generate all the (remaining) .out files.  Specifically, it would generate in the last folder in the list of result folders all the .out files for all the programs which have no .out file yet or which have a a .out file whose contents is different from the currently generated .out.

This would save us a lot of time and it would make the user experience with ktest more pleasant.  Currently, we have to run krun with exactly the same options as in the ktest file on each file which has no output or a different output, and save its output in a .out file.  This is a lot of work.  I've probably spent several days so far doing only this mechanical work.  Not to mention that all this needs to be redone if we make any changes to the output of krun!

**Comment by daejunpark** [comment]
I see. But it seems to take more time than what you expected. The current implementation structure is far from this feature. So, I have to figure out how to implement it without major change of the overall structure.

**Comment by grosu** [comment]
This feature is becoming more and more needed.  Today I spent several hours again to just run krun to generate .out files.  And what is worse is that many of these will need to be regenerated if we make internal changes to the tool that would change the particular names of the generated (symbolic) variables.  While we will  eventually also be able to test modulo renaming of symbolic variables, we should also be able to generate the .out files automatically.

From the outside, it seems a trivial job :)  You already have all the information in junit-report.  All you have to do is to take the outputs of the failed tests or the tests without an output so far, and put them in corresponding .out files.

**Comment by daejunpark** [comment]
@grosu 
I'm sorry to hear you waste so much time. It should be not difficult, but tricky especially for managing sub-processes  in a reliable manner. (The previous non-determinism issue is partly related to that part.) Also, I think it'd better to be implemented at the new ktest.

That being said, I can provide a temporary solution to save your time by automatically creating a bash shell script who replaces all *.out files with the newest results. I think I can do it by tomorrow. Please wait a bit more. Thanks.

**Comment by daejunpark** [comment]
@grosu 

I just modified the dry-run mode to create commands of replacing *.out files: 299c2ca49b18f643123af269d6878064bb4a10a6

You can use `--dry` option, which prints all krun commands without actual krun.

For example, you can see first what commands will be executed:

```
$ ktest tests/config.xml --programs . --results . --dry | grep '^DRY:' | cut -f 2- -d ' '
```

Of course, you can just immediately execute those commands:

```
$ ktest tests/config.xml --programs . --results . --dry | grep '^DRY:' | cut -f 2- -d ' ' | bash
```

Note that this is just for replacing the existing *.out files, not creating a new one. So, it does nothing for a newly added program.

Nevertheless, I think it could be helpful to you until the new ktest supports this feature properly.

**Comment by grosu** [comment]
Thanks, Daejun, this is great!  This is a good tool to replace all the existing .out files without creating new ones, indeed, which I think it very useful in itself and we should keep it regardless of what other things to add to the tool.  What I particularly liked (I tried it, of course :)) was that it correctly calculated the krun options for each .out file, regardless of how many times the .out file has been overwritten; each of them had the correct krun options.  So yes, this is very useful, let's keep it!

Some small comments on the above, though:

1) I think the default output of the --dry option should be directly the output of

  ktest ... --dry |  grep '^DRY:' | cut -f 2- -d ' '

2) I think you should call the --dry option --update-out and keep it like this, that is, without automatically executing the krun commands.  It is easy to just write "ktest ... --update-out | bash" or something similar.  Later on we may ask the user a question at the end "Do you want to proceed?  [Y/N]", but for now the above is good enough.

3) We would like to generate the .out files without colors in them, so we can nicely see them in any editors, including github, kweb, emacs, etc.  Of course, you can say that you should put the --color off option in the config.xml files, but the problem is that we have not done it, and I suspect that people may want to keep these files as simple as possible.  So it would be nice to allow ktest to take the --color option of krun, too (maybe any of krun's commands, for simplicity?), and use it by default when calling krun; maybe just put it at the end of the list of options of krun, because krun seems to only keep the first option and ignore the rest of the options having the same name.

Thanks!
Grigore

**Comment by grosu** [comment]
In addition to keeping --update-out, we should also add a "more intelligent" --generate-out.  We should probably do this after we merge the two ktest implementations, as a demonstration of the easiness to modify it.

So, --update-out simply regenerates all the existing .out files, no matter whether that is needed or not for each file.

What --generate-out should do is to generate or update or even remove a .out file if and only if it is needed!  Unlike --update-out, it needs to first call krun on the definition in question, say lang.k, and on the program in question, say pgm.lang, then compare its output with the current pgm.lang.out (which may or may not be in the current directory), and then: 1) do nothing if they are the same; or 2) generate a new pgm.lang.out in the right place (the last directory in the --programs option).  This is exactly what a human would do.  This is exactly what I've spent tens and tens of hours doing.

The challenge in implementing the above is to make sure that you do things in order, otherwise you may generate too many unnecessary .out files!  You have to first process the included configs, and then the ones that include them.  This is going to be interesting :)

**Comment by daejunpark** [comment]
Oh, I'm happy to hear you like it. :) All things will be done as you suggested.

**Comment by daejunpark** [comment]
I've implemented the new options: --update-out and --generate-out.

The --update-out option replaces all existing *.out files regardless of being matched or not.
The --generate-out option creates an *.out file if needed, that is, when it failed to be matched or there is no *.out file.

Note that both behaviors (updating/generating) are triggered only when krun terminates normally (with return code 0).

Also, when using these options, it takes longer because all krun's are executed sequentially. For example, it took 45 minutes for only krun at fslwork:

```
----------------------------
Definitions kompiled: 0 (time: 0'0'' elapsed, 0'0'' CPU)
PDF posters kompiled: 0 (time: 0'0'' elapsed, 0'0'' CPU)
Programs krun: 835 (time: 45'42'' elapsed, 45'39'' CPU)
Total time: 45'42'' elapsed, 45'39'' CPU
----------------------------
```

**Comment by grosu** [comment]
Thanks!  This is a BIG (and risky) thing, so it needs to be tested thoroughly by several people.  I cannot express it in words how bad it would be if somebody destroys all the .out files and we only notice that weeks later!  So now if you call ktest at the top level of the tutorial with the right parameters, you can re-generate all the hundreds of .out files? One thing which certainly be very very useful, is to have a mode in which very visible messages are shown to the user, with red color, such as:

Modified xyz.simple.out
Removed abc.simple,out
Added mnp.simple.out

I would love to test this, but I cannot do it right now.  Can somebody else in need of it do it?  Liyi?

Thanks, Daejun!

**Comment by traiansf** [comment]
@daejunpark Building on what @grosu said above, how easy would it be to have a --dry-run option for this which would tell you which tests .out would be changes (and maybe give you a diff) but would not actually change them?

**Comment by grosu** [comment]
That would be awesome!

**Comment by daejunpark** [comment]
@grosu  @traiansf 

Indeed, it already prints out which output files are updated or newly generated as follows:
Currently, however, it is printed in the middle of the log message, and I'll make a summary soon.

```
Updating output file: /home/dpark69/ktest/k.2014-01-13.16-04-52/tests/regression/java-rewrite-engine/smt_model/program.test.out

Generating output file: /home/dpark69/ktest/k.2014-01-13.16-04-52/tests/regression/java-rewrite-engine/rhs_list_constructor/program.test.out
```

Also, there is no 'REMOVED' out file. Could you please let me know when it will happen?

As for the Train's suggestion, I would say you can already do it for free: just run ktest with either --update-out/--generate-out and use 'git diff'. :) You can freely revert it using 'git reset' if you are not happy with the result.

This (seemingly hack-ish method) makes sense because it takes same time even if you want to only just check the result. We cannot estimate the result without actually running it at some place. For example, it takes an hour for our master (root) config.xml at fslwork machine. So, it will also save your time to just run ktest and post-process its result with git tools.

Please let me know if I'm missing something.

Thanks,
