### ISSUE TITLE
Quick overview menu

### ISSUE THREAD

**Issue by ylies** [kframework/k-legacy#1334]
On the K web home page (reached by beginners such as I am), it says "The documented K semantics of  LAMBDA, IMP and KOOL (generated by the K Tool); more semantics available below."

It is is not quite clear what are LAMBDA, IMP and KOOL at this stage nor what is means to be generated by K tool.

Moreover, there are no more semantics available below this sentence.

Just my 2cts for now

**Comment by dwightguth** [comment]
Would the following wording be clearer?

"The documented K semantics of LAMBDA, IMP and KOOL (programming languages defined using literate programming in K, with documentation generated automatically by the K Tool); more semantics can be found by downloading K."

**Comment by ylies** [comment]
Yes. Thx.
