### ISSUE TITLE
krun --- better --help explanation needed for option --debug-info

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#135]
I guess we need a more explicit help text, the current one is
not very intuitive. May be we should say what means that for each backend.

Dorel

On 11/8/13 6:34 PM, Park, Daejun wrote:

> Hi Dorel,
> 
> You can use 'krun --debug-info' option which you can find in the experimental option category: 'krun -X'.
> 
> Thanks,
> Daejun
> 
> On Nov 8, 2013, at 9:05 AM, Dorel Lucanu dlucanu@info.uaic.ro wrote:
> 
> > Now krun empties the .k folder. I looked on the help test and I didn't find an option for preserving these files for cases when we want to debug with Maude.
> > I remember that we decided to have such an option.
> > Do we have it?
> > 
> > Dorel

**Comment by osa1** [comment]
I was going to check if the help message updated but apparently we don't have this option anymore. (or maybe merged to some other option)

@dwightguth Do you have any ideas?

**Comment by dwightguth** [comment]
This has been replaced with the --debug flag. You can check the help
message of that if you want.

On Sat, Sep 27, 2014 at 4:55 PM, Ömer Sinan Ağacan <notifications@github.com
