### ISSUE TITLE
Inappropriate error message

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#1351]
The following module includes an error (a duplicate cell in the rule), but the error message is total inappropriate. In a big definition it is not easy to see such an error. I think that it can be easily detected.

```
module TEST

  configuration 
    <k> 1 </k>
    <env> .Map </env>

  rule  <k> 1 => .K ...</k>
        <env> E:Map </env>
        <env> .Map </env>

endmodule
```

Here is the error mesage:

```
$ kompile test.k 
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please file a bug report at https://github.com/kframework/k/issues
```

**Comment by bmmoore** [comment]
I think I know where that assert is
