### ISSUE TITLE
Standardize String syntax in KORE/new parser

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1359]
It looks like we have several different syntaxes for strings in the K framework that do not exist in any particularly consistent manner. In general, as I understand it, there should be exactly one syntax for strings in K which is used above all other mechanisms for enquoting and unquoting strings. This is the regular expression defined in k-distribution/include/builtins/string.k.

You will need to ensure that this syntax of strings is used consistently throughout the entire framework if you want to be able to parse all the definitions in the distribution, so I suggest you get a head start and standardize this now so that you don't have to deal with it later. The longer you wait the more places in the framework are likely to use the incorrect syntax that you will then have to correct later.

**Comment by radumereuta** [comment]
I will keep this in mind when we start integrating the components we are working on right now.
