### ISSUE TITLE
--help should sort options alphabetically

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#136]
Is there any reason why we don't sort the --help options alphabetically?

**Comment by adamsmd** [comment]
I am not sure if the current order does this, but most programs group 
the options so similar options are near each other with the groups 
containing more obscure options placed at the end.  Only after those are 
done do they go to sorting alphabetically.

**Comment by daejunpark** [comment]
The major reason was that there were --abc/--no-abc options. In that case, the alphabetical order does not make sense. Although we do not have such options anymore, I think I can arrange similar options and also put important ones in the higher place. For example, I think kompile, krun and kast are not that horrible. However, I agree that krun has so many options that it is hard to find a specific option. Anyway, if many people think it should be in alphabetical order, then I'll do that.

**Comment by osa1** [comment]
Closing this as it's fixed after moving to JCommander for parsing options.
