### ISSUE TITLE
Substitution Module in 3.5

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1366]
Hello. I got the following message trying to run lesson 2 of lamda.

```
[Error] Critical: Found two modules with the same name: SUBSTITUTION
        Source: File: k\include\modules\substitution.k
        Location: (158,1,298,9)
```

The other substitution module is in substitution-java.k

In my project, I was having a problem with substitution, so I tried running the simplest example, and I got that message even though kompiling my project does not produce it.

**Comment by omarzd** [comment]
The problem I'm having in my project is that it is not substituting a sort that I created. I tried to reduce/simplify the rule so that it works. Here it is:
`rule func(Body:Exp, P:Param) => Body[0/P]`
where Param can only be a `CamelCaseId`, the sort that I created imitating K's builtin `Id`. Here it is:

```
module CCID-SYNTAX-HOOKS
    syntax CamelCaseId ::= Token{[a-z][\_a-zA-Z0-9]*}       
                 [notInRules, regex("(?<![A-Za-z0-9\\_])[a-z\\_][A-Za-z0-9\\_]*")]
endmodule

module CCID-HOOKS
  imports CCID-SYNTAX-HOOKS
  imports STRING-HOOKS
  imports K

    syntax String ::= "CamelCaseId2String" "(" CamelCaseId ")"         
        [function, hook(#CONVERSION:token2string), klabel(CamelCaseId2String)]
    syntax CamelCaseId ::= "String2CamelCaseId" "(" String ")"         
        [function, hook(#CONVERSION:string2id), klabel(String2CamelCaseId)]
    rule CamelCaseId2String(X:CamelCaseId) => #tokenToString(X)         [function,anywhere]
    rule String2CamelCaseId(S:String) => #parseToken("CamelCaseId", S)  [function,anywhere]

    syntax CamelCaseId ::= freshCamelCaseId(Int)    [freshGenerator, function]
    rule freshCamelCaseId(I:Int) => String2CamelCaseId("var_" +String Int2String(I))
endmodule
```

What happens is that the substitution gets stuck:

```
#substitute ( someExp , #patternMatch1 ( decomposeMatching`(_`,_`)(_`(_`)
   (#token("CamelCaseId","x"),.KList),_`(_`)(#_(0),.KList)) , .Map ) )
```

When I tried to convert my `Param` to `Id` and pass that to the substitution function, doing this:

```
  syntax Id ::= Param2Id(Param) [function]
  rule Param2Id(P:Param) => String2Id(#tokenToString(P)) [function,anywhere]
rule func(Body:Exp, P:Param) => Body[0/Param2Id(P)] [function]
```

When I do that, It acts as if it did substitute even though it does not. I know that because the rest of the rule is applied, but the substitution part is not.

**Comment by dwightguth** [comment]
Are you subsorting the correct sorts to `Variable` and declaring the correct productions as `binder`?

By the way, the issue with lambda is that it is configured to use the Java backend, so you need to specify `--backend java` to kompile.

**Comment by omarzd** [comment]
No. I didn't know of the `Variable` builtin sort before, so I just did as you said.
However, regarding `binder`, can you please explain how the `binder` attribute works? I tried it on different constructs but every time it causes an exception of type `AssertionError`. Here is the top of the stack trace:

```
java.lang.AssertionError
        at org.kframework.kil.KLabelConstant.of(KLabelConstant.java:55)
        at org.kframework.compile.transformers.ResolveBinder.visit(ResolveBinder.java:109)
        at org.kframework.compile.transformers.ResolveBinder.visit(ResolveBinder.java:33)
        at org.kframework.kil.Module.accept(Module.java:129)
        at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:95)
        at org.kframework.kil.AbstractVisitor.genericVisitList(AbstractVisitor.java:146)
```

What am I missing?

**Comment by omarzd** [comment]
It worked! I didn't need `binder`! I needed to define my `CamelCaseId` as a subsort of `Variable`. Also, I had another mistake. The `Exp` that I was trying to do the substitution in didn't have a `Param` but another sort that can also be a `CamelCaseId`. Sorry for the confusion, and thanks for the help.
