### ISSUE TITLE
escape character to produce parentheses

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1368]
Suppose I have something like `rule Exp => (Exp)`. I want to produce parentheses on the right side. How do I do that?
I already have `syntax Exp ::= "(" Exp ")"  [bracket]`.
I tried doing `rule Exp => "(" Exp ")"`, but it didn't work.

**Comment by radumereuta** [comment]
If you put `bracket` on a production, this means it will be used just as a syntactic aid for overriding default priorities. It has no semantic meaning.
You can write `rule Exp => ( Exp )`, but it will only create a loop. The production will be discarded immediately after parsing. I'm not sure exactly what you are trying to do, but if it has semantic meaning, maybe you want to make it a normal production, and add it or discard it manually.

**Comment by omarzd** [comment]
Actually, it's like `rule functionCall => ( functionBody )`

**Comment by dwightguth** [comment]
this should work. Can you explain what is happening which is not like you expected?

**Comment by omarzd** [comment]
I think it's working. Thank you.
