### ISSUE TITLE
strange "Cannot compute least sort" error message

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#1372]
The compilation of the module 

```
module TST

  syntax Typename ::= "int"

  syntax Decl ::= Typename IvarList

  syntax IvarList ::= List{Ivar, ","}

  syntax Ivar ::=
       Id
     | Id "=" Expr [ivar]

  syntax Varref ::= 
       Id
     | Id "[" Expr "]"

 syntax Const ::= Int 

  syntax Expr ::=
       Varref
     | Const

  syntax Assign ::=
       Varref "=" Expr [assign]

  rule <k> T:Typename X:Id = V:Const => .K ...</k>

endmodule
```

reports the following error:

```
$ kompile tst.k 
[Error] Critical: Cannot compute least sort of term: '_=_(_8:Id,, _9:Const)
Possible least sorts are: [Assign, Ivar]
```
1. No line & column numbers are displayed.
2. The error is given by the only rule in the module. From my point of view, "T:Typename X:Id = V:Const " is not ambiguous, it should be infered that the least sort of "X:Id = V:Const" is Ivar. Moreover, neither of (X:Id = V:Const)::Ivar , (X:Id = V:Const):>Ivar, (X:Id = V:Const):Ivar, (X:Id = V:Const)<:Ivar solves the problem.

**Comment by radumereuta** [comment]
This looks like something which comes from the backend, so casting the term won't help.

**Comment by dwightguth** [comment]
@andreistefanescu could we maybe adjust the error message for this error to include location information, plus some kind of message like "Consider assigning a different klabel to each possible production"?
