### ISSUE TITLE
Error message "Unsupported map pattern in the rule left-hand side" reported for definitions not using maps

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#1375]
The compilation of the module 

```
module TST

  syntax Edge ::= Int "-->" Int
  syntax SetOfEdges ::= "{" Set "}"

// the set of vertices of a graph

  syntax Set ::= vertices(SetOfEdges) [function]

  rule vertices({ SetItem(I:Int --> J:Int) G:Set }) => (SetItem(I) SetItem(J) vertices({ G }))

endmodule
```

reports the following error:

```
$ kompile tst.k 
[Error] Critical: Unsupported map pattern in the rule left-hand side
    Source: File:
/Users/dlucanu/Documents/cursuri/pa/2015/seminar-special/03mar2015/clasa/xxx/././tst.k
    Location: (10,3,10,94)
```

but the definition does not use maps.

Version of the kompile tool:

```
$ kompile --version
K framework version 3.6-SNAPSHOT
Git revision: 4023860
Git branch: master
Build date: Tue Mar 03 16:11:32 EET 2015
```

**Comment by dlucanu** [comment]
Improving the error message only partially solves the issue. Remains the problem how to write a function that traverses a list/set/map.

**Comment by dwightguth** [comment]
the problem with this rule is that it is nondeterministic and requires associative matching. You are essentially saying that you can match any single element in the set as long as it matches a particular pattern. But the only way to do this is to try and match every element in the set and see if it matches, which in particular leads to (n^2)*k running time, where k is the complexity of the matching algorithm. I believe what you would like to do is simply to iterate through each element in the set and perform a particular transformation on that element, but that's not really what you're doing here. Try the following construct:

```
rule vertices({ SetItem(E:Edge) G:Set }) => vertices(E) vertices({G})
rule vertices(I:Int --> J:Int) => SetItem(I) SetItem(J)
```

**Comment by dlucanu** [comment]
I see the point: the AC matching is triggered by the fact I mentioned the pattern `I:Int --> J:Int` in the argument of the rule. Only patterns of the form `SetItem(X) S`, where X and S are variables, can be done as arguments of sort Set. Correct?
Thanks.

**Comment by dwightguth** [comment]
Correct.

**Comment by dlucanu** [comment]
Thanks.
