### ISSUE TITLE
builtin transitions count

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1385]
I wish to know how many transitions happened up until the current configuration. Does K have a builtin count for that? Or do I have to make my own count and make every transition rule increment it? Will that work correctly?

**Comment by omarzd** [comment]
I just made every transition rule increment my count; It is working correctly. Should I keep it this way or is there a cleaner way to do it using a builtin?

**Comment by bmmoore** [comment]
That's the cleanest way to do this. One reason against trying to add a builtin like that is that more complicated uses of K like running `--search` on a nondeterministic language want to identify states which can be reached along multiple execution paths, even if the paths take a different number of states to arrive. Also, more serious uses of step counting might want to assign a different cost to different rules - it's entirely reasonable to add system support for that, but it would be a bit less one-size-fits-all than a builtin that just counts the number of applied steps.
