### ISSUE TITLE
how threads are sorted in krun Output 

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1386]
When I krun an example that produces multiple threads, the threads are sorted by alphabetical order of the contents of the their k cells. Can I change that? I would like them to be ordered by another cell, the thread ID for exmaple.

**Comment by dwightguth** [comment]
If the thread ID cell is placed before the K cell within the thread cell,
it should sort alphabetically by the thread ID. Please give this a try and
let me know if it does not work.

**Comment by omarzd** [comment]
It worked. Thank you.
