### ISSUE TITLE
LTL Model Checking is not straightforward

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1389]
I've looked into the Cink examples. First of all, I didn't expect that I would need to change my syntax to include labels and to define equality functions and other atomic propositions. My question is: Is this mandatory or is there a simpler way?

**Comment by dlucanu** [comment]
The LTL model checker (that used in Cink) works only with the Maude backend (no longer available in the last version).

Generally, the property language (here the language for atomic propositions) is distinct from the programming language. In oder to check the properties, you need both languages. Moreover, the satisfaction relation between configurations and the atomic propositions must be defined. 
These two components must be sent to the Maude LTL model-checker by the backend tool.

In my opinion, these two components are required by any LTL model-checker built for K definitions.

The labels are required only if you want to have an atomic proposition saying "the execution of the program reached the statement with the label L".

**Comment by omarzd** [comment]
I see. Thanks for explaining what the labels are for; and I understood why we need the property language. But what defines the "satisfaction relation between configurations and the atomic propositions"? Can you please explain. Do I need to make changes to my configuration?

**Comment by dlucanu** [comment]
The satisfaction relation is given as C |=Ltl At and says that the atomic proposition At holds for the configuration C (it is the labelling function in terms of Kripke structures).
Actually, _ |=Ltl _ is implemented as a function Bag X Prop -> Bool .
The configuration remains unchanged.
