### ISSUE TITLE
ktest --- need to configure kompile/krun in include attrbutes

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#139]
To properly write the test for superheat/supercool for IMP++ in lesson 3, I would need to write something liek this:

```
  <include file="../../lesson_2/tests/config.xml" >
    <kompile-option name="-superheat" value="division" />
    <kompile-option name="-supercool" value="lookup increment" />
    <program name="div.imp">
      <krun-option name="-output" value="pretty" />
      <krun-option name="-search" />
      <krun-option name="-color" value="off" />
    </program>
  </include>
```

That is, I want to include the config of the previous tests, but this time I want to kompile everything with the specified options and to krun one particular program, div, with the specified krun options.

**Comment by daejunpark** [comment]
What if the included config.xml has already kompile-option or krun-option's? Which one do you want: union of them or overwritten by the new?

**Comment by grosu** [comment]
I think over-written by the new is the right way to go, because it allows us to also drop previous configurations, so it is more powerful.  Thanks!

**Comment by daejunpark** [comment]
Done: 294e42708d700bea23b418daf0f4eb10b295ec74
