### ISSUE TITLE
internal AssertionError

### ISSUE THREAD

**Issue by kheradmand** [kframework/k-legacy#1392]
Hey, 

I was doing K's tutorials [exercise](https://github.com/kframework/k/tree/master/k-distribution/tutorial/2_languages/1_simple/2_typed/1_static/exercises/no-duplicate-declarations).

I kompiled the [this file](https://uofi.box.com/shared/static/z4a59j65nclddugfkodkina3497uq2hd.k) and then tried to run it on the examples in the tests folder. They all fail with the following error :

`[Error] Internal: Uncaught exception thrown of type AssertionError.
Please file a bug report at https://github.com/kframework/k/issues`

**Comment by kheradmand** [comment]
K framework version 3.6-SNAPSHOT
Git revision: 8f305df
Git branch: UNKNOWN
Build date: Tue Feb 24 15:48:46 CST 2015

on OS X 10.8.5 with JRE 1.8

**Comment by dwightguth** [comment]
I can't actually read that file... can you please create a gist for it, or inline it into this issue?

**Comment by dwightguth** [comment]
I was able to download this file, but it looks like it doesn't compile. There is a parse error on line 534. You modified the syntax of a type so that it included the types it throws, but you didn't update every use of that syntax.

**Comment by kheradmand** [comment]
Sorry dwight I uploaded a wrong file and I don't have the file that caused the bug now. So I'll close the issue and would reopen it if I can reproduce the problem.
