### ISSUE TITLE
naming consistency: require vs imports

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1397]
We should either use `require` and `import` or `requires` and `imports`.  We currently have `require` and `imports`, which is hard to remember.  I propose that we use `require` and `import` only in the future, temporarily deprecating `imports`.

**Comment by radumereuta** [comment]
I think it would be quite simple to add both.
Just like we have `priority` and `priorities`.

**Comment by dwightguth** [comment]
@radumereuta the grammar accepts imports only at the beginning of a module, right? if so, there's really no reason not to add both, because it will not reserve any new identifiers in a way such that they cannot be used in rules.

**Comment by radumereuta** [comment]
How about for `requires` and `ensures` in rules?

**Comment by dwightguth** [comment]
require statements can only exist outside of modules, so that should not be an issue either.

**Comment by radumereuta** [comment]
Yes, of course, but I was trying to raise this other issue, since they are still keywords, and users won't know the difference.

**Comment by grosu** [comment]
The verification community uses requires/ensures for those (see http://rise4fun.com/Dafny/tutorial/guide), so we should probably also keep them like that.

**Comment by radumereuta** [comment]
Closed via #1405
