### ISSUE TITLE
process don't stop when sending Ctrl+Z to a program awaiting input

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#14]
1. kompile simple-untyped
2. krun krun programs/diverse/sortings.simple
3. Type 1 <Enter> Ctrl+Z
4. ps ux

Result: the process is still shown in the list.

This don't happen if we use Ctrl+C instead.

**Comment by chathhorn** [comment]
Isn't this expected behavior? Ctrl+Z is just supposed to suspend the process, not kill it.

**Comment by denis-bogdanas** [comment]
You are right, I'm not a specialist in Linux. Closing the issue. http://superuser.com/questions/476873/what-is-effect-of-ctrl-z-on-a-unix-linux-application
