### ISSUE TITLE
Fix hook exception in tests/regression/java-rewrite-engine/visitor/test2

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1406]
`k-distribution/tests/regression/java-rewrite-engine/visitor/test2/program.test` generates a warning because of an exception thrown because we are trying to call the ==K hook with too many arguments. This was being silently ignored in the past so we did not detect it. It would be good to fix this so that the hook for the visitor behaves correctly and calls everything with the right arguments.

**Comment by radumereuta** [comment]
Make sure that when this gets fixed, the line which suppresses warnings from this tests is deleted. (config.xml -> warnings2errors="false" should be deleted.)
