### ISSUE TITLE
ktest --- needs to override programs, too, not only results

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#141]
In IMP++ we have a spawn.imp in lesson_1, which is purposely suboptimal.  Then in lesson_8 we add the actual spawn.imp.  However, ktest does not let me do what I want in lesson 7, namely to discard the spawn in lesson_1 and replace it by the one in lesson_7:

```
fslwork$ pwd
/home/grosu/k/tutorial/1_k/4_imp++/lesson_7/tests
fslwork$ l
config.xml  spawn.imp
fslwork$ more config.xml 
<tests>

  <include file="../../lesson_6/tests/config.xml"
           more-programs="."
           more-results="." />

</tests>
```

The above still checks the spawn in lesson_1 and gives an error.  If I add 

```
       exclude="lesson_1/tests/spawn"
```

then it works, but it should work without it, too.

**Comment by traiansf** [comment]
2013/11/11 Grigore Rosu notifications@github.com

> In IMP++ we have a spawn.imp in lesson_1, which is purposely suboptimal.
> Then in lesson_8 we add the actual spawn.imp. However, ktest does not let
> me do what I want in lesson 7, namely to discard the spawn in lesson_1 and
> replace it by the one in lesson_7:
> 
> fslwork$ pwd
> /home/grosu/k/tutorial/1_k/4_imp++/lesson_7/tests
> fslwork$ l
> config.xml  spawn.imp
> fslwork$ more config.xml
> <tests>
> 
>   <include file="../../lesson_6/tests/config.xml"
>            more-programs="."
>            more-results="." />
> 
> </tests>
> 
> The above still checks the spawn in lesson_1 and gives an error. If I add
> 
> ```
>    exclude="lesson_1/tests/spawn"
> ```
> 
> then it works, but it should work without it, too.

I think maintaining the current functionality would be more flexible.  The
alternative would be to consider any program having the same name to
"overwrite" checking the previous program.  But this would kind of prevent
having the same program name twice in a test suite, wouldn't it?

best wishes,
Traian

**Comment by grosu** [comment]
Train,

But the current functionality already fails if you have multiple programs with the same name, unless they happen to have exactly the same output!  That's because the reasults are collapsed anyway.  Since out current approach is based on flatenning the set of programs and of results, and since the results are really needed to be flattened, I think we should just be consistent and also flatten the programs.

Grigore

**Comment by daejunpark** [comment]
@grosu 
I did it. Please find it works well with your cases. I tried to check it myself, but could not because the config.xml files are not completed.
