### ISSUE TITLE
[Error] Critical: Could not infer a unique sort for variable 'S'. Possible sorts: Exps, Stmts

### ISSUE THREAD

**Issue by McDowell1234** [kframework/k-legacy#1414]
Dear Dwight,

When putting 5 elements into a ListElement tuple, K gives me the error that not a unique sort for Statements could be inferred even though the type of the tuple that I use is declared to be a KItem.

What does the Kompiler reject?

**Comment by dwightguth** [comment]
Could you please copy and paste the exact error message you are getting into this thread?

**Comment by dwightguth** [comment]
Oh wait never mind, I see you did already. This is occurring because you have a variable S which parses as either Exps or Stmts, but neither of these sorts is subsorted to the other. Have you tried giving this variable the explicit sort that you would like it to have?

**Comment by dwightguth** [comment]
Closing since you didn't respond. Please reopen if this is still an issue.
