### ISSUE TITLE
java.lang.UnsupportedOperationException: missing SMTLib translation for Map:lookup

### ISSUE THREAD

**Issue by McDowell1234** [kframework/k-legacy#1429]
Dear Dwight,

When running untyped-kool.k with ex01.kool from exercises/private-members/tests, an UnsupportedOperationException is returned. 

Implementation has been sent to your e-mail.

Best,
Michael

**Comment by McDowell1234** [comment]
If I delete the [function] annotation, the exception disappears. However, my lookup member rules still get stuck.

**Comment by dwightguth** [comment]
Can you try to update to the latest version of K and let me know if the most recent changes to the framework make it clearer to you what the problem is? I believe the issue is likely to be that some function rule has failed to apply.

**Comment by McDowell1234** [comment]
I updated K but the error message does not change.

**Comment by dwightguth** [comment]
This is quite strange. Are you sure you updated correctly? The latest version of the K framework should not cause this error unless you are passing the --symbolic-execution flag to krun, which I suspect you are not. What does "krun --version" show?

**Comment by dwightguth** [comment]
Closing from lack of activity. Also this was a student question and the semester is over. Please feel free to reopen if you are still interested in this though.
