### ISSUE TITLE
AssertionError in kool-untyped.k

### ISSUE THREAD

**Issue by smeenai** [kframework/k-legacy#1430]
When trying to run my implementation of `untyped-kool.k` with `ex01.kool` from `exercises/private-members/tests`, I get

```
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please file a bug report at https://github.com/kframework/k/issues
```

The implementation, as well as a short explanation, has been emailed.

**Comment by dwightguth** [comment]
I have this definition in my inbox. Whoever is oncall and needs to resolve this, please let me know.

**Comment by radumereuta** [comment]
Is it private? Why don't you attach it to this issue?

**Comment by dwightguth** [comment]
It's part of one of Grigore's assignments, I don't want partial solutions available online.

**Comment by smeenai** [comment]
The issue in question was resolved by adding `[assoc, comm]` to a function definition - it was an AC-matching exception. I'll confess to having no idea what that actually means, but we got it to work eventually :)
