### ISSUE TITLE
latex: cells not horizontally aligned

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1437]
In the drawing of rules or configurations, cells that contain different types of content do not align horizontally, e.g., cells that contain a `\dotCt{something}` are a little below other cells containing `\terminal{}` and `\constant{}`.
I tried playing with the `k.sty` file, but nothing affected that.

**Comment by dwightguth** [comment]
I have to admit, I don't perceive what you're claiming. Can you provide a link to an image that illustrates this issue?

**Comment by omarzd** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7592333/7381824/7a234416-ee10-11e4-8d2c-6b134cca4284.png)

You can see that the cell called defId is not horizontally aligned with the other two perhaps because of its content taking less vertical space.

**Comment by omarzd** [comment]
This one is another example and is produced using the unmodified k.sty
![untitled](https://cloud.githubusercontent.com/assets/7592333/7382029/c83974de-ee12-11e4-8e86-99bd543a4503.png)
