### ISSUE TITLE
ktest ignores color settings

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#144]
current ktest ignores color settings and instead overrides it with `ColorSetting.ON`

https://github.com/kframework/k/blob/master/src/javasources/KTool/src/org/kframework/ktest/KTest.java#L436

this basically forces ktest to print colorful output even though colorful output is disabled with some parameters(or maybe ktest doesn't have that parameter)

In the former case I think this is a bug and in the second case this is an improvement.

**Comment by grosu** [comment]
The idea is that we do not colors to matter in the comparison of the obtained result by ktest and the expected result.  Several other things are disabled in this check: whitespaces (for pretty printing), balanced parentheses (for unparsing).  These can be enabled with --ignore-whitespaces off, etc., which are probably not documented yet.  Daejun will do it soon, so they can be still tested with specialized tests.  We just don't want to have to redo all the test outputs each time we change our mind about how to pretty-print or color 
stuff.

**Comment by osa1** [comment]
This is for ktest output, not krun. Basically there is no way to get colorless ktest output because of this. So this is not related with string comparisons.

But I think string comparisons also have problems. Instead of doing it like this https://github.com/kframework/k/commit/f829646618dc488d7fb4f93cadf366c735fb7f63 why not pass krun to `--color=off`? I think current implementation does it wrong way because it repeats some already existing functionality.

**Comment by osa1** [comment]
In new ktest I added `--colors` parameter that works same as krun's `--color`. It's `on` by default and depending on that parameter coloful output is produced.

**Comment by osa1** [comment]
New ktest is already merged so I'm closing this.
