### ISSUE TITLE
krun is not quoting filenames correctly

### ISSUE THREAD

**Issue by jthywiss** [kframework/k-legacy#1457]
krun is not quoting filenames correctly:

```
$ krun test.toksem 
[Error] Critical: Warning: <standard input>, line 2: unable to locate file:
/Users/user/k/a
Warning: <standard input>, line 2 (mod KRUNNER): module TOKSEM does not exist.
Warning: <standard input>, line 3 (mod KRUNNER): bad token #TCPPORT.
Warning: <standard input>, line 3 (mod KRUNNER): no parse for statement
eq #TCPPORT = 49266 .
Warning: <standard input>, line 6: unable to locate file:
/Users/user/k/a
```

Full path to working directory is `/Users/user/k/a b c`, so krun should be looking for `/Users/user/k/a b c/test.toksem` and `/Users/user/k/a b c/toksem-kompiled`.

kompile works happily in the same directory.

K Version 3.5.1 on Mac OS X 10.9.5

**Comment by dwightguth** [comment]
This is fixed in K v3.5.2 which I have just released. It is also, hopefully, working already in the master branch, which contains the snapshot of the upcoming K 3.6. Please let me know if this works for you.

**Comment by jthywiss** [comment]
Thanks, I will test 3.5.2 tomorrow.

**Comment by jthywiss** [comment]
Actually, I got a moment to check it just now.  Fix confirmed.
