### ISSUE TITLE
krun should not need --backend option

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#147]
There is no reason for krun to have the --backend option.  We can kompile in different directories with different backend options using kompile -d folder ..., and then we can run krun with the option -d saying where the definition is.  It was quite frustrating during my class today that I had to type the --backend java when running each program.

**Comment by traiansf** [comment]
Maybe so, but then we need to save in the compiled folder information about
the backend it was compiled for, and then read that in krun before we
decide which code to run.  It was much simpler to have it as a separate
option as it was quite experimental at the beginning.

It might also be a good idea to completely separate the java krun and try
to standardize the API of launching the external backend.

2013/11/13 Grigore Rosu notifications@github.com

**Comment by osa1** [comment]
My proposal I wrote here https://github.com/kframework/k/issues/145 can help with this. Then every backend can provide a function like `checkBackendFiles` that basically looks for backend specific subfolder and then version number and checks if all files complete and loadable etc.

**Comment by grosu** [comment]
But your proposal would still require you to say which backend you mean when you call krun, which is inconvenient.

**Comment by osa1** [comment]
I guess this would only be the case when we have multiple backends compiled in `*-kompiled` directory.

For other situations, it can easily run whatever backend is there.

Or we can define an ordering for backends, krun first searches for maude backend files and if they're there it runs maude, otherwise searches for java etc. (if `--backend` is not specificied)

**Comment by grosu** [comment]
but why do that?  We already have the -d option in both krun and kompile, so we can put and access definitions anywhere.  We are not (and do not want to be) uniform wrt where we place the results of all the backends anyway; for example, we want the generated PDF files to be at the top level anyway.

**Comment by grosu** [comment]
We should move on with this, because as we use the java backend more and more frequently, it becomes more and more annoying to have to type --backend java in krun when we know it for sure that the -kompiled folder contains a definition kompiled with --backend java.

Omer, I continue to not be in favour of saving all the various kompiled language models, with different backends, under the same -kompiled folder.  Again, we have the option -d in kompile and in krun precisely to allow people to say where they want their definitions kompiled.  ktest is also easy to use with this approach.  Simple is better.  Knowing that each --kompiled folder holds precisely one language model is as simple as it can get.  Why make it more complicated than needed?

**Comment by adamsmd** [comment]
It looks to me like their are only two backends for krun.  Is that right?

Are there any use cases where someone needs multiple backends in the 
same folder?

If these questions are answered "yes" and "no" respectively, I concur 
that each folder should have only one backend.

**Comment by dlucanu** [comment]
Actually we have three backends: maude, java, and symbolic (this is 
experimental, but used).

Dorel

**Comment by grosu** [comment]
The general philosophy of the lang-kompiled folders is that they are unique per folder.  Actually, krun already complains if there is more than one -kompiled folder.  We have the -d option to store (with kompile) or access (with krun) definitions residing in other folders if we want to.  One can and should also use this -d option in ktest to test the same definition multiple times with different kompilation options.  Overall, it is not only safe but even expected now that each folder contains at most one language model folder (i.e, a lang-kompiled folder) as a direct child, so there is no reason at all to have a --backend option for krun.

Grigore

**Comment by dlucanu** [comment]
I just made some experiments and, indeed, the option --d is the right 
solution for running the same programs with various backends..
I agree to get rid of the --backend option for krun.

Dorel

**Comment by osa1** [comment]
OK, so I'll go ahead and do these changes:
- Remove --backend option in krun and krun will run with whatever backend is compiled in `*-kompiled` folder.
- This also requires kompile to have place only one kompiled backend in `*-kompiled` folder.

Does that sound good?

We also need to decide on what to do when kompile is invoked for compile backend `a` but we have backend `b` compiled in `*-kompiled` folder.

**Comment by grosu** [comment]
Your plan sounds great!

> We also need to decide on what to do when kompile is invoked for
> compile backend a but we have backend b compiled in *-kompiled folder.

Just forget that b was kompiled before, and put a in the new -kompiled.  I don't think there is any other reasonable option here.  I would rather keep things clean and simple then try something smart which may work against us...

**Comment by adamsmd** [comment]
What does the "symbolic" backend do?  Is it at all related to the "java" 
backend?

**Comment by andreiarusoaie** [comment]
Its the Maude symbolic backend, so please do not remove it. It's a prototype which has been implemented as part of my thesis. It compiles a K definition differently than usual compilation such that you can execute programs (having as input symbolic values) using Maude.
It is not related to java backend at all.

**Comment by andreiarusoaie** [comment]
@mdmkolbe : Just to clarify: I don't use any backend option at krun time at all. I run programs just in the usual way, as we do when we use Maude.

**Comment by osa1** [comment]
I don't know when was this implemented, but we don't have `--backend` in krun anymore. Closing.
