### ISSUE TITLE
Investigate race condition in kool-typed-static

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1497]
Periodically there is a test failure in kool-typed-static. This seems to be some kind of race condition of unknown origin, but it only is specific to this one definition for some reason. Not sure why. We should try to fix this.

**Comment by radumereuta** [comment]
Can you provide more information about this failure? Does kompile fail? Running specific programs? What is the error message?

**Comment by dwightguth** [comment]
This is what I have currently. More details will have to be investigated. Note that since this is more of a backlog issue than a user request, you don't have to work on this right away, Radu, I am just adding it to the backlog to track it.

http://office.runtimeverification.com:8080/rv-jenkins/job/k-framework-pull-requests/org.kframework.k$k-distribution/1415/testReport/junit/%28root%29/_var_lib_jenkins_jobs_k-framework-pull-requests_workspace_k-distribution_tutorial_2_languages_2_kool_2_typed_2_static/hello_world/

**Comment by yilongli** [comment]
Fixed in https://github.com/kframework/k/pull/1611
