### ISSUE TITLE
Unit tests stalling on RuleGrammarTest

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1503]
`Running org.kframework.parser.concrete2kore.RuleGrammarTest`
keeps the CPU at 100% for at least several minutes -- I've cancel the process.

**Comment by radumereuta** [comment]
Just tested this on my machine windows laptop, and it takes 2s for all tests in that file to pass.
I used IntelliJ.

**Comment by radumereuta** [comment]
This happened because of impropper merge of temporary branches. Closing.
