### ISSUE TITLE
[kompile+kore] no configuration = java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#1509]
```
module TEST
endmodule
```

If I try to `kompile --kore test.k` I get the following stacktrace:

```
java.lang.NoSuchMethodError: scala.collection.immutable.Set.$plus(Ljava/lang/Object;)Lscala/collection/SetLike;
    at org.kframework.kompile.Kompile.lambda$parseDefinition$9(Kompile.java:175)
    at org.kframework.kompile.Kompile$$Lambda$26/1865859824.apply(Unknown Source)
    at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:55)
    at org.kframework.definition.DefinitionTransformer$$anonfun$from$2.apply(transformers.scala:55)
    at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:47)
    at org.kframework.definition.ModuleTransformer$$anonfun$apply$5.apply(transformers.scala:42)
```

If I add a configuration in my file, then it kompiles just fine. This should work because in kast.k there is a default configuration which can be used.
@dwightguth I think you did that part. It should be an easy fix for you.

**Comment by dwightguth** [comment]
so, I can fix the immediate issue, but this still leaves us open to these types of problems going forward. I honestly feel like we need to come up with a better solution for the codebase than Scala collections, because we keep having these types of problems and it's not very nice.

@cos, how would you feel if we replaced the scala collections throughout the KORE interface with org.pcollections? they are also immutable and have a valuable interface for such, but the interface is actually designed to be used from Java.

**Comment by cos** [comment]
it seems the org.pcollections project is rather unmaintained (49 commits in total in its 6 years lifespan). Do we know anything about its performance characteristics?

I would rather stick with the Scala collections. Generally, the compiler is not confused if you don't use the `$` methods. We could either have external method aliases, or wrap the entire collection in our own interface (which would also allow us to have pluggable implementations).

**Comment by radumereuta** [comment]
`org.pcollections` have a crucial role in the parser. `PStack` at least is being tested right now and we didn't have any troubles with them. If you find any bugs, we can consider something else, but for the moment, I at least, am happy with this implementation.

**Comment by dwightguth** [comment]
I suggest, then, that we compare the performance of the two libraries against each other. If pcollections is faster, we will use that. If scala is faster, we will wrap the Scala classes into an interface similar to pcollections (ie, implements java.util but has instance methods for immutable construction).
