### ISSUE TITLE
LTLMC reporting deadlock node

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1517]
If a node is just final because no further rules apply (execution got stuck), is that considered a deadlock node to `ltlmc`?

Also, can I get any extra information about the deadlock like what is the locked resource? 

Thank you

**Comment by laurayuwen** [comment]
Hi Omar, 

In general, execution can also get stuck when programmer didn't not specify rules properly. We shouldn't regard this case as deadlock. But I think ltlmc doesn't distingsuish this case and real deadlock.
I don't think we have a detector for the locked resource. Sorry for that.

Shijiao

**Comment by omarzd** [comment]
OK. I'm talking about a configuration that is an acceptable final state according to my semantics. So should I make these syntactic categories that get stuck `KResult`?
I tried that and it still gave e deadlock!

**Comment by dlucanu** [comment]
What version of K Tool (and ltlmc) do you use?

**Comment by laurayuwen** [comment]
OK, so you have some state that you accept to be final, but it was judged as deadlock in ltcmc, but you don't want that, right? Any computation left in k cell for your final state?

**Comment by omarzd** [comment]
Yes, that's right. I accept the state as final but it was judged as a deadlock in `ltlmc`, and I don't want that. But I didn't understand your question. There are threads with computations left in their `k` cell.

**Comment by omarzd** [comment]
I am using the latest stable 3.5.

**Comment by laurayuwen** [comment]
I guess it is the computations left in K cell that makes ltlmc confused. Can you try craft a rule to remove the stuff in K cell (place it elsewhere maybe) when you reach the final state?

**Comment by dwightguth** [comment]
I'm going to jump in here and try to explain. Deadlock, in this context,
just means that the ltl model checker has detected a cycle in which a state
is succeeded by itself. Because Maude's model checker is based on infinite
sequences of states, a terminal state is simply represented by a state that
leads to itself. Thus, all final states present in a ltl counterexample
will be treated as deadlocks by the model checker. It shouldn't really
matter what the model checker calls it though... Can you explain why you
are concerned about this?

**Comment by omarzd** [comment]
OK, that makes sense. thanks @dwightguth. Actually it is a counter example. I shouldn't be concerned about this, now that I understand. Thank you

**Comment by dlucanu** [comment]
The way a non-total transition system is transformed into a total transition systems is depending on the model checker. Maude LTL model checker does it as Dwight explained.
I asked about the version just to be sure that Maude LTL model-checker is used.
