### ISSUE TITLE
kompile unnecessary error on ? variables

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#153]
kompile gives an inconvenient and unnecessary error if we have a ?T variable in some rule, while the variable T appears without a ? in other rules.  The name ?T is the most natural name one can give to such a don't know variable in a rule like

  rule <k> lambda X:Id . E:Exp => ?T:Type -> E::Type ~> env(TEnv) ...</k>
       <tenv> TEnv:Map => TEnv[?T / X] </tenv>

Yet, there is no way to kompile it:

[Error] Compiler: Variable T:Type  has the same name as a fresh variable.
    File: /home/grosu/k/tutorial/1_k/5_types/lesson_5.5/lambda.k
    Location: (49,12,49,18)
    Compilation Phase: class org.kframework.compile.checks.CheckVariables

Maybe you can keep the error for when the variables ?T and T appear in the same rule, but since variables have rule scoping the error message above makes little sense.  I therefore mark it as a bug.

**Comment by grosu** [comment]
Radu,

Can you please fix this?  It makes using the new rewrite engine quite cumbersome.

In general, it is a good strategy to fix trivial bugs as quickly as possible.  This gives you the time and peace of mind to focus on the more serious bugs without being perturbed by such messages.

Again, the problem is the following:

We would like to write rules in the type systems (and not only) as follows:

```
  rule <k> lambda X:Id . E:Exp => ?T:Type -> (E)::K ~> env(TEnv) ...</k>
       <tenv> TEnv:Map => TEnv[?T / X] </tenv>
```

(well, the :: is still not implemented correctly, either, but that is not the point here).  Unfortunately, we get the following error:

```
[Error] Compiler: Variable T:Type  has the same name as a fresh variable.
    File: /home/grosu/k/tutorial/1_k/5_types/lesson_5.5/lambda.k
    Location: (49,12,49,18)
    Compilation Phase: class org.kframework.compile.checks.CheckVariables
```

This makes no sense whatsoever.  We want to be allowed to use ? variables in rules (and soon also ! variables).

**Comment by radumereuta** [comment]
This step was originally implemented by Traian so I'm not really connected to it.
Grigore, can you delegate someone else (new comer) to deal with it?
This step is fairly independent. Low chances to break something.

**Comment by grosu** [comment]
Traian, what do you think?  In case it is not a trivial job, probably Yilong would be a good person to look into this, because he will also need it to specify his code-generation patterns.

**Comment by traiansf** [comment]
Ok, I'm changing the code to reset the set of fresh variables at sentence
level. Hope it works.

2013/12/2 Grigore Rosu notifications@github.com

**Comment by yilongli** [comment]
@traiansf,

I am running into this issue again in a slightly different situation. The following is the rule, or code-generation pattern, I would like to write:

```
rule [while-loop]: while (B) S => if (B) {S while (B) S} else {} [structural]

rule while (B) S => if (B) {S while (B) S} else {}
  requires B ==K ($1 < 10) andBool S ==K { ?S':Stmt $1 = $1 + 1; }
  [structural, testgen-precede(while-loop)]
```

However, I get error like this:

```
[Error] Compiler: Fresh variable "S':Stmt " is bound in the rule pattern.
    File:
/home/yilongli/Eclipse-Workspaces/sbtg-workspace/java_rewrite_engine/tutorial/2_imp/imp.k
    Location: (81,45,81,53)
    Compilation Phase: class org.kframework.compile.checks.CheckVariables
```

**Comment by traiansf** [comment]
can you create an issue, or at least attach the problematic file here?

Traian

2013/12/11 Yilong Li notifications@github.com

**Comment by yilongli** [comment]
This error occurs whenever a fresh variable like ?X appears in the side
condition.

Yilong
