### ISSUE TITLE
No support for Char2String and String2Char functions

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#1563]
I have the definition as follow:

```
module TEST

    syntax KItem ::= String
    syntax KItem ::= Bool
    rule "a" => "a" ==K "a"
    rule "b" => "b" ==K Char2String(String2Char("b"))
endmodule
```

If the input program is "a", the result will be:

```
<k>
    true
</k>

```

if the input program is "b", the result will be:

```
<k>
    "b" ==K Char2String ( String2Char ( "b" ) )
</k>

```

**Comment by dwightguth** [comment]
K has no dedicated Char sort. A Char is simply a String of length 1. You can use ordChar and chrChar to convert between Unicode code points and integers.

**Comment by liyili2** [comment]
OK.
