### ISSUE TITLE
Nested function calls

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1564]
I have this:

```
    syntax Bag ::= function1(Bag)   [function, klabel(function1Lable)]
    syntax Bag ::= function2(Bag)   [function, klabel(function2Lable)]
    syntax Bag ::= function3(Bag)   [function, klabel(function3Lable)]
```

When I do 

```
rule stuff1 => function1(function2(function3(stuff2)))
```

the rule does apply, but the **following rule does not**:

```
rule function3(stuff2) => stuff3
```

So I find the output stuck in nested calls `function1(function2(function3(stuff2)))`.

**Comment by omarzd** [comment]
No answer?

**Comment by dwightguth** [comment]
Apologies. This seems likely to be some kind of issue associated with the injection of the Bag sort into K. Can you please try to create a wrapper around the bag (e.g. `syntax KItem ::= bag(Bag)`) and determine whether that allows you to work around this issue?

**Comment by bmmoore** [comment]
Is your second rule menat to have the function on the left-hand side? If that's actually the way you wrote it, it's not meant to be supported, and the only issue is that you didn't get a clear compiler error.

**Comment by omarzd** [comment]
@dwightguth OK I inserted exactly that line, but nothing changed. How should I use this `bag` wrapper? By the way, I don't understand at all the problem and how a wrapper could fix it.

**Comment by omarzd** [comment]
OK. I came across a similar scenario. Here is what I had:

```
rule [1]:
  function1(
    <thread>... 
      <k> something1 => something_else </k> 
      <c> condition1 </c>
    ...</thread>
  )
rule [2]:
  <thread>...
    <k> something1 </k>
    <c> . => condition1 </c>
  ...</thread>
```

In order for `rule [1]` to execute, it needs `rule [2]` to execute first because `rule [2]` will provide `condition1`. However, if in runtime you had:

```
  function1
    (<thread>... 
    <k> something1 </k>
    <c> . </c>
  ...</thread>)
```

if you had that, then `rule [2]` will not execute even though it matches the environment at runtime. What made it work is removing the surrounding cell `<thread>` from `rule [2]` making it:

```
rule [2_fixed]
    <k> something1 </k>
    <c> . => condition1 </c>
```

It's as if having the `<thread>` cell in the rule is a specification that the thread will be surrounded in the environment by its parent cell, usually `<threads>`, NOT by any function! Is that intended behavior? Can we get around it?

**Comment by dwightguth** [comment]
K rules that are not function rules are considered to apply at the top of the configuration. So your rule [2] will likely not apply on the argument of function1 because it has been completed to the top and thus requires that  the `<thread>` cell lives inside its immediate parent. Why it works if you remove the `<thread>` cell entirely, I'm not sure, that looks like a bug. If you want the rule 2 to apply during evaluation of function1, you should probably wrap it in that context.
