### ISSUE TITLE
[tutorial-kore branch] data race on field org.kframework.kompile.Kompile.parsedBubbles

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1568]
@bmmoore I ran `kompile --kore imp.k` on your tutorial-kore branch and got the following race report:

```
Data race on field org.kframework.kompile.Kompile.parsedBubbles: {{{
    Concurrent write in thread T14 (locks held: {})
 ---->  at org.kframework.kompile.Kompile.performParse(Kompile.java:407)
        at org.kframework.kompile.Kompile.lambda$resolveBubbles$101(Kompile.java:315)
        at org.kframework.kompile.Kompile$$Lambda$161.apply(Unknown:n/a)
    T14 is created by n/a

    Concurrent read in thread T13 (locks held: {})
 ---->  at org.kframework.kompile.Kompile.performParse(Kompile.java:407)
        at org.kframework.kompile.Kompile.lambda$resolveBubbles$101(Kompile.java:315)
        at org.kframework.kompile.Kompile$$Lambda$161.apply(Unknown:n/a)
    T13 is created by n/a
}}}
```

I took a quick look at the source code: https://github.com/kframework/k/blob/e2d6df353dfa237443139b1f95d8d912305817d9/kernel/src/main/java/org/kframework/kompile/Kompile.java
It looks like a real race to me.

**Comment by bmmoore** [comment]
@dwightguth it looks like parallelism in Kompile is entirely from your commits, starting with 446d2335cabea4e6f220305b008ba6d0376af94f. Did you have a plan for the caching?

**Comment by dwightguth** [comment]
This is actually Radu's code. The precise count is not used for anything except debugging output so it's not terribly high priority. Adding a lock would introduce contention. @yilongli do you have a recommendation for how to remove the race without lock contention?

**Comment by bmmoore** [comment]
AtomicInteger should be enough for the count, I'm worried more about the cache. Maybe concurrentHashMap.computeIfAbsent or a guava MapMaker.makeComputingMap would work, but the map creation is currently fairly distant from this parsing method so it might take a bit of refactoring.

**Comment by dwightguth** [comment]
Sorry I have no idea what a "chace" is, can you explain what you're referring to?

**Comment by bmmoore** [comment]
That was supposed to be "cache".

**Comment by yilongli** [comment]
@dwightguth For this specific race, just make `parsedBubbles` an atomic integer. 

I don't follow the discussion about cache. Is it related to this race report?

**Comment by dwightguth** [comment]
Brandon's concern is over the cache map, but that map is synchronized so it should be fine.

**Comment by bmmoore** [comment]
Yeah, I didn't follow the source of the parser cache back far enough to see that it's wrapped in synchronizedMap.
