### ISSUE TITLE
unnecessary synchronization block on `scopedObjects`

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1578]
I notice that the unnecessary synchronization block on `scopedObjects` introduced in https://github.com/kframework/k/commit/b452074efb889fe29faf4cc2a28c796e2c82ecd0 is still there. Reason: https://github.com/kframework/k/pull/1276#issuecomment-76573850

**Comment by dwightguth** [comment]
Er it's an InheritableThreadLocal... If the main application thread spawns another thread and then invokes a provider that ends up calling this method in order to provide its object, there could be a race here I believe.

**Comment by yilongli** [comment]
OK, I think you are right.
