### ISSUE TITLE
kompile --backend pdf forgets a dangling k.sty

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#158]
A k.sty file is created each time the --backend pdf option is used.

Please do not blindly "git add ~/k", because you can possibly add all kind of garbage to the repository, such as these k.sty files.

**Comment by osa1** [comment]
should be fixed now.

**Comment by traiansf** [comment]
The .sty file should be there only when the backend latex is used.  It puts
the .sty there so that you can easily compile the generated .tex

It should not be there for the pdf backend.

best wishes,
Traian

2013/11/17 Grigore Rosu notifications@github.com

**Comment by osa1** [comment]
@traiansf should pdf backend copy generated .tex file to root folder?

If I understand correctly, when pdf backend is used only .pdf should be copied to root folder, and when latex packed is used .sty and .tex, is that right?

If that's right, I need to make some more changes.

**Comment by traiansf** [comment]
Yes, this is how it used to be, at least...

I think we have experimented at first with importing the .sty file directly
from include/latex;  the problem with that was that if one wanted to move
the .tex file it would have to change the path.

best wishes,
Traian

2013/11/17 Ömer Sinan Ağacan notifications@github.com

**Comment by grosu** [comment]
But please do not generate anything else but the PDF file when the --backend pdf option is used, both when the pdf generation succeeds and when it fails.  I've spent more than 1 hour to clean up my folders after ktest infested all my folders with k.sty and .tex files.

Grigore

**Comment by osa1** [comment]
It should be done now.

@grosu, you don't need to spend hours for these kinds of things, you could use `find . -name "*.sty" -exec rm {} \;` or something similar.

**Comment by traiansf** [comment]
you can also use git clean

http://stackoverflow.com/questions/61212/removing-untracked-files-from-your-git-working-copy

2013/11/17 Ömer Sinan Ağacan notifications@github.com

**Comment by grosu** [comment]
That's exactly what I did.  Actually,

  find -iname *.sty | xargs rm -v

But that also removed the k.sty from k/include/latex and then I made several other commits, so to recover it I had to checkout from origin.  It also removed some latex files which I had my own notes for teaching, etc, which fortunately I had somewhere else saved.  So ... better no garbage, please.

Grigore
