### ISSUE TITLE
Type inference fails with overloading, for variables and wildcards

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#1586]
I thought type inference was supposed to give variables the most general types that let a rule parse, and then assign other labels and terms the least sorts after that.
This doesn't seem to always work, and also I get different errors about variables and wildcards. Here's a sample definition, to be saved as `test.k`

```
require "domains.k"
module TEST-SYNTAX
syntax A ::= B | "a"
syntax B ::= "b"
syntax TA ::= TB | t(A) [klabel(t)]
syntax TB ::= t(B) [klabel(t)]
endmodule
module TEST
imports MAP
imports TEST-SYNTAX
configuration <k>$PGM:K</k>
rule t(X)::TA => .K
rule t(Y) => .K
rule t(_) => .K
endmodule
```

Compiling it produces as `kompile --kore test.k` produces this output:

```
[Error] Compiler: Had 1 parsing errors.
[Error] Critical: Could not infer a unique sort for variable 'Y'. Possible
sorts: A, B
    Source(/home/brandon/test/k/wildcard/././test.k)
    Location(13,6,13,16)
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: syntax TB ::= "t" "(" B ")"
[Location(#token("6",Int),#token("15",Int),#token("6",Int),#token("30",Int))
Source(#token("/home/brandon/test/k/wildcard/././test.k",KString))
klabel(#token("t",AttributeValue)) klabel(#token("t",KString))]
    t(#SemanticCastToB(#token(#KVariable,"_")))
2: syntax TA ::= "t" "(" A ")"
[Location(#token("5",Int),#token("20",Int),#token("5",Int),#token("35",Int))
Source(#token("/home/brandon/test/k/wildcard/././test.k",KString))
klabel(#token("t",AttributeValue)) klabel(#token("t",KString))]
    t(#SemanticCastToA(#token(#KVariable,"_")))
    Source(/home/brandon/test/k/wildcard/././test.k)
    Location(12,6,12,10)
```

Note that there's an error about `Y` but not `X` even though `Y` could be typed just like `X`, and that the wildcard gets only a warning even though the ambiguity is equivalent to the ambiguity about `Y` (and it just happens to default to the less general type).

I expected all of X, Y, and _ to end up having inferred type A.

**Comment by grosu** [comment]
This looks indeed like a bug to me.  @radumereuta ?

**Comment by grosu** [comment]
@bmmoore:

> I thought type inference was supposed to give variables the most general types that let a rule parse, > and then assign other labels and terms the least sorts after that.

Yes, variables should be inferred the largest sorts, but so should be the terms!  The rationale is that one always has the option to use `Term::Sort` to enforce a smaller sort to a term if one wants to, while it is impossible to do the same for a larger sort.

I'm adding some notes for @radumereuta to the manual, to clarify these better.
