### ISSUE TITLE
Wrong start symbol in new parser

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#1589]
It seems the new parser always tries to parse the program in sort K, rather than taking the start sort from the $PGM variable as in the old pipeline. We also can't use `#parse` because it does try to parse as `K` rather than just supplying the text of the program as a string in `$PGM`.

**Comment by bmmoore** [comment]
Thinking of workarounds, something seems to be broken also with `-pPGM` in `krun` with the kore pipeline, but the `--parser` flag works, like `--parser "kast --kore -s <correct start symbol>"`

**Comment by bmmoore** [comment]
Because of the workaround with the `--parser` flag this isn't blocking work on updating the tutorials, but it would definitely be nice.

**Comment by bmmoore** [comment]
Kore execution is now working well enough that this is one of the biggest remaining issues in saying K can handle the tutorials.

**Comment by radumereuta** [comment]
As I was explaining this to @bmmoore, the sort should be provided by `krun`. Taken from the configuration, and call the parser with the appropriate sort.
I think this is handled the same way with the rest of the configuration variables.
I'm not going into `krun` so whoever is in charge of krun, please take over.

**Comment by bmmoore** [comment]
I see this is actually a duplicate of  #1520

**Comment by bmmoore** [comment]
Looks `CompiledDefinition.programStartSymbol` does save and restore a sort, but `KompileFrontEnd.java:88` currently hardcodes it to `K`.
