### ISSUE TITLE
Kore execution problems, maybe from unification?

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#1594]
On the current master, a KORE version of IMP++ cannot run even sum.imp. Something seems to be wrong in unification. First, grab a imp++ from the tutorial-kore branch

```
git checkout tutorial-kore -- k-distribution/tutorial-kore/1_k/4_imp++/lesson_8/imp.k
```

Compiling succeeds:

```
k-framework/k-distribution/tutorial-kore/1_k/4_imp++/lesson_8$ kompile --kore imp.k
```

but running a program doesn't terminate
    k-framework/k-distribution/tutorial-kore/1_k/4_imp++/lesson_8$ krun --kore --smt none --parser "kast --kore -s Stmts" ../../../../tutorial/1_k/2_imp/lesson_1/tests/sum.imp 

and the debugger shows parts of the configuration being replaced by variables, and then no apparent progress:

```
k-framework/k-distribution/tutorial-kore/1_k/4_imp++/lesson_8$ krun --kore --smt none --debugger --parser "kast --kore -s Stmts" ../../../../tutorial/1_k/2_imp/lesson_1/tests/sum.imp 

Command > step
<T> <threads> <thread> <k> ` _188 && _182 ` ~> _190 </k> _183 _184 </thread> _189 </threads> <store> .Map </store> <in> .List </in> <out> .List </out> </T>

Command > back-step
<T> <threads> <thread> <k> int n , ` sum , .AExps ` ;  ` ( n = 100 ) ;  ` ( sum = 0 ) ;  ` ` while ( ! ` n <= 0 ` ) { ( sum = sum + n ) ;  ` ( n = n + -1 ) ;  .Stmts ` } `  .Stmts ` ` ` </k> <env> .Map </env> <id> 0 </id> </thread> </threads> <store> .Map </store> <in> .List </in> <out> .List </out> </T>

Command > step
<T> <threads> <thread> <k> ` _197 && _191 ` ~> _199 </k> _192 _193 </thread> _198 </threads> <store> .Map </store> <in> .List </in> <out> .List </out> </T>

Command > step
<T> <threads> <thread> <k> ` _206 && _200 ` ~> _208 </k> _201 _202 </thread> _207 </threads> <store> .Map </store> <in> .List </in> <out> .List </out> </T>
```

further steps just change the variable numbers. Running without `--smt none` produces error messages from the solver, but doesn't otherwise seem to make more progress.
@andreistefanescu , @yilongli , please take a look.

**Comment by bmmoore** [comment]
I'll assign this to @andreistefanescu  for now. Can you take a look at this? I think you promised you would look into anything that's stopping the Java backend from running Kore, and I'd really like to have more than just IMP available in kore for my own work.

**Comment by andreistefanescu** [comment]
Fixed.
