### ISSUE TITLE
ktest - skip not allowed in config files?

### ISSUE THREAD

**Issue by andreiarusoaie** [kframework/k-legacy#160]
```
fmse:k$ cat config.xml
<?xml version="1.0" encoding="utf-8"?>
<tests>
  <test
      definition="samples/prog-equiv/imp/peq.k"
      programs="samples/prog-equiv/imp/programs"
      extension="peq"
      results="tests/examples/prog-equiv/" 
      skip="pdf">
      <kompile-option name="-add-top-cell" />
      <all-programs>
        <krun-option name="-output" value="none" />
        <krun-option name="-color" value="off" />
      </all-programs>
  </test>
</tests>

fmse:k$ ktest config.xml
Buildfile: config.xml
[Error] Critical: The given configuration file is not valid:
cvc-complex-type.3.2.2: Attribute 'skip' is not allowed to appear in element
'test'.
    File: /home/andrei.arusoaie/work/k/config.xml
    Location: System file.

fmse:k$ 
```

I thought skip works for every test. I added this feature myself to the old ktest. Did this disappeared completely or this is not the right way to use it?

**Comment by andreiarusoaie** [comment]
Omer, I really need this attribute to work in config files. Please add it back.

**Comment by osa1** [comment]
I didn't remove this feature and I didn't know it existed. I'll look into old ktest source and see how it can be used.

It may be the case that even though in XML schema file that we use for validation does not specify `skip` attribute(thus you're getting this error), ktest may be implemented that. In this case it's simple one line fix.

Let me check.

**Comment by osa1** [comment]
@andreiarusoaie it should be working now https://github.com/kframework/k/commit/14321f635b85104430dc024fa4becb1f3d9f79ba

**Comment by andreiarusoaie** [comment]
Great! Thanks.
