### ISSUE TITLE
Type inference ignoring ambiguity

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#1603]
In this example the last rule ends up with an inferred type of `X` for `X`, despite `A` and `B` also being legal sorts and none greater than the others. There are no warnings besides the informative messages that some variables are assigned inferred types.

```
require "domains.k"
module TEST-SYNTAX
syntax T ::= "wrap" M [klabel(wrapM)] | "wrap" X [klabel(wrapX)]
syntax A
syntax B
syntax M ::= A | B
syntax N ::= A | B | X // make A and B both maximal in the intersection of N and M
syntax X
syntax KItem ::= label(N,T)
endmodule
module TEST
imports MAP
imports TEST-SYNTAX
configuration <k>$PGM:K</k>
rule X => label(X,wrap X:A)
rule X => label(X,wrap X:B)
rule X => label(X,wrap X:X)
rule X => label(X,wrap X)
endmodule
```

This happens because VariableTypeInference filter handles parsing ambiguities (between the two "wrap" productions in this case) and type checking together by producing multiple sets of type constraints corresponding to combinations of ambiguous parses, throws out some sets of constraints, and then succeeds if a single uniquely-solvable set of constraints remains.
However, instead of just throwing out inconsistent sets of constraints it also throws out constraints which have multiple solutions but no greatest solution (e.g, X can be either A or B in the constraints coming from the parse of "wrap" as wrapM), before seeing if a single solution remains.

**Comment by grosu** [comment]
This is a very interesting and well thought of example, @bmmoore! As a user, I'd like to see an error/warning message here telling me that variable X can have any of the sorts A, B, and X.

**Comment by bmmoore** [comment]
That's exactly what you will get with changes in #1604.

**Comment by grosu** [comment]
@bmmoore I think this example is nice to include in the manual.  Can you please add it there, with some text extracted from our recent discussions?  Now it is the right moment to do it, because it is still fresh in our mind.  We'll have to soon start writing the manual, we have too much pressure on our shoulders from users.

**Comment by bmmoore** [comment]
Ok, it's added next to the other text on inference.

**Comment by bmmoore** [comment]
(I thought I put the magic text in the #1604 message to automatically close this issue when it merged, looks like it didn't read past the "and")
