### ISSUE TITLE
ktest --- final result needs to be displayed

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#161]
We need ktest to report a big, bold, and grren or whatever color you want "SUCCESS" when everything passes, or a big, bold and read "FAIL (see details above)" message when anything fails.  Otherwise, as we accumulate more and more tests and since each of has to run ktest locally before committing, we collectively waste a lot of time having to go up through the list of displayed tests to make sure none failed.  We want to just see it immediately when the ktest command terminates.

**Comment by grosu** [comment]
Even better, report also statistics.  For example, in the case of success, report something like this if possible:

```
SUCCESS: All tests passed.

Definitions kompiled: 95   (5'27'')
PDF posters kompiled: 95   (6'45'')
Programs krun: 797   (9'23'')
Total time: 21'35''
```

**Comment by osa1** [comment]
Done in #193.
