### ISSUE TITLE
krun - command line variables parser

### ISSUE THREAD

**Issue by andreiarusoaie** [kframework/k-legacy#166]
I would like to be able to tell krun which parser to use for parsing command line terms. For instance, when I call:

```
krun -parser "kast -parser rule" ../lesson_1/tests/sum.imp -cPC="N:Int <=Int 3"
```

I would like to be able to set up the the parser for the value of -cPC option because in this case I want to use the rule parser instead of the default (ground) parser.

**Comment by denis-bogdanas** [comment]
Please be careful not to change the current behavior of the external parser and command line arguments parser, if they are not explicitly specified. In other words, please preserve backwards compatibility. Why I'm worrying - this was already broken once. Thanks for understanding.

**Comment by grosu** [comment]
I am pretty sure that Dwight also needed that, so it probably already works.  Did you try to use the --parse option with the desired parameter before each -c option?  In case it does not work, Daejun, can you please make sure that this functionality has not been lost when you updated the option handling?

**Comment by andreiarusoaie** [comment]
Oh, I didn't noticed that it already exists. Thanks Grigore for pointing me to it and sorry for disturbing everyone about this. 
I'm closing the issue since it doesn't make sense anymore.

**Comment by dlucanu** [comment]
However, it is good to know that the parser "rule" is more than a parser, it also includes some post-processing steps like contextual transformation, adding top cell, resolving anonymous variables .... Therefore it is not suitable for parsing configuration variables.
Perhaps in the future we need a new parser, say "kfull" that has as input a fragment of legal full K code and returns the KAST.
