### ISSUE TITLE
Add support for search

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1667]
--search and --pattern need to be supported

**Comment by grosu** [comment]
@msaxena2 , please note that you have been assigned to do this task.  We'd like to be done with everything needed for the tutorial examples to work with minimal changes before we start the next week if at all possible, so I hope you can work on this today.

**Comment by msaxena2** [comment]
This issue may also be linked to how we handle #1673 (The superheat/supercool issue does not block search though).

**Comment by msaxena2** [comment]
Handled in #1717
