### ISSUE TITLE
Prover frontend

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1669]
need to implement the frontend for the prover for KORE.

**Comment by grosu** [comment]
@andreistefanescu, I see that you are done with KernelC, which is wonderful!  Is the prover frontend the next thing on your list?

**Comment by andreistefanescu** [comment]
@grosu I have a bunch of other small bug fixes to do first, but after that I will work on the prover frontend.

**Comment by andreistefanescu** [comment]
fixed in #1736
