### ISSUE TITLE
KBott/K issue for parsing

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1670]
Need to fix the issue with KBott being a user-visible sort, which causes problems for productions that include K in them.

**Comment by bmmoore** [comment]
I think this will be mostly handled when we finish implementing the change to track the origin module of sorts. Don't we parse rules using a new module that imports the user module, plus k-in-k syntax from kast.k? If so, the KBott from the K syntax isn't imported from any common point with any user sort that they happen to name KBott, and the system would keep them apart (unless perhaps they explicitly required kast.k and imported some modules).

**Comment by grosu** [comment]
If this is a problem that we had before with KIL, too, then it should not be part of this list.  All we care about now is to get rid of KIL and have all the existing tests work.  @dwightguth , if that is the case, please remove the milestone from this issue yourself, to speed up the transition.  Thanks.

**Comment by bmmoore** [comment]
We didn't have a KBott sort before (SDF had some fancy cycle-breaking declaration that allowed declaring the K sort both below and above every other sort without creating infinite parses). @dwightguth, is the only issue here that the user can explicitly refer to the KBott sort?

**Comment by dwightguth** [comment]
No, the issue is that if I have a production that returns a K, it will not currently fit in a spot that expects an Exp. This is because KBott is treated as an actual sort instead of being hidden from the user and used only internally in cases when productions have a return sort of KItem or K.

**Comment by grosu** [comment]
> the issue is that if I have a production that returns a K, it will not currently fit in a spot that expects an Exp.

This is serious.  @radumereuta can you please look into this?

**Comment by cos** [comment]
@radumereuta, is this still an issue?
