### ISSUE TITLE
Nondeterminism in heating/cooling

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1673]
Need nondeterministic heating and cooling to work correctly (either superheat/supercool or something involving strategies)

**Comment by grosu** [comment]
@cos, if I remember correctly, you said this will be solved with strategies, right?  But if that is your plan, then this will probably take quite a bit or time to be done, won't it?  Is there something quick that we can do now to transit with all the tests passing, and do the strategies afterwards?

**Comment by cos** [comment]
The hack-in extreme is to special-case for superheating/cooling like before. The clean extreme is to wait for a clean implementation of strategies (which depends on several other things). I'm working on a middle ground: have the superheating/cooling executed by strategies, but not expose the mechanism to the users just yet -- we'll have to figure out modularization and configuration merging before that. This approach will be ready in a few days for the Java backend.

**Comment by grosu** [comment]
Alright, this sounds like a good plan.  This will also allow you to better understand what you need from the final strategy language that you will eventually come up with, so it fulfills multiple roles.  Thanks.

**Comment by grosu** [comment]
@cos , and ETA on this?

**Comment by cos** [comment]
If everything goes well, I'll make a pull request today. I might need something from Dwight and then I'll make it tomorrow.

**Comment by cos** [comment]
as discussed, we're moving this to 4.1
