### ISSUE TITLE
Rule auditing option bugs

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#1675]
There are a few problems in the rule auditing option parsing

The `-X` text for `--audit-line` and `-audit-file` mention an `--apply-step` option that doesn't exist, but seem to work with `--audit-step`. The text for `--audit-step` does not mention either of those options, only an `--apply-tag` option which is also unknown (it's not `--audit-tag` either).

Passing `--audit-step` and `--audit-line` without `--audit-file` results in an NPE:

```
java.lang.NullPointerException
    at java.lang.String.contains(String.java:2121)
    at org.kframework.backend.java.symbolic.RuleAuditing.setAuditingRule(RuleAuditing.java:51)
    at org.kframework.backend.java.symbolic.PatternMatchRewriter.computeRewriteStep(PatternMatchRewriter.java:194)
```

**Comment by grosu** [comment]
@dwightguth , @msaxena2 : shouldn't rule auditing be incorporated in the debugger?

**Comment by dwightguth** [comment]
Yes, I agree, rule auditing should be turned on when the user runs the match command.
