### ISSUE TITLE
List Parsing adding terminator badly

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#1682]
While trying to fix IMP++ with kore, writing the while rule as

```
rule while (B) S => if (B) {`__`(S,`__`(while (B) S,.Stmts))} else {.Stmts}  [structural]
```

parsed the inside of the first block as

```
`__`(`__`(S,`__`(while (B) S,.Stmts)),.Stmts)
```

with an extra terminator.

**Comment by bmmoore** [comment]
Please also check the concrete syntax works, like `{S while(B) S}`. I think that was rejected with a parse error.

**Comment by grosu** [comment]
Interesting.  How about `{`__`(S,while (B) S)}` ?

**Comment by bmmoore** [comment]
That parses exactly as written, but the label from a list production is still getting declared as a cons list so that rule doesn't work correctly.

**Comment by bmmoore** [comment]
Actually, I'm not sure whether or not it's getting an extra terminator around it, but that part you wrote is enough to cause problems on its own.

**Comment by bmmoore** [comment]
I haven't been able to reproduce this on top of the current master. Maybe something fixed it in the meantime? @andreistefanescu, had you run into this?

**Comment by bmmoore** [comment]
Ok, try `kompile --kore imp.k` in `k-distribution/tutorial/1_k/4_imp++/lesson_8/` at bf3310a1343c0da0ca16639aa27b0bde5d5356ac (in my tutorial-kore pull request).

**Comment by bmmoore** [comment]
Actually, labeled form still gets a bad terminator. I had only tried to reproduce the parse error on the concrete syntax which led us to use labeled form in the first place. Here's a minimal example of the bug:

```
require "domains.k"
module TEST
imports BOOL
imports MAP
configuration <k>$PGM:K</k>
syntax Stmts ::= List{Stmt,""}
syntax Stmt ::= "a" | "b" | "{" Stmts "}"
rule { S } => S
// rule a => { b b } // This version works okay
rule a => { `__`(b,`__`(b,.Stmts)) } // This parses with an extra terminator
rule b => .K
rule S1::Stmt S2::Stmts => S1 ~> S2
rule .Stmts => .K
endmodule
```

The program `a` gets stuck at configuration

```
`<k>`(`{_}`(`__`(`__`(b(.KList),`__`(b(.KList),`.List{"'__"}`(.KList))),`.List{"'__"}`(.KList))))
```

**Comment by msaxena2** [comment]
I ran into a similar problem while dealing with Simple. Here are the relevant details:

```
syntax Bottom
syntax BotCommaList ::= List{Bottom, ","}
syntax Exps ::= List{Exps, ","} | BotCommaList
syntax Vals ::= List{Vals, ","} | BotCommaList
syntax Exps ::= Vals | BotCommaList

rule <k> lambda(Xs,S)(Vs:Vals) ~> K => (Irrelevant) <k>
```

The program gets stuck with the k cell reading : 

```
<k> lambda ( .BotCommaList , { var a , .BotCommaList ; ` ( a = 2 ) ; ` ` a ; ` } ) ( .BotCommaList ) ~> #freezer18 ( ) </k>
```

and auditing with KRun returns:

```
auditing rule <T>(<k>(_(_)(lambda(Xs:Ids,, S:Stmt),, _,_(Vs:Vals,, .List{"'_,_"}(.KList))) ~> K:K),, .....(Irrelevant)....
matching/unification failure: .List{"'_,_"} and _,_
```

The reason behind the failed match could be that variable Vs in rule above was parsed as  `_,_(Vs:Vals,, .List{"'_,_"}(.KList))`, and hence match with .BotCommaList in configuration, having klabel .List{"'_,_"}, failed.
