### ISSUE TITLE
Still a lingering issue with ::

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#17]
rule T => #if T ==K . #then . #else T::Int #fi

This rule kompiles to something that checks isInt. Radu?

**Comment by dwightguth** [comment]
This still makes T a KItem instead of a K. I am removing priority-critical though because a parentheses fixes this bug now, which means I can move forward with python even if you don't fix this right away.

**Comment by radumereuta** [comment]
Just tested it and this is no longer an issue.
