### ISSUE TITLE
Need subsorting between related lists.

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#1705]
The kore kompile and/or krun don't automatically recognize lists of related elements as related sorts. This can be worked around with explicit subsort productions. @andreistefanescu , @radumereuta , where was this handled before?

**Comment by radumereuta** [comment]
The code that handles this in K3 is found in
 `org.kframework.compile.transformers.CompleteSortLatice:122`.
For the definition only, I'm looking for lists where the separator is the same, and if the elements are subsorted, then I automatically add a subsort to the module.

I can have a look at it tomorrow.

**Comment by grosu** [comment]
So, is this issue closed now?

**Comment by cos** [comment]
done
