### ISSUE TITLE
latex backend: new line required after each line of comment

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#171]
Otherwise we will get problems with definitions like:

module TEST
//@ Please don't comment Latex code generated for emdmodule: %
endmodule

**Comment by denis-bogdanas** [comment]
Problem still present.

**Comment by adamsmd** [comment]
We need more details.  Please specify how to produce the problem, the 
expected results and the actual results.

**Comment by dwightguth** [comment]
Next steps here?
