### ISSUE TITLE
kompile---needs better error message for Token

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#173]
If you write the following Token production

  syntax TypeVar ::= Token{['][a-z][_a-zA-Z0-9]*}           [notInRules]

then you get the following error message:

[Error] Parser: org.kframework.parser.basic.TokenMgrError: Lexical error at
line 242, column 29.  Encountered: "\'" (39), after : ""

The line number is good, but:
1) The column should be 28 and not 29, because ' is at column 28.
2) the ", after : \"\"" part makes no sense, I have no idea what it means.

Everything works fine if I write \' instead of '.

**Comment by radumereuta** [comment]
In a regular expression (which in this case is taken straight from SDF), this is how you should write it.
Every character, except for a-zA-Z0-9 has to be escaped by backslash.
Also, underscore should have been escaped. I don't know if you did, or if github hides it.

But the error message is misleading indeed, so I'll assign Michael on this.
