### ISSUE TITLE
add support for indexing in the kore-based java backend

### ISSUE THREAD

**Issue by andreistefanescu** [kframework/k-legacy#1732]

**Comment by grosu** [comment]
So guys, what's going on here?  I thought that @msaxena2 was supposed to do the indexing 2 days ago or so; now I see that @cos was assigned instead.  @cos, are you taking over everything related to the Java rewrite engine, both the indexing and the old performance optimizations?

**Comment by msaxena2** [comment]
@cos mentioned that he needed some to decide whether the indexing and performance optimizations were linked. I assigned the issue to him to make sure that he doesn't forget to have a look at the indexing parts as well. However, I will reassign it to myself if he decides to treat the performance as a separate unit that's not linked to the indexing issue.

**Comment by cos** [comment]
Indexing and other performance optimizations are very related so they can be solved together. I'm working on this with @andreistefanescu and we should have numbers in a few days (likely Tue/Wed). It may take a few more days after that to have the pull request merged depending on many things we manage to brake along the way.

**Comment by cos** [comment]
done
