### ISSUE TITLE
Remove org.kframework.main.OptionsParser

### ISSUE THREAD

**Issue by adamsmd** [kframework/k-legacy#174]
As far as I can tell, org.kframework.main.OptionsParser is unused.  Can this file be removed?

**Comment by osa1** [comment]
Yes, please remove it.

(I'm removing all unused classes without asking anyone all the time. When they're needed again, we can bring them back using git commit history and they will probably never be needed, there's still huge amount of unused code in the codebase, even though I'm removing them for weeks now)

**Comment by dwightguth** [comment]
Resolving due to #244.
