### ISSUE TITLE
Cell Fragments Related Issue

### ISSUE THREAD

**Issue by msaxena2** [kframework/k-legacy#1744]
I ran into the following problem while trying to work with Simple. Here are the relevant details:
Consider the following configuration:

```
<T>
    <a> <b> .List </b> <c> .List </c> </a>
</T>
```

A pattern of the form `<a> <b> X </b> Y:ACellFragment </a>` compiles to: ``<T>`(`<a>`(`<b>`(X), Y)) requires __andBool__(isList(X), isACellFragment(Y))`. 

A match on any configuration using this pattern fails as the inferred sort of Y during the match is CCell, and isACellFragment(Y) fails as CCell isn't a cell subsort of ACellFragment.

**Comment by cos** [comment]
@msaxena2, is this still failing?
