### ISSUE TITLE
cell fragment as an argument

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1748]
Consider the following example that is simplified from KOOL.

```
configuration <T> 
  <k> $PGM:K </k>
  <x> 
    <a> 1 </a>
    <b> 2 </b>
    <c> 3 </c>
  </x>
</T>

syntax KItem ::= frag(XCellFragment)

rule frag(<x>-fragment `<a> A </a>`:>ACell `<b> B </b>`:>BCell C </x>-fragment) => A +Int B

rule <k> run1 => frag(X) ... </k>
     <x> 
       X:XCellFragment
       <c> _:Int </c>
     </x>

rule <k> run2 => frag(A B) ... </k>
     <x> 
       A:ACell
       B:BCell
       <c> _:Int </c>
     </x>
```

Rule `run1` works, but `run2` does not. 

@bmmoore  Any idea?

**Comment by daejunpark** [comment]
see also #1744

**Comment by daejunpark** [comment]
see also #1747

**Comment by bmmoore** [comment]
To make this work, I think we will need special handling for cell fragments in rule parsing and configuration abstraction, like we already specially handle cells (also #1747, but that's a fairly independent problem).

For a workaround, you can try changing the right hand side to

```
frag(<x>-fragment A B `noCCell`() </x>-fragment)
```

handling fragments in configuration abstraction would let you write

```
frag(<x>-fragment A B </x>-fragment)
```

and then more work in parsing should allow

```
frag(A B)
```

**Comment by bmmoore** [comment]
Do you need to write rules like `run2` instead of `run1`?

**Comment by daejunpark** [comment]
@bmmoore yes, but as we discussed, I'll first try to use K instead of *CellFragment sort as the argument sort, to see if there are any other issues.

**Comment by bmmoore** [comment]
Did you also try the workaround I suggested with explicitly writting a cell fragment term instead of just `A B`?

**Comment by bmmoore** [comment]
Writing `rule <k> run2 => frag(<x>-fragment A B noCCell </x>-fragment) ... </k>` is at least accepted by the parser

**Comment by cos** [comment]
@daejunpark, can we consider this solved?
