### ISSUE TITLE
Use static initializers to set GlobalSettings.os

### ISSUE THREAD

**Issue by adamsmd** [kframework/k-legacy#175]
Currently org.kframework.utils.general.GlobalSettings is written as:

```
public static OS os() {
        if (os == null) {
            String osString = System.getProperty("os.name").toLowerCase();
            if (osString.contains("nix") || osString.contains("nux")) os = OS.UNIX;
            else if (osString.contains("win")) os = OS.WIN;
            else if (osString.contains("mac")) os = OS.OSX;
            else os = OS.UNKNOWN;
        }
        return os;
    }
```

I think it would be cleaner and more declarative to instead write it as something like:

```
static {
            String osString = System.getProperty("os.name").toLowerCase();
            if (osString.contains("nix") || osString.contains("nux")) os = OS.UNIX;
            else if (osString.contains("win")) os = OS.WIN;
            else if (osString.contains("mac")) os = OS.OSX;
            else os = OS.UNKNOWN;
}

public static OS os() { return os; }
```

Any reason not to do this?

**Comment by andreiarusoaie** [comment]
Since we call os() multiple times probably then it is ok to only compute os only once at the beginning, so I think it is a good idea.

**Comment by traiansf** [comment]
Apparently static initializes can be troublesome as you never know when
precisely they get initialized.
The way the code is right now, all you waste is an extra check for null
each time you call the method (which is not too often anyway), but you know
for sure that the os will be computed the first time this method is called.

best wishes,
Traian

2013/11/27 Andrei Arusoaie notifications@github.com

**Comment by dwightguth** [comment]
Resolving this also because of issue #245.
