### ISSUE TITLE
Eliminate org.kframework.utils.generals package

### ISSUE THREAD

**Issue by adamsmd** [kframework/k-legacy#176]
Currently org.kframework.utils.general contains only one class.  Namely GlobalSettings.

I don't see any real point in having an extra "general" package here so would it be okay to move GlobalSettings to the org.kframework.utils pacakge and remove the org.kframework.utils.general package?

**Comment by dwightguth** [comment]
Resolving as irrelevant given the eventual deprecation of all this code when we stop using static state. See issue #245.
