### ISSUE TITLE
Eclipse 4.5 + latest Scala plugin is completely unusable for K

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1761]
I follow the instructions in `README.md` but it doesn't work at all. Hundreds of errors complaining about unresolved scala classes.

Even in the `kore` project, there are two errors. The first one complains about the underscore at [transformers.scala#34](https://github.com/kframework/k/blob/master/kore/src/main/scala/org/kframework/definition/transformers.scala#L34): `missing parameter type for expanded function The argument types of an anonymous function must be fully known. (SLS 8.5) Expected type was: ?`. The second one complains about the [list constructor in CollectionsTest.java](https://github.com/kframework/k/blob/master/kore/src/test/java/org/kframework/CollectionsTest.java#L18): `The method List(Seq<T>) in the type Collections is not applicable for the arguments (int, int, int)`.

Anybody runs into these problems before? @cos @dwightguth ? Thanks!

**Comment by dwightguth** [comment]
I stopped using eclipse because of this issue. I think, if we want to fix
this, we need to stop using any Scala collections. I am just using intellij
though and it works fine.

**Comment by yilongli** [comment]
Interestingly, intellij is giving the same error in the first case. Although it works fine. I think we should at least make it clear in the `README.md` that Eclipse doesn't work with our code base at this moment.

**Comment by grosu** [comment]
I agree.  We do not want to deceive people.  Better give them less but good quality.

**Comment by cos** [comment]
added a warning to README.md: #1785
