### ISSUE TITLE
org.kframework.krun.api.* deserves better documentation

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1764]
There is very little documentation in this package at this moment.

**Comment by msaxena2** [comment]
@yilongli . Please do keep in mind that a lot of the code here belongs to the old Kil pipeline, and with the exception of some classes, will be discarded with the pipeline itself. That said, there may be a need for better documentation in other parts of the codebase. The new pipeline is managed by org.kframework.krun.KRun. That class, and other related classes mentioned in it, I feel, are more relevant for this discussion.

**Comment by yilongli** [comment]
I see. It would be good to find some time to mark the old classes as deprecated though.
