### ISSUE TITLE
class RewriteRelation should contain a reference to the startState

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1765]
Right now, it only has a `finalState`. Besides, the `executionGraph` is really a chain rather than a general graph.

**Comment by msaxena2** [comment]
This class contains a lot of code that was relevant to the old debugger. Since the debugger has fallen out of use, the java backend can be refactored to not use RewriteRelation at all.

**Comment by yilongli** [comment]
There are several places in the java backend refer to `RewriteRelation`, even in the `Executor` interface. If this class belongs to the old debugger and you don't plan to bring it up to date with the new debugger, I would like to remove such dependency gradually. What do you think?

**Comment by msaxena2** [comment]
The new debugger doesn't need anything backend specific. Please feel free to remove that dependency, or any dependency in the java backend exclusive to the debugger for that matter. The only thing that can break stuff can be a change to the Rewriter interface. As long as the interface and the implementing classes (SymbolicRewriterGlue.java in the case of the java backend) do what they're supposed to, cleaning up shouldn't be an issue. Thanks.
