### ISSUE TITLE
KompileFrontEnd: Simplify the setting of "step"

### ISSUE THREAD

**Issue by adamsmd** [kframework/k-legacy#178]
I think the following code

```
        String step = null;
        if (cmd.hasOption("step")) {
            step = cmd.getOptionValue("step");
        }
```

can be more simply written as

```
        final String step = cmd.getOptionValue("step");
```

given that cmd.getOptionValue will return null if it doesn't have the option.

(Writing it this way has the advantage of being more declarative.)

Was there a reason to write it the other way?

**Comment by traiansf** [comment]
Probably not, except for copying and pasting from other options which were
already in this form.

2013/11/27 mdmkolbe notifications@github.com

**Comment by dwightguth** [comment]
Please don't create issues for things this simple. Just fix them. I will leave this open though because it's unclear if it was ever addressed.
