### ISSUE TITLE
sort inference in kore

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1803]
It seems that sort inferencer of kore works differently than kil. It is hard to minimize example, but refer to:
- ~~https://github.com/kframework/k/blob/7b551511247836d2bceff7d4621df69eb8d2bc31/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L375-L379~~
- ~~https://github.com/kframework/k/blob/7b551511247836d2bceff7d4621df69eb8d2bc31/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L450-L454~~
- ~~https://github.com/kframework/k/blob/7b551511247836d2bceff7d4621df69eb8d2bc31/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L495-L499~~
- https://github.com/kframework/k/blob/7b551511247836d2bceff7d4621df69eb8d2bc31/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L583-L587
- https://github.com/kframework/k/blob/7b551511247836d2bceff7d4621df69eb8d2bc31/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L1151-L1155

**Comment by bmmoore** [comment]
I don't understand what changing from `KItem` to `Exp` means.

What goes wrong with the second and third examples?

The concrete syntax of `notBool` doesn't have parentheses, so I would blame any problems more specifically on sort inference for labelled terms.

In the third example, I don't see why the `_` would be expected or needed to have sort Exp, are you sure it's not just that the K grouping syntax changed from parentheses to backtics? (Evmen if changing to backticks fixes it, this could still be a parsing bug if you get a bad set of ambiguities).

**Comment by daejunpark** [comment]
@bmmoore The first three examples are fixed by #1805.

The remaining two examples, I think, are necessary because `lookup` and `lookupMember` can appear in Exp position, especially function expression in function call. 

Question is how they worked before in KIL?
