### ISSUE TITLE
Remove Backend.autoinclude

### ISSUE THREAD

**Issue by adamsmd** [kframework/k-legacy#181]
It looks like Backend.autoinclude() is not used anywhere (all of the current backends just return "true") and thus the code that depends on it is untested.  If it is not used, that code should re-removed.

**Comment by radumereuta** [comment]
autoinclude() was used at one point to differentiate between normal kompilation when we have to include the builtin stuff in every user module, and between a documentation workflow, where we wanted the modules to be as close to the original as possible. That meant we should not include anything anywhere by default.

Since spring cleaning came early, the documentation branch was removed (not particularly happy about that), therefore autoinclude() is not used anymore.

I guess you can remove it for now. But at one point we will have to redo some work that was interrupted, because of all this cleaning.

**Comment by adamsmd** [comment]
How does the pdf backend differentiate this currently?

**Comment by radumereuta** [comment]
Right now it doesn't.
It uses the location attribute to differentiate between what was added and what was parsed.
Something added during kompilation would always have location="generated".

I don't remember exactly why I had to use that autoinclude() option. And now I don't have the code to remember.
So just delete it. It's not needed. We will have to redesign the documentation from scratch at one point.

**Comment by osa1** [comment]
I was just going to delete that method and close this issue but I think `autoinclude` is still useful and we may want it to set to `false` in the future. I think it's better to leave it as-is right now.

`BasicParser` does some other things if `autoinclude` is true and even though currently `autoinclude` is always true in all backends we may change it to false depending on some command line flag or something easily in the future and have different parser behavior(though I'm not sure what does `BasicParser` do if `autoinclude` is false, I guess it doesn't parse standard library files?)

**Comment by adamsmd** [comment]
Since autoinclude is currently always true, any code paths for when 
autoinclude is false have bit rotted.  (I discovered this when 
attempting to implement a pass for Kore.)  Therefore, I think we should 
still remove autoinclude until we implement it properly and have code 
that acually needs and uses both paths.

**Comment by osa1** [comment]
I probably won't be the one who will implement this functionality if it's needed again so I'm okay with deleting it. If no one objects to it I'll remove that code and close this issue.

**Comment by radumereuta** [comment]
I object :-1: 
This was originally introduced by me when I tried to generate documentation.
Since documentation is again in discussion, I would like to delay this issue until we figure out how to properly generate it. Maybe it is useful again.

**Comment by dwightguth** [comment]
Code that does nothing should not exist. Code that is never live should not exist. If you need it later, dig it up. Leaving stuff around that is no longer in use is one way projects slowly become unmaintainable.

**Comment by radumereuta** [comment]
This is used again. autoinclude() helps the implementation of --no-prelude and --backed=doc
