### ISSUE TITLE
kompile on windows produces random errors

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#183]
running kompile for a larger semantics, such as java, produces random errors like:

```
Generating equations for hooks                              =   278
[Error] Compiler: Unbounded Variable K:K .
  File: /mnt/hgfs/e/work/java-semantics/semantics/elaborate-blocks.k
  Location: (394,16,394,17)
  Compilation Phase: class org.kframework.compile.checks.CheckVariables

[Error] Compiler: Unbounded Variable S:String .
  File: /mnt/hgfs/e/work/k-framework/include/io/uris.k
  Location: (81,65,81,66)
  Compilation Phase: class org.kframework.compile.checks.CheckVariables

[Error] Compiler: Unbounded Variable T2:Type .
  File: /mnt/hgfs/e/work/java-semantics/semantics/expressions.k
  Location: (228,103,228,105)
  Compilation Phase: class org.kframework.compile.checks.CheckVariables
```

Every time I run compile i get a different error.

The errors are virtually never produced on fmse server, have a roughly 50% occurence rate on my windows pc, and virtually 100% occurence in a linux guest inside my windows pc. This strongly suggests a file-related race condition.

k version: Git Revision: 45c2e15

**Comment by osa1** [comment]
I don't think race conditions happen in kompile. @denis-bogdanas can you please try again a few times, but this time by removing `.k` and `*-kompiled` folders before running kompile and see if it still produces different error messages each time?

I think there are some re-use going on in kompile but it's hard to find where it happens and how it happens because code is a complete mess.

**Comment by radumereuta** [comment]
I can confirm that this happens even at first time compilation.

**Comment by traiansf** [comment]
I also had students reporting strange errors at first time compilation
(just downloaded the tool).

best wishes,
Traian

2013/12/4 Radu Mereuta notifications@github.com
