### ISSUE TITLE
inner parser error when using local rewrite

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1835]
Looks like a bug to me.

```
require "domains.k"
module TEST
  rule  <in> (L1:List => .List) ListItem("off") </in>          // inner parser error!!!
  rule  <in> L1:List ListItem("off") => ListItem("off") </in>  // this is fine
endmodule
```

**Comment by bmmoore** [comment]
We've changed the K grouping syntax to use backtics to avoid conflicts with user syntax in languages like Scheme, as documented here: https://github.com/kframework/k/wiki/!!!-Module-System . But, `List` isn't a user sort so there's no reason not to add a bracket production using parentheses. Once we add module-based implementation we may switch back to adding parentheses along with the other K syntax.

**Comment by yilongli** [comment]
I see. Thanks for the explanation. Closing it.
