### ISSUE TITLE
PatternMatchRewriter becomes unused

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#1840]
`PatternMatchRewriter` becomes unused after the kil kill pull request. I am wondering if we are going to keep it? @dwightguth @andreistefanescu

**Comment by andreistefanescu** [comment]
The class is unused because the pattern matching based rewriting is wrongly wired in `SymbolicRewriter`, instead of `PatternMatchRewriter`.

**Comment by yilongli** [comment]
@dwightguth I think the relevant code is in `InitializeRewriter`. Looks like your territory?

**Comment by dwightguth** [comment]
I don't have time to fix this at the moment. @msaxena2 you may want to look into this, it could improve performance of the C semantics somewhat on the Java backend, once you get it working.
