### ISSUE TITLE
Lookup directories

### ISSUE THREAD

**Issue by kheradmand** [kframework/k-legacy#1857]
I have the following folder structure:

```
project
 \_ src
 |    \_ common
 |    \_ rvm
 |    |   \_ rvm-syntax.k
 \_ test
```

In rvm-syntax I have something like

```
require "domains.k"
require "../common/common-syntax.k"
...
```

If I go to src/common/rvm folder and try to kompile rvm-syntax it works fine, however If I go to test folder and try to kompile ../src/rvm/rvm-syntax.k I get:

```
Lookup directories:[./../src/rvm,
/home/ali/FSL/kbuild3/lib/java/../../include/builtin]
    Source(./../src/rvm/rvm-syntax.k)
    Location(2,1,2,35)

```

I'm not sure it is a problem or a feature!

**Comment by radumereuta** [comment]
@cos implemented this part in the new implementation, I think he can clarify things.

**Comment by cos** [comment]
I think @dwightguth touched that part with his latest pull request. From I understand, one way to do it would be: `kompile -I ../src/rvm rvm-syntax.k`, but the way you did it should be accepted too.

**Comment by dwightguth** [comment]
I do not have time to look into this at the moment. It seems though that we have somehow made this code dependent on the current working directory which it should not be. @daejunpark you are oncall until Friday so it's your responsibility to investigate this.

**Comment by cos** [comment]
Actually, I'm on call -- we've switched. 

Why shouldn't the code be dependent on the current directory. Isn't `kompile` relative to the current directory? 

Also, @kheradmand, could you please run that with --debug and give us the entire error message + stack trace.

**Comment by dwightguth** [comment]
The idea is that the directory for the include path should be relative to the file being compiled, not the current working directory. So `kompile rvm-syntax.k` and `kompile ../src/rvm/rvm-syntax.k`  should have the same behavior. Somehow that is not being the case here, at least according to the report.

**Comment by kheradmand** [comment]
@cos 

```
kompile ../src/rvm/rvm-syntax.k --syntax-module RVM-SYNTAX --debug
org.kframework.utils.errorsystem.KEMException: [Error] Critical: Could not find file: ./../src/rvm/rvm-syntax.k
Lookup directories:[./../src/rvm, /home/ali/FSL/kbuild3/lib/java/../../include/builtin]
    Source(./../src/rvm/rvm-syntax.k)
    Location(2,1,2,35)
    at org.kframework.utils.errorsystem.KExceptionManager.create(KExceptionManager.java:166)
    at org.kframework.utils.errorsystem.KExceptionManager.criticalError(KExceptionManager.java:60)
    at org.kframework.parser.concrete2kore.ParserUtils.slurp(ParserUtils.java:154)
    at org.kframework.parser.concrete2kore.ParserUtils.loadModules(ParserUtils.java:170)
    at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:197)
    at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:279)
    at org.kframework.kompile.Kompile.run(Kompile.java:138)
    at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
    at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
    at org.kframework.main.Main.runApplication(Main.java:109)
    at org.kframework.main.Main.runApplication(Main.java:99)
    at org.kframework.main.Main.main(Main.java:51)
[Error] Critical: Could not find file: ./../src/rvm/rvm-syntax.k
Lookup directories:[./../src/rvm,
/home/ali/FSL/kbuild3/lib/java/../../include/builtin]
    Source(./../src/rvm/rvm-syntax.k)
    Location(2,1,2,35)
```

**Comment by dwightguth** [comment]
Oh crap, this seems to be a result of the way we are bootstrapping implicit
requires. We need to absolutize the path that we include in the
automatically generated header. Either that or rewrite that code to require
files using a different mechanism.

**Comment by cos** [comment]
Making that path absolute seems a bit ugly. We could simply read the file in `parseDefinition` and not use `require` indirection.

**Comment by dwightguth** [comment]
Yeah that could work too as long as you continue to require prelude.k.
