### ISSUE TITLE
prover skipping paths

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1864]
https://github.com/yilongli/k/commit/769a794f4de4fef40826c195ab9d9af5b35587cc

This change makes the prover to consider only a single path, skipping the others, which results in being unsound.

**Comment by yilongli** [comment]
@daejunpark I don't get notified this way :) Feel free to revert that commit.

**Comment by daejunpark** [comment]
@yilongli Thanks for finding this. :) I can revert it, but I just wanted to make sure if there is a way to keep your performance improvement, yet safe for the prover. I'll talk to @andreistefanescu this Monday. Let me know if you have an idea though.
