### ISSUE TITLE
prefer attribute ignored

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#187]
This maybe related to #182, although I tried to test a different thing.

So the definition below ignores the fact that + is preferred over everything, probably because it identifies the ambiguity higher than it should, on the same production:

```
module TRY
  syntax Exp ::= Int
               | Exp "+" Exp  [prefer]
               > Exp "=" Exp
               | Int Int
endmodule

fslwork$ krun --parser "kast -e" "3=1+2"
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: Exp ::= Exp "=" Exp 
   3 = (1 2)
2: Exp ::= Exp "=" Exp 
   3 = (1 + 2)
    File: 3=1+2
    Location: (1,1,1,6)
    Compilation Phase: Ambiguity filter

<k>
    3 = (1 2)
</k>
```

**Comment by radumereuta** [comment]
A really old bug of SDF came back to hunt me.
Calling the workaround procedure to fix the bug for programs too.
It should work now.
