### ISSUE TITLE
  [owise] attribute not working in K3.6

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1870]
After following the suggestion in #1836, [owise] doesn't appear to be processed. It's as if the `rule anyBadThread(_) => false [owise]` is just `anyBadThread(_) => false` because it's always returning false! The true part is correct. I tested it. What am I doing wrong?

@cos, you probably need to self-assign this as I can't assign it to you. Thank you.

**Comment by cos** [comment]
Thanks!

**Comment by omarzd** [comment]
OK. `[owise]` does work in general, but not in the special case where I use it. What's special about my case is that I'm using the `#configuration` variable. Maybe the totality of my pair of rules is not seen by K.

**Comment by omarzd** [comment]
I think I made it work just now. I'll make sure through further testing before closing this issue, but let me first document what I did. Like I said, the totality of the rule needs to be seen by K for `owise` to work.
In my example, I'm matching a pattern inside a function, so the two rules are not really total. Here is how it was done before:

```
syntax Bool ::= anyBadThread(Bag) [function]

rule [total-1]: anyBadThread(
        <generatedTop>... 
            <T>... 
                <threads>... 
                    <thread>... 
                        <k> pattern </k> 
                    ...</thread> 
                ...</threads> 
            ...</T>
        ...</generatedTop>
        ) => true

rule [total-2]: anyBadThread(_) => false    [owise]
```

The problem is in `rule [total-2]`. Perhaps K doesn't realize that it is contrary to `rule [total-1]` so it doesn't really see the totality pair. So it came to me to do it like `rule anyBadThread(_:Bag) => false [owise]`, but even that didn't work. 
Now here is how it _should_ be done:

```
rule [total-2]: anyBadThread(
        <generatedTop>... 
            <T>... 
                <threads>... 
                    <thread>... 
                        <k> _ </k> 
                    ...</thread> 
                ...</threads> 
            ...</T>
        ...</generatedTop>
        ) => false
    [owise]
```

This worked for me. This is needed because of the nature of the `#configuration` variable and that you _must_ include the `<generatedTop>` cell. As I said, I will do further testing before I decide to close this.

**Comment by cos** [comment]
I'm not familiar with the `[owise]` current implementation. @bmmoore or @andreistefanescu, do you have any idea?

Overall, if you found a way around it, we could simply not worry about it until K 4.0, where we'll solve it with strategies.

**Comment by omarzd** [comment]
All is working fine. @cos, you can close this if you wish. I already posted the solution to my problem. In my opinion, this should be open only if we have a well-defined bug report about `[owise]`. If from my case you can make a sample test that will reproduce the problem, then you'll have a bug to solve. The key problem is the pattern returned by `#configuration` inside a function and how `owise` deals with that. My uninformed guess is that `#configuration` is the source of the bug.
