### ISSUE TITLE
Matching a `Map` key that is a concatenated `String`

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1881]
I tested this. In the configuration I have a `Map` that includes `"MyCow" |-> 0`. In the rule, when I do `"MyCow" |-> 0`, it matches, but when I do `"My" +String "Cow"`, it doesn't!
I have tested this in version 3.5.2. I wasn't able to test it in 3.6.

**Comment by dwightguth** [comment]
+String is a function and thus does not support matching on itself. If you want to test that a particular value is equal to the concatenation of two strings, I suggest you use something like:

```
MyCow:String |-> 0 requires MyCow ==String "My" +String "Cow"
```

**Comment by omarzd** [comment]
Your suggestion works. Thanks.

**Comment by omarzd** [comment]
@dwightguth, too many of those (6) in one rule and `kompile` either runs forever or give this error:

```
[Error] Critical: SDF failed to parse a rule by throwing: null
        Source: File:
C:\somefile.k
        Location: (161,9,181,16)
Aborted at
        javaParseStringConfig_0_0
        justFine_0_0
        justFine2_0_0
        to_xml_0_0
        to_xml1_0_0
        to_xml_0_0
        to_xml1_0_0
        to_xml1_0_0_fragment_3
        to_xml1_0_0_fragment_2
        to_xml_0_0
        to_xml1_0_0
        to_xml1_0_0_fragment_3
        to_xml1_0_0_fragment_2
        to_xml_0_0
        to_xml1_0_0
        to_xml1_0_0_fragment_3
        to_xml1_0_0_fragment_2
        to_xml1_0_0_fragment_1
        to_xml_0_0
        to_xml1_0_0
        to_xml1_0_0_fragment_3
        to_xml1_0_0_fragment_2
        to_xml1_0_0_fragment_1
        to_xml_0_0
        to_xml2_0_0
        to_xml2_0_0_fragment_3
        to_xml2_0_0_fragment_2
        to_xml2_0_0_fragment_1
        to_xml2_0_0_fragment_0
        to_xml_0_0
        to_xml1_0_0
        to_xml1_0_0_fragment_3
        to_xml_0_0
        to_xml2_0_0
        to_xml2_0_0_fragment_3
        to_xml2_0_0_fragment_2
        to_xml2_0_0_fragment_1
        to_xml_0_0
        to_xml2_0_0
        to_xml2_0_0_fragment_3
        to_xml2_0_0_fragment_2
        to_xml2_0_0_fragment_1
        to_xml_0_0
        to_xml3_0_0
        to_xml_0_0
        to_xml2_0_0
        to_xml2_0_0_fragment_3
        to_xml2_0_0_fragment_2
        to_xml2_0_0_fragment_1
        to_xml_0_0
        to_xml3_0_0

```

**Comment by radumereuta** [comment]
That's a parsing limitation. Can you post the exact rule you are trying to parse?
Try to put parenthesis around the rewrite terms: `(X +String ... Y) => (Z)`. That usually helps reduce the number of ambiguities during parsing time.

**Comment by omarzd** [comment]
That worked again. Thank you @radumereuta.

**Comment by cos** [comment]
@omarz1, what are you using K for? I see an SDF error there. If you're ok with seeing a few more errors for a while, you can switch to the master version of K. We are actively working on it so any problems you may encounter will get fixed quicker.

**Comment by omarzd** [comment]
@cos Thank you but now is not a good time for me to see more errors even though I do like reporting bugs. I will get to it once I can.

**Comment by omarzd** [comment]
In K3.6, the following rule:

```
  rule 
        <gVars> Lock:String |-> (true => false)
        ...</gVars>
        when Lock ==String ("Car" +String "_lock")
```

gives the following error:

```
[Error] Critical: Unsupported map pattern in the rule left-hand side
```

Of course the rule is simplified to narrow down the source of the error. The following doesn't cause an error:

```
  rule 
        <gVars> "Car_lock" |-> (true => false)
        ...</gVars>
```

@dwightguth, your suggestion worked in K3.5 but not in K3.6.

**Comment by dwightguth** [comment]
This is due to a limitation in how map patterns are compiled in K 3.6. You should be able to write rules that directly iterate over your gVars using a pattern like `Lock:String |-> Val:Bool` and then remove each element you iterate over, place it in a special-purpose cell, and then match Val against true.

K 4.0 will also support the original rule.

**Comment by omarzd** [comment]
@dwightguth, I'm sorry I didn't quite understand. Each element needs a cell?

**Comment by dwightguth** [comment]
So, it looks something like this:

```
rule <gVars> M:Map => processMap(M, .K) </gVars>
       requires processMap(M, .K) =/=K M

syntax Map ::= processMap(Map, K) [function]

syntax KItem ::= pair(K, K)
rule processMap((Key |-> Val => .Map) _:Map, (.K => pair(Key, Val)))
rule processMap(_, pair(Lock:String, true) => .K) (.Map => Lock |-> false)
       requires Lock ==String "Car" +String "Lock"
rule processMap(.Map, .K) => .Map
rule processMap(_, pair(Lock:String, Value:K) => .K) (.Map |-> Lock |-> Value) [owise]
```

Note that this is iterating over the entire map. That is effectively the only way to determine whether any of the elements match your particular constraint (Key matching side condition, value matching pattern). If you have a large map and this rule tries to apply on every rewrite step, it's going to be pretty slow. If you want faster performance you are going to have to write a pattern that can be efficiently translated into a lookup in a hash map.

**Comment by omarzd** [comment]
Closed because @dwightguth said it will not be a problem in K 4.0.
