### ISSUE TITLE
How to extend the configuration in a separate module

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1884]
My definition has multiple independent modules, each needs only the syntax module. The main module has the configuration defined, but some cells in the configuration are only needed by individual modules that I sometimes choose not to import. Can I append a cell to the configuration in one module?

**Comment by daejunpark** [comment]
This feature is under development by @cos  #1873

**Comment by cos** [comment]
just a now, the feature is only available on `master` now and it won't get retrofitted to 3.x releases.

**Comment by cos** [comment]
*just a note

**Comment by omarzd** [comment]
OK @cos, now I'm ready to start working on `master`. Does it include binaries or will I have to compile myself?

**Comment by cos** [comment]
afaik, you'll have to compile it yourself. It should work pretty smoothly.
