### ISSUE TITLE
Merged PR is gone

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1905]
I cannot find the merged PR #1754 in the latest master. There is no history regarding neither merge nor revert of the PR. I suspect it is somehow rebased. Or, what am I missing? Any idea?

**Comment by cos** [comment]
The PR is still there. Only the branch is gone -- Brandon deleted it after the merge. There's usually no point in keeping merged branches around. What do you need it for?

**Comment by cos** [comment]
Seem like github added a "Restore branch" button -- see towards the end of #1754.

**Comment by daejunpark** [comment]
What I'm saying is that the PR was merged into master, but the change is not found in the current master. 

I'm trying to find who reverted the change, but I cannot find the attempt to revert in history. Even, I cannot find the merge history neither. That's why I suspect someone accidently rebased it, but I have no idea how to find it.

**Comment by cos** [comment]
This is indeed strange. I'll look into it.

**Comment by cos** [comment]
It might be something like this:
http://stackoverflow.com/questions/13468027/the-mystery-of-the-missing-commit-across-merges

**Comment by cos** [comment]
@daejunpark, it's of your own making: https://github.com/kframework/k/commit/daa1978488c3f9c7c0a040c22462e8d5c784bc7a
:)

**Comment by daejunpark** [comment]
@cos Oh, it was due to me. Thanks a lot! 

What happened is that I cherry-picked commits from a pending PR, but reverted them later because the pending PR had not been merged before my PR was merged. I thought that merging the pending PR will bring the changes back, but it didn't. 

This is counter-intuitive because my reverting the commits preceded merging the pending PR. That is, merging a PR could have no effect. Is there any way to prevent this kind of mistakes later?

But, still the strange thing is that 'git log' didn't show such a history. For example, the following directory history does not show the 'merge-revert' history:
https://github.com/kframework/k/commits/master/k-distribution/tests/regression/kore-cell-fragments

**Comment by cos** [comment]
> This is counter-intuitive because my reverting the commits preceded merging the pending PR. That is, merging a PR could have no effect. Is there any way to prevent this kind of mistakes later?

I don't think so. I think the principle is that git prioritizes the latest commits. If you don't make explicit commits that re-add the content, git considers the reverts as authoritative.

> But, still the strange thing is that 'git log' didn't show such a history. For example, the following directory history does not show the 'merge-revert' history:
> https://github.com/kframework/k/commits/master/k-distribution/tests/regression/kore-cell-fragments

I had some trouble finding it also. I don't know why they disappear. I eventually found them with gitk.

**Comment by bmmoore** [comment]
> What happened is that I cherry-picked commits from a pending PR, but reverted them later because the pending PR had not been merged before my PR was merged. I thought that merging the pending PR will bring the changes back, but it didn't. 

If `cherry-pick` actually made a new commit, and then the pr was merged like with the `merge` command, that's exactly how it should have worked. Other things like `rebase` (and `pull` may use `merge` or `rebase` depending on settings) might act differently.

**Comment by dwightguth** [comment]
For education purposes, understand that the tip of a branch and its history
are different things. Thus there is a distinction between rebasing a commit
out of the history, and reverting it. Both lead to the same working copy,
but one preserves history and adds a new revert commit, the other refactors
history and removes the existing commit. When you merge changes, what
actually happens is that the changes of both branches are combined using a
merge strategy to create a new commit that is the child of both commits.
Changes (deltas) applied in both parents are simply redundant and merge
cleanly. So what actually happened was you took one branch with the feature
commits and one branch with both those commits and the revert commits, and
created a new commit that also had both and thus was the reverted form.

Something to bear in mind in the future so you can avoid this happening
again...

**Comment by bmmoore** [comment]
Merges generally only take into account the state at the tip of the tree and at the common ancestor.
In particular, cherry-picking a commit onto master, reverting the cherry-picked commit, and then merging the pull request should result in the change being applied:

```
$ git init
Initialized empty Git repository in /home/brandon/test/git/.git/
$ echo 'Hello' > foo
$ git add foo
$ git commit -a -m starting
$ git checkout -b feature
Switched to a new branch 'feature'
$ echo 'Goodbye' > bar
$ git add bar
$ git commit -a -m "Feature work"
[feature 1db360b] Feature work
 1 file changed, 1 insertion(+)
 create mode 100644 bar
$ git checkout master
Switched to branch 'master'
$ git cherry-pick 1db360b
[master d0f1caf] Feature work
 Date: Tue Dec 15 12:37:22 2015 -0600
 1 file changed, 1 insertion(+)
 create mode 100644 bar
$ echo ' World' >> foo
$ git commit -a -m 'More master work'
[master edbddf1] More master work
 1 file changed, 1 insertion(+)
$ git revert --no-edit d0f1caf
[master 0121bf6] Revert "Feature work"
 1 file changed, 1 deletion(-)
 delete mode 100644 bar
$ git merge --no-edit feature
Merge made by the 'recursive' strategy.
 bar | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 bar
$ cat foo bar
Hello
 World
Goodbye
$ git log --graph --oneline
*   ec3522c Merge branch 'feature'
|\  
| * 1db360b Feature work
* | 0121bf6 Revert "Feature work"
* | edbddf1 More master work
* | d0f1caf Feature work
|/  
* 49e44dd starting
```

The revert would only take precedence in a merge if the reverted commit was already part of the common ancestor of the two commits.

**Comment by bmmoore** [comment]
> understand that the tip of a branch and its history are different things.

That's certainly true, but git merges are only interested at the state of the code at the tips of branches and at certain common ancestor points, not at all in how they got to that state (as opposed to VCS like darcs which consider sets of changes primitive instead of tree states).
