### ISSUE TITLE
no comment in temporary changes in language definition transition to kore

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1912]
@cos Are you tacking it down? 2230bb39

When you make such a temporary change in language definitions, you have to write a big TODO comment to revert it back to the original later. Could you please write such a comment, consulting the other comments, named `TODO(KORE)`, in the same file?

The idea is to ask Grigore to review the changes by looking at the diff:

```
git di 6dfee8da18e2ba638e5d27baa7e1bdadfebe988c k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k
```

**Comment by cos** [comment]
fixed by #1915
