### ISSUE TITLE
least sort of list unit

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1913]
_[For a tracking purpose.]_

The list unit may not have a least sort.

For example, suppose we have three lists:

```
syntax Exps ::= List{Exp,","}
syntax Vals ::= List{Val,","}
syntax Ids  ::= List{Id, ","}
```

where

```
syntax Exp ::= Int | Id
syntax Val ::= Int
```

Then, the term `.List{"'_,_"}(.KList)` has no least sort.

One possible solution is to declare `Ids` with a different klabel:

```
syntax Ids ::= List{Id,","}  [klabel("'_,_::Ids")]
```

**Comment by daejunpark** [comment]
An example to reproduce this issue:

```
require "domains.k"

module KOOL-UNTYPED-SYNTAX
  imports KOOL-UNTYPED-COMMON
  imports ID
endmodule

module KOOL-UNTYPED-COMMON
  imports DOMAINS-COMMON

  syntax Decl ::= "var" Exps ";" 

  syntax Exp ::= Int | Id
               | Exp "[" Exps "]" 

  syntax Ids  ::= List{Id,","}

  syntax Exps ::= List{Exp,","}          [strict]

  syntax Stmt ::= Decl

  syntax Stmts ::= Stmt
                 | Stmts Stmts                          [right]

  rule var E1:Exp, E2:Exp, Es:Exps; => var E1; var E2, Es;          [macro]

endmodule

module KOOL-UNTYPED
  imports KOOL-UNTYPED-COMMON
  imports DOMAINS

  syntax Val ::= Int 
  syntax Vals ::= List{Val,","}

  syntax Exps ::= Vals
  syntax Exp ::= Val 

  rule <k> var X:Id[N:Int]; => .K ...</k>

endmodule
```

kompile output: (note that this error occurred during the macro expansion, which is essentially a part of krun, not of kompile.)

```
[Error] Critical: Cannot compute least sort of term: .List{"'_,_"}(.KList)
Possible least sorts are: [Exps, Ids, Vals]
All terms must have a unique least sort; consider assigning unique KLabels to
overloaded productions
  while executing phase "expand macro rules" on sentence at
Source(*.k):Location(40,8,40,42)
```

**Comment by radumereuta** [comment]
This might be related to the issue #1705, which is being fixed in #1891.
Try to test it again after it has been merged.

**Comment by daejunpark** [comment]
Thanks, @radumereuta, but I don't think it is about the implicit list sub-sorting. The problem is that `Vals` and `Ids` have no relationship, while the list unit `.List{"'_,_"}` can be of both.

**Comment by radumereuta** [comment]
I know, but just try it... from what I remember it doesn't work quite like that. @andreistefanescu might know more.

**Comment by bmmoore** [comment]
In the Java backend this is handled by adding a new dummy sort which just contains the unit, and it subsorted into all thoses lists.

**Comment by andreistefanescu** [comment]
@bmmoore is right: in the old pipeline the java backend added a `List{Bot}` sort for the unit.

**Comment by grosu** [comment]
Then we can do the same here.   We do not have time to come up with perfect solutions to everything as part of the transition to K4.0.  Whenever we encounter such situations where it is not clear what needs to be done, let us do the following:

1) Pick whatever we did before in K3.6. and do that, because we know that should work; and

2) Add a sentence or two in the K Manual that this needs to be done properly eventually, both at the foundational level and in the implementation.

When you do pull requests, _please_ make sure you are enforcing that.

**Comment by cos** [comment]
is this required for 4.0?

**Comment by daejunpark** [comment]
only if it is hard for @grosu to update readme and videos.

See https://github.com/kframework/k/blob/ea399959d2d3ab33791b37cff565f3a94f77ab0f/k-distribution/tutorial/2_languages/2_kool/1_untyped/kool-untyped.k#L202

**Comment by grosu** [comment]
@daejunpark , if you are referring to having to put the attribute `[klabel(_,_::Ids)]` then yes, we do not want that.  Not because it is "hard to update the readme and video", but because that is something that should not be there and will very very likely change soon anyway.  We should do what I said above @cos's last comment above.

**Comment by grosu** [comment]
Guys, we still have this comment in SIMPLE-UNTYPED:

```
  // TODO(KORE): drop klabel once issues #1913 are fixed
  syntax Ids  ::= List{Id,","}           [klabel("_,_::Ids")]
```

This is very very ugly, and an artifact of a poor implementation.  We cannot leave this in the tutorial, and certainly it becomes even more annoying as we/I have to add the same dirty hack in all the other languages that are not yet modified.  This sucks!  I thought that we eliminated all the road blockers.

**Comment by radumereuta** [comment]
@andreistefanescu, any input on this? The error reported if I remove the klabel comes from the backend.
Although, after looking over the definition, the current fix has a point. The rules used to evaluate Ids are different from those used for Exps and Vals, so it's not completely wrong to have a different klabel.

**Comment by andreistefanescu** [comment]
@radumereuta the input is what has been said at the beginning of the thread: k3.6 adds a dummy sort `List{Bot}` which is subsorted to all list sorts, and then all list units have least sort `List{Bot}`.

**Comment by grosu** [comment]
@radumereuta can this be fixed quickly?  I have the same problem in simple typed.  So all languages suffer because of this.

**Comment by andreistefanescu** [comment]
The transformation is in `CompleteSortLatice.java` in k3.6, if anyone wants to look (is is no longer in the main repository).

**Comment by cos** [comment]
I'm talking to @radumereuta now and he says this is to be added in the compiler. we'll give it a try after we finish with the $PGM issue.

**Comment by radumereuta** [comment]
Fixed in #2099.

**Comment by daejunpark** [comment]
Issue recurred. https://github.com/kframework/k/pull/2113/files#r50074467

**Comment by cos** [comment]
@andreistefanescu, you fixed this at some point, right?

**Comment by andreistefanescu** [comment]
This should be fixed now.
