### ISSUE TITLE
[K4.0]: How to exclude strings from `Id` category

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1923]
How do I exclude certain strings from being treated by the lexer as Identifiers?
It used to be done like this:

```
syntax "zero" -/- [a-zA-Z0-9]
```

But this is not accepted anymore.

**Comment by omarzd** [comment]
I've just upgraded from K3.6 to the latest master and I'm facing some issues with `kompile`. Before I start flooding you with issues, do you have some guide as to how to update my definition to fit K4.0?
For example the builtins `Int` and `Id` are not identified except with `imports DOMAINS-COMMON`. The error message of course doesn't say that.

**Comment by radumereuta** [comment]
Yes, please have a look at this: https://github.com/kframework/k/wiki/Syntax-specification-for-the-new-parser since we changed a few things about syntax specification.
We improved a bit how we specify tokens and reject patterns, so we get more control over each production.

**Comment by omarzd** [comment]
So the builtin `Id` imported in `domains.k` already uses the `autoreject` attribute. Brilliant. Thanks.
