### ISSUE TITLE
substitution module

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#1924]
The lambda example would not `kompile`. It says 

```
[Error] Critical: Could not find file: modules/substitution.k
```

I found another `substitution.k` in the `include/builtin` folder that had a comment saying that _it_ is the one used by `lambda.k`. I tried importing that but I got the same message:

```
[Error] Critical: Could not find file: builtin/substitution.k
```

**Comment by cos** [comment]
which lambda example?

**Comment by cos** [comment]
we're in the process of translating the tutorial so not all definitions are adapted to K 4.0

**Comment by omarzd** [comment]
`lesson2/lambda.k` and the later lessons I believe.

**Comment by omarzd** [comment]
Then how do I know how I should change my definition for K4.0? I need the substitution module. I remember this happened before when I upgraded from 3.4 to 3.5 when it was master before its release.

**Comment by cos** [comment]
We're only converted the last lessons of several definitions. For lambda, lesson 9 should work.
If you have any other questions, feel free to ask here or on the gitter chat.

**Comment by omarzd** [comment]
Oh I didn't know that. I should've directly looked at the last lesson. OK thank you. Where is the gitter chat? Never used it!

**Comment by cos** [comment]
https://gitter.im/kframework/k
