### ISSUE TITLE
ktest --- improve reported times

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#193]
I just ran the new ktest, and I love it!  This output is great:
## SUCCESS

Definitions kompiled: 96 (46'19'')
PDF posters kompiled: 96 (37'39'')
Programs krun: 651 (42'23'')
## Total time: 126'21''

However, the times seem a lot larger than the elapsed time.  Probably you output the total CPU time, or how long it would take to execute the entire thing if there was only one processor.

Since this is still hot, I think it would be a lot more informative for users to see both times, something like this:
## SUCCESS

Definitions kompiled: 96 (time: 46'19'' (total CPU), 12'17 (elapsed))
PDF posters kompiled: 96 (time: 37'39'' (total CPU), 8'23 (elapsed))
Programs krun: 651 (time: 42'23'' (total CPU), 11'12'' (elapsed))
## Total time: 126'21'' (CPU), 24'35'' (elapsed)

Thanks, Omer!!

**Comment by osa1** [comment]
I just fixed that, shown times were wrong because I was adding times
elapsed for every test which gave wrong total time because they're running
in parallel.

Total ktest time will still a bit longer than total time printed because of
time spend scheduling threads and parsing config files etc.

---

Ömer Sinan Aðacan
http://osa1.net

2013/12/4 Grigore Rosu notifications@github.com

**Comment by osa1** [comment]
So I'm currently printing real time spent on each step, do we also want to see previously printed times? (e.g. sum of times spent for each process. I personally think this number is useless because it's wrong since processes are run in parallel, so I'm not printing that currently)

**Comment by grosu** [comment]
I think it would be instructive to know how long it would take to run all the tests without parallelism.  Maybe we don't need to split that up per each phase (kompile, pdf, krun), but at least the total time would be nice to be both total cpu time and real elapsed time.

**Comment by osa1** [comment]
Does that look good:

```
➜  sample git:(master) ✗ ktest config.xml
Kompile the language definitions...(1 in total)
SUCCESS
Generate PDF files...(1 in total)
ERROR: [/home/omer/K/k_new_dist/k/bin/kompile --backend=pdf /home/omer/K/k_new_dist/k/sample/kool-typed-dynamic/kool-typed-dynamic.k] failed with error (time: 13877 ms)
FAIL
Kompiling definitions that are not yet kompiled.
Kompile the language definitions...(0 in total)
SUCCESS
Running /home/omer/K/k_new_dist/k/sample/kool-typed-dynamic/kool-typed-dynamic.k programs... (2 in total, 0 with input, 2 with output, 0 with error)
SUCCESS

FAIL (see details above)
----------------------------
Definitions kompiled: 1 (time: 0'10'' (total CPU), 0'10'' (elapsed))
PDF posters kompiled: 1 (time: 0'13'' (total CPU), 0'13'' (elapsed))
Programs krun: 2 (time: 0'21'' (total CPU), 0'14'' (elapsed))
Total time: 0'44'' (CPU), 0'37'' (elapsed)
----------------------------
```

?

**Comment by grosu** [comment]
Nice.  Now that I look at it, probably the elapsed time is more important than the total CPU, so maybe we shouls swap them.  Also, nested parentheses don't look that nice.  How about:

```
----------------------------
Definitions kompiled: 1 (time: 0'10'' elapsed, 0'10'' total CPU)
PDF posters kompiled: 1 (time: 0'13'' elapsed, 0'13'' total CPU)
Programs krun: 2 (time: 0'14'' elapsed, 0'21'' total CPU)
Total time: 0'37'' elapsed, 0'44'' CPU 
----------------------------
```

The above should be good enough for now, but any other idea or suggestion is welcome (let's try to keep it simple, though).

**Comment by osa1** [comment]
Done.
