### ISSUE TITLE
Using functional notation in productions in the include folder

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1939]
In the include folder in the distribution, I see we use a lot of explicit, redundant KLabels.  For example:

```
syntax String ::= "Id2String" "(" Id ")"    [function, hook(STRING.token2string), klabel(Id2String)]
syntax Id ::= "String2Id" "(" String ")"    [function, klabel(String2Id)]
```

Remember the functional notation convention in productions,

```
syntax Sort ::= name(Sort1,Sort2,...,Sortn)  [attributes]
```

is completely equivalent to

```
syntax Sort ::= "name" "(" Sort1 "," Sort2 "," ... "," Sortn ")"   [attributes, klabel(name)]
```

We introduced this notation inspired from SDF and indeed, it seems to be quite a common scenario.
1. @radumereuta, @cos: please confirm that there is no technical problem with the above.
2. Then @laurayuwen please go ahead and apply this change everywhere.

In the meanwhile, I'm going to make sure that this is properly explained in the manual.

**Comment by laurayuwen** [comment]
I see, it is redundant.

**Comment by grosu** [comment]
It should not be redundant!  If you don't put it, then the automatically generated attribute would be `name(_,_,...,_)`.  However, if you use the functional notation then it becomes redundant.

**Comment by laurayuwen** [comment]
yes, I saw your example. and I saw other cases that are using the way your example shows in domains.k

**Comment by laurayuwen** [comment]
What about these?
`syntax Int ::= Int "+Int" Int     [klabel('_+Int_), function, hook(#INT:_+Int_), left]`
The concrete syntax would automatically result in the same klabel.

**Comment by grosu** [comment]
Good question, @laurayuwen.  I don't like the quotes, but it is probably best to not open cans of worms if we don't have to right now.  Let us focus on what is absolutely needed for the transition to K4.0 right now.  Renaming these KLabels can wait.

**Comment by cos** [comment]
I removed quotes from klabels everywhere.
