### ISSUE TITLE
bracket for K

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1943]
@radumereuta's suggestion doesn't work:

> In `kast.k` line 51, there is this production:
> 
> ```
> syntax KBott     ::= "`" K "`"    [bracket]
> ```
> 
> To add parenthesis as brackets, just add (I would suggest modify and change all the current examples):
> 
> ```
> syntax KBott     ::= "(" K ")"    [bracket]
> ```

I tried the suggestion and tested against kool-untyped, but parsing failed many places (having 82 parsing errors). I guess it is due to ambiguities between an user-defined function's parenthesis with the bracket parenthesis of K.

Note that I tried both ways: either having additional bracket syntax or replacing it, but both failed.

**Comment by daejunpark** [comment]
split from #1929

**Comment by cos** [comment]
solved
