### ISSUE TITLE
make e-kore definition parser full-K attributes

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#1963]
`e-kore` currently parsers the attributes using labeled form. So it is not full K and requires things like `.::KList`. As I'm using it for `kdoc`, I need it to work, as expected, with full K. I don't really care in what form the attributes are parsed as long as we can use `latex` annotations on their productions.

Furthermore, I propose we postpone any philosophical discussion on how attributes should be represented in general. Let's make this work for `kdoc` and, as everything is K now, we will change it easily when we'll figure things out completely.

This is on the critical path for `kdoc`, so for the K 4.0.

**Comment by dwightguth** [comment]
Sorry I'm not entirely following what you're saying in this issue. Can you please clarify whether you are proposing to change the default syntax for existing attributes in a non-backwards-compatible manner?

**Comment by cos** [comment]
@dwightguth, no, it's related to the `e-kore.k` definition, which is not used by the main pipeline right now.
There will be no change to the current definitions.
I think @radumereuta knows what I'm talking about.

**Comment by grosu** [comment]
I agree with not deciding the exact syntax of attributes in `e-kore.k` now and I also agree with keeping things backwards-compatible.  We will worry about that later, after we transit to K4.0, when we'll use the syntax in e-kore.k for parsing full K.  So for now, @cos, anything that keeps the current attributes unchanged in the definitions in the tutorial and in the C semantics is acceptable.

**Comment by cos** [comment]
@radumereuta, I took a closer look at the productions for attributes, and it should actually work already. I remembered a previous intermediate step when they didn't. I'll bug you if I run into any trouble.

**Comment by cos** [comment]
should be ok
