### ISSUE TITLE
ktest --- typos and bad English in --help text

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#197]
I assigned this to Omer, but can you Michael please work with Omer to make sure the English displayed to users when they type ktest --help is correct?  Actually it would be great to do the same for all K tool ...

(e.g., ktest --help contains words like "comparsing")

**Comment by osa1** [comment]
I fixed typos, for other parts I'm waiting for a native English speaker's assistance :-)

**Comment by adamsmd** [comment]
Omer, what is that best way to coordinate this?  Do you just want to 
compile a list of error messages that ktest might generate and have me 
proofread them?

Michael

**Comment by dwightguth** [comment]
What are next steps here?
