### ISSUE TITLE
including domains automatically?

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#1972]
I'm revising the README.md files in the tutorial and I find it difficult to have to explain upfront about the domains.k file and about its DOMAINS and DOMAINS-SYNTAX modules.  Besides, these may/will change anyway in the future, in which case we'd have to change the tutorial again.  Also, we'd like to have good defaults in general, that give beginners a quick way to using K without much upfront learning, especially of low level details that may change anyway.

I would therefore like to suggest that we include automatically the domains.k file, and that each user-defined module suffixed with -SYNTAX includes DOMAINS-SYNTAX and any other user-defined module includes DOMAINS.  This will allow us to have minimal changes to the tutorial and will buy us time to think about how to organize our domains without bothering our users yet.

Then for those who do not want to have the predefined domains included in their definitions, we can offer an option --no-domains.  Note that this is also what Maude does with its prelude.

What do you guys think?

p.s. I know this looks like "something new that was not planned" and we are under time pressure, but I actually think that this will save us overall time!  Is should be easy to add the above right after ekore/outer parsing, probably it will take a couple of hours, and then we don't have to spend hours and hours of low-level work to change tens of definitions and readmes.

**Comment by grosu** [comment]
We have no time to argue about this, there are literally only a bit more than 2 weeks left, which is barely enough time to revise the tutorial.  So I take full responsibility for this decision: let's include domains.k and DOMAINS-SYNTAX and DOMAINS automatically as described above.  It is a very risky move to change the user-visible syntax in all definitions for a temporary reason.

**Comment by grosu** [comment]
I'm saying this after revising #1966 and seeing how ugly all those imports are.  It is just too early in the learning flow to tell students about it, so it must be a default.

**Comment by cos** [comment]
solved by #1976
