### ISSUE TITLE
kompile bad erorr message reported by a student

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#201]
A poor student run into the following K error:

```
$ krun test.fun
Krun was executed with the following arguments:
syntax_module=FUN-TYPE-INFERENCER
main_module=FUN-TYPE-INFERENCER
compiled_def=/home/garton1/K/homework/HW6/ex1/fun-type-inferencer-kompiled

Warning: Compiled definition file name (fun-type-inferencer) and the extension of the program (fun) aren't the same. Maybe you should use --syntax-module or --main-module options of krun
Warning: Maude produced warnings or errors.
Warning: "base.maude", line 104 (mod FUN-TYPE-INFERENCER-BASE): variable GeneratedFreshVar3:K is used before it is bound in equation:
ceq 
< generatedTop > GeneratedFreshVar2:Bag 
 < k > '_|_(C:KItem,,Cs:KItem) ~> 'compCases(GeneratedFreshVar0:K) ~> GeneratedFreshVar1:K </ k > 
 < tenv > Tenv:Map </ tenv > </ generatedTop > = 
< generatedTop > (GeneratedFreshVar2:Bag 
 < tenv > Tenv:Map </ tenv >) 
 < k > (C:KItem ~> 'tenv(Map2KLabel Tenv:Map(.KList)) ~> Cs:KItem ~> 'compCases(GeneratedFreshVar3:K)) ~> GeneratedFreshVar1:K </ k > </ generatedTop > if '#andBool(isCases(Cs:KItem),,isCase(C:KItem)) = # true(.KList) .
```

He finally managed to realize that the problem was that he used an underscore variable in the RHS of the rule, but ... what does this error message have to do with that error?  :)

Why do we event report the warning "Warning: Compiled definition file name (fun-type-inferencer) and the extension of the program (fun) aren't the same. Maybe you should use --syntax-module or --main-module options of krun" when we give a Maude error?

**Comment by traiansf** [comment]
Hm... I remember we used to check that all variables in the rhs appear in
the lhs.
Radu, do you know why woudn't we catch it before it gets to Maude?

2013/12/6 Grigore Rosu notifications@github.com

**Comment by radumereuta** [comment]
I also remember doing that. Maybe it's a bug.
Maybe we didn't take into consideration anonymous variables.

**Comment by grosu** [comment]
But the point is not only that we do or do not do the check ... What bothers me and the student here is that the warning message regarding the name of the module and the program extension makes no sense, and that we should not see any Maude errors.  Maybe all these are related in some way, but our users do not know that.

Grigore

**Comment by traiansf** [comment]
2013/12/6 Grigore Rosu notifications@github.com

> But the point is not only that we do or do not do the check ... What
> bothers me and the student here is that the warning message regarding the
> name of the module and the program extension makes no sense, and that we
> should not see any Maude errors. Maybe all these are related in some way,
> but our users do not know that.

No, they're not really related.  This was our default Maude-related error
message... for anything Maude-related.

The issue here is that we should not have any error messages due to Maude.
If you want to go to the extreme, we should report an internal error here,
and ask users to send a message.

Printing the output from Maude can be useful, though, as your student
finally figured out he was missing a variable.

Traian

**Comment by radumereuta** [comment]
Traian, did you manage to reproduce this bug?
I created a small example, but the tool works fine, it gives the correct error message.

Grigore, can you give as something that we can test? I'm not sure if it's because of parsing reasons. It may be because of something later on in the compilation stages.

**Comment by traiansf** [comment]
2013/12/6 Radu Mereuta notifications@github.com

> Traian, did you manage to reproduce this bug?
> I created a small example, but the tool works fine, it gives the correct
> error message.
> 
> I didn't try.  It would be best if we can get the failing definition...

Traian
