### ISSUE TITLE
Unable to match $PGM variable

### ISSUE THREAD

**Issue by jarsp** [kframework/k-legacy#2012]
The following rule, attempting to match $PGM fails:

```
configuration <T> <k> test </k> <program> $PGM:String </program> </T> 
syntax Test ::= "test" 
rule <k> test => .K </k> <program> S </program>
```

Note that if the `<program> S </program>` section is removed then the rule successfully matches.

**Comment by dwightguth** [comment]
Can you please tell me what version of K you are using?

**Comment by jarsp** [comment]
The latest version, I pulled it straight from master yesterday.
(Commit ef11f905bf7d7a6ec27e4f0eec0b7d0ff435f3b0)

**Comment by dwightguth** [comment]
Can you please tell me what command you are passing to krun? I tested the following and it works:

```
$ cat test.test
"5"
$ kompile test.k
$ krun test.test
```

**Comment by jarsp** [comment]
My bad, I did not realize that the input had to be enclosed in quotes. Sorry for the trouble.
