### ISSUE TITLE
ktest new error messages --- little bug

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#203]
First, let me tell you that I really like the new ktest output!  Here is a small improvement.  Consider the following message currently displayed:

```
ERROR: [/home/grosu/k/bin/krun /home/grosu/k/tutorial/2_languages/4_logik/basic/tests/reverse-fast-palindromes-2.logik --search --pattern=<solution> Solution:Map </solution> --directory=/home/grosu/k-private/tutorial/2_languages/4_logik/extended/exercises/logik-extended] output doesn't match with expected output (time: 12715 ms)
```

It would be great if the shown command can be executed as is, so people could just copy and paste what is between the square brackets and then execute it as a command.  That almost works, except for the pattern, which should be in-between quotes, that is:

```
/home/grosu/k/bin/krun /home/grosu/k/tutorial/2_languages/4_logik/basic/tests/reverse-fast-palindromes-2.logik --search --pattern="<solution> Solution:Map </solution>" --directory=/home/grosu/k-private/tutorial/2_languages/4_logik/extended/exercises/logik-extended
```

Probably there are other options in the same category, so you may want to fix them all at the same time.

**Comment by grosu** [comment]
Note that the --dry option also fails to put quotes around the pattern string.

**Comment by osa1** [comment]
I implemented this feature and pushed changes to master. I made some tests and even for most complicated krun tests it seems to working correctly.

**Comment by grosu** [comment]
hm, strange.  it puts the quotes like this `"--pattern=..."` instead of like this `--pattern="..."`, but krun seems to now care.  I think we should fix both ktest and krun here, to only work with the latter way of using the quotes.

**Comment by osa1** [comment]
I think this is not related with krun or some other program, this is related with shell. Command line arguments are separated with whitespace only, so these parameters are same:

```
"--arg=val"
--arg="val" (when arg does not have whitespace)
--arg=val (when arg and val do not have whitespace)
```

and they are all one parameter.

Current implementation can be easily improved for `--arg="val"` style quoting but I thought since there is no advantage in doing that, it's better to keep implementation simple.

**Comment by grosu** [comment]
it is OK to not do anything in krun then, if this is indeed a matter of shell, but in what regards ktest, I think we should be uniform with how to tell people to use the options, directly (in the tutorial) or indirectly (in the ktest output).  In the tutorial, we told them to write `--transition="a b c"`.

**Comment by osa1** [comment]
OK, I'll fix this and report back.

**Comment by osa1** [comment]
@grosu I pushed new version to master. Now only RHS is quoted and only quoted when necessary.

**Comment by osa1** [comment]
I'm closing this issue since it seems to be fixed already.
