### ISSUE TITLE
Caching rules does not work

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#2039]
**How to reproduce:**  
`kompile -v lambda.k` any definition should be the same though  
**Expected behavior:**  
After running kompile the second time, the number of parsed rules should be `[0/100]`.  
**What happenes:**  
This is what kompile with verbose mode prints:  
`Parse definition [104/108 rules]                             =  2574`   

This is a regression after merging #2036.

**Comment by dwightguth** [comment]
@cos if you could make this a high priority that would be great because while it doesn't break anything per se, it does really really slow down k development if I have to wait an extra 6 minutes every time I build the C semantics.

**Comment by cos** [comment]
@radumereuta, thanks for highlighting it. I'll solve it tonight.

**Comment by cos** [comment]
addressed by #2045

**Comment by radumereuta** [comment]
Caching works right now. Sort of. I found another bug which you can trigger after you move a rule up or down in the file. The warnings are not updated to the new location.
Try 1: `kompile -v -w all test.k`

```
module TEST
  rule A => .K
endmodule
```

prints out:

```
Parse definition [109/109 rules]                             =  5900
[Warning] Compiler: Variable 'A' was not declared. Assuming sort K.
    Source(D:\work\test\.\test.k)
    Location(2,8,2,15)
```

Try 2: `kompile -v -w all test.k`

```
module TEST

  rule A => .K
endmodule
```

prints out:

```
Parse definition [0/109 rules]                               =  3476
[Warning] Compiler: Variable 'A' was not declared. Assuming sort K.
    Source(D:\work\test\.\test.k)
    Location(2,8,2,15)      // this should have been line 3.
```

This used to work in K3.6.

**Comment by dwightguth** [comment]
@radumereuta I think that is less urgent because it probably didn't used to work in my version of the code either. We should probably fix it at some point but I'm not sure it should be part of #2045.

**Comment by cos** [comment]
thanks, @dwightguth, right.
@radumereuta, please open a separate issue for the new problem.

**Comment by radumereuta** [comment]
Opened #2047.
