### ISSUE TITLE
ktest/krun simple enhancement

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#204]
Looking again at the nice output for ktest when krun tests fail:

```
ERROR: [/home/grosu/k/bin/krun /home/grosu/k/tutorial/2_languages/4_logik/basic/tests/append-3.logik --search --pattern=<solution> Solution:Map </solution> --directory=/home/grosu/k-private/tutorial/2_languages/4_logik/extended/exercises/logik-extended] output doesn't match with expected output (time: 14044 ms)
```

The only thing which is missing there is the actual output file that it is checked against.

This leads to the following simple and I believe effective idea: let us add an option to krun, say `--expected-output <file-name>`.  With this option given, krun would succeed silently if the output is as expected, or would give an error otherwise.

Then ktest would generate the EXACT commands that failed, and users can simply copy and paste them to see what happened, without having to look into anything else, such as which out file has been checked against.

I think this would be quite nice and practical

**Comment by osa1** [comment]
This is very easy to add but I was afraid of having super-verbose output so omitted this. We can easily have something like:

```
ERROR: [/home/grosu/k/bin/krun /home/grosu/k/tutorial/2_languages/4_logik/basic/tests/append-3.logik --search --pattern=<solution> Solution:Map </solution> --directory=/home/grosu/k-private/tutorial/2_languages/4_logik/extended/exercises/logik-extended] output doesn't match with expected output (time: 14044 ms)
Expected output: (specified in file <output file path>)
<expected output>
But got:
<what output we got from program>
```

How does that look?

I personally do not prefer adding testing features to krun, I prefer having Unix-style specialized and simple programs instead. This should make maintaining and learning easier.

**Comment by silviuburceadev** [comment]
I have personally used diff and I think it's much better. If there is a large output + large expected output file and only a few lines are different, it will be hard to spot the different part.
