### ISSUE TITLE
Is jenkins supposed to throw exceptions that ktest does not?

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#2053]
I understand that we may not want warnings, but it is strange to have ktest pass the tests and then have jenkins throw exceptions:

http://office.runtimeverification.com:8080/job/k-framework-pull-request/org.kframework.k$k-distribution/710/testReport/junit/_var_lib_jenkins_jobs_k-framework-pull-request_workspace_k-distribution_tutorial_1_k_3_lambda++_lesson_2_lambda/k/lambda_k/

We should have the same behavior in both, I think.

**Comment by laurayuwen** [comment]
Yes, that would make developers better off. In fact, when you kompile, you also receive this warning, it's just ktest ignores such warnings.

**Comment by laurayuwen** [comment]
It's because Jenkins have this '--warnings-to-errors' option.

**Comment by cos** [comment]
The current behavior seems ok. Reopen if you disagree.
