### ISSUE TITLE
krun --parser option does not work on Windows 10

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#2064]
```
D:\github\grosu\k\k-distribution\tutorial\1_k\4_imp++\lesson_7>krun ..\lesson_1\tests\sum-io.imp --parser "kast --sort Stmts"
[Error] Critical: Error while running process:Cannot run program "kast" (in
directory "."): CreateProcess error=2, The system cannot find the file
specified
```

And because of that kast does not work for imp++ lesson 7.

**Comment by radumereuta** [comment]
This issue has been discussed before.
On Linux is ok to write that, but on Windows, calling kast needs the extension: `.bat`.
Try: `krun ..\lesson_1\tests\sum-io.imp --parser "kast.bat --sort Stmts"`

I don't think this is something that we can fix, it's just how java works in relation to windows.

**Comment by grosu** [comment]
But ktest with the provided config files fails because of that (the config file of imp++, lesson 7, needs to set the parser option) , which makes K unusable on Windows.  On the other hand, if we modify the config files to use kast.bat instead of kast then ktest will fail on the other platforms.  There must be a solution to this problem.

**Comment by radumereuta** [comment]
I know. When I was testing such things, I would temporarily add the `.bat` extension, and make sure I don't commit them.
I agree, this solution is silly. I someone could come up with a simple and elegant solution, that would be great.

**Comment by cos** [comment]
@grosu, I would guess this is essential for 4.0. @dwightguth would know best how to handle this. Otherwise, I can pick it up.

**Comment by grosu** [comment]
If @dwightguth can fix it quickly fine, but you do not have time to spend on this.  I am currently just modifying the "kast" to "kas.bat" in my config.xmls temporarily.  We can live with such known bugs and fix them immediately after the release.  What is critical is for all the definitions in the tutorial, with all their examples that were tested before, to work the same way now.

**Comment by dwightguth** [comment]
adding the .bat extension manually is the most elegant solution I can come up with. I agree it's not nice, but manually modifying the parsers people specify on the command line is even less nice. Eventually when you have correct support for start symbols this will not be as much of an issue though because it only affects ktest tests where the parser has been specified manually.

**Comment by grosu** [comment]
No need to fix it now, but the big problem right now is that people download K and the tests it comes with fail on Windows.  Yes, the problem will be minimized once the parser takes the user-declared sort of $PGM into account, but it is still strange that everything works fine if I type `kast --sort --Stmts sum.imp` in the command line, but it does not work if I type `krun sum.imp --parser "kast --sort --Stmts"`.  Can't we just do same call from Java that the command line does?  Again, not urgent.
