### ISSUE TITLE
wrongly-assigned associativites of non-binary operators

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#208]
`"absInt" "(" Int ")"` is specified as left-associative here:
https://github.com/kframework/k/blob/94e48be8fecfee275e414e722cc8565890e10f29/include/builtins/int.k#L39

`"~Int" Int` as right-associative:
https://github.com/kframework/k/blob/94e48be8fecfee275e414e722cc8565890e10f29/include/builtins/int.k#L13

`"notBool" Bool` as left-associative:
https://github.com/kframework/k/blob/94e48be8fecfee275e414e722cc8565890e10f29/include/builtins/bool.k#L12

I have corrected the third one. However, I am sure how to correct the first two. Can you help take a look, @radumereuta

**Comment by radumereuta** [comment]
left and right associativity attributes have no effect on unary operators. 
Also something like syntax Exp ::= "abc" "(" A "," B ")" [left]
does nothing. In this case it includes priorities too.
The only place where they have effect is on binary operators where you have two outermost non-terminals (ex _+_). If you see any more of these, feel free to remove them. If you have at least one outermost non-terminal, then you can use priorities to disambiguate your grammar. In any other cases it doesn't make sense.

**Comment by yilongli** [comment]
Thanks for your explanation! Although the left/right-associativity
attributes are safe to be "abused" w.r.t the parser, it confuses the test
generation functionality because sometimes I need to grab all
left/right-associative productions by looking at the attributes. Of course,
I can filter them out in my code but I think it would be nicer to not have
unnecessary attributes in the first place.

**Comment by radumereuta** [comment]
I wouldn't call it "abuse", I would call it "useless". In those cases the left attribute does nothing.
I guess in the worst case scenario we could detect that and give a hidden warning.

**Comment by traiansf** [comment]
I would say a hard warning won't hurt; it seems people should not use left
for non-binary productions, anyway...

2013/12/13 Radu Mereuta notifications@github.com

**Comment by grosu** [comment]
I agree.  The more warnings/errors we report to users, the better and faster they learn K.

**Comment by radumereuta** [comment]
@yilongli do you care to take over this task?
It shouldn't be that hard. You would have to extend this class
https://github.com/kframework/k/blob/master/src/javasources/KTool/src/org/kframework/compile/checks/CheckSyntaxDecl.java
with a few ifs.

**Comment by yilongli** [comment]
Sure, I can take care of this.

But right now, I wonder if there is a fix to the k definition. For example,
is there a "non-assoc:" label beside the "left:" and the "right:"?

**Comment by dwightguth** [comment]
What are next steps here?

**Comment by yilongli** [comment]
Resolved via https://github.com/kframework/k/commit/096c1a0d6ae55b1843fea889f81eb42269bfafd0.

**Comment by yilongli** [comment]
Reopened this issue until I correctly address the problem mentioned in https://github.com/kframework/k/commit/096c1a0d6ae55b1843fea889f81eb42269bfafd0

**Comment by yilongli** [comment]
@radumereuta I am still confused about how to fix this according to your comment: https://github.com/kframework/k/commit/096c1a0d6ae55b1843fea889f81eb42269bfafd0
How is the condition you described going to prevent  production like `"absInt" "(" Int ")"`? What do you mean by "The condition above should seek for a left-most-non-terminal"?

**Comment by radumereuta** [comment]
According to the current semantics of the associativity filters, `left` means that a set of productions (which are in relation to this one) are not allowed to be the right most child.
For example:

```
Exp ::= Exp "+" Exp | Int
```

and the input "1+2+3" will produce the following ambiguous tree:

```
amb(+(+(1, 2), 3), +(1, +(2, 3)))
```

The left associativity will eliminate the second variant, and will leave only the first term.

Looking back at the previous discussion, I think it's not worth trying to do this check. We want to define a new semantics for priority and associativity for the new parser; something that is safer and more intuitive.
@grosu what do you think?
