### ISSUE TITLE
Strange behaviour with floats

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#2081]
Consider the following simple definition:

```
module TEST-SYNTAX
  syntax Exp ::= Int | Float
  syntax Stmt ::= Id "=" Exp ";"
endmodule

module TEST 
  imports TEST-SYNTAX
endmodule
```

For the input `a = 0.0;` it works fine:

```
$ kompile test.k 
$ krun ex.test 
<k> a = 0e+00 ; </k>
```

Instead, for the input `a = 0.1;` it gives the following error message:

```
$ krun ex.test 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00000001241f6adb, pid=11916, tid=6403
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libmpfr_java-64-2300459451087067447.jnilib+0xbaadb]  __gmpn_popcount+0x5b
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/dlucanu/Documents/temp/testk/float/hs_err_pid11916.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/Users/dlucanu/k/k-distribution/target/release/k/bin/../lib/k: line 23: 11916 Abort trap: 6           java -Djava.awt.headless=true $K_OPTS -ea -cp "$(dirname "$0")/java/*" org.kframework.main.Main "$@"
```

A similar error is obtained with the input `a = 0.1f;`. 
With the input `a = 0.31e+2;` it works fine:

```
$ krun ex.test 
<k> a = 3.1e+01 ; </k>
```

but with the input `a = 0.314e+2;` it gives again an error:

```
$ krun ex.test 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x000000011a490adb, pid=12549, tid=5891
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libmpfr_java-64-8798624540130436044.jnilib+0xbaadb]  __gmpn_popcount+0x5b
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/dlucanu/Documents/temp/testk/float/hs_err_pid12549.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/Users/dlucanu/k/k-distribution/target/release/k/bin/../lib/k: line 23: 12549 Abort trap: 6           java -Djava.awt.headless=true $K_OPTS -ea -cp "$(dirname "$0")/java/*" org.kframework.main.Main "$@"
```

I used the last version:

```
$ kompile --version
K framework version 4.0-beta4-SNAPSHOT
Git revision: f587a40
Git branch: master
Build date: Mon Jan 18 18:38:56 EET 2016
```

The version 3.6 has the same behaviour.

**Comment by dwightguth** [comment]
This looks like a bug in the MPFR java bindings. I will look into this when I have some time.

**Comment by dwightguth** [comment]
This is on Mac OS, correct?

**Comment by dlucanu** [comment]
Thanks. It would be nice to fix it in 3.6 as well. I use it for teaching.
Yes, it is a Mac OS. The OS is El Capitain 10.11.2.

**Comment by dwightguth** [comment]
Okay. Can you tell me the exact processor your computer has?

**Comment by dlucanu** [comment]
Hardware Overview:

  Model Name:   MacBook Pro
  Model Identifier: MacBookPro7,1
  Processor Name:   Intel Core 2 Duo
  Processor Speed:  2,4 GHz
  Number of Processors: 1
  Total Number of Cores:    2
  L2 Cache: 3 MB
  Memory:   8 GB
  Bus Speed:    1,07 GHz
  Boot ROM Version: MBP71.0039.B0E
  SMC Version (system): 1.62f7
  Serial Number (system):   W802926PATP
  Hardware UUID:    5D811644-45B9-521A-A09F-8E621C97055E
  Sudden Motion Sensor:
  State:    Enabled

**Comment by dlucanu** [comment]
Any news?

**Comment by dwightguth** [comment]
Apologies, I didn't see your update with the hardware info. In order for me to determine whether this is affecting all machines or just your machine, I need to be able to test on another Mac, unfortunately, I am out of the office for the week and away from the development Mac we usually use.

@andreistefanescu can you please test this for me quickly and let me know if you can reproduce it?

**Comment by dlucanu** [comment]
It seems the same problem is on some linux machines. 
I asked my students to use Windows machine for the examples with floats, but this is far to be a fair solution.

**Comment by cos** [comment]
I know little about how we use the MPFR Java bindings. @dlucanu, is MPFR required for your problem?

@andreistefanescu, you probably know more about this. Are the MPFR bindings actually required in most cases or are we simply using them because they are available? It may be good to have the common case not use non-Java libraries.

**Comment by dlucanu** [comment]
I need an implementation of floats in order to execute algorithms from computational geometry. Any implementation that works on all platforms is fine for me. Note that there are more than 400 students that have to use K Tool to execute the taught algorithms.
