### ISSUE TITLE
The last stretch on the tutorial

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#2083]
- [x] 1_k
  - [x] 1_lambda
    - [x] last lesson
    - [x] all lessons (lesson 2, exclude: omega)
  - [x] 2_imp
    - [x] last lesson
    - [x] all lessons
  - [x] 3_lambda++
    - [x] last lesson
    - [x] all lessons (lesson 3, exclude: omega closed-variable-capture free-variable-capture)
  - [x] 4_imp++
    - [x] last lesson
    - [x] all lessons
  - [x] 5_types
- [x] 2_languages
  - [x] 1_simple
    - [x] 1_untyped (exclude: dekker -- it has been excluded in K 3.6 also)
    - [x] 2_typed/1_static - **@grosu**
    - [x] 2_typed/2_dynamic - **@grosu**
  - [x] 2_kool
    - [x] 1_untyped (exclude: cycle -- it has been excluded in K 3.6 also)
    - [x] 2_typed/1_static
    - [x] 2_typed/2_dynamic
  - [x] 3_fun
    - [x] 1_untyped - **@andreistefanescu**
      - [x] 1_environment
      - [x] 2_substitution 
  - [x] 4_logik
    - [x] basic - **@laurayuwen**

**Comment by cos** [comment]
This doesn't seem hooked in `config.xml`, should it?

https://github.com/kframework/k/tree/master/k-distribution/tutorial/1_k/4_imp%2B%2B/lesson_5/exercises/no-duplicate-declarations

**Comment by cos** [comment]
These look like bugs in the definition itself:
https://github.com/kframework/k/blob/master/k-distribution/tutorial/1_k/4_imp%2B%2B/lesson_7/tests/config.xml

**Comment by grosu** [comment]
Exercises are not hooked.  They have a separate repository with solutions, which needs to be kept private, for instructors.  Those also need to be updated, but I will do it later.  The idea is for students to call ktest on the provided config.xml of the exercise from the folder with the solution.  Likely the config.xmls need to be updated, too, but again, after.

**Comment by grosu** [comment]
> These look like bugs in the definition itself:
> https://github.com/kframework/k/blob/master/kdistribution/tutorial/1_k/4_imp%2B%2B/lesson_7/tests/config.xml

Why are you saying that?

**Comment by cos** [comment]
> Why are you saying that?

Nevermind, I thought the special casing was added to avoid flaky non-determinism. I see it's related to the $PGM sort hooking bug.

**Comment by grosu** [comment]
If there are no unexpected problems, I think I should be able to do SIMPLE and KOOL.  However, if there are problems, I don't know.  FUN is the most exposed one at this moment.  One possibility is that I move to FUN after SIMPLE.  @daejunpark are you also available today?  Not sure when you are flying back from Korea, might be today ...

**Comment by daejunpark** [comment]
@grosu I was still working on the error message, but it seems that I'd better to work on KOOL typed right now. Do you agree?

**Comment by grosu** [comment]
yes, i agree!  we can fix the remaining errors afterwards, but we cannot release without all the languages in the tutorial working.

**Comment by grosu** [comment]
I checked the simple typed dynamic and also fixed the list: there is no type inference for FUN, but there is an environment-based substitution and a substitution-based one; also, logik extended was HW, so there is only logik basic.

I am stuck with simple typed static.  @cos, was it clear from my descriptions what the problem was?  Can I help with anything there?

@laurayuwen : how is logik going?  any road-blockers?

@andreistefanescu : do you need my help?  should I take over one of the two FUN definitions?

@daejunpark : have you managed to pass KOOL typed dynamic?  Were there unexpected issues?  Simple typed dynamic was really easy.  The only thing which confused me was to make sure that the auxiliary `lookup` construct returns an `Exp` instead of `KItem`.  Otherwise it was a smooth ride.  Do you want me to take over one of the two?

**Comment by andreistefanescu** [comment]
@grosu I am working on the environment based fun. I will add some hooks for the pattern matching, rather than fix the version based on k rules, and we can fix that once we have a proper meta-level.

**Comment by cos** [comment]
@grosu, not quite clear, see my comment on that thread: 
https://github.com/kframework/k/issues/2100#issuecomment-172709012

**Comment by daejunpark** [comment]
@grosu I'm still working on kompiling KOOL typed dynamic. There are two issues regarding cell fragment variables. I just fixed one of them, and will fix another. I think it would be better if you can take over KOOL typed static in the meantime.

**Comment by laurayuwen** [comment]
@grosu logik has half its tests ok, but --symbolic-execution --search does not give correct output in the other half tests.

**Comment by grosu** [comment]
And are you trying to fix it yourself or you are waiting for somebody else to fix it?  Who?  I think @andreistefanescu is stuck with FUN.

**Comment by laurayuwen** [comment]
I have been trying it myself. This afternoon I was in lab, so I know Andrei's working on FUN. Just a little busy at home this evening.

**Comment by cos** [comment]
module very few exceptions, done.
