### ISSUE TITLE
ktest does not work with .k input files

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#209]
There are several errors reported here.

The new ktest does not work with lang.k input files anymore!  It seems to only work with config.xml files at this moment ...

For example, if we go to k/tutorial/1_k/2_imp/lesson_1, we should be able to type 

```
  ktest imp.k --programs tests --results tests --extension imp
```

everything should work.  But we get the following error:

```
[Error] Critical: Unrecognized option: --extension
    File: command line
    Location: System file.
```

Then, moreover, the following command should report an error, that --programs is given but no --extension is given:

```
ktest imp.k --programs tests --results tests
```

Instead, it works just fine, but it does not test any program with krun!

It seems that it accepts the deprecated --extensions option instead, but that does not work anyway:

```
ktest imp.k --programs tests --results tests --extensions imp
```

does not krun any programs either.

Finally, the --verbose option does not work with lang.k inputs either.

**Comment by osa1** [comment]
Grigore,
- `--extension` option should be fixed now(it was actually working before, but it was just named as `--extensions`).
- about "should report an error, that --programs is given but no --extension is given", `--programs` is set to parent folder of target `.k` file by default. So it's like always given. Do you want me to change this?
- I tried `--verbose` and it seems working. What difference are you observing?

**Comment by dwightguth** [comment]
Is this fixed?

**Comment by osa1** [comment]
> Then, moreover, the following command should report an error, that --programs is given but no --extension is given ...

This part is not fixed yet. Related with #138. I'll fix this.
