### ISSUE TITLE
logik tests

### ISSUE THREAD

**Issue by laurayuwen** [kframework/k-legacy#2090]
Logik/basic can pass tests `fact`, `append` and `family` now, stuck in k for `reverse` and `takeout` tests. 
I checked K online tutorial and it also stuck there for those tests. Were they left for homework?

**Comment by grosu** [comment]
don't have time to look into this now.  pick the same thing as in 3.6.

**Comment by laurayuwen** [comment]
Is online tutorial 3.6?

**Comment by grosu** [comment]
Doesn't matter.  This is the official 3.6:

https://github.com/kframework/k/tree/3.6Base

**Comment by laurayuwen** [comment]
OK, not homework. some search bug here.
