### ISSUE TITLE
unkool warning

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#2112]
Trying to dig more into the warnings reported in #2109, I finally identified this nasty little bugger:

```
module TEST
  syntax Type ::= Id [klabel("class")]
  configuration <k> .K </k>
endmodule
```

Kompiling it, you get this:

```
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: syntax KBott ::= "."
[Location(#token("48",Int),#token("20",Int),#token("48",Int),#token("80",Int))
Source(#token("D:\\github\\grosu\\k\\k-distribution\\target\\release\\k\\lib\\java\\..\\..\\include\\builtin\\kast.k",KString))
hook(#token("org.kframework.kore.EmptyK",AttributeValue))
klabel(#token("#EmptyK",AttributeValue)) klabel(#token("#EmptyK",KString))]
    #EmptyK()
2: syntax Type ::= Id
[Location(#token("2",Int),#token("19",Int),#token("2",Int),#token("38",Int))
Source(#token("D:\\github\\grosu\\k\\k-distribution\\tutorial\\2_languages\\2_kool\\2_typed\\2_static\\.\\test.k",KString))
klabel(#token("class",AttributeValue)) klabel(#token("class",KString))]
    class(#EmptyK())
        Source(D:\github\grosu\k\k-distribution\tutorial\2_languages\2_kool\2_typed\2_static\.\test.k)
        Location(3,21,3,22)
```

As a user, here I throw the towel.  :)

**Comment by radumereuta** [comment]
Hmm...ok. I understand what happens.
I'm working on a fix.

**Comment by grosu** [comment]
Please @radumereuta , I'm currently stall, as KOOL typed static is the only one nobody is working on.

**Comment by grosu** [comment]
Finally, I have managed to eliminate all the other kompilation errors from `kool-typed-static.k`!  So if I comment the attribute of the subsort relation like below,

```
  syntax Type ::= Id              // [klabel("class")]
```

I can kompile it.

**Comment by radumereuta** [comment]
I've managed to create a fix for the problem, but I got stuck in some caching issues in the visitors for TermConses. At least this is what @cos thinks happens.

I will continue to work on this tomorrow.

**Comment by cos** [comment]
@radumereuta, I will close this now. Reopen if you think there's anything not clarified here.
