### ISSUE TITLE
duplicate ktest

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#2114]
Currently kool-typed-dynamic's config.xml has two test nodes, which are duplicate except that one is for concrete java backend, and another for symbolic java backend. I can remember that we did before, but forgot why. 

@grosu Can we delete one of them, especially symbolic one, which will reduce time for regression test.

**Comment by daejunpark** [comment]
https://github.com/kframework/k/blob/18cb31ec469967d4a7afeaf8a2aa092e4be03e85/k-distribution/tutorial/2_languages/2_kool/2_typed/1_dynamic/tests/config.xml

**Comment by grosu** [comment]
Yes.  I've done exactly the same thing in SIMPLE a few hours ago (after checking with @andreistefanescu).
