### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#212]
When will there be native windows support without having to use K VM, Cygwin, etc.

**Comment by radumereuta** [comment]
K works on windows right now. We still provide the K VM because it does not scale as good as the linux and mac systems.
But at this moment, you can just copy the files of the K distribution, put the /bin directory in your path, and you are set to go.

**Comment by sirinath** [comment]
Perhaps it will be worthwhile to investigate how be better support any platform easily.

One idea is that you have a formal architecture definition language which formally defines a platform. Also have a scheme in which the k tools are defined in a DSL. Then tools for any new language target can be defined changing the architecture definition.

**Comment by dwightguth** [comment]
Closing. Please reopen if you still have questions.
