### ISSUE TITLE
Pattern matching for configuration displaying is not available for normal execution 

### ISSUE THREAD

**Issue by andreistefanescu** [kframework/k-legacy#2123]
The option `--pattern` should be available for normal execution (without --search).

**Comment by andreistefanescu** [comment]
@cos reassign as appropriate.

**Comment by cos** [comment]
@dwightguth knowns best how this is hooked. If this is urgent (please add a milestone tag) and @dwightguth doesn't have time, I can do it.

**Comment by dwightguth** [comment]
This should work already as long as you correctly implement executeAndMatch. If there is a problem it's not in anything having to do with my code because the ocaml backend does this all the time.

**Comment by andreistefanescu** [comment]
It works. I assumed it did not work because `--pattern` was used with `--search` on deterministic definitions. The config files must have been old.
