### ISSUE TITLE
## Environment

### ISSUE THREAD

**Issue by imran-iitp** [kframework/k-legacy#2126]
PATH=$PATH:<release>/lib/native/linux:<release>/lib/native/linux64
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<release>/lib/native/linux64

What is the meaning of <release> in the above path?.. What should I write over there?

**Comment by daejunpark** [comment]
It should be: (Note that we have `<release>`.)

```
PATH=$PATH:<release>/lib/native/linux:<release>/lib/native/linux64 
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<release>/lib/native/linux64
```

`<release>` is a path to `k-distribution/target/release/k` in your source tree.
