### ISSUE TITLE
Question: Lambda Cube, Pattern Calculus, Process Calculus and Targets

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#213]
This is one of the most promising project I have seen. I am looking to see if some of the features below are supported and if not what is the road map to support them.

Does Rascal support:

1) All bases of the lambda cube
1.1) Ability to support different type systems
2) Pattern calculus
3) Process calculus

with interaction between the 1, 2 and 3

Also what the targets are. Can it target:
1) JVM
2) CLI
3) LLVM

**Comment by dwightguth** [comment]
Closing. If you still want an answer, reopen and we will try to respond. I am really sorry we didn't do so before, but the project ops structure was in a very bad state and we are only now going through everything and trying to set up a system to make sure all questions are answered.
