### ISSUE TITLE
Add more-excludes to ktest config file includes element

### ISSUE THREAD

**Issue by traiansf** [kframework/k-legacy#214]
It's very nice to have more-programs and more-results attributes to an 'include' element in the ktest configuration file.

It would be wonderful to also support more-exclude, which would add more programs to the current list of excludes.

This is needed because now, if one needs to add an extra program to the excludes list when importing a configuration, one needs to remember all the previously excluded files.

**Comment by osa1** [comment]
@traiansf I made required changes and pushed new version to `issue214` branch, can you please test and tell me if it's working as you expect?
