### ISSUE TITLE
K Tutorial in a Document form

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#215]
Is it possible have the K tutorial in a document form. You can read and do things at your own pace than video.

**Comment by adamsmd** [comment]
This would also be nice to serve as a searchable reference.  E.g., if 
you know that one of the tutorials explained "bind" but don't remember 
which one.

At the simplest level, this could either just be a copy of the script 
(or those still exist) or a transcription of the code and words said in 
the videos.

**Comment by sirinath** [comment]
It can be a Wiki or in github so others can also contribute to the documentation efforts.

**Comment by sirinath** [comment]
Also looking forward to seeing the tutorials completed. 

Perhaps you could add some examples in type state, dependent types, pattern calculus languages like bondi, etc.

**Comment by grosu** [comment]
This is one of my resolutions this year, to complete the tutorial :)  But I'm going to write a script that will turn the tutorial files into one document soon.

**Comment by sirinath** [comment]
Great ;-)

This is a great framework looking to use this in production soon when it is ready for such use.

**Comment by davidlazar** [comment]
I am teaching K to a friend and he requested exactly the same thing: the K tutorial as a document, rather than a video.

**Comment by sirinath** [comment]
Also added the following for a visual interactive book style tutorial for K

https://github.com/kframework/k/issues/227

**Comment by dwightguth** [comment]
Closing. Please reopen if you have further questions.
