### ISSUE TITLE
ktest --report

### ISSUE THREAD

**Issue by pdaian** [kframework/k-legacy#216]
As part of a feature I am working on for kweb, a necessary component is the ability to parse the output of the ktest process and assign a numerical "score" to the resulting output.

Right now, the only way to do so seems to be to use this line:
Programs krun: 38 (time: 0'35'' elapsed, 3'42'' CPU)
along with manually counting the number of failures to assign the score. 

I'm interested in a more consistent form of output that's easily machine processed... I know there was a --report feature (which now seems to do nothing on my machine) that was similar to this, but I seem to recall that even before being disabled it wasn't fully working.

Consider this a feature request for machine parseable/standardized ktest output :).

**Comment by andreiarusoaie** [comment]
The `--report` option should still work, otherwise Jenkins wouldn't work. It should generate a folder named --junit-reports which contains a lot of xml files containing the data. I'm not sure if Omer also puts the timing data into that XML but we can kindly ask him to do that.

**Comment by osa1** [comment]
@pdaian `--report` is exactly for this purpose and it's supposed to create a `junit-reports` folder when used. Did you check that folder?

**Comment by pdaian** [comment]
Yes, that is indeed what I am looking for and I missed it, my bad!  Closing the issue.

On a related note it would be nice if we could specify the output of these XML files.  The way I have it right now, kweb has no way of distinguishing whether a report was just generated by the process that exited or is older/newer than that.  It seems to work just fine but is slightly inconvenient.

Thanks!
