### ISSUE TITLE
Setting up K for development

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#2160]
Hello. What is the best way to set up the Java backend of K for development? I'm using Eclipse. Should I import it as a Git project or as a Maven project? Can I compile the whole thing in Eclipse? or is every part separate?

**Comment by cos** [comment]
If you no not want to change any of the K code, simply add the jar from the K release as a dependency for your project: https://github.com/kframework/k/releases

If you do want to change K, it may be better to use IntelliJ. We had some trouble making Eclipse play well with both Scala and some mvn packages.

If you run into any trouble, i'll be on gitter most of the day today.

**Comment by omarzd** [comment]
IntelliJ was straightforward. Thank you.

**Comment by omarzd** [comment]
IntelliJ was straightforward. Thank you.
