### ISSUE TITLE
KItem not acting as least sort

### ISSUE THREAD

**Issue by lucaspena** [kframework/k-legacy#2166]
I'm using K 4.0 trying to kompile the LLVM semantics, and I came across this bug that I believe is a bug in K, caused by KItem not acting as a least sort. Below is a minimal version of the code that caused the bug. The error message was "Unexpected sort KItem for term, ..., expected Loc"

```
module TEST-SYNTAX
  syntax Loc ::= loc(Int, Int)
  syntax KItem ::= "nextSym" Loc 
endmodule

module TEST
  imports TEST-SYNTAX

  configuration <T color="yellow">
                  <k color="green"> $PGM:Loc </k>
                  <nextLoc> loc(1, 0) </nextLoc>
                </T>

  /* since KItem is supposed to be a least sort, the following rule should be
     ok, as it should be the case that KItem is a subsort of Loc */
  rule <k> loc(1, 0) => L </k>
       <nextLoc> L:Loc => nextSym L </nextLoc>
endmodule
```

**Comment by cos** [comment]
It is best to avoid playing with the KItem as a bottom sort. In my view, we would be better of if we simply didn't even expose it to end users. Why not express this somehow else, e.g., `syntax Loc ::= "nextSym" Loc`?

**Comment by lucaspena** [comment]
Yes, I had tried that, and it works, and I'll change it to that, but should it not also work as is?

**Comment by dlucanu** [comment]
Maybe I am wrong, but I guess that the problem is not that KItem is not a bottom sort. Note that the configuration specifies that the sort of the cell `<nextLoc>` is `Loc` (= the sort of `loc(1,0)`) and it expected that the content of the cell to be always of sort Loc.

**Comment by cos** [comment]
The KItem sort is split into a top and bottom sort. There is a mechanism for shoving something below the bottom sort, which is useful in certain circumstances, e.g., allowing the rewrite arrow to appear anywhere. I think the mechanism is still exposed to the end users, and I think that's what @lucaspena was trying to use. So, in this case, `"nextSym" Loc` would have become a bottom sort and be allowed to appear anywhere.

**Comment by radumereuta** [comment]
That sort is `KBott`. It's not finalized, and it's better if it's not used by users since it may get abused and lead to other issues in the future.

**Comment by daejunpark** [comment]
So, there are cases where users want to use such a bottom sort explicitly. Think about a polymorphic function, e.g., a function replacing all sub-terms that match some patterns. In that case, a return value of the function should be able to be used for arbitrary sorts, and we need a kind of least sort for that.

The thing is that this is a situation that we have in LLVM semantics. It heavily uses such a least sort that was available at K 3.6, and now we have a problem to port it to K 4.0. 

@cos @radumereuta What do you think is the best to resolve this issue? Re-organizing/changing the existing semantics not to use such a feature? Or, waiting until the least sort feature is finalized? When do you think it will be finalized?

**Comment by grosu** [comment]
did you try to use K instead of KItem?  and you can alway use casting to make a term of sort K be parsed as any sort you want, can't you?

**Comment by daejunpark** [comment]
I cannot use K because it cannot be extended. I can try the casting, which will be ugly and cumbersome though.

**Comment by grosu** [comment]
You can define your own Bottom sort if you wish to do subsort polymorphism manually.

**Comment by radumereuta** [comment]
It used to be that in K3, the sort K would be used as a Top and a Bott at the same time.
But I think that made it less clear of what was happening because it was based on a trick that SDF was able to do.
With K4, we migrated to a slightly different system, where every user sort is contained between a top (`K`) and a bottom (`KBott`): `K ::= Exp` and `Exp ::= KBott`
For example, the rewrite production is defined as follows: `KBott ::= K "=>" K`, which means you can use it in almost any context to rewrite terms, and can rewrite any user defined terms.

To answer the original issue: go ahead and use `KBott`, but avoid at all costs using it in subsorts. The automatic subsort mechanism is very sensible to modifications. If you run into problems, please let me know, so I can define the safe ways in which `KBott` can be used.

**Comment by daejunpark** [comment]
Another possible workaround is to use the sort casting `:>`, like:

```
<nextLoc> L:Loc => `nextSym L`:>Loc </nextLoc>
```

It could be a simpler solution if there are not many places to annotate the sort casting.

**Comment by daejunpark** [comment]
@lucaspena can we close this?

**Comment by lucaspena** [comment]
Yes, sorry. I just closed it.
