### ISSUE TITLE
Infinity Int

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#2170]
How do you say infinity integer in K? I need to find the least number in a certain bag, and I need to initially compare to infinity.

**Comment by radumereuta** [comment]
I don't remember having such a thing in K for Integers. Only for floats.
Another thing is, bags are supposed to be commutative, so no order on them.
Maybe you need a different structure to keep track of an order?

**Comment by omarzd** [comment]
No, the number is in a cell inside a cell inside the bag, but that's not my problem. I already solved my problem though. I'm using an upper limit. But just for reference, how do you refer to infinity with floats?

**Comment by radumereuta** [comment]
https://github.com/kframework/k/blob/master/k-distribution/include/builtin/domains.k#L318
