### ISSUE TITLE
investigate problems found in tool relating to spin

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#2175]
spin (https://spinroot.com/spin/Src/) is a tool they were testing kcc on at JPL with Grigore. We ran into several issues that need investigating:
1. an issue with line numbers where an indeterminate value error is reported on a line that contains the empty statement. it seems to actually be occurring on the line immediately above it.
2. An issue with running kcc on older versions of linux where we get an "incompatible types in different translation units" error relating to the stuff that we do with __fxstat. This is a false positive, and we need to actually compile dist/x86_864-linux-gcc-glibc/lib/libc.so on the target machine during postinstall.
3. An issue with an extern local variable where its definition cannot be found in the environment even though it is in fact defined.

**Comment by grosu** [comment]
And there is also the fact that the produced binary crashed in the end.

**Comment by dwightguth** [comment]
Closing this. Opened it in the wrong repo, sorry.
