### ISSUE TITLE
K4.0 will not recognize cell names if separate files

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#2177]
This used to work in K3.5 and 3.6. I had a number of files, each containing a single module. The main module imports all of them while each one of them imports the syntax module. When I tried to `kompile` the project in K4.0, I got the following error:

```
[Error] Inner Parser: Parse error: unexpected character '>'.
```

This error occurred at every rule that has a cell name in it like `<thread>`, which tells me that the parser does not recognize the labels of these cells. Moving rules or whole modules into the same file that contains the configuration solved this problem. What is causing this problem?

**Comment by dwightguth** [comment]
You need to import the module containing the actual configuration
declaration. K4 is much more strict about requiring that any module
containing a rule that uses a piece of syntax import the module that syntax
is declared in.

**Comment by omarzd** [comment]
I tried that. I put the configuration in a separate file and imported that from other modules. The same error appeared.

**Comment by dwightguth** [comment]
That's definitely a bug then. You should construct a minimal example.

**Comment by omarzd** [comment]
You were right again @dwightguth. I made a mistake before in importing. It's working now. Thank you.
