### ISSUE TITLE
PEG and Flexible Parer Schematics Definition

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#219]
Is there a possibility to add PEG as Parboiled, Nemerle support this and if would be easy to convert PEG based definitions into K

**Comment by adamsmd** [comment]
There are two things that you might be asking for here.

The first is to support PEG style grammars within K.  We are in the 
process of redesigning the parser and I will be sure to see if we can 
incorporate such grammar styles.

The second is to support a particular third-party PEG notation.  I do 
not see that happening any time soon as any incongruities between K's 
parser and the third party parser would lead to trouble.

**Comment by sirinath** [comment]
Make it such that 3rd party or any other notation can be defined through K language by the user and the tooling would handle it. Also ability to define the parser algo. The parser can be generated through a DSL and / or through the defined notation. This will be the ultimate tool then. Also the parser functionality can be verified to spec.

This can happen some point later in case you want to take this route. All the tooling in K will be defined and generated through a K DSL.

**Comment by grosu** [comment]
Note that K allows you to plug your own parser for programs.  See the --parser option of krun.  As Michael said, we are going to soon have a better parser in K than we have now, but that will be the only parser used to parse the semantic rules.  But parsing the programs is an entirely different bussiness, which can be done with any parser, and K has been specifically designed to allow that.

**Comment by sirinath** [comment]
What I am saying is slightly different as per my 2nd comment above. When defining the language give the ability to define the parsing semantics for which you will have a generated parser to do the parsing. So when you define a language you automatically get a parser and can control the grammar and language it is defined in in terms of the K language. This would help in maximum extensibility, generality, portability and re-usability of prior work when using K.

**Comment by sirinath** [comment]
In a nutshell a grammar defined in terms of K for which a parser is generated to parse the language written in the new grammar defined in k using an additional DSL for parser schematics written also in K.

This way if you have something defined in any other grammar you still can get to use it within K.

**Comment by dwightguth** [comment]
Closing. Please reopen if you have further questions.
