### ISSUE TITLE
Circular dependencies in k-distribution/include/builtins

### ISSUE THREAD

**Issue by adrianherrera** [kframework/k-legacy#2192]
E.g.

```
bool.k -> ../k-prelude.k -> builtins/builtins.k -> bool.k
```

```
int.k -> k-equal.k -> list.k -> k-equal.k
                            `-> int.k
```

**Comment by radumereuta** [comment]
These are used by K3.x.
We're trying to move towards K4, which uses files only from `/include/builtin`. Hopefully, this won't be an issue then since we're planning to remove them completely.

**Comment by adrianherrera** [comment]
Cool, thanks Radu. Any timeframe for when you’ll move to K4?

**Comment by radumereuta** [comment]
@cos might be able to answer that better, but in the meantime, you can use it in the master branch of the K framework. To call it K4, we just have to iron out some kinks and clean out old files.

**Comment by cos** [comment]
@adrianherrera, we have already released K4: https://github.com/kframework/k/releases/tag/v4.0.0

We'll do another release in about a month with new features and cleaning up the old files.

**Comment by cos** [comment]
related to deprecated code so closing
