### ISSUE TITLE
How to write conditional rule in K

### ISSUE THREAD

**Issue by manueldallavalle** [kframework/k-legacy#2195]
I'm trying to implement the condition statements of COBOL into K.
I've already implemented with success the logic of the IF [condition] THEN .. ELSE .. END-IF

Now i'm trying to implement the negated condition for this statement but i cannot figure how to do it..
I thought to write a new rule with the following condition:
_**If BExp contains "IS NOT" negate the final result with notBool, else do nothing**_
Or better, _**if PreBExp is equals to "IS NOT" negate the final result with notBool, else do nothing**_
My current implementation is (Faulty and not optimized):

```
syntax PreBExp ::= "IS NOT"
                   > "IS"
  syntax BExp  ::= Bool
                 | AExp PreBExp "GREATER THAN" AExp    [strict(1,3)]
                 | AExp PreBExp "LESS THAN" AExp       [strict(1,3)]
                 | AExp PreBExp "EQUAL TO" AExp        [strict(1,3)]

  rule I1:Int IS GREATER THAN I2:Int => I1 >Int I2
  rule I1:Int IS NOT GREATER THAN I2:Int => notBool(I1 >Int I2)

  rule I1:Int IS LESS THAN I2:Int => I1 <Int I2
  rule I1:Int IS NOT LESS THAN I2:Int => notBool(I1 <Int I2)

  rule I1:Int IS EQUAL TO I2:Int => I1 ==Int I2
  rule I1:Int IS NOT EQUAL TO I2:Int => notBool(I1 ==Int I2)

  rule IF (true) THEN S  ELSE _ END-IF => S 
  rule IF (false) THEN _ ELSE S END-IF => S

```

The only rule with condition that i've found is: rule 0 ? _ : E:Exp => E
but i'm not able to figure how to use with my case

Can someone give me a hint that allow me to write that rule?
I've searched in all tutorials and on the official site, but nothing.

**Comment by cos** [comment]
hi @manueldallavalle, sorry for the late reply. did you figure out a solution?

**Comment by manueldallavalle** [comment]
@cos Yes, found a solution myself. Thanks anyway
