### ISSUE TITLE
Latest version of Java fails with error on IntelliJ

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#2220]
Tested on version jdk1.8.0_101 and 102.
I always get an error in master, in file AttCompare.java:69
This worked somehow in version 60, but I couldn't revert to that state.

Note that maven works correctly, only IntelliJ fails.

**Comment by cos** [comment]
is it that IntelliJ just highlights that as an error, or does it also fail to build?

If it fails to build, what is the exact error?

**Comment by cos** [comment]
@radumereuta, could you have a look?

**Comment by radumereuta** [comment]
Fails to buld with error:

```
Error:(69, 28) java: no suitable method found for filterKeys(attNames::contains)
    method scala.collection.GenMapLike.filterKeys(scala.Function1<java.lang.String,java.lang.Object>) is not applicable
      (argument mismatch; scala.Function1 is not a functional interface
          multiple non-overriding abstract methods found in interface scala.Function1)
    method scala.collection.MapLike.filterKeys(scala.Function1<java.lang.String,java.lang.Object>) is not applicable
      (argument mismatch; scala.Function1 is not a functional interface
          multiple non-overriding abstract methods found in interface scala.Function1)
```

Did you try to update to the latest versions of Java and IntelliJ?

**Comment by cos** [comment]
It looks like it's compiling with the wrong version of Scala. This is a setting in IntelliJ -- you usually select it through the "Setup Scala SDK" button that appears when the Scala library is not automatically detected.

**Comment by cos** [comment]
Check that the IntelliJ module settings are the same as the the version in the ".pom", 2.12-M5 I think.

**Comment by radumereuta** [comment]
Ok, that worked. I had to reimport the entire project from the maven files. I guess it got desynchronized at one point while switching between different branches.

Thanks.
