### ISSUE TITLE
Source to Source (S2S) Translation Support under Constraints Optimisation

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#224]
Is it possible to add the ability to perform S2S translations for any language defined in K under contents.

E.g.  If you define the x86 ASM language give the ability to translate from any other k defined language to this under optimisation for speed.

In the case you are translation say one source language to another the constraints  can be defined in term of readability etc. The contents and goals can be fuzzy or subjective in some cases.

At some point the applications can spill over beyond computer languages into natural languages.

**Comment by sirinath** [comment]
The compilation process would be a constraints optimization also

**Comment by dwightguth** [comment]
Closing. If you still want an answer, reopen and we will try to respond. I am really sorry we didn't do so before, but the project ops structure was in a very bad state and we are only now going through everything and trying to set up a system to make sure all questions are answered.
