### ISSUE TITLE
Minimise Other Dependencies

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#225]
Is it possible to cut down on external dependencies like:

1) Maude 
2) Proof assistant

and implement such functionality within k tool chain it self.

Also make K coherent than piecemeal combination of tools. 

One aspect would be to define K tools in terms of a K DSL than Java. This can help:
1) productivity (DSL would be focusing in a particular area it would handle it well)
2) maintainability in the long run (Since it is defined in DSLs, this would be easy to changed if the DSLs are well designed)
3) extensibility (New K schematics defined in Older K)
4) verifiability and provability with the ability to do so recursively to any K defined language and any system implemented in the K defined language if designed that way.
5) reduce barrier for usage and extensions (easy to contribute and extend K through DSLs than wrestling a very large code base in a general purpose language)
6) Portability (with proper DSL to bytecode / native code translators this can be ported to many platforms)

**Comment by dwightguth** [comment]
Closing. If you still want an answer, reopen and we will try to respond. I am really sorry we didn't do so before, but the project ops structure was in a very bad state and we are only now going through everything and trying to set up a system to make sure all questions are answered.
