### ISSUE TITLE
Build failing on master

### ISSUE THREAD

**Issue by msaxena2** [kframework/k-legacy#2264]
I get the following error when trying to build master - 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project kernel: Compilation failure
[ERROR] kernel/src/main/java/org/kframework/kompile/KompileFrontEnd.java:[74,102] unreported exception org.kframework.minikore.ParseError; must be caught or declared to be thrown

**Comment by daejunpark** [comment]
It was temporarily broken due to updated dependencies. Now it should work. You can follow:
https://app.codeship.com/projects/130795/builds/21832044

**Comment by daejunpark** [comment]
You can close once you find it is fixed. I think we have to think about a better approach to prevent this happen later.

**Comment by msaxena2** [comment]
@daejunpark Thanks.
