### ISSUE TITLE
does #include work?

### ISSUE THREAD

**Issue by kheradmand** [kframework/k-legacy#2277]
@daejunpark 
I see in javascript semantics that things like `#include "js-init-configuration.k"` are used. I was wondering if this thing is supported in the current version of K and if not, what is the alternative?

**Comment by daejunpark** [comment]
That's what a simple C-like preprocessor handles:
https://github.com/kframework/javascript-semantics/blob/master/kpp.py

**Comment by kheradmand** [comment]
Oh I thought it was supported by K (like `#requires`). thanks
