### ISSUE TITLE
Types in Configuration Cells

### ISSUE THREAD

**Issue by omarzd** [kframework/k-legacy#2281]
I have a cell that is supposed to hold the type `Id`. How do I define that cell in my configuration? In K3.6, I had it defined as `<defId> "" </defId>`. It worked fine but now K 4.0 expects a `String` and complains when it sees a `Id`.

**Comment by omarzd** [comment]
I solved it by declaring in the configuration `<defId> ?X:Id </defId>`, but I'm not sure if it should be `?X` or `!X`.

**Comment by radumereuta** [comment]
Since the configuration is regarded as a ground term, usually we use the null element of the required type. `.Map`, `.K`... In this case, you could try `0`. I find the error message from your first message as expected behavior, and what happened in K3.6 as a flaw that happened to work in that case.

**Comment by omarzd** [comment]
Why is `0` better than `?X:Id` ? `0` does not carry a specific type.

**Comment by radumereuta** [comment]
Actually `0` carries the sort `Int`, but now I noticed that you wanted `Id`, in which case I guess you could use that. But my suggestion still applies. The configuration reads the sort of the term in that cell and applies it to later rules. So you could use anything that parses unambiguously as `Id`.

**Comment by omarzd** [comment]
> anything that parses unambiguously as `Id`.    

I see. That was very helpful. Thank you.
