### ISSUE TITLE
Templating and macro expansions

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#229]
In order to be able to reuse much of the modules with maximum generality a way to template / macro scheme would be ideal where specifics for the syntax and rules can be injected later.

**Comment by dwightguth** [comment]
Closing. If you still want an answer, reopen and we will try to respond. I am really sorry we didn't do so before, but the project ops structure was in a very bad state and we are only now going through everything and trying to set up a system to make sure all questions are answered.
