### ISSUE TITLE
Dialecting Existing Language Definitions to Form New Languages Perhaps Inheriting from Multiple Parents

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#230]
There are 2 use cases here

1) I need to extend a language by small delta like introducing syntactic sugar

2) Derive a new languages influenced by some common languages.

The syntax and rules should be easily referenced such that they can be overridden and also inherited. There should be a proper data structure around this similar to a Meta object.

Also may need a more granular object and module system. Syntax / rule / module definition can be a object??? Must think through how this can be implemented.

Also they should be easily transformed into a new form when the syntax / rules is like but not exact. If K has a transformation mechanism where K constructs can be manipulated this would be possible. May be this can have some features from Homoiconic languages.

**Comment by sirinath** [comment]
In a nutshell, reuse by inheriting and also rewriting the syntax and rules.

**Comment by dwightguth** [comment]
Closing. If you still want an answer, reopen and we will try to respond. I am really sorry we didn't do so before, but the project ops structure was in a very bad state and we are only now going through everything and trying to set up a system to make sure all questions are answered.
