### ISSUE TITLE
ktest -- unexpected behavior of option exclude

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#232]
It took me an hour to realize that `exclude = ""` actually means excluding EVERYTHING... Is this the expected behavior? If yes, it should be clearly documented in the help.

**Comment by osa1** [comment]
Yes, this is expected. `exclude` is simply a pattern that is searched in full file paths. Since there was also someone else confused by this, I think it's a good idea to either change this behavior or improve help message.

**Comment by osa1** [comment]
btw, exclude string it's not a glob or regex pattern, it's just a character string.

**Comment by osa1** [comment]
@daejunpark can we explain this behavior in `to-be-processed.txt`(where's that file?) and close this issue?

**Comment by daejunpark** [comment]
I've put this behavior in the following wiki page,
https://github.com/kframework/k/wiki/Manual-(to-be-processed):-KTest#ktest-exclude-attribute
and close this issue.

@osa1 
Previously the file was:
https://github.com/kframework/k/blob/master/documentation/to-be-processed.txt
but now it is:
https://github.com/kframework/k/wiki/Manual-(to-be-processed)
