### ISSUE TITLE
What is you don't want to use all the syntaxt and rules

### ISSUE THREAD

**Issue by sirinath** [kframework/k-legacy#234]
When you have alternative or language features that are not ready for use if might be helpful to be able to enable and disable features.

**Comment by dwightguth** [comment]
Closing. If you still want an answer, reopen and we will try to respond. I am really sorry we didn't do so before, but the project ops structure was in a very bad state and we are only now going through everything and trying to set up a system to make sure all questions are answered.

**Comment by dwightguth** [comment]
Closing. If you still want an answer, reopen and we will try to respond. I am really sorry we didn't do so before, but the project ops structure was in a very bad state and we are only now going through everything and trying to set up a system to make sure all questions are answered.
