### ISSUE TITLE
Type inferencer --- error message missing location information

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#235]
The following is the simplified failure-inducing input:

```
module TEST

  configuration
    <k> .K </k>
    <list> .List </list>
    <map> .Map </map>

  syntax KItem ::= (Int,BagItem)
  rule <list> . => (1, <map>.Map</map>) ...</list>
endmodule
```

The correct way to write the rule above is:
`rule <list> . => ListItem((1, <map>.Map</map>)) ...</list>`

However, the error message fails to give the correct location of the error source:

```
[Error] Critical: Wrong type in cell 'list'. Expected sort: List but found K
    File: File System
    Location: generated
    Compilation Phase:
org.kframework.parser.concrete.disambiguate.CellTypesFilter2
```

I ran into this problem when debugging kool-untyped for the Java backend, without correct location info of the error source, I had to trace the rule which caused the problem using IDE debugger.

Radu, I am assigning this issue to you. It is not urgent but it would be great to have it. Thank you.

**Comment by yilongli** [comment]
Well, I just figure out that this problem is not just about the type inferencer. Another example:

```
module TEST

  configuration
    <k> .K </k>

  rule <k> . => K </k>

endmodule
```

Warning message:

```
[Warning] Compiler: Unbounded Variable K:K .
    File: File System
    Location: generated
    Compilation Phase: class org.kframework.compile.checks.CheckVariables
```

@traiansf, can you also take a look at this? It seems that the location attribute has not been correctly passed to the variable inside a rule.

Thanks!

**Comment by radumereuta** [comment]
This appears to be fixed.
I think @andreistefanescu found the issue in a visitor which didn't copy correctly all the fields when creating a copy of the variables.
