### ISSUE TITLE
ktest --- option --update-out slows down test execution significantly

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#238]
It seems as if the updating operation is always executed even if that output is correct.

**Comment by daejunpark** [comment]
Yes, you're right. The option --update-out/--generate-out does not work in parallel. It executes each task sequentially in order.

I'll think about if it could be made in parallel without any problem.

**Comment by osa1** [comment]
@daejunpark Are you currently working on this? I think can help.

To do that I think we first make sure that no multiple output files will be generated in same file path. Once we checked for that I think solution is trivial(just don't set nThreads to 1 in `startTpe` method of `TestSuite`).

Or are there other reasons to set nThreads to 1 when `--update-out` or `--generate-out` is supplied?

**Comment by daejunpark** [comment]
@osa1 That assumption is the reason why I didn't it in parallel. I'm not sure if I can assume that, because I remembered that I've seen *.out files shared by multiple <test>'s, but I cannot remember which one is the case. I think you can freely work on this if you want. I'm sorry I'm hard to find time to work on this these days.

**Comment by osa1** [comment]
Okay, so in order to fix this issue I think we need to have a design decision about whether to assume this or not. Maybe I should send an e-mail for further discussion..

**Comment by daejunpark** [comment]
@yilongli 

It turned out that ktest is not able to run in parallel, until the structure of ktest is totally changed.

Please find the details of the `--update-out` option in the following:
https://github.com/kframework/k/issues/391#issuecomment-40861364
