### ISSUE TITLE
ktest: display what's going on, at least add a verbose mode

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#24]
It would be nice to see what's going on when ktest executes.  For example, to display a message each time a definition kompiles, or a PDF is generated, or programs are executed, etc.  If that is too much text, then we may consider adding a -verbose option to ktest.

**Comment by andreiarusoaie** [comment]
I have added -v (or --verbose) option which displays which definition/program finished compilation/running and timing information. In this way you can get a feel of what is happening behind ktest.
