### ISSUE TITLE
Strict subsort klabel (old issue 677)

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#240]
I've recently made a change where typed variables are no longer K, but the sort that has been declared. This improved performance of parsing rules, but revealed some problems.
Now, in some places the subsort is introduced, but in some other places is not.

One is related to an older issue from google code 677: https://code.google.com/p/k-framework/issues/detail?id=677

The other problem is in kool-typed-static. Because Id is subsorted to Type and Exp, and Type is subsorted to Exp, there are two ways of reaching an Id from an Exp. One of them has subsort with a klabel attached.

For now I've patched kool by forcing a ::K context. I don't know which is the best solution. We should discuss this.

The most simple solution would be to simulate the previous behavior, and remove the newly introduced subsorts.

**Comment by grosu** [comment]
I think this requires a serious discussion.  Let's meet some time today (wed feb 5), say at 1pm, those of you interested in this discussion.  I stick to my guns that we should have all injections added automatically everywhere, as I suggested in the past several times, but I was turned down.

**Comment by traiansf** [comment]
can you move this meeting to 2pm?  I might be interested in attending.

best wishes,
Traian

2014-02-05 Grigore Rosu notifications@github.com:

**Comment by grosu** [comment]
ok, let's do it at 2pm, then.

**Comment by dlucanu** [comment]
I am interested in attending it as well.
