### ISSUE TITLE
Fix command line parser for all tools

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#244]
Right now we are dependent on a command line parser that is not very good and is causing us all kinds of problems. We need to migrate off this parser and on to something else which allows us the correct functionality in all cases.

**Comment by andreiarusoaie** [comment]
I kind of agree with Dwight here, even if I was the one which proposed the thing we currently use. Any proposals?

**Comment by dwightguth** [comment]
Closing. Also fixed some time ago
