### ISSUE TITLE
ktest: -processors option

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#25]
To avoid exhausting the computing resources, it would be good for ktest to take an option saying how many parallel processes, or threads, or however is best to call them, we want it to execute in parallel.

**Comment by andreiarusoaie** [comment]
Done. Still, there is a problem with the subprocesses that kompile or krun create. If I set -threads 1 then there will be only 1 kompile of krun process at a time (created by ktest) but I cannot handle their subprocesses.

**Comment by grosu** [comment]
I guess that is OK, because kompile and krun do not have --processors options.

Have you also added info to --help about these, so that we remember what they are?

Thanks,

Grigore

**Comment by andreiarusoaie** [comment]
Yes, I added information in the help message.
