### ISSUE TITLE
Clean up duplicate unparser transformers

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#257]
I found in the code 3 different nearly identical unparser filters:

org.kframework.backend.unparser.UnparserFilter
org.kframework.backend.unparser.UnparserFilterNew
org.kframework.krun.gui.Controller.XmlUnparserFilter

I believe you are the owner of at least some of these classes. I need you to work to collapse all three into a single class which separates out the differences in functionality without duplicating any logic. The fact that we have three of these classes introduces the possibility of bugs if they are not all updated in sync. So we need to get rid of two of them. Preferably the most recent two.

**Comment by liyili2** [comment]
OK. I can take a look at them.

**Comment by dwightguth** [comment]
Another one I found:
org.kframework.backend.kore.KoreFilter
