### ISSUE TITLE
syntax KLabel ::= "'A" [strict(1)]

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#260]
[Error] Compiler: only productions of sort K, sort KLabel or of syntactic sorts can have strictness attributes

**Comment by radumereuta** [comment]
I think Traian knows more about this.

**Comment by traiansf** [comment]
This was implemented by Cansu & Pat.  Did anyone took over from them?

best wishes,
Traian

2014-03-03 18:48 GMT+02:00 Radu Mereuta notifications@github.com:

**Comment by grosu** [comment]
None of them works on K anymore, so we need somebody to take over.

Grigore
