### ISSUE TITLE
krun get stuck when an undeclared KLabel is used in a rule

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#262]
Please report a compile-time error in this case.

In the case below we get a maude error, but in some case in java semantics maude just get stuck indefinitely with CPU usage 0%.

issue.k:

module ISSUE
rule 'X(_) => 1
endmodule

issue.kast:

'X(.KList)

**Comment by traiansf** [comment]
But this used to work, and I think it should still work.

Weren't we collecting and declaring KLabel constants?
If not, and we don't want to support undeclared labels, then I guess we
should check all labels at compile time and error if undeclared ones are
used.

2014-03-03 21:55 GMT+02:00 Denis Bogdanas notifications@github.com:
