### ISSUE TITLE
Execute external command to check condition

### ISSUE THREAD

**Issue by timfel** [kframework/k-legacy#284]
We're trying to model a language where some rules have conditions that are checked by an external program that we want to treat as a black box. Is it possible to run a command in the `when` part of a rule (with the current configuration as input, in any format) and use the exit value of that command as condition?

**Comment by dwightguth** [comment]
Not currently, no. It is, however, possible to communicate with external
processes by means of reading and writing to files on disk. Consider the
following K fragment:

syntax Bool ::= pollExternalProgram(K, String) [function]
| writeAndPoll(K, Int) [function]

rule pollExternalProgram(K, Path) = writeAndPoll(K, #open(Path))
rule writeAndPoll(K, Fd:Int) => poll(Fd, #write(Fd, K2String(K)))
rule poll(Fd:Int, _) => checkResultOfRead(Fd, #read(Fd, 1))
rule checkResultOfRead(_, ReadResult:String) => ReadResult ==String 1
rule checkResultOfRead(Fd:Int, #EOF) => poll(Fd, .)

Not ideal for what you are looking for, but it should get the job done.
Note I haven't tested this code, it may have bugs. But it should capture
the general idea of what you need to do. Although it might not be very
efficient, given that it is polling. We at one point talked about the
possibility of having an invocation mechanism for communicating with
parallel processes, but that has not been implemented yet.

**Comment by timfel** [comment]
That works, thank you! Although I ended up writing my own serialization (inspired by the one in smt.k), because the K2String output was very noisy. And I'm using the parsing method from uri.k to read results into the program.
