### ISSUE TITLE
Rename releases to "k-stable" and "k-nightly"

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#29]
Can we change the naming of the binary releases to k-stable.zip and k-nightly.zip, as discussed?  The name k-latest-stable.zip is rather confusing.

**Comment by traiansf** [comment]
I've modified jenkins to generate k-nightly and k-stable, respectively.

Philip, Could you please update the synchronization and download scripts from k-framework.org to reflect that?

Also, could somebody at iasi (Dan?) update the links on the fmse K download page?

**Comment by bmmoore** [comment]
It seems this has all been done.
