### ISSUE TITLE
Refactor import system in Ktest

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#296]
I spent like half an hour today trying to figure out how the hell to make a single test suite in the ktest test suite break out into its own file. Eventually what I found out is that ktest does all kinds of crazy strange logic in order to try to figure out where files are relative to the paths you specify, and it doesn't really work at all in any kind of intuitive way.

So I suggest that the import system be modified according to the following design principles (which I am willing to discuss if you disagree):
- A ktest xml file should contain all the information needed to execute the tests it contians. No matter what working directory I am in, I should always be able to successfully run the xml file by running `ktest some/path/to/file.xml`
- All parameters except the path to the xml file should be optional in an include statement. If I specify parameters, it should /override/ the value specified in the xml file, not modify it according to a relative path.
- Parameters should override in the following way:
  *\* If I override the "directory" flag, I modify the base path around which all relative paths in the xml file are specified.
  *\* If I override the "file" flag, I overwrite the relative or absolute path of the k definition, relative to the resolved directory.
  *\* If I override the "programs" or "results" flags, I overwrite the relative or absolute path of the folder containing programs/outputs, relative to the resolved directory.

Does this seem like a reasonable refactoring? It should make it very easy to modularize ktest files instead of the more complex system we have now where it's very hard to determine where the paths are coming from and what values need to be specified where in order to make the xml pass validation.

**Comment by radumereuta** [comment]
I had some issues myself at one point with paths in ktest config files, so I think something definitely has to be changed/fixed.

**Comment by grosu** [comment]
Dwight,

The current design of paths in ktest is the process of a long, long series of discussions, motivated by its use in the tutorial.  Just look at how it works to test the tutorial.  It is quite complex, actually.  Daejun should have written down the details of how it works in our manual-to-be.  Why don't you take a look at these and then let's have this discussion again.  If you come up with a better design then fine, we can take it, but only if we don't lose anything we have now and we don't have to write more info in the config files.  The current design is quite modular in what regards the import of the config files (don't know about the implementation).

Grigore

**Comment by dwightguth** [comment]
I understand what you're trying to do which is to have a modular xml system where you can include xml files in one another. The problem is that the implementation is incredibly complex and requires extremely specific insider knowledge in order to understand how the paths you specify in the xml file actually resolve into the directories you are trying to specify.

Some examples:
1. While the "directory" attribute on an include element is a path relative to the path passed on the command line, the "file" attribute is a path relative to the directory the xml file is contained in.
2. In order to include one xml file in another, it is necessary to specify the path for the directories in question three times. Once on the command line, once in the outer xml file, and once in the inner xml file.
3. If you do not specify a relative path for any of the attributes, it is made relative to the location of the xml file rather than the working directory of the process.

Thus I propose the following specific changes:
1. All relative paths in an xml file are relative to one "master" directory which can be either specified on the command line, or corresponds to the working directory of the process.
2. An include element contains only one parameter, the new path to the "master" directory to execute the included xml under.

This would replace the following:

```
$ cat tests/config.xml
<tests>
  <include file="../some/directory/tests/config.xml" directory="some/directory" programs="some/directory/programs" results="some/directory/tests" />
</tests>
$ cat some/directory/tests/config.xml
<tests>
  <test definition="def.k" programs="." results="." extension="def" />
</tests>
$ ktest tests/config.xml --programs . --results .
$ cd some/directory
$ ktest tests/config.xml --programs "some/directory/programs" --results "some/directory/tests"
```

with:

```
$ cat tests/config.xml
<tests>
  <include file="some/directory/tests/config.xml" directory="some/directory" />
</tests>
$ cat some/directory/tests/config.xml
<tests>
  <test definition="def.k" programs="programs" results="tests" extension="def" />
</tests>
$ ktest tests/config.xml
$ cd some/directory
$ ktest tests/config.xml
```

Do you see how this is an improvement?

**Comment by grosu** [comment]
Dwight,

You think to low of us if you think we have not thought about that.  Actually, that was the very first solution we tried.  But we really had to separate the various folders and have different policies for them, in order to make the tool modular.  The current design was reached after a long series of design changes in the tool.

I don't know what else to tell you than to go through all the config.xml files that we have both in the tutorial and in the private repository k-exercises, to see all the instances that we had to fight with.  Sometimes a language needs to run all the tests of another language; for example, when you extend  language with some features and you want to run both the new tests and the old tests.  See, for example, the k-exercises, because they are almost all language extensions.

Then, if you are still not convinced, we will discuss it when we meet.

Grigore

**Comment by dwightguth** [comment]
Okay, well, Grigore, the problem is that the more I look at how the system works right now the more I don't understand it at all. Consider for example lambda lesson 2 in the tutorial. The config file contains two paths. One is relative to the directory the xml is currently in, and one is relative to some kind of path associated with the definition being tested. But if you go and look at the file being included, you find that this contains more relative paths. Seemingly the relative paths are both relative to the same directory, because otherwise how could lesson_2's xml find lesson_1's lambda.k. But if that's the case then why specify that the results are in "." twice? So in reality we have three different directories that relative paths are deriving from. Except that I don't even know what some of those relative paths are because it doesn't explain to me why in tests/config.xml we have to specify both directory, programs, /and/ results, or it doesn't work. But in the tutorial we don't do that. Which makes seemingly four different behaviors, one of which I don't understand at all.

Furthermore, the examples you direct me to worry me somewhat. Consider the case of lambda lesson 8's exercises in the k-exercises directory. These xml files are not modular at all! They actually specify a relative path with seven levels of ".." even though in fact the repository is only 6 levels deep. So they won't work at all unless you have also checked out the other repository and put it in the same directory as the k-exercises repository.

I suggest we discuss this at the K meeting. I have no problem with trying to achieve something like what you desire, but I feel like you are overstating the degree to which the current implementation actually accomplishes these objectives without making the tool almost impossible to use.
