### ISSUE TITLE
Map does not handle strings properly

### ISSUE THREAD

**Issue by azulehner** [kframework/k-legacy#297]
I created the following simple language with strings as keys for my storage map:

```
module IMP-SYNTAX
    syntax Exp ::= Int | Exp "+" Exp [strict, left]
    syntax Stmt ::= Id "=" Exp ";" [strict(2)]
            | Stmt Stmt [left]
endmodule

module IMP
    imports IMP-SYNTAX

    syntax KResult ::= Int

    configuration
        <T>
            <k>$PGM:Stmt</k>
            <store>.Map</store>
        </T>

    //Stmt
    rule S1:Stmt S2:Stmt => S1 ~> S2

    rule <k>I:Id = X:Int ; => . ...</k>
        <store>M:Map (. => Id2String(I) |-> X )</store>
        requires notBool (Id2String(I) in keys(M))

    rule <k>I:Id = X:Int ; => . ...</k>
        <store>... Id2String(I) |-> ( _ => X) ...</store>

    //Exp
    rule I1:Int + I2:Int => I1 +Int I2

endmodule
```

When I  run krun on the following input file, the computation gets stuck after the first line.

```
x = 2+3+4;
x = 2;
```

The problem is, that the strings are not handled properly in the map. (Id2String(I) in keys(M)) yields true, but the key is not found in the rule:

```
rule <k>I:Id = X:Int ; => . ...</k>
        <store>... Id2String(I) |-> ( _ => X) ...</store>
```

There is a workaround for my problem, but I think it is a bug because the key should be found in the map if it is in keys(M). I have to change the rule to the following and the computation finishes.

```
    rule <k>I:Id = X:Int ; => . ...</k>
        <store>... Y |-> ( _ => X) ...</store>
        requires Id2String(I) ==String Y
```

**Comment by traiansf** [comment]
In this line:

> ```
> rule <k>I:Id = X:Int ; => . ...</k>
>     <store>... Id2String(I) |-> ( _ => X) ...</store>
> ```
> 
> you attempt to match on Id2String(I).  This is not supported, i.e.,
> functions are not computed before/during the matching process.

Side question: why using strings in the map? why don't you map directly Ids
to values?

**Comment by dwightguth** [comment]
Closing. please reopen if you have further questions.
