### ISSUE TITLE
[function] attribute for KLabels does not work

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#298]
The following 

```
module TRY
  syntax KLabel ::= "cxt"
  syntax KItem ::= foo(K)  [function]
  syntax KLabel ::= "baz"  [function]
  rule foo(I) => 0
  rule baz(I) => 0

  configuration <k> cxt(foo(3),, baz(3)) </k>
endmodule
```

should reduce to `cxt(0,,0)`.  However, it reduces to `cxt(0,, baz(3))`, showing that the `[function]` attribute for KLabel `baz` does not work.

**Comment by dwightguth** [comment]
Grigore, the problem here is there is an ambiguity in the semantics. Is baz
a klabel that represents a function, or is it a function of arity zero that
returns a klabel? We can discuss finding a way to bridge this problem, but
the syntax as it exists now is not able to support what you're trying to do
here.

**Comment by grosu** [comment]
Well, it is the former.  We do know that some KLabels are going to be functions, so we expect to just put the attribute `[function]` to those in KORE.  This ambiguity should be reported an error, if that is indeed the problem, but in my view the fact that we have this ambiguity is a problem with our current design of KORE.

**Comment by dwightguth** [comment]
I was given to understand KORE had concrete syntax declarations though...
so if you had a function baz(Int) you would say

syntax Int ::= baz(Int) [function]

and it would create the baz klabel without adding the corresponding
concrete syntax. This way there is no ambiguity and we don't unnecessarily
preprocess definitions before outputting KORE.

**Comment by grosu** [comment]
No, KORE does not any any concrete syntax.

The problem is that

```
syntax KLabel ::= "baz"  [function]
```

is currently correct in KORE, and as you said it is ambiguous.  We do not want to allow such ambiguities in KORE.  Which is why I believe that we should not allow functions producing KLabels at all in KORE, so the above is interpreted as the KLabel `baz` which is expected to be a function (i.e., its rules apply everywhere, etc.).

Grigore

**Comment by dwightguth** [comment]
Okay we need to have a larger discussion about the design of KORE again
then because I know myself, Brandon, and possibly also Andrei definitely
want the KORE of a definition to be identical to full K except that you use
abstract syntax in sentences to make it possible to parse in linear time.

**Comment by traiansf** [comment]
I kind of agree with Dwight here.  We should have an intermediate language
which is easy to parse, yet requires little to none compilation to achieve.

2014-03-21 18:26 GMT+02:00 dwightguth notifications@github.com:

**Comment by grosu** [comment]
But that's exactly the problem, that our current KORE is a big mess, patched at various moments in time without a clean design.  I don't think we want to separate the KORE language from the 'easy to parse' variant of full K, because as soon as you can write anything down using any syntax, somebody will want to write a patters over that syntax and match it.  Having three different variants of K is even worse than having a bad KORE.

Grigore

Sent from phone

-------- Original message --------
From: traiansf
Date:03/21/2014 13:10 (GMT-06:00)
To: kframework/k
Cc: "Rosu, Grigore"
Subject: Re: [k] [function] attribute for KLabels does not work (#298)

I kind of agree with Dwight here. We should have an intermediate language
which is easy to parse, yet requires little to none compilation to achieve.

2014-03-21 18:26 GMT+02:00 dwightguth notifications@github.com:

**Comment by dwightguth** [comment]
Well yes, Grigore, I agree that we want only one KORE language which is
easy to parse. But I think we're making a very serious mistake if we try to
perform postprocessing following the parsing process in order to generate a
"KORE" document. The whole point of KORE was to separate parsing from
everything else. If we put some of that everything else inside KORE, then
we haven't really separated the parser.

**Comment by andreistefanescu** [comment]
We need to keep the concrete syntax in KORE, otherwise we cannot access the
sort information and we cannot concretize syntax. And I know that we can
encode the sort information, but I think that is a bad idea, in the sense
that some backends (like the java backend or probably the coq backend)
would have to use these predicates to reconstruct the sort information.
KORE should be simple, but we should not try to make it minimal just for
the sake of minimality.

Andrei

**Comment by grosu** [comment]
I think we have been in agreement for a long time that we need to keep the concrete syntax declarations in KORE.  It surprises me that you say that.  Maybe you meant something else?

Regarding sorts, yes, they should also be there.  In fact, I always strongly supported that there should be a bijective correspondence between KLabels and the productions they come from.  That is, the concrete syntax declarations

```
syntax Exp ::= Exp "+" Exp | Val
syntax Exps ::= List{Exp}{","}{.Exps}
syntax Vals ::= List{Vals}{","}{.Vals}
```

should be completely equivalent, in terms of syntax, to

```
syntax KLabel ::= '_+_:Exp*Exp->Exp | 'Val2Exp:Val->Exp
syntax KLabel ::= 'Exp2Exps:Exp->Exps | '_,_:Exps*Exps->Exps
syntax KLabel ::= 'Val2Vals:Val->Vals | '_,_:Vals*Vals->Vals
```

Semantically, we may add some structural rules of the form

```
rule '_,_:Exps*Exps->Exps(Vs1:Vals,Vs2:Vals) => '_,_:Vals*Vals->Vals(Vs1:Vals,Vs2:Vals)
etc
```

but now we are getting into a different territory.

Andrei, your final conclusion has nothing to do with your arguments prior to it.  I mean, I am in agreement with your arguments (and have been for a very long time), but I am in strong disagreement with the fact that I'm trying to make KORE minimal for the sake of minimality.  We need it to be very simple, easy to explain and process.  The more syntactic categories you have in it, the more things you need to worry about when you or others write visitors, when you convert to different backends, when you pretty-print, when you develop essentially any tool for K.

Grigore

**Comment by andreistefanescu** [comment]
I got confused by this discussion thread. I thought you changed your mind,
and wanted to drop the syntax declarations from KORE, hence my arguments.
If that is not the case (or we go to some equivalent form which preserves
the sort information), then I am happy :)

Andrei

**Comment by grosu** [comment]
We are in agreement then.  You guys brought very solid arguments long ago why we want to keep the concrete syntax declarations in KORE, and I accepted them.

Grigore

**Comment by dwightguth** [comment]
I was confused also on the same point. But I want to make a very important
note here which is that if you want to keep syntax declarations in KORE
then you /can't/ treat a KLabel declaration and the declaration of its
concrete syntax as identical. The [function] attribute is the perfect
example of this. As I said before:

syntax KLabel ::= "foo" [function]

is a function of arity zero that returns a KLabel.

syntax Exp ::= foo(Exp, Exp) [function]

is a function of arity 2 that returns an Exp.

We need a new type of syntax declaration to break this ambiguity.

On Fri, Mar 21, 2014 at 2:15 PM, Andrei Stefanescu <notifications@github.com

**Comment by grosu** [comment]
Ok, then it is good that we clarified that.

> We need a new type of syntax declaration to break this ambiguity.

Not if we disallow such atrocities as functions returning lables, which is what I'm proposing in fact.

Grigore

**Comment by dwightguth** [comment]
Okay but if you don't allow functions returning labels, how do you do
higher order functions? Do you have another proposal for how to make a
function return a function?

**Comment by grosu** [comment]
Dwight, I think I addressed this, but here is my perspective, again.

I believe that by adding some simple framework-builtin-and-fixed operations like

syntax KToken ::= #toKToken(KLabel)
syntax KLabel ::= #toKLabel(KToken)

that allow us to go back and forth between the only two elements that users can define, allows us to maintain
the simple KORE syntax

syntax KItem ::= KLabel(KList)
syntax KList ::= List{K}{","}{".KList"}
syntax K ::= List{KItem}{"~>"}{.K}

without requiring our meta-level users resort on dirty tricks.  Also, in terms of backends, each backend will have to have efficient implementations of KTokens and KLabels anyway, and they both contains names inside, so they will find a way to go back and forth efficiently.

So the point is that there will be no postprocessing; people will simply have to use the syntax above in their non-syntactic definitions.  In fact, with good parsing, we hope that very few expert people will need to see the sorts above in their definitions.

Grigore
