### ISSUE TITLE
null reference example on the "Code Quality Principles" page

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#319]
I was reading through the wiki pages and, on the Code Quality Principles page, found a _positive_ example using a null reference for encoding "the entire string". Yes, the example was trying to illustrate a different principle. But do we really want to teach first-time k developers, some of them maybe younger programmers, that it is ok to use null to encode a meaningful non-exceptional state?

In case it is needed, for reference:
http://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare

Also, I don't know exactly how gospel these pages are. Should I feel free to edit when I encounter something like this?

**Comment by dwightguth** [comment]
If you have a better example, send it to me and I'll update the wiki.

**Comment by cos** [comment]
I don't think we should replace the example. I think we should simply apply the "less is more" principle and get rid of anything that is presented much better in other sources. I don't think the "Foo null" example will enlighten somebody who doesn't know what code modularity is. I'm not even sure this is about code modularity, but anyhow. My proposal is to replace any text which is not of higher quality than what is available in other sources with references. A quick fix for this is to point to the wikipedia pages for DRY and modularity:
http://en.wikipedia.org/wiki/Modular_programming
http://en.wikipedia.org/wiki/Don't_repeat_yourself

Maybe the wiki could also use a bit of DRYing up.

**Comment by dwightguth** [comment]
I don't really have the time right now to be able to do detailed work
revising the wiki. I suggest you draft some proposed revisions, put them
here, and we can discuss them as a group. What you propose sounds like an
okay replacement for what we have here as long as you give a brief 1-2
sentence summary of the article's contents along with the link.

**Comment by cos** [comment]
> You should keep your code [modular](http://en.wikipedia.org/wiki/Modular_programming) and [DRY](http://en.wikipedia.org/wiki/Don't_repeat_yourself).

**Comment by dwightguth** [comment]
again, that's all well and fine, but I think at least a brief definition of
those terms is needed, because otherwise you have nothing to point to if
people don't follow the links. And people love to not follow links.

**Comment by cos** [comment]
I can handle it at some point also if you like.

**Comment by dwightguth** [comment]
Go ahead and write up a draft somewhere for me to take a look at, and post the link in this ticket. If it looks good, I will update the page.

**Comment by cos** [comment]
updated the page with a note on the use of the null value. Didn't change the example as it would make it harder to comprehend -- the reader would have to understand both the issue at hand, and the `Optional` construct.
