### ISSUE TITLE
ktest: warn on ineffective exclude

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#32]
Trying to exclude the test fixed by
120a52816b930d35b6b9279aa078628b578f9d80
I made a change

```
 <test definition="tests/regression/java-rewrite-engine/io/test2/test.k"
       extensions="test"
       programs="tests/regression/java-rewrite-engine/io/test2/programs"
+      exclude="tests/regression/java-rewrite-engine/io/test2/programs/readInt.test"
       results="tests/regression/java-rewrite-engine/io/test2/tests">
   <kompile-option name="-ml" />
   <all-programs>
```

which should have just set exclude="readInt.test". It would be nice if there was a warning for excludes that list a single program which doesn't actually exist.

**Comment by andreiarusoaie** [comment]
@daejunpark or @osa1  can you guys take a look at this? I think (I'm not sure) that Omer does all these kind of checks right now in ktest. If so, please feel free to close the issue.

**Comment by osa1** [comment]
`exclude` parameter is actually a pattern that is searched in full file path and not a program name/path. I'm closing this issue, please open again if something is misunderstood by me.
