### ISSUE TITLE
kompile layers clearly separated

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#328]
We want the kompiler's layers very clearly separated, where GeneriK and KORE parsing/generation are themselves layers.  The layers have individual names, and those are public and users can refer to them through command line options.  That is:
1) Each printed error should contain the layer that produced it.  No exception, please.  So we should go through all the error reports and make sure the layer producing them is always there.
2) If a definition passes a certain kompilation layer, then a user option should allow to pretty-print the definition after that layer has just been passed.  Again, this includes the GeneriK and KORE parsing/generation.
Both of these should be very easy to achieve with what we already have implemented, but we want to make sure they really work well and that the user interface is crystal clear.

I assigned Liyi to this task because he is working on the pretty-printer anyway, but I think help will be needed from Michael and Radu to make sure this all applies for the parsing stages, too.

**Comment by liyili2** [comment]
ok.
