### ISSUE TITLE
Pretty printer doesn't handle subsorting correctly

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#334]
dwightguth@rvwork-1:~/test$ cat test.k
module TEST

syntax A ::= "(" A ")" [bracket]
           | B

syntax B ::= A "/" A
           | A "+" A
           | Int

endmodule
dwightguth@rvwork-1:~/test$ krun --parser "kast -e" --term "(1 + 2) / 3"
1 + 2 / 3

This should add parentheses because they're needed, but it doesn't because the bracket is of sort A which is not the same exact sort as B.

**Comment by liyili2** [comment]
Does it handle subsort in the past? If it does not, I am not sure if it is
a good idea to handle it now.

**Comment by dwightguth** [comment]
Sorry, I was maybe a little bit unclear. This is actually a bug, because the code right now is functionally incorrect. Depending on how you define your production, the unparser may or may not actually be sound. For instance, the example I just gave above demonstrates its unsoundness by showing that it fails to add brackets where the language both allows and needs them. This is because your code did not correctly handle the case where the term being wrapped in parentheses was a subsort of the sort the bracket was declared as.

**Comment by dwightguth** [comment]
This is blocked on #333 by the way so don't start it yet.

**Comment by liyili2** [comment]
Does the krun parser use the UnparserFilterNew? I do not think so.

**Comment by dwightguth** [comment]
See my comment on the pull request for more context, but to address this
issue specifically:

The whole point of the unparser that you were supposed to write was that it
was supposed to add parentheses everywhere the syntax for programs allows
and nowhere else. That would, if implemented correctly, guarantee that
program fragments output by krun would be copyable by scripts into source
files and compilable without further modification.

My example shows that this is not being done. It shows a program that
parses unambiguously due to a bracket, but the code incorrectly believes
that no bracket can exist there because the sort of the expression is B,
not A. But B subsorts A, which means a B can appear anywhere an A appears,
causing your algorithm to be incorrect.

Your task is to find a way to modify CollectBracketsVisitor to precompute
whatever information is needed to be able to efficiently check at runtime
whether a bracket can be used, taking into consideration the complete sort
lattice of the definition. If you need to understand better how subsorting
works, I suggest you schedule time with Grigore, he can likely explain it
better than I can.

**Comment by liyili2** [comment]
My point is like I think we should get rid of unparserFilter and all other way of printer out final result first. Then considering changing if the pretty printer is right. I mean I am sure that there is some button in Krun which does not use my printer at all. And I do not even know what is CollectBracketsVisitor?
