### ISSUE TITLE
Cooling rule not applied in java semantics

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#35]
Execution of helloworld.java hangs with the following content at the beginning of <k>:

'packageId`(_`)(#token("#Id", "")(.KList)) 
~> #freezer 'CompilationUnit('Some('PackageDec(.K,,HOLE)),,'ListWrap(.KList),,'ListWrap('ClassDec('ClassDecHead('ListWrap('Public(.KList)),,#token("#Id", "helloWorld")(.KList),,'None(.KList),,'None(.KList),,'None(.KList)),,'ClassBody('ListWrap('MethodDec('MethodDecHead('ListWrap('Public(.KList),,'Static(.KList)),,'None(.KList),,'void(.KList),,#token("#Id", "main")(.KList),,'ListWrap('Param('ListWrap(.KList),,'ArrayType('ClassOrInterfaceType('TypeName(#token("#Id", "String")(.KList)),,'None(.KList))),,#token("#Id", "args")(.KList))),,'None(.KList)),,'Block('ListWrap('ExprStm('Invoke('MethodName('AmbName('AmbName(#token("#Id", "System")(.KList)),,#token("#Id", "out")(.KList)),,#token("#Id", "println")(.KList)),,'ListWrap('Lit('String('ListWrap('Chars(# "Hello World!"(.KList)))))))),,'ExprStm('Invoke('MethodName('AmbName('AmbName(#token("#Id", "System")(.KList)),,#token("#Id", "out")(.KList)),,#token("#Id", "println")(.KList)),,'ListWrap('Lit('String('ListWrap('Chars(# "Done!"(.KList))))))))))))))))(.KList) ~> ...

Since packageId(...) is KResult (see core.k), it should be cooled at this step.

K version: 3.2.1-108. Worked fine with 3.2.1-63.

**Comment by denis-bogdanas** [comment]
P.S. See java-semantics/INSTALL.md for installation/execution instructions.

**Comment by radumereuta** [comment]
#Id is no longer part of the standard library. If you have tokens, you should use Id instead of #Id. Please give it a try. We had several issues like this one today. Even the Python semantics fails because of this change.

**Comment by denis-bogdanas** [comment]
Semantics don't use any #Id. What you see above is the result of krun output-mode=raw.

**Comment by ciobaca** [comment]
Here's what you wrote:

'packageId(_)(#token("#Id", "")(.KList)) ~> #freezer
'CompilationUnit('Some('PackageDec(.K,,HOLE)),,'ListWrap(.KList),,'ListWrap('ClassDec('ClassDecHead('ListWrap('Public(.KList)),,#token("#Id",
"helloWorld")(.KList),,'None(.KList),,'None(.KList),,'None(.KList)),,'ClassBody('ListWrap('MethodDec('MethodDecHead('ListWrap('Public(.KList),,'Static(.KList)),,'None(.KList),,'void(.KList),,#token("#Id",
"main")(.KList),,'ListWrap('Param('ListWrap(.KList),,'ArrayType('ClassOrInterfaceType('TypeName(#token("#Id",
"String")(.KList)),,'None(.KList))),,#token("#Id",
"args")(.KList))),,'None(.KList)),,'Block('ListWrap('ExprStm('Invoke('MethodName('AmbName('AmbName(#token("#Id",
"System")(.KList)),,#token("#Id", "out")(.KList)),,#token("#Id",
"println")(.KList)),,'ListWrap('Lit('String('ListWrap('Chars(# "Hello
World!"(.KList)))))))),,'ExprStm('Invoke('MethodName('AmbName('AmbName(#token("#Id",
"System")(.KList)),,#token("#Id", "out")(.KList)),,#token("#Id",
"println")(.KList)),,'ListWrap('Lit('String('ListWrap('Chars(# "Done!
"(.KList ))))))))))))))))(.KList) ~> ...
I see an #Id there.

If you don't manage to fix the problem yourself, you could help someone
else by reducing your example to a workable definition.

Cheers,
Stefan

**Comment by denis-bogdanas** [comment]
Please see te minimal example in the related email thread. Cannot attach it here due to github limitations.

**Comment by grosu** [comment]
Denis, the idea was to add the k/tests/issues folder, in the k tool git repository.  Since you are a developer, you have access to that.  Obviously, our K users are not asked to do that, but you are more than a normal user, you are part of the K team.  So the idea is to add an test under issues, and then submit the issue compaining about the problem.  The philosophy of this approach is that if you do not bother to write a test, then probably  you are not thay interested in getting your bug fixed.  So other bugs with tests added under issues will be given priority.

**Comment by denis-bogdanas** [comment]
Particular case of issue 36. Closing.
