### ISSUE TITLE
Unify the pdmc and newparser algorithms of SCC Tarjan

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#359]
At the moment there are two implementations in:
branch: newparser 
org.kframework.parser.concrete2.SCCTarjan
branch: pdmc2
org.kframework.backend.pdmc.pda.graph.TarjanSCC<Data, Label>

Since the one used by the parser still has some issues, it would be nice to implement the best features of both.
Note that the parser requires the order of the SCCs so it should return a list of sets.

**Comment by dwightguth** [comment]
Closing since this is now Traian's module
