### ISSUE TITLE
Cooling rule is not applied when KResult is of type foo(Id)

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#36]
Example:

module TEST-CONTEXT-WITH-LABEL
syntax KLabel ::= "'L" | "'A"
syntax KResult ::= "res" "(" Id ")"
context 'L(HOLE)
rule 'A(_) => res(String2Id("X"))
endmodule

program:
'L('A(.KList))

Expected:
'L(res)

Actual:
res ( X ) ~> 'L(HOLE)

K version: 3.2.1-141. Also 3.2.1-128.
See the directory in k/issues.

**Comment by andreiarusoaie** [comment]
Maybe is because of  String2Id("X") ?
The rule for String2Id:   rule String2Id(S:String) => #parseToken("#Id", S)

Andrei

**Comment by andreiarusoaie** [comment]
Err... I closed the issue by mistake.

**Comment by radumereuta** [comment]
Andrei, you were right. I've commited the change and moved the test to the regression folder.
