### ISSUE TITLE
strange symbols in Windows displaying

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#368]
What are the symbols appearing before and after SUCCESS below?  Probably
colors.  Note that colors work just fine with krun (the displayed configurations
have colors in them), so we should do the exact same thing in ktest:

```
←[32mSUCCESS←[0m
----------------------------
Definitions kompiled: 1 (time: 0'30'' elapsed, 0'30'' CPU)
PDF posters kompiled: 1 (time: 0'35'' elapsed, 0'35'' CPU)
Programs krun: 3 (time: 0'7'' elapsed, 0'20'' CPU)
Total time: 1'12'' elapsed, 1'25'' CPU
----------------------------
```

**Comment by grosu** [comment]
Similarly funny symbols for colors when FAIL is reported:

```
←[31mERROR: [D:\github.grosu\k\bin\krun.bat D:\github.grosu\k\tutorial\1_k\4_i
++\lesson_7\tests\spawn.imp --search] output doesn't match with expected outpu
(time: 6159 ms)←[0m
←[31mFAIL←[0m

←[31mFAIL (see details above)←[0m
----------------------------
Definitions kompiled: 1 (time: 0'8'' elapsed, 0'8'' CPU)
PDF posters kompiled: 0 (time: 0'0'' elapsed, 0'0'' CPU)
Programs krun: 4 (time: 0'8'' elapsed, 0'29'' CPU)
Total time: 0'16'' elapsed, 0'37'' CPU
----------------------------
```

**Comment by dwightguth** [comment]
Looks like we need to detect whether the terminal supports ANSI color codes.

**Comment by osa1** [comment]
Some parts of the framework uses `jansi` library for colorful printing and that library handles this cases(e.g. if terminal does not support colors, it doesn't print useless escape codes. I think it may even convert color codes for different terminals?). Maybe we can use `jansi` in ktest too. (I don't know why we didn't use it in the first place)

EDIT: I just read Grigore's first message and yeah, apparently jansi even converts color codes for terminal's expected ones.

**Comment by osa1** [comment]
I just checked and places that `jansi` is used:

```
➜  k git:(master) ack --java AnsiConsole
src/javasources/KTool/src/org/kframework/krun/Main.java
32:import org.fusesource.jansi.AnsiConsole;
516:                    AnsiConsole.out.println(output);
525:                    AnsiConsole.out
622:                    AnsiConsole.out.println(debugger.printState(debugger
683:                            AnsiConsole.out.println(debugger
704:                            AnsiConsole.out.println(debugger
725:                            AnsiConsole.out.println(states);
742:                            AnsiConsole.out.println(debugger
761:                            AnsiConsole.out.println(debugger
777:                            AnsiConsole.out.println(debugger.printEdge(state1,
807:                            AnsiConsole.out.println(

src/javasources/KTool/src/org/kframework/backend/java/ksimulation/Waitor.java
8:import org.fusesource.jansi.AnsiConsole;
99:                AnsiConsole.out
118:                    AnsiConsole.out

src/javasources/KTool/src/org/kframework/backend/java/ksimulation/Adjuster.java
27:import org.fusesource.jansi.AnsiConsole;

src/javasources/KTool/src/org/kframework/kil/TermCons.java
6:import org.fusesource.jansi.AnsiConsole;
```

Imports in Adjuster and TermCons are useless because imported classes are never used. (I just removed them in my local copy and it worked).

I guess `AnsiTerm` calls in `krun.Main` are used for colorful cell name printing.

**Comment by osa1** [comment]
(off-topic: what is `Waitor`? isn't that supposed to be `Waiter` instead? (in `org.kframework.backend.java.ksimulation`)

**Comment by grosu** [comment]
Note that `krun` works just fine with colors, so we should just use the same thing in ktest for displaying colors.

@denis-bogdanas please get involved into this as well, because you also contributed to having nice colors in krun.  Thanks.

**Comment by osa1** [comment]
@grosu I used same library that is used in krun in my pull request #379

**Comment by osa1** [comment]
@grosu This should also be fixed on current master.

@dwightguth can you rebase `unified-builtins2` again for this patch, so that Grigore can try and close this issue?

**Comment by dwightguth** [comment]
Yeah, I accidentally messed up the merge again, so I am fixing that, but I
will clean everything up and make it nice.

On Tue, Apr 15, 2014 at 8:49 AM, Ömer Sinan Ağacan <notifications@github.com

**Comment by dwightguth** [comment]
Okay this should be taken care of.
