### ISSUE TITLE
poor error message when missing sort

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#372]
Error reported when mistyped S2Stmt instead of S2:Stmt

```
D:\github.grosu\k\tutorial\1_k\4_imp++\lesson_3>kompile imp.k
[Error] Compiler: Unbounded Variable S2:K .
        File: File System
        Location: generated
        Compilation Phase: class org.kframework.compile.checks.CheckVariables
```

Please add correct file and line numbers.

**Comment by radumereuta** [comment]
This will be extremely easy to fix with precede restrictions which will be available in the new parser.

**Comment by radumereuta** [comment]
The location information is fixed. @andreistefanescu found a bug in a visitor which didn't copy the location information when creating new variables.
I will leave this opened for now since it is still useful for the new parser.
