### ISSUE TITLE
poor error message when using . instead of .List in RHS

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#374]
Error when wrote . instead of .List in RHS of rule; very bad error, because it does
not even mention the location.

```
[Warning] Compiler: Expecting an empty list but got class
org.kframework.kil.KSequence of sort K.
Won't transform.
        File: File System
        Location: generated
        Compilation Phase: Resolve Blocking Input
```

**Comment by traiansf** [comment]
I guess the problem here is that we deliberately deprecated the Empty class
to use empty collections instead.  This was thought to be a good idea in
general, but it makes it harder to track location information during
compilation.

2014-04-14 11:31 GMT+03:00 Grigore Rosu notifications@github.com:
