### ISSUE TITLE
--search does not work with unified-buildings2

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#376]
No idea why the following does not work:

```
D:\github.grosu\k\tutorial\1_k\4_imp++\lesson_6>krun ..\lesson_1\tests\spawn.imp --search
Search results:
No search results
```

**Comment by traiansf** [comment]
I'm copying this over from the pull request #371 

> I might have identified the issue, but I'm not sure if I'm the most
> qualified to fix it.
> 
> There was a mechanism to disable i/o when doing search (setting a barrier
> in the stream cells). which apparently does not work anymore, and thus
> Maude attempts to send output through the socket.  Does anybody remember
> messing with this recently?

**Comment by dwightguth** [comment]
I investigated this and it turns out that the bug is in the transformer that converts from KApps to ListBuiltins. I am assigning this to Andrei S with a minimal example that can reproduce the bug:

```
module TEST

rule .List ((ListItem(6) V:List) ListItem(6)) => .List

endmodule
```
