### ISSUE TITLE
Allow ktest users to specify a phase topology

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#392]
One of the examples that came out of #369 was to run krun, and then run kast or krun on the output of running krun. Our test framework does not currently support this, or indeed any more complex workflows than:
1. kompile all definitions
2. run all programs for each definition one at a time.

It would be good to be able to have some kind of generalization of the phase mechanism which would allow you to specify building blocks like "kompile a definition", "test this program", "test all programs matching <blah>" etc and compose them together into larger test cases.

I am creating this issue to track the possibility of adding this feature. Note that once we have something that does this it will be necessary to delete the test created in #388 and replace it with a phase descriptor.

**Comment by daejunpark** [comment]
This issue will be further discussed the wiki page of ktest design:
https://github.com/kframework/k/wiki/KTest-Design
