### ISSUE TITLE
'krun --help' throws exception 

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#407]
$ krun --help
usage: krun [options] <file>

 -h,--help                          Print this help message.
    --version                       Print version information.
 -v,--verbose                       Verbose output.
 -d,--directory <dir>               Path to the directory in which the kompiled
                                    K definition resides. The default is the
                                    current directory.
    --main-module <name>            Specify main module in which a program
                                    starts to execute. The default is the
                                    module specified in the given compiled K
                                    definition.
    --syntax-module <name>          Specify main module for syntax. The default
                                    is the module specified in the given
                                    compiled K definition.
    --io <[on|off]>                 Use real IO when running the definition.
                                    (Default: enabled).
    --color <[on|off|extended]>     Use colors in output. (Default: on).
    --terminal-color <color-name>   Background color of the terminal. Cells
                                    won't be colored in this color. (Default:
                                    black).
    --parser <command>              Command used to parse programs. (Default:
                                    kast).
    --config-var-parser <file>      Command used to parse configuration
                                    variables. (Default: kast -e).  See
                                    --parser above. Applies to subsequent -c
                                    options until another parser is specified
                                    with this option.
 -c,--config-var <name=value>       Specify values for variables in the
                                    configuration.
 -o,--output <mode>                 How to display Maude results. <mode> is
                                    either
                                    [pretty|smart|compatible|kore|raw|binary|no
                                    ne]. (Default: pretty).
    --search                        In conjunction with it you can specify 3
                                    options that are optional: pattern (the
                                    pattern used for search), bound (the number
                                    of desired solutions) and depth (the
                                    maximum depth of the search).
    --search-final                  Same as --search but only return final
                                    states, even if --depth is provided.
    --search-all                    Same as --search but return all matching
                                    states, even if --depth is not provided.
    --search-one-step               Same as --search but search only one
                                    transition step.
    --search-one-or-more-steps      Same as --search-all but exclude initial
                                    state, even if it matches.
    --pattern <string>              Specify a term and/or side condition that
                                    the result of execution or search must
                                    match in order to succeed. Return the
                                    resulting matches as a list of
                                    substitutions. In conjunction with it you
                                    can specify other 2 options that are
                                    optional: bound (the number of desired
                                    solutions) and depth (the maximum depth of
                                    the search).
    --bound <num>                   The number of desired solutions for search.
    --depth <num>                   The maximum number of computational steps
                                    to execute or search the definition for.
    --graph                         Displays the search graph generated by the
                                    last search.
    --backend <backend>             Specify the krun backend to execute with.
                                    <backend> is either [maude|java]. (Default:
                                    maude).
    --simulation <string>           Simulation property of two programs in two
                                    semantics.
 -X,--help-experimental             Print help on non-standard options.

Exception in thread "Thread-1" java.lang.NullPointerException
    at java.io.File.<init>(File.java:277)
    at org.kframework.krun.Main$2.run(Main.java:954)

**Comment by grosu** [comment]
This is very bad!  Please fix immediately, we cannot afford such errors.  Dorel, I assume you did an "ant clean; ant", right?

Grigore

**Comment by dlucanu** [comment]
yes.
Dorel

**Comment by osa1** [comment]
I think this error exists for months. I know ktest has same problem for months too. (not introduced by me)

```
➜  k git:(master) ./bin/ktest 
org.kframework.ktest.CmdArgs.InvalidArgumentException: ktest requires exactly one <file> parameter.
        at org.kframework.ktest.CmdArgs.CmdArg.validateArgs(CmdArg.java:176)
        at org.kframework.ktest.KTest.run(KTest.java:47)
        at org.kframework.ktest.KTest.main(KTest.java:102)
        at org.kframework.main.Main.main(Main.java:57)
Exception in thread "main" java.lang.NullPointerException
        at org.kframework.ktest.KTest.main(KTest.java:107)
        at org.kframework.main.Main.main(Main.java:57)
```

**Comment by dwightguth** [comment]
I will fix this today.
