### ISSUE TITLE
Symbolic expressions now only accept integer arguments

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#41]
Using  #symInt(n) gives compilation errors. Only  expressions like #symInt(1) are supported. It would be nice to support id's inside #symInt(), like it was before the elimination of #Id. This would make symbolic execution results more readable.
How to reproduce:
kompile -v -symbolic simple-untyped
krun -cPC=true -cIN="ListItem(n)" programs/exceptions/exceptions_01.simple

Result:
Critical: Parse error: Syntax error near unexpected character ')'
        File: ListItem(n)
        Location: (1,11,1,11)

**Comment by denis-bogdanas** [comment]
Problem confirmed with v3.2.1-234.

**Comment by andreiarusoaie** [comment]
I noticed that too. Apparently there is a problem when parsing any command line arguments containing identifiers.

**Comment by dlucanu** [comment]
This was also reported in Issue #43.  
Maybe these two issues should be merged.
