### ISSUE TITLE
Char "B" & B:Bool

### ISSUE THREAD

**Issue by nwpuzhangfan** [kframework/k-legacy#420]
I defined the hex digit, and It's include the Char "B". the code like this:
  syntax ExtendedDigit ::= Digit | "A" | "B" |...|"f"
and when I kompile the k file, it's report following error:

[Error] Critical: Production "B"  has not been imported in this module.
    Defined in module: AADL-SYNTAX file:
       /home/frank/AADL_in_K/LexicalElement.k
File: /k/include/builtins/bool.k
Location: (26,21,26,22)

It seems that Char "B" have conflict with the rule defined in bool.k "rule true andBool B:Bool => B:Bool", actually It's have conflict with B:Bool.

**Comment by radumereuta** [comment]
This is a known issue in the modularity system.
Unfortunately, the current implementation doesn't allow me to fix it. I have to delay it for the new parser.
