### ISSUE TITLE
krun: values for configuration variables not parsed

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#43]
Consider the following simple definition:

```
module CFGP
  syntax Exp ::= Id "=" Int
  configuration 
    <k> $PGM:Exp </k>
    <st> $ST:Map </st>

  rule <k> X:Id = I:Int => . </k>
       <st>... X |-> (_ => I) ...</st>
endmodule
```

and the program ex.cfgp including "a = 2"
If we run this program with the following comand
  $krun ex.cfgp -cST "a |-> 0"

then we get the following error:

[Error] Critical: Parse error: Syntax error near unexpected character ' '
    File: a |-> 0
    Location: (1,2,1,2)

This is due to the fact the parser does not know how to parse "a". Kasting the program we get

```
$ kast ex.cfgp
_`(_`)('_=_, _`,`,_(_`(_`)(#token("Id", "a"), .KList), _`(_`)(#_(2), .KList)))
```

Then trying to replace "a" with its builtin form "#token("Id", "a")(.Klist)" we get a different error:

$ krun ex.cfgp -cST "#token(\"Id\",\"a\")(.KList) |-> 0" 
[Error] Critical: Parse error: Syntax error near unexpected character '"'
    File: #token("Id","a")(.KList) |-> 0
    Location: (1,13,1,13)

I think this should work, even if it is not a perfect solution.

A hack is to add the syntax declaration 
  syntax Id ::= "a"
to the definition, as we used to do it four years ago. Obviously, this is an unacceptable solution.

We have to urgently find a solution for it. It breaks the definition for the algorithmic language that I want to use for teaching.

**Comment by radumereuta** [comment]
This should work, we have this implemented in K. I think it broke when we changed #Id in to Id.

Right now I'm generating two parsers that contain the combined syntax of the language with the syntax of K. One is the rule parser where I have variables that can take the place of any term, and another one where I replace variables with Ids. I will have a look at it when I have the time. It may be a simple case where I have to reconnect some subsorts, or it may require me to introduce some new labels that give a better control over where productions are used.

I'm thinking of replacing onlyLabel with 'notInRules', 'notInGround', and 'notInPrograms'. It's more intuitive as a name, and it gives you control over how a production is used.
