### ISSUE TITLE
Unable to run graphical debugger using symbolic backend

### ISSUE THREAD

**Issue by daniel-ionut-vicol** [kframework/k-legacy#431]
Steps:
1. run kompile on a definition using symbolic backend 
(ex: kompile seq.k --backend symbolic)
2. launch the graphical debugger for a program
(ex:krun programs/morse.seq -cPC true --debug-gui)

Result : 
When the graphical debugger is launched it reports :
[Error] Critical: Currently supported backends are 'maude' and 'java'

**Comment by dwightguth** [comment]
Fixed in #432. @dlucanu can you please verify and then close this if you're happy?
