### ISSUE TITLE
DataStructureBuiltin.of does not work correctly for map terms

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#447]
If you call DataStructureBuiltin.of(context.dataStructureSortOf(DataStructureSort.DEFAULT_MAP_SORT), term1, term2), you expect to get the map term1 |-> term2. However, both term1 and term2 are put into baseTerms, and the resulting MapBuiltin object has no elements.

When you fix this, can you please write a junit unit test for this method? Something that exercises all the obvious cases and asserts that they behave approximately as you would expect them to.

**Comment by andreistefanescu** [comment]
Actually, on second thought, I think there is a source of ambiguity here. DataStructureBuiltin#of would essentially do what __ does: concatenate an array of terms which represent (the same type of) data structures. You should use DataStructureBuiltin#element to create a map entry "_|->_".

**Comment by dwightguth** [comment]
I think you should cause some kind of error to occur then if someone uses
this incorrectly. Otherwise they will have successfully created a
MapBuiltin object and not realize that it contained the incorrect data.

On Thu, May 15, 2014 at 1:01 PM, Andrei Stefanescu <notifications@github.com
