### ISSUE TITLE
Id constants with the same name with a variable do not parse

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#46]
Kompiling the definition

```
module CV 

  syntax Id ::= "B"

endmodule
```

produces the following error:
$ kompile cv
[Error] Critical: Production "B"  has not been imported in this module.
    Defined in module: CV file: /Users/dlucanu/teste-temp-k/constvsvar/cv.k
    File: /Users/dlucanu/k/dist/include/builtins/bool.k
    Location: (26,16,26,17)

The row 26 in bool.k is
  rule true andBool B:Bool => B:Bool

**Comment by dlucanu** [comment]
Here is another example. Kompiling the definition

```
module TOK

  syntax Exp ::= Token{"X"} | Int

  rule X:Exp => 1

  configuration <k> $PGM:Exp </k>
endmodule
```

produces the following long list of warnings:

$ kompile tok 

[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Id
2: 
   X ::Id
    File: /Users/dlucanu/k/dist/include/builtins/id.k
    Location: (14,13,14,17)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Id
2: 
   X
    File: /Users/dlucanu/k/dist/include/builtins/id.k
    Location: (14,37,14,38)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X ::Variable
    File: /Users/dlucanu/k/dist/include/modules/pattern-matching.k
    Location: (44,37,44,47)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X
    File: /Users/dlucanu/k/dist/include/modules/pattern-matching.k
    Location: (45,38,45,39)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X
    File: /Users/dlucanu/k/dist/include/modules/pattern-matching.k
    Location: (46,32,46,33)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X ::Variable
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (26,14,26,24)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (26,59,26,60)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X ::Variable
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (125,13,125,23)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (126,40,126,41)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X ::Variable
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (127,13,127,23)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (128,42,128,43)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Variable
2: 
   X
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (128,59,128,60)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:K
2: 
   X ::K
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (221,23,221,26)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:K
2: 
   X
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (222,34,222,35)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:K
2: 
   X
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (222,67,222,68)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:K
2: 
   X ::K
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (244,41,244,44)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:K
2: 
   X
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (245,43,245,44)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:K
2: 
   X ::K
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (252,20,252,23)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:K
2: 
   X ::K
    File: /Users/dlucanu/k/dist/include/modules/substitution.k
    Location: (252,25,252,28)
    Compilation Phase: Ambiguity filter
[Warning] Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: 
   X:Exp
2: 
   X ::Exp
    File: /Users/dlucanu/teste-temp-k/tokens/tok.k
    Location: (6,3,6,8)
    Compilation Phase: Ambiguity filter

**Comment by cos** [comment]
does this still apply to the new parser? can we delete the issue?

**Comment by radumereuta** [comment]
This was an issue with the modularity of the old parser.
Not an issue in the new implementation.
