### ISSUE TITLE
Another bug related with built-in name clashes

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#48]
I think I found another bug that is related with name clashing with built-in names. Here's my first bug about this: https://github.com/kframework/k/issues/34

Now the problem is, this module:

```
module BUG

  syntax Stx ::= S(Stx, Stx, Stx) [strict(1), seqstrict(3, 2)]
               | "end"

  configuration
    <k> $PGM:Stx </k>

endmodule
```

fails to compile with the error:

```
➜  bug  kompile bug.k
[Error] Critical: Parse error: Syntax error near unexpected character ':'
        File: /home/omer/K/k/dist/include/builtins/string.k
        Location: (69,11,69,11)
```

but when I rename `S` nonterminal with, for example, `Asdf`, it compiles fine. This suggests to me that we have a name clash problem here. (though I couldn't find the name `S` used in `string.k` file -- maybe it's somewhere in Java parts?)

**Comment by ciobaca** [comment]
This is a known bug in the kompiler.

Unfortunately, all .k files (including those in the standard library (in
this case, string.k)) get parsed _after_ the concrete syntax of the
language is generated. Unfortunately, this means that the variable
"S:String"

  rule isChar(S:String) => lengthString(S) ==Int 1 [function, anywhere]

used on line 69 of the file string.k gets confused with the "S" in the
production declared for Stx.

Everyone designing languages should be aware of this annoying limitation
until it gets fixed.

Cheers,
Stefan

On Fri, Sep 27, 2013 at 5:31 PM, Ömer Sinan Ağacan <notifications@github.com

**Comment by osa1** [comment]
Maybe we should introduce namespaces? Or is there a way to fix this without introducing namespaces?

**Comment by radumereuta** [comment]
This was a modularity issue. Should be fixed in the new parser because we use a different parser for each module.
