### ISSUE TITLE
LTL model checking don't work for negative results

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/k-legacy#481]
Steps to reproduce:
- Download php semantics from http://www.phpsemantics.org/
- cd kphp-sources\
- kompile php.k --transition step
- krun --debug-info --parser="java -jar parser/parser.jar" --ltlmc="<>Ltl(eqTo(gv(variable(\"x\")),val(\"world\")))" examples/hello-world-ltl.php

Result:

[Error] Critical: Cannot parse result xml from maude. If you believe this to be
in error, please file a bug and attach
D:\kphp-sources.k\krun8698076417810780425\maudeoutput.xml

The following, positive formula works instead:
krun.bat --debug-info --parser="java -jar parser/parser.jar" --ltlmc="<>Ltl(eqTo(gv(variable(\"x\")),val(\"hello\")))" examples/hello-world-ltl.php

platform: windows

**Comment by dwightguth** [comment]
I will fix this tomorrow. Long past time we had a regression test for this.

**Comment by denis-bogdanas** [comment]
Looks like Danielle had the same problem. Here he presents a workaround (section LTL model checking ):
http://www.doc.ic.ac.uk/~maffeis/phpsemantics/documentation.html

**Comment by dwightguth** [comment]
This is fixed. @denis-bogdanas , can you verify and close?
