### ISSUE TITLE
Unable to run ktest from my Eclipse

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#488]
There are actually two problems here:
1) ktest can not compute the location of `ktest.xsd` correctly in https://github.com/kframework/k/blob/af7d41e4404f3a55ad795f6ddf820e70a0d49d71/src/javasources/KTool/src/org/kframework/ktest/Config/ConfigFileParser.java#L437
It returns `k/src` instead of `k`. 
@dwightguth suggests include `ktest.xsd` somewhere together. Sorry, I forgot the place you mentioned...

2) The other problem is that  `args[0]` at https://github.com/kframework/k/blob/83c86c8d290b0308dee06b623f588976ed7e64a8/src/javasources/KTool/src/org/kframework/ktest/Proc.java#L139 contains `/src` at the end when starting ktest from IDE.

**Comment by dwightguth** [comment]
I said as a resource in the jar.

**Comment by osa1** [comment]
I'm running ktest from intellij all the time(for debugging) without problems. @yilongli are you still having these issues? Otherwise can we close this?

**Comment by yilongli** [comment]
Yes, but since you are able to run it all the time, it's probably a configuration problem I need to figure out. I am closing this issue. Thanks.
