### ISSUE TITLE
syntax KItem

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#5]
There's still an issue about this on the Google Code issue tracker but I am making a new one here because I ran into something specific and I'm not sure if Radu is aware of it, because he's been working on the KItem thing and I don't know how far he's gotten.

Consider the following module:

module TEST

syntax KItem ::= close(Int)

endmodule

Run the command:

kast -e "close(5)"

This should work. But instead it says "Desired start symbol not found: K"

**Comment by grosu** [comment]
So, does it work?  We need this in order to unblock two people: Andrei S and Dwight. So it has a high priority.

**Comment by radumereuta** [comment]
I've added the patch. During today's meeting Dwight said it works. If there aren't any more issues, then you can close it.

**Comment by grosu** [comment]
Dwight, it is probably you who should close this if it works.

**Comment by dwightguth** [comment]
Closing
