### ISSUE TITLE
why does ktest generate pdf files by default?

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#504]
I guess the solution is `--skip pdf`. Is it common to want a pdf file when running tests? Or it is considered a test of the pdf generation mechanism?

**Comment by traiansf** [comment]
It is considered a test of the pdf generation mechanism. However, it is mostly used for regression testing in Jenkins.  We should maybe consider skipping it by default. This would mean we need another option to enable it.

@grosu @osa1 @dwightguth What do you think about this?

**Comment by grosu** [comment]
I think this is minor, so I would not worry about it.  Besides, we have already discussed it in the past and decided to keep it this way.  There is also a way to state default option values in the config.xml files, which I hope is documented.  If not, I would recommend Daejun to do it.

**Comment by radumereuta** [comment]
Well... I think it's time to reopen this discussion. It takes a lot of time to generate the PDFs for all the examples, and currently the build is broken, because it takes more than 30 minutes to test everything.

**Comment by traiansf** [comment]
However, we need to make sure that all pdfs in the tutorial work.  It has
happened before that some of them were working while others were not.

2014-05-27 19:02 GMT+03:00 Radu Mereuta notifications@github.com:

**Comment by grosu** [comment]
Agreed.  We may "cheat" by only checking the last one in each part, except for the one lesson in the first part which introduces and discusses the PDF generation.

Grigore

**Comment by grosu** [comment]
@daejun and @osa1: guys, could you please create a wiki page, or add a section in the manual-to-be, about possible design options for ktest as proposed by various users?  When the dust settles and several of us get more experience with using ktest, we will revise all those and possibly come up with a default behavior that will satisfy most of us.  But right now I think it is premature to change the default options, considering that ktest already has all the features that we need if we use the right parameters.

**Comment by radumereuta** [comment]
A followup on what I did to take down the execution time of ktest.
Last week, master started to take more than 30 minutes (timeout limit) to test, so I added skip="pdf" to some redundant tests. I added the option to all of the /tests/regression, /tests/newparser, and a few other definitions from /samples.

One thing that I wasn't able to do, was to remove the pdfs for the first lessons in the tutorial. Apparently the <task /> element is defined for the first lesson and inherited by the others. I wasn't sure how to proceed, so I left it alone. The good thing is that I managed to take the time down to 23 minutes.

**Comment by grosu** [comment]
Radu, I hope you did not remove the generation of PDFs for SIMPLE, KOOL, FUN, etc., because these are referred to all the places on the kframework.org webpage.

**Comment by radumereuta** [comment]
No I haven't. The only one from /samples that I remove was quine-short.k
Everything should be in place.

**Comment by grosu** [comment]
These are not in samples, they are in tutorial/2_languages.

**Comment by radumereuta** [comment]
This is what I actually modified: https://github.com/kframework/k/pull/509/files
I haven't touched the tutorial.

**Comment by cos** [comment]
Shall we close this?

**Comment by radumereuta** [comment]
Yep, we can close this one.
