### ISSUE TITLE
Java backend cannot deal with some very simple function rule

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#511]
When I test this rule in c-semantics, the java backend's CompileDataStructures step will complain that the rule 

" rule areVoidOrComplete(ListItem(Head:Type) Tail:List)
          => isVoidOrComplete(Head) andBool areVoidOrComplete(Tail)"

has the error:

[Error] Critical: unexpected left-hand side data structure format; expected
elements and at most one variable

I am trying to compile this piece in language/translation/function-def.k

```
 syntax Bool ::= isVoidOrComplete(Type) [function]
 rule isVoidOrComplete(T:Type)
      => isCompleteType(T)
      orBool isVoidType(T)
      orBool isIncompleteArrayType(T)

 syntax Bool ::= areVoidOrComplete(List) [function]
 rule areVoidOrComplete(ListItem(Head:Type) Tail:List)
      => isVoidOrComplete(Head) andBool areVoidOrComplete(Tail)
 rule areVoidOrComplete(.List) => true
```

The output is like:
[Error] Critical: unexpected left-hand side data structure format; expected
elements and at most one variable
'_List_('ListItem(Head:Type ),, Tail:List )
    File:
/home/qangel/project/c-semantics/semantics/language/translation/function-def.k
    Location: (109,6,110,67)
    Compilation Phase: Compile collections to internal K representation
make[1]: **\* [c11-translation-kompiled] Error 1
make[1]: Leaving directory `/home/qangel/project/c-semantics/semantics'
make: **\* [semantics] Error 2

**Comment by yilongli** [comment]
I would like to have a minimal example separated if possible.

The `dataStructure` at https://github.com/kframework/k/blob/bcbfff724c1271995def1c48503126b2e2fcf48a/src/javasources/KTool/src/org/kframework/compile/utils/CompileDataStructures.java#L134 should look like `[Head:Type ][Tail:List ][]` if the rule is correctly compiled.

**Comment by liyili2** [comment]
This is the minimal set of example

it is in the attachment.

**Comment by liyili2** [comment]
Sorry, I do not know if you receive the package.

I send it to your uiuc mail

**Comment by dwightguth** [comment]
You should put your minimal example on the github issue itself. Use ````` blocks to delimit code.

**Comment by yilongli** [comment]
I am working on your example. However, a definition of more than 1000 lines is not a minimal example. Please try to simplify it as much as possible next time.

**Comment by yilongli** [comment]
Here is a minimal failure-inducing example:

```
module TEST
  syntax List ::= ListItem(Bag)
  syntax Bool ::= foo(List) [function]
  rule foo(ListItem(H:K) T:List) => true
endmodule
```

The problem is the production `syntax List ::= ListItem(Bag)`; which probably shouldn't be used anymore. I can throw an error exception for this, but you will have to try to eliminate this in the C semantics.

**Comment by chathhorn** [comment]
That's how the call stack is implemented in the C semantics, which seems like a pretty legit use case to me. Is there a suggested alternative to this pattern?

**Comment by yilongli** [comment]
@andreistefanescu What do you think about Chris' question?

**Comment by liyili2** [comment]
YIlong, that is just one of the problem another problem in this file with a minimal set of test cases is like this:

module C-FUNCTION-DEF-SYNTAX
     syntax K ::= initFunction(K, K) [strict]
     syntax Bool ::= hasDupParams(Type) [function]
endmodule

module C-FUNCTION-DEF
     imports C-FUNCTION-DEF-SYNTAX

```
 syntax Bool ::= areCompatible(Type, Type) [function]
 syntax Type ::= compositeType(Type, Type) [function]

 syntax Bool ::= isUnionType(Type) [function]
 syntax Bool ::= isAggregateType(Type) [function]
 syntax Bool ::= isFunctionType(Type) [function]
 syntax Bool ::= isOldStyleFunctionType(Type) [function]
 syntax Bool ::= isFunctionPointerType(Type) [function]
 syntax Bool ::= isBitfieldType(Type) [function]
 syntax Bool ::= isCompleteType(Type) [function]
 syntax Bool ::= isIncompleteArrayType(Type) [function]
 syntax Bool ::= isIncompleteStructType(Type) [function]
 syntax Bool ::= isIncompleteUnionType(Type) [function]
 syntax Bool ::= isVoidType(Type) [function]
 syntax Bool ::= isTypedDeclaration(Type) [function]

 syntax Bool ::= isVoidOrComplete(Type) [function]
 rule isVoidOrComplete(T:Type)
      => isCompleteType(T)
      orBool isVoidType(T)
      orBool isIncompleteArrayType(T)

 syntax Bool ::= areVoidOrComplete(List) [function]
 rule areVoidOrComplete(ListItem(Head:Type) Tail:List)
      => isVoidOrComplete(Head) andBool areVoidOrComplete(Tail)
 rule areVoidOrComplete(.List) => true
```

endmodule

The problem is like:
qangel@qangel-Satellite-S855:~/project/k-unified/bin$ kompile c-function-def.k --backend java
[Error] Critical: Parse error: Syntax error near unexpected character 'o'
    File: /home/qangel/project/k-unified/bin/c-function-def.k
    Location: (25,17,25,17)
qangel@qangel-Satellite-S855:~/project/k-unified/bin$ kompile c-function-def.k --backend java
Exception in thread "main" java.lang.ClassCastException: org.kframework.backend.java.kil.KItemProjection cannot be cast to org.kframework.backend.java.kil.KItem
    at org.kframework.backend.java.indexing.IndexingPair.getIndex(IndexingPair.java:25)
    at org.kframework.backend.java.indexing.IndexingPair.getIndexingPair(IndexingPair.java:58)
    at org.kframework.backend.java.kil.Term$1.visit(Term.java:66)
    at org.kframework.backend.java.kil.Cell.accept(Cell.java:116)
    at org.kframework.backend.java.symbolic.BottomUpVisitor.visit(BottomUpVisitor.java:68)
    at org.kframework.backend.java.kil.CellCollection.accept(CellCollection.java:165)
    at org.kframework.backend.java.symbolic.BottomUpVisitor.visit(BottomUpVisitor.java:61)
    at org.kframework.backend.java.kil.Term$1.visit(Term.java:68)
    at org.kframework.backend.java.kil.Cell.accept(Cell.java:116)
    at org.kframework.backend.java.kil.Term.getIndexingPairs(Term.java:62)
    at org.kframework.backend.java.kil.Rule.<init>(Rule.java:76)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:636)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:74)
    at org.kframework.kil.Rule.accept(Rule.java:72)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:683)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.visit(KILtoBackendJavaKILTransformer.java:74)
    at org.kframework.kil.Definition.accept(Definition.java:185)
    at org.kframework.kil.AbstractVisitor.visitNode(AbstractVisitor.java:92)
    at org.kframework.backend.java.symbolic.KILtoBackendJavaKILTransformer.transformDefinition(KILtoBackendJavaKILTransformer.java:101)
    at org.kframework.backend.java.symbolic.JavaSymbolicBackend.lastStep(JavaSymbolicBackend.java:65)
    at org.kframework.main.LastStep.compile(LastStep.java:22)
    at org.kframework.main.LastStep.compile(LastStep.java:11)
    at org.kframework.compile.utils.CompilerSteps.compile(CompilerSteps.java:44)
    at org.kframework.kompile.KompileFrontEnd.genericCompile(KompileFrontEnd.java:192)
    at org.kframework.kompile.KompileFrontEnd.kompile(KompileFrontEnd.java:161)
    at org.kframework.kompile.KompileFrontEnd.main(KompileFrontEnd.java:72)
    at org.kframework.main.Main.main(Main.java:49)

**Comment by liyili2** [comment]
I mean for showing up the statement  

"[Error] Critical: unexpected left-hand side data structure format; expected
elements and at most one variable"

I comment out the //List ::= ListItem(Bag)

But it still show the same error, but for different rules. I think the ListItem(Bag) is just one such example. I will go ahead to give you another example without ListItem(Bag) to show the statement.

**Comment by chathhorn** [comment]
Actually, after looking at it closer, that appears to be a pretty nasty part of the semantics. Embedding the individual cell contents into a K sort production would probably be a bit cleaner.

**Comment by traiansf** [comment]
@chathhorn One should not define any constructors on builtin collections,  The idea would be to inject the Bag into K, and then use the regular ListItem.
So, something like  ListItem(Bag2K(Bag))

**Comment by liyili2** [comment]
This is the smallest example to show another problem in this topic:

module C-FUNCTION-DEF
     syntax CId ::= genLabel(Int, K) [klabel('genLabel)]
     syntax Type ::= t(Set, SimpleType) [klabel('t)]
     syntax Type ::= typedDeclaration(Type, CId) 
          [klabel('typedDeclaration), latex(\terminal{typedDecl}!({#1},{#2}!))] 

```
 syntax SimpleType ::= "char" [function]

 syntax Bool ::= "#hasDupIds'" "(" List ")" [function]
 rule #hasDupIds'(
           _
           ListItem(typedDeclaration(_, X:CId))
           _
           ListItem(typedDeclaration(_, X:CId))
           _
      ) => true
```

endmodule

the output is like:

[Error] Critical: unexpected left-hand side data structure format; expected
elements and at most one variable
'_List_('_List_(GeneratedFreshVar0:List ,,
'ListItem('typedDeclaration(GeneratedFreshVar1:Type ,, X:CId ))),,
GeneratedFreshVar2:List )
    File: /home/qangel/project/k-unified/bin/c-function-def.k
    Location: (10,6,16,19)
    Compilation Phase: Compile collections to internal K representation

**Comment by yilongli** [comment]
This error message is actually correct. Associative matching an element inside a list is not allowed in the Java backend.

**Comment by liyili2** [comment]
OK. I know how to change it, go to  #511 please. There is another problem there.

**Comment by andreistefanescu** [comment]
Actually, if the only case use is the call stack, there is a better
solution. You can do something like this:
configuration
  ...
  <frame-stack list="*">
    <frame>
      .Bag
    </frame>
  </frame-stack>
  ...
The java engine is going to use a list to represent the frame cells, and
keep the order. I think this notation is nicer than the one with ListItem.

Andrei

**Comment by liyili2** [comment]
In order to write up the original rule like:

```
 syntax Bool ::= "#hasDupIds'" "(" List ")" [function]
 rule #hasDupIds'(
           _
           ListItem(typedDeclaration(_, X:CId))
           _
           ListItem(typedDeclaration(_, X:CId))
           _
      ) => true
```

Now, I need to write a set of rules like:

```
     syntax Bool ::= "#hasDupIds'" "(" List ")" [function]
     syntax Bool ::= cIdIsInList(CId,List) [function]

     rule cIdIsInList(X:CId, .List) => false
     rule cIdIsInList(X:CId, (ListItem(typedDeclaration(_, X:CId)) Tail:List)) => true
     rule cIdIsInList(X:CId, (ListItem(typedDeclaration(_, Y:CId)) Tail:List)) => cIdIsInList(X, Tail) when X =/=K Y

     rule #hasDupIds'(.List) => false
     rule #hasDupIds'(
               ListItem(typedDeclaration(_, X:CId))
               Tail:List
          ) => true when cIdIsInList(X, Tail) ==K true

     rule #hasDupIds'(
               ListItem(typedDeclaration(_, X:CId))
               Tail:List
          ) => #hasDupIds'(Tail) when cIdIsInList(X, Tail) ==K false
```

This is not rewriting rules any more, it is completely functional programming.

**Comment by grosu** [comment]
So what is the actual problem here, that we do not have associative matching anymore in the Java backend?  We are going to add it, as we repeatedly said in our meetings.  So in these cases, Liyi and others, make sure that you comment such rules with a TODO note.  For example:

/\* TODO: Replace the rules below with one rule once associative matching is available
in the Java backend. */

As a side note, please get used with using the functional notation for syntax when you have prefix-form operations, which we added precisely because Chucky and others defining lots of functions in their large language definitions wanted so much.  That is, instead of

```
syntax S ::= "foo" "(" A1 "," A2 ")"
```

use

```
syntax S ::= foo(A1,A2)
```

**Comment by chathhorn** [comment]
In the past, that function syntax hasn't worked for function names that
contain any non-alpha[numeric?] characters, so any of [#'-] prevent its
use. Admittedly, this one has a particularly ugly name that maybe should be
changed, but it might be nice to at least support that function syntax for
function names that end in a tick or something.

**Comment by grosu** [comment]
@radumereuta what do you think, can it be done easily?  If you don't want to invest in the SDF-based parser, then at least put a note somewhere for the new parser, please.

**Comment by radumereuta** [comment]
The change should be done in JavaCC-outer-parser.
I think @liyili2 has the most experience with JavaCC now.

Anyway. This is only syntactic sugar.
syntax S ::= foo(X, Y)
is equivalent to:
syntax S ::= "foo" "(" X "," Y ")" [klabel('foo)]

You can write whatever you want as long as you put quotes around the terminals.

**Comment by liyili2** [comment]
If I am going to do it, I am not sure what should be changed for the parser.
