### ISSUE TITLE
kast doesn't work on a valid K program

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#52]
```
➜  lesson_4 git:(master) ✗ rm -rf imp-kompiled
➜  lesson_4 git:(master) ✗ kompile imp.k
➜  lesson_4 git:(master) ✗ kast imp.k
[Error] Critical: Parse error: Syntax error near unexpected character 'I'
        File: /home/omer/K/k/dist/tutorial/2_imp/lesson_4/imp.k
        Location: (1,8,1,8)
➜  lesson_4 git:(master) ✗ kast -fastKast imp.k
[Error] Critical: Parse error: character 'I' unexpected
        File: /home/omer/K/k/dist/tutorial/2_imp/lesson_4/imp.k
        Location: (1,8,1,8)
```

(also, can anyone explain me what does kast do? if I understand correctly it prints KIL AST in a user-readable format, is that correct?)

**Comment by andreiarusoaie** [comment]
kast is meant to be run on programs. When constructing the initial configuration, krun calls kast on the program given as argument and plugs into the initial configuration (in the <k> cell) the parsed program.

Andrei A.

**Comment by osa1** [comment]
Right .. help messages are a little bit confusing because for every
frontend same help message is printed ( org.kframework.utils.Error line 29 )

I'm going to send a pull request shortly.

---

Ömer Sinan Aðacan
http://osa1.net

2013/10/2 Andrei Arusoaie notifications@github.com

**Comment by osa1** [comment]
okay apparently this is not a bug and confusion will be removed once we have new help messages. closing.
