### ISSUE TITLE
Context rule does not work becasue of no associative matching

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#530]
In the c-semantics/language/translation/expr/function-call.k, I find that the rule "context revalParams(list(_ ListItem((HOLE => reval(HOLE))) _))" in the following context.

```
     syntax KItem ::= revalParams(K)
     context revalParams(list(_ ListItem((HOLE => reval(HOLE))) _))

     rule revalParams(list(L:List)) => revalParams(rvlist(L))
          when all(L, isKResult)
          [structural]
```

I do not know how to turn the context rule into a rule without using associative matching. @chathhorn Chris, Do you know whether or not you can delete this rule and use other set of rules to substitute this rule? 

OR can anyone else tell me whether or not the java backend can handle this rule in other way? The problem is that the context rule requires an  associative matching, but the Java backend does not support it currently. Once, I change this rule to other format, the compiler will complain that a context rule cannot have more than one rewrites or a context rule cannot rewrite other things other than HOLE.

Liyi Li

**Comment by grosu** [comment]
Hm, interesting.  Maybe we should support associative matching sooner than later in the Java engine.  Many of our users wanted it.  In some sense, we already have it, don't we?  I mean, we have the KList sort with its constructor, currently double comma, which is associative, isn't it?  All we have to do is to reduce the associative matching of a given label to that of KList.  At the level of KAST, I expect an associative label to be defined something like this: syntax KLabel ::= "mylabel" [assoc]

What do you guys think?  Is there any serious technical difficulty to support associative labels and matching?  Don't we have it already for KList?

Grigore

**Comment by chathhorn** [comment]
On Fri, May 30, 2014 at 9:06 PM, Liyi Li notifications@github.com wrote:

> In the c-semantics/language/translation/expr/function-call.k, I find that
> the rule "context revalParams(list(_ ListItem((HOLE => reval(HOLE))) _))"
> in the following context.
> 
> ```
>  syntax KItem ::= revalParams(K)
>  context revalParams(list(_ ListItem((HOLE => reval(HOLE))) _))
> 
>  rule revalParams(list(L:List)) => revalParams(rvlist(L))
>       when all(L, isKResult)
>       [structural]
> ```
> 
> You left off the "[ndheat]" tag on the context rule, which seems like an
> important detail. Could that context rule be applied to the list of
> parameters if it were turned into a Set? Then the Set could be turned back
> into a List, but you'd have recover the original ordering.

FWIW, that "reval" stuff probably could be refactored out eventually (in
favor of making evaluation to rvalues the default), but it would take quite
a bit of effort.

Chris

**Comment by chathhorn** [comment]
On Sun, Jun 1, 2014 at 1:30 PM, Chris Hathhorn chathhorn@gmail.com wrote:

> On Fri, May 30, 2014 at 9:06 PM, Liyi Li notifications@github.com wrote:
> 
> > In the c-semantics/language/translation/expr/function-call.k, I find that
> > the rule "context revalParams(list(_ ListItem((HOLE => reval(HOLE))) _))" in
> > the following context.
> > 
> > ```
> >  syntax KItem ::= revalParams(K)
> >  context revalParams(list(_ ListItem((HOLE => reval(HOLE))) _))
> > 
> >  rule revalParams(list(L:List)) => revalParams(rvlist(L))
> >       when all(L, isKResult)
> >       [structural]
> > ```
> 
> You left off the "[ndheat]" tag on the context rule, which seems like an
> important detail. Could that context rule be applied to the list of
> parameters if it were turned into a Set? Then the Set could be turned back
> into a List, but you'd have recover the original ordering.

Oh, right, the rule came from the translation semantics, which doesn't
care about non-determinism. But that context rule is duplicated in the
execution semantics, only with that [ndheat] tag.

Chris

**Comment by andreistefanescu** [comment]
We do not have any support for associativity in the java backend. There was
no need for it when handling KList.

Andrei

**Comment by liyili2** [comment]
This is not the only place to have context with ListItem(HOLE). There are totally five places to have this kind of problems.

I think in terms of syntax, this is the final place to cause me problem. Now, the java semantics can be kompiled with some warning because of substitution.k file and the make will get stuck at the "ctype.o" library and showing the following error:
Translating the standard library...
Error during translation: ctype.o
Use "kcc -d" to get the final configuration.
