### ISSUE TITLE
Sprawling `TermContext` (now `State`) and circular dependencies

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#536]
It seems that the former `TermContext` is rather entangled throughout the code base. Even `KItem` itself receives it in its constructor... grrr... 

It is ugly for the AST to have links the outer world. It should only receive such information on a need-to-know basis (e.g., though visitors/transformers). In any case, I'm afraid of the amount of the changes I would have make to fix this, so I won't attempt it (at least not without @andreistefanescu's or @dwightguth's help).

Still, I have to figure this out somehow because it give me a circular dependency: As we discussed, `State` will contain a `ConstraintedTerm`, which in most (likely all) cases needs a `State` for its construction. 

Furthermore, even if I swallow the circular dependency and construct the State before setting it's `ConstraintTerm`, I would still have to update all KItem's (and likely other) objects to the correct `State`, on each transition -- ugly and slow.

@dwightguth , @andreistefanescu suggestions?

**Comment by andreistefanescu** [comment]
the KItem dependence is on the definition object, which is (or should be)
immutable. So in that sense is not cyclical. Also, the KItem does not
actually store a reference to the definition, it just uses it to compute
sort information.

Andrei

**Comment by dwightguth** [comment]
I agree that having circular dependencies is bad and will cause problems
for me down the road with what I want to do. I believe the correct solution
is to make State contain a ConstrainedTerm and a Definition and make
ConstrainedTerm and all the Term constructors require only Definition.

Similarly, if a ConstrainedTerm requires a FileSystem, you do the same
thing.

Is that doable, or do you think you will have trouble with cyclical
dependencies even so?

**Comment by cos** [comment]
@andreistefanescu, right, I see now, it doesn't store it. Ok. So this means the circular dependency is only in the construction phase, and it can be broken by having KItem's constructor receive only the definition, not the entire state. 

@dwightguth, yes, that is the aim.

**Comment by cos** [comment]
`KLabelConstant` actually keeps the `State` in a field. It is only used in a couple of places, so I think I can break it easily.

**Comment by cos** [comment]
Referenced from #578.
