### ISSUE TITLE
ant checkstyle should check for uniform line endings

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#539]
Today with Cosmin, I found some files that contain windows new line characters.
Working from linux or mac afterwards creates a diff containing the entire file making code review harder.

So @dwightguth please add a check to ant that looks to see if you have the 0D 0A characters in a file, and reject them.

I'm working on windows, but I've set git to checkout with windows newline, and commit with linux newline. So it won't be a problem for me or others which wish to work on the same platform.

I think this should check ALL text files.

**Comment by dwightguth** [comment]
Fixed in #723
