### ISSUE TITLE
Do not understand why this map will not work

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#541]
Hi, I have a set of rules by using java backend, and it keeps complain about the map, and give me this indication:

[Error] Critical: Unsupported map pattern in the rule left-hand side

The rules are:

```
 syntax CId ::= Identifier(String) [klabel('Identifier)] // new   
syntax KItem ::= addBuiltins(Map)
rule <k> addBuiltins((B:String |-> _ => .Map) _) ...</k>
          <external-types> Types:Map </external-types>
          <external-defs> Defs:Map </external-defs>
          when (Identifier(B) in keys(Defs))
               orBool (notBool Identifier(B) in keys(Types))
```

**Comment by liyili2** [comment]
This problem is so serious. It seems that every map definitions in C are not supported.

**Comment by liyili2** [comment]
This is the minimal set to produce this problem:

```
module TEST

  syntax ABC ::= Identifier(Id)

  syntax KItem ::= AddMap(Map)

  rule AddMap((Identifier(A:Id) |-> _ => .Map)  _:Map) 

endmodule
```

Basically, the keys of a map cannot be in any structures.

**Comment by liyili2** [comment]
This set of rules will not work either:

```
module TEST

  syntax ABC ::= Identifier(Id)

  syntax KItem ::= AddMap(Map)
        | MinMap(Map)

  rule AddMap((A:Id |-> _ => .Map)  _:Map) 
    ~> MinMap(AMap:Map)
    when Identifier(A) in keys(AMap)
endmodule
```

**Comment by grosu** [comment]
Such rules should work.  Andrei, Traian, what do you think?

**Comment by andreistefanescu** [comment]
This does not work, because these rules above constrain the key (for
example the last rule requires a key A which is also a key in another map
(AMap)). We can discuss later about how to go around it (maybe after we
talk about the NSF report).

Andrei

**Comment by liyili2** [comment]
@chathhorn, Do you satisfy this, or do you really want to have structure on keys of map.

**Comment by liyili2** [comment]
Yes, this test also fails:

```
module TEST

  syntax ABC ::= Identifier(Id)

  syntax KItem ::= AddMap(Map)
        | MinMap(Map)

  rule AddMap((A:Id |-> _ => .Map)  _:Map) 
    ~> MinMap(AMap:Map)
    when A in keys(AMap)
endmodule
```

**Comment by liyili2** [comment]
I find that every rules which mentions map will fail and some other rules which are related to Map will also fail. This restriction will affect 20% of the rules in c semantics.

**Comment by chathhorn** [comment]
On Tue, Jun 3, 2014 at 10:14 AM, Andrei Stefanescu <notifications@github.com

> wrote:
> 
> This does not work, because these rules above constrain the key (for
> example the last rule requires a key A which is also a key in another map
> (AMap)). We can discuss later about how to go around it (maybe after we
> talk about the NSF report).

I don't quite understand what you mean here. Could you please describe
exactly what the limitations or differences are with the Java backend when
it comes to Maps (as well as Lists and Sets, for that matter), when you get
the chance?

Thanks!

Chris

**Comment by liyili2** [comment]
He means that
1, a semantics cannot have structure around the keys of maps.

2, a semantics cannot have two map and check whether one key is in keys of another map.
