### ISSUE TITLE
ktest: creates PDF without extension

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#57]
If I type

ktest -def simple-typed-static.k

everything is fine: the definition is kompiled and the PDF file is also generated and has the expected name and extension.

However, if I type

ktest -def simple-typed-static

(without the .k extension) then everything seems to work as well, except that the generated PDF has no .pdf extension.  But it is a correct PDF file.

All you have to do is to make sure the generated PDF file always has the .pdf extension.

**Comment by daejunpark** [comment]
This problem cannot be occurred any longer from a45814cd8a8a6ed65ed6ed34535b8a433b464e33, because those input is not allowed.
