### ISSUE TITLE
Switch to Java 8?

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#572]
I've been using it to compile K locally for the last few days. Everything seems ok.

**Comment by grosu** [comment]
How about Mac people?  Do they also have Java 8?  I remember the reason we delayed switching to Java 7 was that Mac didn't have a compiler for it.

Grigore

**Comment by cos** [comment]
I'm using a Mac. Apple doesn't have a special version of Java anymore. Oracle handles the Mac distribution, and, so far, they keep it in perfect sync with Windows.

**Comment by grosu** [comment]
Then I don't mind switching.  Others?

Grigore

**Comment by cos** [comment]
BUMP 

We forgot to discuss this today.

**Comment by yilongli** [comment]
I would love to play with the new Java 8 features.

**Comment by grosu** [comment]
As I said, we can switch if nobody has any complains.  If anybody has any complains, please express them in 24 hours.  Otherwise, let's switch.

Grigore

**Comment by traiansf** [comment]
I would say it's premature to switch to Java 8.

According to the java.com page, it is still in beta:
http://www.java.com/en/download/faq/java8.xml

Moreover, it cannot be installed on Windows XP, and probably it is hard to
put it on a Mac, too.

Although it might make it nicer for us, it might make it harder for our
users.

2014-06-11 3:37 GMT+03:00 Grigore Rosu notifications@github.com:

**Comment by andreiarusoaie** [comment]
It works nicely on my mac and it wasn't hard to install it at all.

**Comment by pmeredit** [comment]
Is anyone using K actually on Windows XP?  That's a scary thought.

On Wed, Jun 11, 2014 at 1:23 AM, Traian Florin Șerbănuță <
notifications@github.com> wrote:

> I would say it's premature to switch to Java 8.
> 
> According to the java.com page, it is still in beta:
> http://www.java.com/en/download/faq/java8.xml
> 
> Moreover, it cannot be installed on Windows XP, and probably it is hard to
> put it on a Mac, too.
> 
> Although it might make it nicer for us, it might make it harder for our
> users.
> 
> 2014-06-11 3:37 GMT+03:00 Grigore Rosu notifications@github.com:
> 
> > As I said, we can switch if nobody has any complains. If anybody has any
> > complains, please express them in 24 hours. Otherwise, let's switch.
> > 
> > Grigore
> > 
> > ---
> > 
> > From: Yilong Li [notifications@github.com]
> > Sent: Tuesday, June 10, 2014 7:36 PM
> > To: kframework/k
> > Cc: Rosu, Grigore
> > Subject: Re: [k] Switch to Java 8? (#572)
> > 
> > I would love to play with the new Java 8 features.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/kframework/k/issues/572#issuecomment-45689485>.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kframework/k/issues/572#issuecomment-45689571.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kframework/k/issues/572#issuecomment-45703021.

## 

-Patrick

**Comment by dwightguth** [comment]
The Windows XP thing is not something we should worry about. Trying to
support OS's that the developers of them have end-of-lifed is a losing
battle we shouldn't fight.

That said, if Java 8 is still officially in beta, we should probably hold
off...

**Comment by cos** [comment]
@traiansf that page does not say Java 8 is in beta.

Java 8 has been officially released. As far as I know, Java doesn't have a beta system anymore, they only use release candidates (which are kind of like beta). Java 8 is out of release candidates stage.

I would be very, very surprised if we would hit a bug in Java 8.

The only issue would be third-party tool support, but it already works for Eclipse and Intellj.

**Comment by traiansf** [comment]
Well, I read the quote below as "beta"
The new release of Java is first made available to developers to ensure no
major problems are found before we make it available on the java.com
website for end users to download.

2014-06-11 22:55 GMT+03:00 Cosmin Radoi notifications@github.com:

**Comment by cos** [comment]
Mark Reinhold, the chief architect of Java, replied to a comment on the release blog post:

> We're very conservative with java.com auto-updates. We'll switch that over to JDK 8 in a few months.
> (http://mreinhold.org/blog/jdk8-ga)

This was three almost months ago. I think they're not publishing to java.com in order to have a somewhat gradual release. 

Also, it seems the March 25 release was coordinated with Netbeans, Eclipse, and Intellij releases. So all  have support for Java 8.

I really don't think we have anything to worry about. A cautious approach would be to make the next release of K (the current master branch) require Java 7, and move on to Java 8 starting with the unified-builtins branch and subsequent releases.

I'm pushing for this because we are refactoring code in the Java engine and it would be nice to be able to use the new Java 8 features.

**Comment by denis-bogdanas** [comment]
There is really no reason to delay switching to Java 8. By possible major problems they probably mean problems in newly added features (API features, not language ones) such as JavaFX. Features that we don't use. An upgrade of an existing project to Java 8 may hardly trigger any problems. A single run of the test suite with Java 8 should be convincing enough.

**Comment by dwightguth** [comment]
Okay. Let's say that the existing release targets Java 7 and the unified
builtins release targets Java 8. That way we don't break people who haven't
upgraded yet, but we also allow Cosmin and others to use the new features.

If nobody objects, I will handle the switch tomorrow sometime.

**Comment by radumereuta** [comment]
Denis, I don't share your confidence in 'no bugs' in the java 8 beta.
For example when we switched to java 7, I found a bug in Collections.sort() which caused me some headaches for a few days.

**Comment by cos** [comment]
@radumereuta, again, Java 8 is not in beta. It has been officially released with no "beta" or similar tag. 

Regarding `Collections.sort()`, was it a bug in Java 7, or was your `Comparator` not consistent with `equals`?

**Comment by grosu** [comment]
Guys, supposing that we switch to Java 8, would that mean that our users (not developers) also need Java 8 to run their code?  I mean, is the JVM also different, or only the JavaC?  Is this a problem to worry about or not?

**Comment by radumereuta** [comment]
This bug was in the release version (I think between 7.05 and 7.10)  http://stackoverflow.com/questions/13768919/collections-sort-issue-in-java7
@grosu users will also need java 8.

**Comment by cos** [comment]
@radumereuta, that was not a bug. The Java 6 implementation was lenient about inconsistencies between the comparator and equals (e.g., the comparator returning a non-zero value for equal objects). `TimSort` in Java 7 enforced the contract, and revealed a bug in your code, not Java 7's.

**Comment by cos** [comment]
The purpose of this issue was to decide whether to switch to Java 8. We've decided so I'm closing it.
