### ISSUE TITLE
missing base2String in java backend

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#573]
I find that the c semantics contains this code:

```
     syntax String ::= base2String(Int, Int)
          [function, klabel('base2String), hook(#CONVERSION:base2String)]

```

It indicates that there is a hook backend function to support converting integers with arbitrary bases into a decimal based integer string. I think it is hard to implement this function in c semantics directly. I wonder if someone would like to implement a hook function in java backend.

**Comment by andreistefanescu** [comment]
We should definitely implement it.

Andrei

**Comment by dwightguth** [comment]
Fixed. Please delete this production and use the one in the prelude.
