### ISSUE TITLE
Terminal productions versus Token{...}

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#579]
So in the unified-builtins2 branch we decided to change terminal productions of the form

```
syntax Id ::= "main"
```

into token ones

```
syntax Id ::= Token{"main"}
```

Is this a temporary fix, or a permanent solution?  I hope the former, until we come up with a uniform and powerful notation for syntax declarations (including *, greedy lists, etc.).

**Comment by dwightguth** [comment]
Radu: syntax Id ::= "main" works in the new parser, right?

**Comment by radumereuta** [comment]
It works right now in both parsers.
You can remove Token{...} safely.

What I'm doing is to collect all token sorts (in this case one would be Id) and then each time I'm seeing a single terminal on a token sort, I'm transforming that one automatically to a constant.
