### ISSUE TITLE
ktest -- the -skip option does not skip

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#58]
ktest -def simple-typed-static.k -skip kompile pdf

This is supposed to skip both the kompilation and the pdf generation, but it does not.  It only skips the kompilation.  If I swap kompile and pdf, then it skips only the pdf.  Same is I write

ktest -def simple-typed-static.k -skip kompile -skip pdf

However, this works:

ktest -def simple-typed-static.k -skip "kompile pdf"

Is this a bug or a feature?  If the list of options should be put in quotes, then we should say it so when we call ktest --help.

**Comment by andreiarusoaie** [comment]
This is because of the command line options of ktest. It works exactly as kompile options (e.g. --transition "tag1 tag2 ..." )

**Comment by grosu** [comment]
Ok, I see.  Daejun, is this still going to be a problem with the new options?  Actually, it may not be a problem, but it seems like a problem, particularly because it is not documented and because you don't need quotes for only one option.

Grigore
