### ISSUE TITLE
ktest -- -extension seems to be required

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#59]
If you don't use the -extension option, ktest will find no programs.  This could be Ok as a behavior, at least for now, but please give a warning whenever one specifies the -programs option without the -extensions option!

Another acceptable behavior could be to simply take all the files in the programs folder by default and run them as programs.  This way, one would have to write fewer options in common cases.

**Comment by daejunpark** [comment]
Fixed: a45814cd8a8a6ed65ed6ed34535b8a433b464e33
