### ISSUE TITLE
ktest should test a blank definition with "-w all" and fail

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#591]
Right now, If I kompile -w all test.k

> cat test.k
> module TEST-SYNTAX
> endmodule
> module TEST
> imports TEST-SYNTAX
> endmodule

I get all sort of warnings regarding unhooked operations, and unsorted variables from /include.
I've asked @dwightguth and he suggested to create an issue about it.

So what I'm expecting to happen, is to fail the build in such cases.
An empty test is required (just like above) and the output and err of kompile should be tested to be empty.

**Comment by dwightguth** [comment]
We actually already have this test, so if you fix the bug, it will probably break the build. Hopefully the work needed to resolve the regressions should be just routine. Let me know if it's not and we can evaluate who to have work on it.

**Comment by osa1** [comment]
I don't understand what's the problem and how is this related with ktest. I tried to kompile same file using same command(`ktest -w all test.k`) and no warnings/errors are printed. What am I missing?

**Comment by dwightguth** [comment]
Radu: you mean unified-builtins2 right?

Omer: Have you tried it in both master and unified-builtins2?

**Comment by radumereuta** [comment]
Ah, yeah, something that I forgot to mention:
kompile --backend java test.k -w all
That's the complete command.

**Comment by dwightguth** [comment]
Okay, this is not a ktest issue then. I am reassigning to Yilong, but it's very low priority so I would suggest that @yilongli only work on this if there is absolutely nothing he could be doing to assist with the deliverable or the merge instead.

**Comment by osa1** [comment]
I'm currently checking if ktest shows a success when something is printed to stderr. If that's the case this is still a ktest issue.

**Comment by dwightguth** [comment]
Alright. If that is the case, can you please separate this issue into its
two components by creating a separate issue to assign to Yilong which
mentions the fact that -w all is not tested for the java backend?

On Thu, Jun 12, 2014 at 2:43 PM, Ömer Sinan Ağacan <notifications@github.com

**Comment by osa1** [comment]
OK. There's a problem with ktest:

```
➜  bug git:(master) ✗ ktest config.xml --dry --skip "pdf"
'/home/omer/K/k_new_dist/k/bin/kompile' '/home/omer/K/k_new_dist/k/bug/test.k' '--backend' 'java' '-w' 'all'
➜  bug git:(master) ✗ '/home/omer/K/k_new_dist/k/bin/kompile' '/home/omer/K/k_new_dist/k/bug/test.k' '--backend' 'java' '-w' 'all'
[Warning] Compiler: Singleton variable I:Int .
    If this is not a spelling mistake, please consider using anonymous
variables.
        File: File System
        Location: generated
        Compilation Phase: class org.kframework.compile.checks.CheckVariables
... snipped warnings ...
➜  bug git:(master) ✗ ktest config.xml --skip "pdf" 
Running initial scripts...
SUCCESS
Kompile the language definitions...(1 in total)
SUCCESS
Running /home/omer/K/k_new_dist/k/bug/test.k programs... (0 in total, 0 with input, 0 with output, 0 with error)
SUCCESS

SUCCESS
----------------------------
Definitions kompiled: 1 (time: 0'6'' elapsed, 0'6'' CPU)
PDF posters kompiled: 0 (time: 0'0'' elapsed, 0'0'' CPU)
Programs krun: 0 (time: 0'0'' elapsed, 0'0'' CPU)
Total time: 0'6'' elapsed, 0'6'' CPU
----------------------------
```

**Comment by osa1** [comment]
I created the issue but later realized that may not be a problem. ktest only reports a failure when kompile returns non-zero. Do we really want to report a failure when warnings are printed but kompile still returned zero?

**Comment by dwightguth** [comment]
Well the ideal solution here would be to be able to optionally specify what
should appear on stdout, and then include a blank file. How much work would
that be to achieve?

On Thu, Jun 12, 2014 at 2:51 PM, Ömer Sinan Ağacan <notifications@github.com

**Comment by osa1** [comment]
It should not be very hard to implement but there are some design decisions to make:
- How to specify kompile output file path?
- What happens if it's not specified? (signal an error when printed to stdout vs. ignore stdout and focus on return value)
- Do we also want to check stdout?
- How to do these without breaking current tests?

**Comment by dwightguth** [comment]
Probably ignore output if the files aren't present, I think that's what we
do with programs now anyway. It shouldn't be too hard to come up with a
naming convention. If the definition is imp.k, you would look for a file
imp.k.out and imp.k.err in the results directory. If we do it this way, it
should be backwards compatible.

On Thu, Jun 12, 2014 at 3:07 PM, Ömer Sinan Ağacan <notifications@github.com

**Comment by dwightguth** [comment]
Assigning to @osa1 so he doesn't forget. Can we please get action on this soon? It is blocking us from implementing a solution to a particular type of undesirable regression in the tool.
