### ISSUE TITLE
krun error message does not confirm to 80chars/line

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#6]
fslwork$ krun
[Error] Critical: Could not find a compiled K definition. Please ensure that either a compiled K definition exists in the current directory with its default name, or that --k-definition or --compiled-def have been specified.

We agreed that all messages output to users will use up to 80 characters per line, to fit any terminals.  For example, compile outputs this message:

fslwork$ kompile
[Error] Critical: You have to provide a file in order to compile!.
    File: command line
    Location: System file.

Actually, I'm not sure that these should be errors.  We should simply output "usage" information.  But no matter what, let's stick to 80 characters.

**Comment by dwightguth** [comment]
I have trimmed this error message to have only 80 characters. There may be others that need it however. Please continue to report these issues as you notice them.

**Comment by grosu** [comment]
Typing "krun" alone shows a message which does not confirm to the 80 characters per line:

fslwork$ krun 
[Error] Critical: Could not find a compiled K definition. Please ensure that either a compiled
K definition exists in the current directory with its default name, or that --k-definition or
--compiled-def have been specified.
fslwork$ 

Dwight is under no obligation to continue to fix this, but I reopen the issue for others who will work on krun.

**Comment by ericmikida** [comment]
I fixed most of these issues in Main.java. I think the problem was that although the strings themselves were less than 80 chars per line, the Error class appended "Error [Critical]: " to the strings causing many of them to be over 80 chars.
