### ISSUE TITLE
need to know what sorts variables in a rule were inferred, as well as what why a rule does not apply

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#606]
See #605 for details.  I report this as a separate issue, so we can keep track of it.  We need an easy and quick way to see what sorts the variables in a rule have been inferred, as well as why a rule does not apply.  Actually, we may want to also see the entire, explicit KAST version of the rule somehow.

**Comment by radumereuta** [comment]
One quick fix would be to kompile -w all
This will show even the hidden warnings. (The inferred sort for variables are considered hidden warnings.)

**Comment by grosu** [comment]
We know that, but the problem with it is that it would show hundreds of warnings to an extent that it would make things unreadable.  We need a very simple way to show how a rule is translated to KAST.  Maybe as part of the KAST tool?  Then this tool will be integrated in the IDE, showing you things as you hover the mouse over the rule.

**Comment by grosu** [comment]
OK, so it looks like the `kompile --backend uflatten` option partially helps us with the first problem (i.e., seeing how the variables have been sorted), but it does not help with the second: why are rule does not apply.

**Comment by dwightguth** [comment]
Closing since both of these have been addressed. Cf --audit-step, etc
