### ISSUE TITLE
unification.k broken

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#607]
I cannot work on this lesson in the tutorial until the unification.k module gets fixed:

```
fslwork$ pwd
/home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_4
fslwork$ kompile lambda.k
[Error] Critical: Could not infer a unique sort for variable 'K'. Possible
sorts: Map, Set
    File: /home/grosu/github.grosu/k/include/modules/unification.k
    Location: (17,3,17,51)
fslwork$ 
```

**Comment by radumereuta** [comment]
Have you tried typing the variable K?
I know you like to not type the variables, and let the sort inferencer do the job, but the /include directory is a bit different. Since we are throwing a silent warning message each time we are inferring a variable, the users definitions would look terribly when they will get warnings from predefined modules.

**Comment by grosu** [comment]
No, I did not modify the included files at all.  I only focused on the actual definitions, which I am responsible for.  If nobody fixes unification.k by then, I will do it after I am done with everything else.

Grigore

**Comment by radumereuta** [comment]
Ok, I just found that there are actually 3 different productions which start with applyMgu
K ::= applyMgu(Mgu,K)
Set ::= applyMgu(Mgu,Set)
Map ::= applyMgu(Mgu, Map)

The rule that is ambiguous is:
rule applyMgu(Theta:Mgu,K) => applySubst(Theta,K)

Coupled with #605 and #109, what is the point of the last two productions?
What should I chose between the 3?
I don't really understand how I should handle overloaded production. As we can see, they make a big difference when trying to infer sorts for variables, even though in the end we collapse to the same klabel.

**Comment by traiansf** [comment]
Well, now that Set and Map are also K, we can probably only keep the first

2014-06-17 1:38 GMT+03:00 Radu Mereuta notifications@github.com:

**Comment by grosu** [comment]
Traian, I think you are the best person to fix unification.k, in case you can spare some cycles.

Grigore

**Comment by grosu** [comment]
@traiansf While the definition kompiles now, thanks to the changes you've made, it still does not seem to run correctly:

```
fslwork$ pwd
/home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_4
fslwork$ krun tests/tricky-2.lambda<k>
    (lambda f . (lambda #symType(1) . (f 0))) ~> (HOLE (lambda y . (if 
      true then y else #symType(1)))) ~> (#symType(1) -> HOLE)
</k>
<mgu>
    subst(.KList)
</mgu>
fslwork$ 
```

This should be an actual type, not a stuck computation.
