### ISSUE TITLE
Does the `--backend unparse` option work?

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#611]
Can it be trusted at all?  For example, for KOOL, which works, the semantic rule for addition is unparsed as follows:

```
    rule I1:K + I2:K => I1 +Int I2
```

Shouldn't it be

```
    rule I1:Int + I2:Int => I1 +Int I2
```

?

**Comment by yilongli** [comment]
I personally haven't tried this backend before, and I don't think this backend is very useful. I take a look at the code and it is basically the unflatten backend which stops right after at the first step. That's why the inferred sorts are not yet set.

**Comment by ciobaca** [comment]
Since there were no tests for unparse, things must have broken
significantly some time ago. Since noone noticed, I guess it is not used
anymore so maybe it is time to get rid of it if people don't find it useful.

Stefan

**Comment by grosu** [comment]
@yilongli But `kompile --backend unflatten kool-untyped.k -v --step "FirstStep"` does exactly the same think.  It produces a `kool-untyped.unparsed.k` file whose sorting information is just wrong.  Same like I reported above with the unparse backend.  So we basically have no way to see how things are parsed at this moment; we have to look into the generated Maude code, which is horrible.

**Comment by yilongli** [comment]
You can specify `--step "Set the sort of each variable to the inferred sort"` instead of `--step "FirstStep"` to see the inferred sorts. This is not user-friendly, but at least you don't have to look into the generated Maude code.
