### ISSUE TITLE
unified builtins - strange behaviour of fresh integers

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#620]
I see now that the fresh int variables like !N:Int are generated as integers, which is i.m.h.o. very confusing. Let's consider the following module:

```
module TEST
  syntax Exp ::= Int | Id
  rule <k> .K => !N </k>
       <env>... .Map => !X:Int |-> !N:Int ...</env>
  configuration
    <k> .K </k>
    <env> 2 |-> 3 </env>
endmodule
```

When kompiled and executed, it produces the following output:

```
$ kompile test.k
$ krun
<k>
    1
</k>
<env>
    1 |-> 1
    2 |-> 3
</env>
```

There are at least two problems here:
1. the values generated for two variables !X and !N are the same (1)
2. if the user does not know the initial configuration, then she/he cannot distinguish which is the generated  pair.
Moreover, if the cell <env> already includes a pair with the key 1, then the new pair is not longer added to its content.

**Comment by traiansf** [comment]
The fact that they are generated as integers is by design.  That means,
fresh does not have the same meaning like before (generating a new symbolic
constant), but rather it generates a fresh element of the given sort (as
fresh as it is given by a counter of freshness).

The fact that they are the same is a bug, though.

2014-06-17 15:03 GMT+03:00 Dorel Lucanu notifications@github.com:

**Comment by ciobaca** [comment]
I like this design decision, as it is more general. In order to get back
the old behaviour, we can simply use #symInt(!N:Int) instead of !N.

Cheerios,
Stefan

**Comment by traiansf** [comment]
To get fresh symbolic constants of a given sort, one can use
#freshSymSort("Int")
which would generate a #symInt(I)  where I is the next counter.
If more than one are needed in the same rule, they can be distinguished using
#freshSymSortN("Int", 0)  #freshSymSortN("Int", 1),...

**Comment by dlucanu** [comment]
Since we may have only one fresh generator per sort, we are not longer able to generate symbolic constants for the sort Int. 
For instance, for maps we may define

```
  syntax Map ::= "symMap" "(" Int ")"
  syntax Map ::= freshSymMap(Int)    [freshGenerator, function]
  rule freshSymMap(I:Int) => symMap(I)
```

and it seems it works fine (I tested).
For integers is not possible because now only one fresh generator is allowed.
Why are not allowed more generators for the same sort?

**Comment by traiansf** [comment]
One could have more generators for the same sort;  however, there is no guarantee which generator would be used when you ask for something fresh.

But.. Stefan solution should work for you, shouldn't it? Then you don't even need to define a new one for freshSymMap, you could use symMap(!I:Int).

However, if you define the SymInt sort, you can define a new fresh for it.

**Comment by dlucanu** [comment]
I was also thinking on a solution with SymInt, but in that case you need a rule like
rule isInt(I:SymInt) => true

in order to subsort SymInt to Int and to use in your definition !N:SymInt, which is a bit polluting. But sometimes is better to distinguish between symbolic values and the concrete ones.

However, having an integer for !N:Int is confusing: for me, !N is an existential variable and it should a special notation.

**Comment by ciobaca** [comment]
Actually, it seems there are two uses for fresh, for which the current
solution is not entirely satisfactory.

The first use is to faithfully model non-determinism e.g. in choosing
memory locations:

rule <k> new X ...</k> => <env> X |-> L </env> <heap> !L -> 0 ...</heap>

chooses a "fresh" location L.

The !L should model the fact that any integer location is allowed except
for locations already used as heap keys.

The theoretically generated transition system should allow to generate any
sequence of fresh locations, while the default implementation should just
generate 0, 1, 2, 3, etc. In order for the current solution to allow this,
the fresh operation should have an extra argument (the set of disallowed
values).

The second use is to theoretically create new symbolic values of the given
sort. This was the old implementation of fresh and it was useful e.g. in
symbolic execution.

The current implementation seems to miss both uses.

Cheers,
Stefan
