### ISSUE TITLE
reducing the number of files opened during kompile

### ISSUE THREAD

**Issue by owolabileg** [kframework/k-legacy#627]
In KompileFrontEnd.java:197 we have the following conditional expression:

```
return f.isDirectory() && f.getAbsolutePath().endsWith("-kompiled");
```

This causes a number of files to be opened (at the process level) unnecessarily during kompile. The number of files opened can be reduced by simply swapping the conditions in the expression like so:

```
return f.getAbsolutePath().endsWith("-kompiled") && f.isDirectory();
```

**Comment by dwightguth** [comment]
Sounds good. Make a pull request.

**Comment by osa1** [comment]
I don't understand this. Do you mean `isDirectory` "opens" the file? I don't think any [`open`](http://man7.org/linux/man-pages/man2/open.2.html) system calls used for that but I may be wrong. Can you tell me how did you test for this? I'd expect this method to use [`stat`](http://man7.org/linux/man-pages/man2/stat.2.html) under the hood and no real "opening" would be involved.

**Comment by owolabileg** [comment]
@osa1, you are right. No `open` is done, only `stat`. Please see #646 for the minor change that I proposed.
