### ISSUE TITLE
redundancy in and issue with buildjava.xml

### ISSUE THREAD

**Issue by owolabileg** [kframework/k-legacy#628]
In src/javasources/KTool/buildjava.xml, this line is added twice:

```
<pathelement location="bin" />
```

In addition, these two lines:

```
           <pathelement location="lib/junit.jar" />
            <pathelement location="lib/mockito-all.jar" />
```

Causes kompile or krun to refer to and try to open jar files that are outside k3.jar and in the sources directory) at runtime.

I am not sure whether this file is autogenerated (as it says in the comment) or what the correct fix would be.

**Comment by dwightguth** [comment]
Does it actually crash though? If so, that's really bad and I'll fix it
tomorrow morning. But if it works by silently failing to include those
jars, it should be fine. They're not runtime dependencies, they're only
test dependencies.

**Comment by owolabileg** [comment]
No, it doesn't crash. For some reason, though, kompile and krun both `stat` these dependencies.

**Comment by dwightguth** [comment]
Well they're in the classpath, so the JVM has to check to see if they're
present and use the class loader on them if they exist. This is a
limitation of the current build system which I think is not worth fixing.

You are welcome to create a pull request for the duplicate element, however.
