### ISSUE TITLE
code is pretty printed with very many parentheses

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#63]
I'm trying to figure out if I'm doing something wrong with my syntax or the printing of kast is overly eager to add parentheses.

It may be related to this issue:
http://code.google.com/p/k-framework/issues/detail?id=527

Was there any progress on this?

Thanks!

**Comment by cos** [comment]
Just found out about the --no-parens option. It works very well for now. I also talked with @andreistefanescu about this and might look into making a safer solution in the future. From my perspective, the issue can be closed for now.

By the way, the K primer paper is a great resource for how K works - why isn't it linked on the homepage?

**Comment by cos** [comment]
@liyili2 is this solved now?

**Comment by liyili2** [comment]
not yet.

**Comment by dwightguth** [comment]
Cosmin: The pretty printer requires a whole lot of drastic overhauling in
order to get it into a good state. It's on my todo list, after a whole
crap-ton of other stuff. So don't expect it to be any time very soon... If
you want to work on it I will support your efforts though.

**Comment by cos** [comment]
it's not on my critical path. I was just pruning the issues I've created. I'll leave this open.

**Comment by cos** [comment]
yes, this is very old (issue number 63) -- we know about the need for an unparser
