### ISSUE TITLE
Make all attributes strongly typed

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#634]
Attributes should be strongly typed and staticly reject values that are not of the correct syntax. This requires changes to Attributes.java and Attribute.java.

**Comment by radumereuta** [comment]
Can you be a bit more specific on this?
I don't really see your point.

**Comment by dwightguth** [comment]
If an attribute is expected to have a certain structure, then it will be parsed into that structure. So for example:

```
class StrictnessAttribute extends org.kframework.kil.Attribute {
  List<Integer> strictPositions;
  boolean sequential;
}
```
