### ISSUE TITLE
`ant test` produces hundreds of checkstyle 5.7 failures

### ISSUE THREAD

**Issue by liblit** [kframework/k-legacy#659]
I have a completely pristine checkout of the latest K master branch. I run `ant` followed by `ant test`. The latter produces 656 failures: one for each ofthe 656 files checked. This looks like a failure of the testing system rather than actual style violations.

I won't give the full output here, as it is quite long and fairly repetitive. Here are some representative samples, starting with the first few lines of the `checkstyle` phase of `ant test`'s execution:

```
checkstyle:
[checkstyle] Running Checkstyle 5.7 on 656 files
[checkstyle] Can't find/access AST Node typecom.puppycrawl.tools.checkstyle.api.DetailAST
[checkstyle] Can't find/access AST Node typecom.puppycrawl.tools.checkstyle.api.DetailAST
[checkstyle] Can't find/access AST Node typecom.puppycrawl.tools.checkstyle.api.DetailAST
...
[checkstyle] /home/liblit/Downloads/k/src/javasources/KTool/src/org/kframework/backend/Backend.java:0: Got an exception - java.lang.ClassCastException: antlr.CommonAST cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
[checkstyle] /home/liblit/Downloads/k/src/javasources/KTool/src/org/kframework/backend/BackendFilter.java:0: Got an exception - java.lang.ClassCastException: antlr.CommonAST cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
[checkstyle] /home/liblit/Downloads/k/src/javasources/KTool/src/org/kframework/backend/BasicBackend.java:0: Got an exception - java.lang.ClassCastException: antlr.CommonAST cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
...
BUILD FAILED
/home/liblit/Downloads/k/build.xml:204: Got 656 errors and 0 warnings.
```

Notice that the `checkstyle` version mentioned is `5.7`. I ran this without `checkstyle` installed as a package on my own system (a Fedora 20 machine), so presumably that refers to `checkstyle` as packaged with K itself? If I do install the official Fedora 20 `checkstyle` RPM packages, those give me `checkstyle-5.6`. When I run `ant test` again, the `checkstyle` phase of testing reports that it is using `5.6` and that phase now succeeds. So perhaps one is required to have `checkstyle` installed without assuming it is bundled with K? Or perhaps there is something wrong with the `checkstyle-5.7` that K seemingly includes?

**Comment by dwightguth** [comment]
This seems to be some version of dependency hell. The version of checkstyle we include is packaged with all its dependencies such as antlr 2.7.7.

Did you have a different version of antlr installed on your system in the default ant classpath?

I have made a diff which I hope might resolve the issue, but I'm not really sure. It is on the ant-checkstyle branch. Can you download it and let me know if it does?

**Comment by liblit** [comment]
Unfortunately the `ant-checkstyle` branch fails in the same way. I double-checked that I have that branch by comparing it with a checkout of `master`. I do indeed have your small tweak, but it doesn't fix the problem.

I do have `antlr` installed on my system, as a prebuilt Fedora RPM. That includes `/usr/bin/antlr` and `/usr/share/java/antlr.jar`, among other files. Presumably that `jar` archive is in the default `ant` class path? However, it is not a different version: the Fedora RPM is `antlr-tool-2.7.7`. I also see an `ant-antlr-1.9.2` package installed.
- With _both_ `antlr-tool-2.7.7` and `ant-antlr-1.9.2` installed, `ant checkstyle` _fails_ as documented in my original report on both the `master` and `ant-checkstyle` branches.
- With _neither_ `antlr-tool-2.7.7` nor `ant-antlr-1.9.2` installed, `ant checkstyle` _succeeds_ on both branches.
- With `antlr-tool-2.7.7` installed but `ant-antlr-1.9.2` _not_ installed, `ant checkstyle` _succeeds_ on both branches.
- Installing `ant-antlr-1.9.2` without `antlr-tool-2.7.7` is not an option, as the latter is a dependency of the former on both branches.

So it seems that having the `ant-antlr-1.9.2` RPM installed is key to triggering this bug. I'm not sure why. I can tell you that the following is the complete list of files installed by that RPM:

```
/etc/ant.d/antlr
/usr/share/ant/lib/ant-antlr.jar
/usr/share/java/ant/ant-antlr.jar
/usr/share/maven-fragments/ant-antlr
/usr/share/maven-poms/JPP.ant-ant-antlr.pom
```

Does that help any?

**Comment by dwightguth** [comment]
It does help, unfortunately, I don't entirely know what could be done to solve this issue. Normally the way this would be solved would be to fork a new JVM for checkstyle with only the classpath specifically required, however, the checkstyle ant task does not support the "fork" attribute.

The best advice I can really give you is to refer you to the [Checkstyle issue tracker](https://github.com/checkstyle/checkstyle/issues) to report the issue there. I will add a note in the readme, however.

**Comment by dwightguth** [comment]
Declared known issue in #673

**Comment by dwightguth** [comment]
Can I close this now, or do you have further concerns?

**Comment by liblit** [comment]
I'm satisfied. Thanks!
