### ISSUE TITLE
ktest -- junit-reports

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#66]
When using ktest, it always creates an empty folder junit-reports in the current directory.  Is this intentional?

**Comment by andreiarusoaie** [comment]
This is not intentional, that folder should contain the actual xml reports. And it does on Jenkins. I'll look into that. Traian proposed to have an option if we want or not to also generate the tests and I think it is a good idea.

**Comment by grosu** [comment]
An option is great!  But to generate by default an empty folder, that is not nice.

**Comment by andreiarusoaie** [comment]
I think this is fixed now.
