### ISSUE TITLE
Unify the various of visitors/transformers

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#670]
There are now no less than five Visitor-like interfaces, each with its own set of implementing classes. @dwightguth has already refactored the functionality on the frontend side. We could take one more step and unify the visiting mechanism for both sides. The advantage is not only uniformity, but less boilerplate code as each AST class has to implement a separate method for each applicable Visitor.

**Comment by radumereuta** [comment]
@cos, try to be a bit more descriptive when you post an issue.
Other people read them too, and they need to know if they have to read it or not.

**Comment by cos** [comment]
OK, I'll try to be more descriptive, unless I assign myself to the issue.

**Comment by cos** [comment]
In any case, considering the amount of emails the K repo produces, I, at least, have reverted to skimming and assuming that if it doesn't ring a bell, then it doesn't concern me.

**Comment by radumereuta** [comment]
Not everybody has this luxury. Some people have to pay attention to as many things as possible to maintain a unified view of the entire project.

**Comment by yilongli** [comment]
If you create issues that nobody except yourself understand, why bother creating it in the first place?

**Comment by cos** [comment]
@radumereuta, it is not about luxury, it's about priorities. Try to track how much time you spend every day reading each and every issue in detail, and then ask yourself whether that is time well spent. The important aspect is to notice and be involved in the discussions where you can make a contribution. I achieve this by skimming the latest issues from time to time, and by getting email notifications for the issues where I'm mentioned. If I miss something important that depends on me, somebody will very likely bug me about it. Also, I like to think that I did gain a unified view of the entire project.

@yilongli, because I want to have a note of something that is wrong/could be improved. Yes, I could make the note locally but I didn't think it is so much trouble for the others. I didn't put more details because I kept working on the task at hand. On the other hand, if you look at the (albeit few) issues created by me, you'll notice that obsolete ones have been closed, while the others generally have a person assigned to them.

In any case, I apologize for the inconvenience and, from now on, I will only add issues to github when I have enough time to also add details.

Taking a step back, if we are to fix something about how people deal with issues, I think the bigger problem is the overwhelming number of old, obsolete issues.

**Comment by cos** [comment]
no longer relevant.
