### ISSUE TITLE
`KException` should not hide the original exceptions 

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#675]
For example, this is a snippet from `BinaryLoader`:

```
try(ObjectOutputStream serializer = new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(fileName)))) {
  serializer.writeObject(o);
} catch (IOException e) {
  GlobalSettings.kem.register(new KException(ExceptionType.ERROR, KExceptionGroup.CRITICAL, "Could not write to " + fileName));
}
```

The exception was a `NotSerializableException` but that is not retained in any way in the `KException`. While the original succinct  "Could not write to ..." is ok for normal execution, `-v` (or another option) should show the original problem.

The easiest solution I see is for `KException` to retain the original exception, like other exception wrappers. 

Also, it may be a good idea to not replace original exceptions that are not due to user error. If the exception is not due to improper use of the tool, the original exception should should reach the surface.

(cc @dwightguth, @andreistefanescu, @traiansf, @yilongli, @radumereuta)

**Comment by yilongli** [comment]
Yeah, I agree. It's pretty inconvenient.

**Comment by traiansf** [comment]
I also agree with that.  Had some hard times debugging because of hidden
exceptions.  But I would hide it unless -v is used, as you propose.

2014-06-26 20:03 GMT+03:00 Yilong Li notifications@github.com:

**Comment by radumereuta** [comment]
+1

**Comment by cos** [comment]
I noticed @dwightguth fixed this at some point. The change is probably not propagated everywhere, as it allows the original exception to be omitted, but we can fix it as we encounter it.
