### ISSUE TITLE
Java backend krun steps escaping error

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#677]
If I have this set of rules:

```
module TEST

     configuration <k> $PGM:K</k><ss>""</ss><intlist multiplicity="?">.Map</intlist>            
    <curr-program-loc>
                UnknownCabsLoc
            </curr-program-loc>

     syntax KResult ::= C
     syntax KItem ::= klist(KList) | Int | listToK(List) [function] | "skip"
     syntax C ::= list(List)

     syntax C ::= Definition

     syntax KItem ::= CodeLoc(K, K) [klabel('CodeLoc)]
     syntax Definition ::= "DefinitionLoc" "(" K "," K ")"
          [klabel('DefinitionLoc)]

     syntax CabsLoc ::= "UnknownCabsLoc"

     syntax CabsLoc ::= CabsLoc(String, Int,Int)
          [klabel('CabsLoc)]

     syntax TranslationUnit ::= TranslationUnit(String, K)
          [strict(2)]

     syntax List ::= klistToList(KList) [function]

     rule DefinitionLoc(K:K, L:K) => CodeLoc(K:K, L:K) [macro, structural]

     rule <k> CodeLoc(K:K, L:CabsLoc) => K ...</k>
          <curr-program-loc> _ => L </curr-program-loc>
          [structural]

     rule klistToList((K:K,, L:KList)) => ListItem(K) klistToList(L)
     rule klistToList(.KList) => .List

     rule 'klist(KL:KList) => 'list(klistToList(KL))

     rule listToK(.List) => .K
     rule listToK(ListItem(K:K) L:List) => K ~> listToK(L)

     rule <k>I:Int => . ...</k>
      <intlist>... (.Map => I |-> "") ...</intlist>

     rule <k> skip => . ...</k>
      (.Bag => <intlist>.Map</intlist>)

     rule <k>TranslationUnit(S:String, list(L:List)) => skip ~> listToK(L) ...</k>
      <ss> _:String => S </ss>

endmodule
```

and I run the following command by "krun a.test --smt=none --parser "kast --parser ground":

```
'TranslationUnit("/home/qangel/project/c-semantics/libc/src/ctype.c",, 'klist('DefinitionLoc(1,, 'CabsLoc("a",, 1,, 0)) ,, 'DefinitionLoc(2,, 'CabsLoc("b",, 2,, 0)) ,, 'DefinitionLoc(3,, 'CabsLoc("c",, 3,, 0)) ,, 'DefinitionLoc(4,, 'CabsLoc("d",, 4,, 0))))
```

The output will be:

```
[5, 16.75 ms]
<k>
    .K
</k>
<ss>
    "/home/qangel/project/c-semantics/libc/src/ctype.c"
</ss>
<intlist>
    .Map
</intlist>
<curr-program-loc>
    UnknownCabsLoc
</curr-program-loc>

```

This output basically means that the krun completely escape the step of listToK(ListItem(K) L:List) => K ~> listToK(L) .

However, if I eliminate the function label in the listToK def as:

```
module TEST

     configuration <k> $PGM:K</k><ss>""</ss><intlist multiplicity="?">.Map</intlist>            
    <curr-program-loc>
                UnknownCabsLoc
            </curr-program-loc>

     syntax KResult ::= C
     syntax KItem ::= klist(KList) | Int | listToK(List) | "skip"
     syntax C ::= list(List)

     syntax C ::= Definition

     syntax KItem ::= CodeLoc(K, K) [klabel('CodeLoc)]
     syntax Definition ::= "DefinitionLoc" "(" K "," K ")"
          [klabel('DefinitionLoc)]

     syntax CabsLoc ::= "UnknownCabsLoc"

     syntax CabsLoc ::= CabsLoc(String, Int,Int)
          [klabel('CabsLoc)]

     syntax TranslationUnit ::= TranslationUnit(String, K)
          [strict(2)]

     syntax List ::= klistToList(KList) [function]

     rule DefinitionLoc(K:K, L:K) => CodeLoc(K:K, L:K) [macro, structural]

     rule <k> CodeLoc(K:K, L:CabsLoc) => K ...</k>
          <curr-program-loc> _ => L </curr-program-loc>
          [structural]

     rule klistToList((K:K,, L:KList)) => ListItem(K) klistToList(L)
     rule klistToList(.KList) => .List

     rule 'klist(KL:KList) => 'list(klistToList(KL))

     rule listToK(.List) => .K
     rule listToK(ListItem(K:K) L:List) => K ~> listToK(L)

     rule <k>I:Int => . ...</k>
      <intlist>... (.Map => I |-> "") ...</intlist>

     rule <k> skip => . ...</k>
      (.Bag => <intlist>.Map</intlist>)

     rule <k>TranslationUnit(S:String, list(L:List)) => skip ~> listToK(L) ...</k>
      <ss> _:String => S </ss>

endmodule
```

The output will be fine as:

```
[18, 34.44 ms]
<k>
    .K
</k>
<ss>
    "/home/qangel/project/c-semantics/libc/src/ctype.c"
</ss>
<intlist>
    1 |-> "" 2 |-> "" 3 |-> "" 4 |-> ""
</intlist>
<curr-program-loc>
    CabsLoc ( "d" , 4 , 0 )

```

**Comment by dwightguth** [comment]
Yilong does this need action on your part or is it expected behavior?

**Comment by yilongli** [comment]
It looks weird to me that `listToK` is declared as a function return sort KItem, yet the rules defining `listToK` rewrite it to something of sort K.
@radumereuta Should the front-end reject such definition?

**Comment by radumereuta** [comment]
But do we have a .KItem element to maintain the type of the rewrite?
Right now, K is viewed as an exception almost everywhere. If I encounter something of sort K in any context, I don't give an error message. This is important for the parser because it allows me to entangle concrete syntax with abstract syntax.

If I didn't answer your question, please let me know.

**Comment by yilongli** [comment]
@radumereuta I see. But what about this rule:`rule listToK(ListItem(K:K) L:List) => K ~> listToK(L)`, the right-hand side is definitely a K sequence. Do we want to allow this as well eventually? Is it a current limitation or the expected behavior in the long run?

If this is indeed the expected behavior of the parser, does it mean that our type system is fundamentally flawed? @grosu

**Comment by grosu** [comment]
@yilongli `listToK` must be a function that returns sort `K` and not `KList`.  In that case we would have no problem, wouldn't we?

@radumereuta `.KItem` does not and will never exist.  `.` are units only for collections.  In fact, we should get rid completely of `.Map`, `.List`, `.K`, etc., and only have _one_ polymorphic `.`.  Then, you can say `.::Map`, `.::K`, etc., to help the parser if it cannot infer its right sort.  Anything else different from that that you do in the front end, @radumereuta , is temporary and will be eventually thrown away.

**Comment by yilongli** [comment]
@grosu The is how `listToK` is defined.

```
syntax KItem ::= listToK(List) [function]
...
rule listToK(ListItem(K:K) L:List) => K ~> listToK(L)
```

Is this a problem?

**Comment by grosu** [comment]
Yes.  Functions can return K, so it should be defined like this:

```
syntax K ::= listToK(List) [function]
```

Grigore

**Comment by liyili2** [comment]
I try both K and KItem. They both work now for this example. I don't know why.

**Comment by yilongli** [comment]
@grosu And the front-end's type system cannot catch this error right now. So this is a current limitation of the parser as described by Radu, and not the expected behavior in the long run, right?

**Comment by grosu** [comment]
Yes, that's how I think about it (now).

**Comment by yilongli** [comment]
Since the example now works fine, I am closing this issue.
