### ISSUE TITLE
ktest --- the -d option does not have the new meaning, as it does in the other K tools 

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#68]
fslwork$ pwd
/home/grosu/k/dist/tutorial/2_languages/1_simple/1_untyped/programs/threads
fslwork$ krun -d ../.. threads_01.simple --output-mode none5
fslwork$ ktest -d ../.. --skip "kompile pdf" --programs . --extensions simple[Error] Critical: Testing data missing.
    File: command line
    Location: System file.
fslwork$ ktest -d ../../simple-untyped.k --skip "kompile pdf" --programs . --extensions simple
Kompiling the language definitions...
Skipped 1 definitions
Generating PDF documentation...
Skipped 1 definitions
Running ../../simple-untyped.k programs... (12)
SUCCESS
fslwork$

**Comment by grosu** [comment]
I was just informed by Andrei A that due to some personal problems he cannot work on ktest until Tuesday, at best.  Since students in cs422 will be asked to use ktest as part of their submission process next week, and since it is very confusing to have the same option -d mean different things in different tools, I wonder if anybody can volunteer to fix at least this -d problem of ktest.  Thanks in advance!

**Comment by daejunpark** [comment]
Fixed: a45814cd8a8a6ed65ed6ed34535b8a433b464e33
