### ISSUE TITLE
No 1 usability issue with K

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#682]
Each time I use K after a break of a couple of weeks, I invariably run into the same problem: a configuration is reported as the result, but there are rules which should still apply and I have no idea why they don't and no mechanism in K to allow me to quickly understand it.  We MUST do something about this.  I would give this issue top priority in terms of K usability.  Here is an example I ran into right now:

```
fslwork$ krun tests/tricky-2.lambda<k>
    (lambda f . (lambda #symType(1) . (f 0))) ~> (HOLE (lambda y . (if 
      true then y else #symType(1)))) ~> (#symType(1) -> HOLE)
</k>
<mgu>
    subst(.KList)
</mgu>
fslwork$ 
```

On the other hand, in my semantics I have a rule

```
  rule lambda X . E:Exp => ?T:Type -> E[?T/X]
```

So the top lambda should reduce.  The only thing I can think of is that `E` matches something which does not have the sort `Exp`, but how can I be absolutely sure?

I think we need, urgently, at least the following two options:

1) Given a term, to know exactly how it is parsed and what the sorts of all its subterms are.  something like this:

```
$ kast "(lambda f . (lambda x . (f 0)))" --sorts
(lambda f::Id . (lambda x::Id . (f::Id 0::Int)::Exp)::Exp)::Exp
```

2) Given a term and a rule, to analyze the application of the rule to that term.  If the rule applies, then to say it so and give the user all possible ways to apply to the rule on the term, with the corresponding matchings.  If the rule does not apply, to tell why now: the LHS may not match, or the side conditions (which ones?) do not hold.

The two options above would significantly improve the user experience.  Who can work on these?  Is the infrastructure ready for these, so we can assign them to some new people/volunteers who can just do them without having to refactor or change other parts of the framework?

**Comment by cos** [comment]
This would be very useful. From my perspective, especially option 2 -- it would be nice to have the subpattern-subexpression pair which got stuck. 

The functionality would fit well under the debugger.

**Comment by osa1** [comment]
> 2) Given a term and a rule, to analyze the application of the rule to that term. If the rule applies, then to say it so and give the user all possible ways to apply to the rule on the term, with the corresponding matchings. If the rule does not apply, to tell why now: the LHS may not match, or the side conditions (which ones?) do not hold.

:+1: for this. I requested and even tried to implement this feature several times in the past.

**Comment by grosu** [comment]
@dwightguth , so we finally have this?  Can somebody add a line or two in the manual on how to use it?

**Comment by dwightguth** [comment]
Done
