### ISSUE TITLE
ktest generates no pdf, but a log file, and reports SUCCESS

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#683]
What happens below makes no sense:

```
fslwork$ pwd
/home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_1
fslwork$ ls
imp.k  media.properties  NOTES  README.md  tests
fslwork$ ktest tests/config.xml 
Running initial scripts...
SUCCESS
Kompile the language definitions...(1 in total)
SUCCESS
Generate PDF files...(1 in total)
SUCCESS
Running /home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_1/imp.k programs... (8 in total, 0 with input, 8 with output, 0 with error)
SUCCESS

SUCCESS
----------------------------
Definitions kompiled: 1 (time: 0'9'' elapsed, 0'9'' CPU)
PDF posters kompiled: 1 (time: 0'8'' elapsed, 0'8'' CPU)
Programs krun: 8 (time: 0'3'' elapsed, 0'23'' CPU)
Total time: 0'20'' elapsed, 0'40'' CPU
----------------------------

fslwork$ ls
imp.k  imp-kompiled  imp.log  media.properties  NOTES  README.md  tests
fslwork$ 
```

1) ktest should NOT report success if it cannot generate the PDF correctly.

2) ktest should generate no imp.log file.

How can we even have this bug unnoticed for so long?  Aren't anybody else using ktest?

**Comment by osa1** [comment]
This is a problem with kompile, not with ktest. Here's how you try it yourself:

Let's see what command is run by ktest for this config file to generate PDF:

```
➜  lesson_1 git:(master) ✗ ktest tests/config.xml --dry --skip "kompile krun"
'/home/omer/K/k_new_dist/k/bin/kompile' '--backend' 'pdf' '/home/omer/K/k_new_dist/k/tutorial/1_k/5_types/lesson_1/imp.k'
```

Let's run this command. If it fails the process should return non-zero:

```
➜  lesson_1 git:(master) ✗ '/home/omer/K/k_new_dist/k/bin/kompile' '--backend' 'pdf' '/home/omer/K/k_new_dist/k/tutorial/1_k/5_types/lesson_1/imp.k'
[Warning] Compiler: pdflatex returned a non-zero exit code.  The pdf might be
generated, but with bugs. please inspect the latex logs.
➜  lesson_1 git:(master) ✗ echo $?
0
```

So this kompile process fails, but still returns 0. ktest can't do anything in that case other than assuming process is finished with a success(this is how to check successes/failures of spawned processes). Log file is created by this kompile process, again not related with ktest.

**Comment by grosu** [comment]
Thanks, Omer.  Who can then fix this bug in kompile?  Besides the bug, the error message needs to also be fixed: "The pdf might be generated, but with bugs. please inspect the latex logs."

First, the grammatical error.  Second, why say "might" there?  The PDF has either been or not been generated, there is no might, isn't it?  in case it has been generated, but with Latex warnings/errors, then ask the user to check the logs.

**Comment by osa1** [comment]
I can fix this bug and the error message over the weekend. I'm assigning this to myself.
