### ISSUE TITLE
Better error message needed when forgetting ? in front of fresh variables

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#684]
This rule

```
  rule <k> lambda X:Id . E:Exp => T:Type -> (E)::K ~> env(TEnv) ...</k>
       <tenv> TEnv:Map => TEnv[X <- T] </tenv>
```

yields the following error message:

```
[Error] Compiler: Unbounded Variable T:Type .
    File: /home/grosu/github.grosu/k/tutorial/1_k/5_types/lesson_5.5/lambda.k
    Location: (44,37,44,38)
    Compilation Phase: class org.kframework.compile.checks.CheckVariables
```

Everything works fine if I replace `T` with `?T`.

**Comment by radumereuta** [comment]
What would you have expected to happen, and why?

**Comment by grosu** [comment]
An error message saying that unbounded variables should start with either ? or !.

Because that's what we decided, to make sure people do not mistype a variable and suddenly get symbolicity without even realizing it.  When you type ? or ! you know what you are doing.

**Comment by radumereuta** [comment]
But there are other cases when you just simply miss typed the name of a variable on the right hand side.
I think the current error message is correct, and is more general. There are other cases to consider other than fresh.

**Comment by grosu** [comment]
I don't understand how to make it any clearer than I just did, without saying that 1+1=2.  Let me know what is not clear to you, or otherwise explain clearer what you mean.
