### ISSUE TITLE
unexpected ambiguity reported

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#695]
Let us consider the following definition:

```
module TEST
  syntax Prog ::= Defs "slave" Defs Words "master" Defs Words "endprogram"
                | "master" Defs Words "endprogram"

  syntax Defs ::= List{Def, ""}

  syntax Def ::= IpDef 
               | ":dyn" Id Words ";dyn"  [dyndef]
               > ":" Id Words ";"   [staticdef]

  syntax Words ::= List{Id, ""}
  syntax IpDef ::= "ip" Id Int Int 
endmodule
```

If we parse the program

```
slave
:dyn madyn sub ;dyn
master
endprogram
```

then we get an ambiguity:

```
$ krun ex.test 
<k>
     slave :dyn madyn sub ;dyn blop master : main b ; main endprogram
</k>
[Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
1: Prog ::= Defs "slave" Defs Words "master" Defs Words "endprogram" 
   .Defs slave ((:dyn madyn (sub) ;dyn)) (blop) master ((: main (b) ;)) (main) 
     endprogram
2: Prog ::= Defs "slave" Defs Words "master" Defs Words "endprogram" 
   .Defs slave ((: dyn (madyn (sub)) ;)) (dyn (blop)) master ((: main (b) ;)) (
     main) endprogram
    File: ex.test
    Location: (1,1,9,12)
    Compilation Phase: Ambiguity filter
```

IMHO the second parsing should be removed by the filter because the production [dyndef] has a higher priority than [staticdef].

**Comment by radumereuta** [comment]
Priorities can't disambiguate this case, because the two productions `dyndef` and `staticdef` are not parent and child. In fact they are not even siblings, so not even prefer/avoid would work.

One solution for this case would be to add a follow restriction:
syntax ";" -/- [d].[y].[n]
The second would be to make `dyn` a keyword:
syntax Id ::= "dyn" [reject]

**Comment by dlucanu** [comment]
Strange, in a simplified version of the definition (with only Def and words production) it worked.
I used the second choice and it worked.
Thanks.
