### ISSUE TITLE
Java backend krun runing c semantics and applying unexpected rule problems

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#706]
I got an unexpected result when I used krun to run a c program. 

When I used the java backend krun by using the following command:

```
krun --smt=none --output="pretty" --output-file="ctype.pretty.o" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser "kast --parser ground" -d /home/qangel/project/c-semantics/dist/c11-translation-kompiled ctype.c11-translation --depth=3
```

The final thing in k cell is something like:

```
 listToK (.... ) ~> allocateIncompleteTentatives ~> link ~> cleanup
```

There is no any place in the final result to mention the constructor "completeTagInTags" and I got a correct result from Krun. However, once I set depth equal to 4 as:

```
krun --smt=none --output="pretty" --output-file="ctype.pretty.o" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser "kast --parser ground" -d /home/qangel/project/c-semantics/dist/c11-translation-kompiled ctype.c11-translation --depth=4
```

I got a result show that the final things in k cell is:

```
completeTagInTag ( _23089:CId , _23092:FieldInfo , 
              choice(_23086:Set) ) ~> completeTagInTags ( _23089 , _23092 , 
              _23086:Set[choice(_23086:Set) <- undef] ) ~> 
              allocateIncompleteTentatives ~> link ~> cleanup
```

The problem is that I should get the ListItem inside the body of listToK in step 3 result step by step by applying the following rule and there are actually 5 list items in the body of listToK and I expect that the krun will apply this rule for five times:

```
rule listToK(ListItem(K:K) L:List) => K ~> listToK(L) [structural]
```

; However, because of the step 4, I got the final result after step 6 as:

```
allocateIncompleteTentatives ~> link ~> cleanup
```

It seems to me that the krun does not execute the rules for listToK completely and I believe that the rule I mentioned above for listToK is the only rule which can be applied for the constructor listToK and listToK is not declared as strict.

However, once I do more testing on the krun to the c semantics, I find that the situation is worse than the situation I mentioned above. 

Once the krun load the program into a full configuration, the result of the k cell is that and I got the result by setting krun depth to 0:

```
loadObj (  ) ~> TranslationUnit(...) ~> link ~> cleanup
```

I believe that the first rule the krun will try to apply is the rules for loadObj and the loadObj contractor has the syntax and rules as:

```
syntax KItem ::= loadObj(Bag)
     rule <k> loadObj(<global> G:Bag </global>) => .K ...</k>
          <global> (_:Bag => G) </global>
          when (G =/=Bag .Bag)
          [structural]

     rule loadObj(.Bag) => .K
          [structural]
```

However, when I use the command as follow :

```
krun --smt=none --output="pretty" --output-file="ctype.pretty.o" -cOPTIONS="(SetItem(NOLINK) .Set)" -cOBJ1=".Bag" -cOBJ2=".Bag" --parser "kast --parser ground" -d /home/qangel/project/c-semantics/dist/c11-translation-kompiled ctype.c11-translation --depth=1

```

Then, I try to print out the rule and constraints which krun is trying to apply, I find that the java backend krun is trying to apply the following rule and get a constraint as:

```
     rule completeTagInTags(_, _, .Set) => .K
          [structural]

constraint: 'loadObj((# )(.KList)) =? projection('completeTagInTags(_23067:CId,, _23068:FieldInfo,, _23064:Set))
```

I find this is strange to me. Again, There is no any place in the initial configuration mentioning the constructor  completeTagInTags and the k cell is the only k cell in the whole configuration.

**Comment by liyili2** [comment]
update information:

I think I might know what is the problem now. If I define the syntax of the completeTagInTags as:

```
     syntax K ::= completeTagInTags(CId, FieldInfo, Set)
                | completeTagInTag(CId,FieldInfo,CId)
```

instead of

```
syntax KItem ::= completeTagInTags(CId, FieldInfo, Set)
                | completeTagInTag(CId,FieldInfo,CId)
```

Then there will be a constraint as:

```
'loadObj((# )(.KList)) =? projection('completeTagInTags(_23067:CId,, _23068:FieldInfo,, _23064:Set))
```

Once I define the two constructors as KItem. There will not introduce this constraint and everything looks fine.

**Comment by grosu** [comment]
We should have a decent error message for `syntax K ::= ...`.  Can you please add it to the issues list, in case it is not there already?

Grigore
