### ISSUE TITLE
detecting error message for declare syntax K

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#708]
When someone declare syntax K ::= something in their definitions, we should have an error message to suggest that this is wrong in java backend.

**Comment by yilongli** [comment]
@radumereuta I am not sure what is the right place to put the check. Basically, all I need to do is to throw an error when the user tries to extend sort K.

**Comment by radumereuta** [comment]
It should be here:
org.kframework.compile.checks.CheckSyntaxDecl

**Comment by yilongli** [comment]
fixed via https://github.com/kframework/k/pull/714
