### ISSUE TITLE
Strange non-determinism when I use krun with kompile in java backend

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#721]
If I have the following definition:

```
module TEST

    syntax Type ::= pushTypeDown(Type, KLabel) | "int" | "good" | "start"
    syntax KLabel ::= makeFunctionType(List)

    rule pushTypeDown(int, Lbl:KLabel) => Lbl(int) 

    rule start => pushTypeDown(int,makeFunctionType(ListItem(1)))

    rule makeFunctionType(L:List)(int)
          => good 
          [structural,anywhere]


endmodule

```

Assume that there is no such definition previously kompiled in our directory. If I run the program "start", the output will be:

```
[2, 15.86 ms]
<k>
    makeFunctionType ( ListItem ( 1 ) )(int)
</k>

```

Which is not correct. Now, if I remove the anywhere attribute and compile the definition again without delete the old kompiled file, when I run the program "start", I will get the same result:

```
[2, 15.86 ms]
<k>
    makeFunctionType ( ListItem ( 1 ) )(int)
</k>
```

However, if I remove the kompiled file, and kompile the definition again without anywhere attribute, when I run program "start" I will get the correct output:

```
[3, 17.26 ms]
<k>
    good
</k>

```

If I kompile the definition with the anywhere attribute again without removing the kompiled file, I will get the correct output again:

```
[3, 17.26 ms]
<k>
    good
</k>

```

**Comment by yilongli** [comment]
I have no idea what is going on, so I couldn't fix it. Why would removing/keeping the kompiled file make a difference? @dwightguth Besides, `[anywhere]` is not yet implemented in the Java backend; rules tagged with `anywhere` will be excluded.

**Comment by andreistefanescu** [comment]
@radumereuta just to be sure, is the rule caching handling changed attributes?

**Comment by radumereuta** [comment]
No it doesn't. It's kind of hard to detect those changes, that's why I wanted to make caching optional.
@cos disagreed and said he will take over that part of the code.

**Comment by yilongli** [comment]
`anywhere` is not yet supported, so getting stuck is the expected behavior right now. Except this limitation, this is not a problem in the Java backend but the caching mechanism of parsing. Remove myself from the assignee.

**Comment by cos** [comment]
@liyili2, I haven't gotten to #697 yet, and I will not get to it very soon. In the meantime, simply delete your `*-kompiled` directory.
