### ISSUE TITLE
Causing infinite rewrites in Java backend when we have sequence of function constructors

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#727]
When I have the following set of rules:

```
module TEST

    syntax Type ::= pushTypeDown(Type, KLabel) [function] | "int" | "good" | "start"
    syntax KLabel ::= makeFunctionType(List)

     syntax Type ::= applyTypeFunction(KLabel,Type) [function]

    rule pushTypeDown(int, Lbl:KLabel) => applyTypeFunction(Lbl,int) 

    rule start => pushTypeDown(int,makeFunctionType(ListItem(1)))

    rule applyTypeFunction(makeFunctionType(L:List),int)
          => good

     syntax TypedValue ::= tv(CSize, Type) 
          [klabel('tv), latex(renameTo \\ensuremath{{_}\\mathop{:}{_}})]

     syntax Type ::= "cfg:largestUnsigned" [function]
     syntax CSize ::= Int

     rule N:CSize => tv(N, cfg:largestUnsigned)
          [structural] // for internal computations


endmodule

```

If I run the program "start" in Java backend, it will run infinitely. I ask the java to print out the rule it executes, and I find that the Java backend is trying to execte the last rule again and again on the term: 

```
applyTypeFunction(makeFunctionType(...),int) 
```

However, one can easily that the applyTypeFunction has sort Type and even if I change the sort of applyTypeFunction to KItem, it still tries to apply the last rule. 

However, Once I delete the function label in the applyTypeFunction constructor, it works fine as:

```
module TEST

    syntax Type ::= pushTypeDown(Type, KLabel) [function] | "int" | "good" | "start"
    syntax KLabel ::= makeFunctionType(List)

     syntax Type ::= applyTypeFunction(KLabel,Type)

    rule pushTypeDown(int, Lbl:KLabel) => applyTypeFunction(Lbl,int) 

    rule start => pushTypeDown(int,makeFunctionType(ListItem(1)))

    rule applyTypeFunction(makeFunctionType(L:List),int)
          => good

     syntax TypedValue ::= tv(CSize, Type) 
          [klabel('tv), latex(renameTo \\ensuremath{{_}\\mathop{:}{_}})]

     syntax Type ::= "cfg:largestUnsigned" [function]
     syntax CSize ::= Int

     rule N:CSize => tv(N, cfg:largestUnsigned)
          [structural] // for internal computations


endmodule
```

```
[2, 13.14 ms]
<k>
    good
</k>
```

In c semantics, I definitely have a place which needs a function rewrite to another function and get results, so I want someone to help me to fix this problem.

**Comment by liyili2** [comment]
Actually, all other issues are not that urgent since I have solutions for them, but this one actually block me doing further work.

**Comment by yilongli** [comment]
@grosu @dwightguth Shall we allow extending KLabel like this? If so, why not make it a KItem instead?
`syntax KLabel ::= makeFunctionType(List)`

**Comment by grosu** [comment]
I think we decided to allow it in the concrete syntax, but not in KAST.  The idea is that there is an automatic way to translate it into a KItem, which is what the concrete parser will eventually do.  But in this case, yes, why don't you define a KItem instead, Liyi?  Also, it looks like you want it to be a function.

**Comment by liyili2** [comment]
I think I might be able to do that.

**Comment by yilongli** [comment]
There are at least two things need to be done here:
- figure out the cause of the infinite loop
- clean up the `AddInjection` pass and add defensive code to detect incorrect projection/injection

Since you have found a way to work around, I will leave it for now and get back to it later.
