### ISSUE TITLE
strange behaviour of the backslash character in definitions

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#734]
The following definition

```
module SPEC
  syntax Ids ::= List{Id, "/\\\\"}
  configuration <k> $PGM:Ids </k>
endmodule
```

compiles, but when it is executed on the input "a /\ b /\ c" the following output is displayed:

```
$ krun ex.spec 
<k>
    a/\\ b/\\ c
</k>
```

What is the exact meaning of `\\\\`?

**Comment by radumereuta** [comment]
This happened because of the bug reported in #733. I forgot to escape the separator string when printing to SDF.
I will mark this as duplicate and close it.
