### ISSUE TITLE
IO server looses output messages

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#74]
Compiling and running the following definition

```
module IO
  syntax Exp ::= "start"

  configuration 
    <out stream="stdout"> ListItem("running...") </out>

  rule <out> ListItem("running...") => ListItem("finished") </out>

endmodule
```

we get the following final result:

```
$ kompile io
$ krun
running...<k>
    .K
</k>
<out>
    ListItem(#ostream ( 1 ))
    ListItem(#buffer ( "" ))
</out>
```

We see the the last content of the output cell is lost somewhere on the way.
I had also a case when the message from the final configuration didn't leave the output cell, but I couldn't reconstruct it on a minimal example.

**Comment by dwightguth** [comment]
Since it's not really supported behavior to match on anything in an output stream cell, I am going to close this.

**Comment by grosu** [comment]
OK and thanks @dwightguth , but can you add this to the "manual", to make sure we address it properly when the time comes?  Don't spend time with it, just copy and paste it in to the wiki, maybe under some section called "Unsupported features".
