### ISSUE TITLE
support for associative matching on list in the Java backend

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#757]
According to Grigore, we may only need to support associative matching on KList, since any other user-defined associative list, say `List{Sort}{"@"}{"."}`, should become `@(KList)` in KAST, that is, label `@` applied to a KList.

However, normal list and KList are represented differently in the Java backend KIL right now. We need to consider how to unify them, given that we take the above approach.

For those who request this feature, please provide examples and explanation that why associative matching is essential in such case.

**Comment by bmmoore** [comment]
From Li's email about the C semantics, I think matching individual items from the end of a list is an important special case, even if we don't think of it as full AC matching.
