### ISSUE TITLE
krun --prove does not work as expected

### ISSUE THREAD

**Issue by andreistefanescu** [kframework/k-legacy#765]
This is the error krun throws with --prove
[Error] Critical: Configuration variable missing: $PGM
    File:
/Users/andrei/andrei_k/samples/java_rewrite_engine/tutorial/2_languages/1_simple/1_untyped/simple-untyped.k
    Location: (314,42,314,52)
It can be circumvented by using -cPGM=".". I am assigning it to @dwightguth because of his work on the options.

**Comment by dwightguth** [comment]
@andreistefanescu is this still happening or did this get fixed?
