### ISSUE TITLE
ktest/jenkins output format

### ISSUE THREAD

**Issue by andreistefanescu** [kframework/k-legacy#767]
I would like ktest/jenkins to output the exact commands needed for reproducing a failing test. For example this output http://office.runtimeverification.com:8080/rv-jenkins/job/k-framework-pull-requests/232/testReport/_samples_wcet_wcet/k/timers/ does not specify which backend is used (I can guess from the error output in this case, but that is not the point), and what options. @dwightguth @grosu what do you think?

**Comment by osa1** [comment]
@andreistefanescu do you still need this?
