### ISSUE TITLE
Destructors for Map and Set in Java backend

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#768]
I played a bit with the java backend and I noticed that the data structures Map and Set have no destructors, hence it is difficult to check some properties for or define operations over environments, stores, and other semantical ingredients modelled with these data structures.
I am not sure how difficult is to define destructors for them now, but I think that it will be helpful to have at least conversions from these data structures to lists, which can be easier handled.

**Comment by traiansf** [comment]
I agree with @dlucanu on this. Although we cannot currently iterate over sets and maps, we can do it over lists, so having a way to associate lists to sets and maps is basically providing iterators over them.  This would probably also be an efficient K pattern to achieve iteration over sets, maps, and bags.

**Comment by grosu** [comment]
I agree, too.  And yes, I think we should map these operations to collections and iterators over them in Java; that's the most efficient way to do it and that's how we would implement them anyway if we were to iterate over maps, sets, etc.

Grigore

**Comment by yilongli** [comment]
How does the operation that iterates over list/set/map look like?

**Comment by andreistefanescu** [comment]
We already have this capability. For example, one can define size as
follows:
syntax Int ::= size(Map)
rule size(_ |-> _ M:Map) => 1 +Int size(M)
rule size(.Map) => 0
We do not support AC matching, but we can iterate as long as the result
does not depend on the iteration order.
