### ISSUE TITLE
Create dynamic attributes

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#771]
We are putting in place a static attribute system for terms to achieve one of our deliverables. I talked with @cos and he wants a dynamic system that allows you to match and rewrite attributes. We will need to talk about this when the time comes to determine how we want to integrate the two features, but he asked me to create this task to track it so I am assigning it to him.

**Comment by radumereuta** [comment]
I want this feature, since I would like to match on location information for disambiguation purposes.
