### ISSUE TITLE
bad behavior when useing krun --version option.

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#780]
After I compile K in the new version, when I use "krun --version" in a directory without K definitions, it will show me the following error message:

```
qangel@qangel-Satellite-S855:~/project/k-unified$ krun --version
[Error] Critical: Could not find a compiled definition. Use --directory to
specify one.

```

If I use krun --version in a directory which contains a K definition, it will show me the following message:

```
qangel@qangel-Satellite-S855:~/project/k-unified/bin$ krun --version
K-framework nightly build.
Git Revision: 336be29
Build date: Sun Aug 3 21:58:01 CDT 2014

```

**Comment by dwightguth** [comment]
Fixed #783
