### ISSUE TITLE
krun --- help message is messed up

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#79]
This is the explanation of the --pattern option.  I cannot make much sense out if it:

Specify a term and/or side condition that the
                                 result of execution or search must match in
                                 order to succeed. Return the resulting matches
                                 as a list of substitutions.rch must match in
                                 order to succeed. Return the resulting matches
                                 as a list of substitutions. In conjunction
                                 with it you can specify other 2 options that
                                 are optional: bound (the number of desired
                                 solutions) and depth (the maximum depth of the
                                 search).

**Comment by daejunpark** [comment]
Fixed typo: 5fe62325ee07b0a106572c1b1a997820c3fe88e0
