### ISSUE TITLE
ktest --- skip option does not work when used in config.xml

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#81]
I have the following test in a config.xml file:

  <test
      definition="../simple-typed-static.k"
      programs="../../../../2_dynamic/exercises/exercise_2/programs/"
      extension="simple"
      results="."
      skip="pdf"
  />

The skip option is completely ignored.

We have two options here: either we consider the skip option as well in config.xml files, or otherwise we disallow it and report an error message when one uses it.

**Comment by andreiarusoaie** [comment]
It should work now. However, if you run something like: 

ktest tests/config.xml --skip="kompile" 

This will override whatever skip option is given in the XML.
