### ISSUE TITLE
ktest --- error message when config.xml does not conform

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#82]
It appears that config.xml must contain a top-level <tests>...</tests> cell.  If you only want to test one test, then you may be tempted to just include that, without a tests cell: <test> ... </test>.  I actually just did that by mistake.  ktest did not complain, it parsed everything and started working, but it completely ignored my test.  We should either accept only one test, or otherwise we should give an error message if the config.xml file does not have a top tests cell.

**Comment by andreiarusoaie** [comment]
Grigore, but this is how xml works: you must have a root tag.In our case that tag must be <tests>, not <test>. If you want to test a single <test> then you have to wrap it into <tests>. 
Actually, when I 'designed' this I thought that  having a root <tests> all the time which contains one or more <test> is quite uniform.

**Comment by grosu** [comment]
But only one test is also a tag, so one may think, like a I did, that it were enough.  So I found it strange that everything worked but 0 programs were tested.  All I'm saying here is that an error message should be reported if the root tag is not "tests" (or, alternatively, to also allow "test" to be a root tag, but this probably requires more coding.

**Comment by andreiarusoaie** [comment]
Ok, ktest throws an error. I haven't investigated why it does not run any programs yet, but from now on this should not happen anymore.
