### ISSUE TITLE
Wrong configuration found

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#823]
Kompile currently takes the first configuration found in a breadth-first traversal of the imports. If you define your configuration too far from the main module, the one from DEFAULT-CONFIGURATION will be used instead. What policy do we actually want?

```
module TEST
imports A

syntax T ::= "a" | "b"
rule <cell>a => b</cell>
endmodule

module A
imports B
endmodule

module B
imports TEST-CFG
endmodule

module TEST-CFG
configuration <k>.K</k><cell>$PGM:T</cell>
endmodule
```

**Comment by traiansf** [comment]
This issue has resurfaced several times already.  Until now, the resolution was that, given the important role it plays,  the configuration should be close to the main module.  

A potential solution would be that the default configuration is tagged as such and only used if no other configuration can be found.  Altering the existing code to do that should be pretty straight-forward.

Nevertheless, if working with multiple configuration, races may appear between them if they are at the same level of inclusions.
