### ISSUE TITLE
no filename, location information available in the Java backend

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#840]
I just realize that the attributes of a `java.kil.Rule` do not contain filename, location information anymore. This is very inconvenient for debugging the Java backend. Besides, the semantic debugger will need such information as well. Anybody knows what happens? @dwightguth @andreistefanescu

**Comment by dwightguth** [comment]
ASTNode now stores location information as fields and not attributes. Looks
like I missed a place where it should have been copied. I suggest you check
to make sure this is still occurring in the latest unified-builtins (it
might not be, I made a change that might have fixed it) and if it is,
modify KILtoBackendJavaKIL.

**Comment by yilongli** [comment]
fixed via https://github.com/kframework/k/pull/847
