### ISSUE TITLE
getLocation and getSource functions return null when I try to krun a program

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#845]
I am trying to test my c program by running krun and finding a sequence of rules it executed. In order to do that, I tried to insert a line as follow between line 261 and 262 in SymbolicRewriter class computeRewriteStep function

```
                    System.out.println(rule.getSource()+","+rule.getLocation());
```

The line 261 and 262 are:

```
                    appliedRules.add(rule);
                    if (indexingStats){
```

After that, I krun a c program and wait for the sequence of executed rules, but I get the result as:

```
null,null
```

instead of showing me the file name and location of the rules. I asked @dwightguth and he suggests that @yilongli needs to make a simple fix to insert the info into the new getLocation and getSource functions in Java Backend.

**Comment by yilongli** [comment]
fixed via https://github.com/kframework/k/pull/847
