### ISSUE TITLE
`AlphanumComparator` seems a fork of a third-party project

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#856]
if this is the case, @yilongli, could you move this into a separate project, and have it linked through maven?

**Comment by yilongli** [comment]
I would be grateful if someone familiar with maven can help me solve this. Otherwise, I will get to it when I am available.

**Comment by dwightguth** [comment]
Cosmin, I okayed this knowing that going in because it was the best we
could do with the old build system. Assign this issue to me and I'll make
sure it gets done after the maven migration.

**Comment by dwightguth** [comment]
@cos how do you think we should handle this? As far as I can tell there is no package in maven central for this code, and I personally think that creating an entire jar for it is overkill.

**Comment by cos** [comment]
we're adding our copyright claim on other people's code.... 
`// Copyright (c) 2014-2015 K Team. All Rights Reserved.`
what does this class do actually (the javadoc is not clear)?

**Comment by dwightguth** [comment]
Yes, I'm aware at the very least that that copyright notice should be removed. We will do that regardless of the ultimate status of this file. But its purpose is to create an ordering for strings that orders "a10b" after "a2b"

**Comment by cos** [comment]
I think we should move this into `org.framework` hierarchy (maybe as an inner class), and add very explicit comments around the copied code stating its origin.

**Comment by radumereuta** [comment]
I think the same issue applies to `org.kframework.utils.algorithms.SCCTarjan.java`.

**Comment by dwightguth** [comment]
It doesn't actually. At the time, we communicated with the owner of that file and he released it into the public domain. So I added a copyright notice to the top copyrighting the derivative work consisting of the file with a copyright notice at the top. It's recursive, but legitimate. We don't need to do anything special there because it's not under copyright by anyone except us.
