### ISSUE TITLE
label hybrid doesn't work in Java backend

### ISSUE THREAD

**Issue by liyili2** [kframework/k-legacy#859]
If I have the following definition:

```
module TEST

   syntax KItem ::= varg(K) [hybrid, strict]

   syntax KResult ::= Int

   syntax KItem ::= "start" | con(K) [strict]

   rule start => con(varg("a"))

   rule S:String => 1

   rule con(K:KResult) => .K

endmodule
```

When I run the program "start", I get the following result:

```
<k>
    varg ( 1 ) ~> con ( HOLE )
</k>
```

However, since the hybrid label means that the constructor can act like a KResult term if the argument is KResult, I will expect the following result:

```
<k>
    .K
</k>
```

**Comment by yilongli** [comment]
I thought the `hybrid` attribute was deprecated. Is this the case? @grosu

**Comment by grosu** [comment]
I don't remember if `hybrid` was deprecated or not.  Anybody with a better memory?  Anyway, in case it was deprecated, then a warning or error message  must be reported.

**Comment by dwightguth** [comment]
I remember you didn't want it and I did, Grigore. I have a guess as to why
this is occurring though. Yilong, check the pass that deals with hybrid to
see if the generated rules have location information. If they don't, assign
them the location of the production tagged with hybrid and see if that
solves the problem.
