### ISSUE TITLE
Visitor is wrong w.r.t. copying attributes.

### ISSUE THREAD

**Issue by radumereuta** [kframework/k-legacy#878]
Right now, if I have a term of the form: `A(B(X))`, and I want to eliminate `B`, then `X` will inherit the attributes of `B`. @dwightguth did this for the case when we have attributes for a cast, but there are cases where this is completely wrong. For example the location information will be wrong if `B` is a `bracket` production. Such removals are quite frequent in the front-end.

Instead of copying the arguments from a the child, the Cast case should be handled separately. There are two places where Casts are being dissolved:

1 CorrectCastPriorityFilter:50
This is the case when the user casts a variable. The type inference algorithm needs all variables to have their sort locally, so I'm dissolving the Cast and copy all the information into the variable. Please add the line:

```
var.copyAttributesFrom(cst);
```

2 RemoveSyntacticCasts
Final removal of Casts from the AST. No matter what term is casted, the attributes should be copied to the child and the Cast node should be eliminated.

@dwightguth I tried to follow your instructions, but I failed to make it work. Not to mention that I run into krun issues with the external parser `kast.bat --parser rules`. I think you have a hack that recognizes `kast --parser rules` that short circuits the external call, but only works on linux.

**Comment by dwightguth** [comment]
Fixed #905
