### ISSUE TITLE
should get rid of the dist folder

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#90]
As Stefan suggested and several of us gladly approved, we should get rid of the dist folder and move everything inside it one level higher.  This way, the distribution and the developers' directories will have exactly the same structure, the only difference being that the latter will have one more folder with the code.

Is this change something git can handle smoothly without lots of ocnflicts, or we should better all commit everything we have and then do it during the K meeting when nobody works on it?

I am particularly concerned because I have some files in my k directory which are not committed in the repostitory and which I do not want to commit (HW solutions, e.g.).  Will git be smart enough to move those files higher in the file hierarchy as well, or it will report conflicts?

**Comment by ciobaca** [comment]
git can handle renames better than svn, but since we don't have a lot of
experience with it, I suggest everyone to commit everything beforehand.

In particular, in your case, you will need to manually copy the homework
from k/dist/examples/hw into k/examples/hw after you git pull.

Cheers,
Stefan

**Comment by adamsmd** [comment]
Can we close this issue since we have now done the move described?
