### ISSUE TITLE
Invalid config files in the repository

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#911]
These files in the repository are invalid ktest config files. Probably left over from previous versions.

```
./tests/examples/prog-equiv/config.xml
./tests/examples/prog-equiv/imp-sym/config.xml
./tests/examples/exp/untyped/environment/config.xml
./tests/examples/exp/type-inference/config.xml
```

Maybe we should fix or remove them.

**Comment by dwightguth** [comment]
The entire tests/examples directory should be removed, if I recall
correctly.

On Sun, Aug 31, 2014 at 7:03 AM, Ömer Sinan Ağacan <notifications@github.com

**Comment by osa1** [comment]
Apparently those files are removed.
