### ISSUE TITLE
refactor methods with 100+ lines

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#92]
We have several 100+ lines methods, which are impossible to understand, modify, maintain, and fix, and even read.

One example is `execute_Krun` method, which is 438 lines long, with a huge if-then-else block with 6 levels of indentation(nested if-then-elses). `normalExecution` in the same module is 140 lines long. They're probably sharing some huge amounts of code but that code is just duplicated.

`kompile` is another method, which is 214 lines long.

Here's an exercise to see how hard it is to understand codebase right now: Try to figure out what is the simplest way to parse a user program using a definition saved in a known point in hard drive.

Also, once user program parsed, try to print it in colorful, indented way(e.g. pretty print, like krun does).

---

I'm assigning this to myself, if no one objects to this I'll go and refactor this methods.

**Comment by traiansf** [comment]
The simplest way to find how to parse a program is to ask Radu what is the simplest method to call :-)

For pretty printing, one needs to talk with Stefan :-)

Joking aside, I think you are right Omer.  kompile and krun are huge and poorly documented and if you take it on you to refactor them, this would be of great help to everyone.

**Comment by ciobaca** [comment]
Omer, I full-heartedly agree about kompile and krun. I ran into both issues
at some point. If you decide to refactor them, please make it a mechanical
refactoring so that nothing breaks ;-)

Cheers,
Stefan
