### ISSUE TITLE
ktest --- misbehaving missing programs and results entries in config.xml

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#93]
With the new ktest, we should allow one to drop the "programs" and "results" attributes in tests in config.xml

For example, this test

  <test
      definition="simple-typed-static.k"
      programs="../../programs/"
      extension="simple"
  </test>

finds no results (the results are all in the same folder with the condig.xml, while this one

  <test
      definition="simple-typed-static.k"
      programs="../../programs/"
      results="."
      extension="simple"
  </test>

finds the results.

With the current approach, programs and results attributes which are just a "." are completely useless, so we should not force people write them.

**Comment by grosu** [comment]
Daejun and I had a discussion about this issue today and it turned out it was a misunderstanding on my side.  I forgot about the (nice!) feature that we can provide a list of folders as programs or as results, e.g.

programs="folder1 folder2 folder3"
results="folder1 folder2"

If we want to include the config.xml folder as well, then we have to list "." as one of the folders.

Missing a programs or results entry in a test should be therefore equivalent to providing an empty list of foders, and NOT as providing the folder ".".

So the current behavior is correct, but I keep it as a bug until Daejun checks that a missing programs/results entry is equivalent to programs=""/results="".  Once you check that, Daejun, then please turn this issue into an enhancement instead of a bug, where the enhancement should be that an error message is reported when and extension entry is provided while the programs entry is empty.

**Comment by daejunpark** [comment]
@grosu One thing in my head: Is it consistent with the 'single job mode'? If given '/path/to/lang.k', the absence of --results or --programs means the default '/path/to'. Should we also fix that?

**Comment by daejunpark** [comment]
@grosu 

~~What if both `--programs='rootDir1 rootDir2'` and `<test> ... programs='dir1 dir2' … </test>` is given at the same time?~~

~~My suggestion:~~

~~I'd say we need two separate options:~~
~~--root_program: both single job and batch modes~~
~~--programs: only single job mode (which is given at config.xml for batch mode)~~
~~This will also simplify the help message.~~

~~Similar with --results.~~

Also it would be better when the separator is not a blank ' ' but a colon ':' or a comma ',' in case of a path containing a whitespace. For example, `--programs='dir1,dir2'`.

**Comment by daejunpark** [comment]
@grosu 

For the consistency between single job and batch modes, same policy is applied both to --programs/--results options at command-line and programs/results attributes at config.xml. But, at batch mode, --programs/--results options are not following the policy because it has different meaning, that is, it stands for --program-root/--result-root.

For example, the following pairs are equivalent:

```
$ ktest lang.k
$ ktest lang.k --programs "" --results ""
```

```
$ ktest /path/to/config.xml
$ ktest /path/to/config.xml --programs "/path/to" --results "/path/to"
```

```
<test
  definition=lang.k
/>
<test
  definition=lang.k
  programs=""
  results=""
/>
```

Also, error messages are generated for the followings:

```
$ ktest lang.k --programs "dir"
[Error] Critical: You have to provide a list of extensions by using --extension option, when --programs is given.
```

```
$ ktest lang.k --extension "lang"
[Error] Critical: The given --extensions option has no effect. You might miss --programs option.
```

```
<test
  definition=lang.k
  programs="dir"
/>
[Error] Critical: You missed 'extension' attribute: <test definition=lang.k programs=dir />
```

```
<test
  definition=lang.k
  extension="lang"
/>
[Error] Critical: You cannot use 'extension' attribute without 'programs' attribute: <test definition=lang.k programs= />
```

**Comment by grosu** [comment]
Thanks!  Three comments on your error message:

fslwork$ ktest programs_and_results/config.xml --skip "kompile pdf"
Buildfile: programs_and_results/config.xml
[Error] Critical: You cannot use 'extension' attribute without 'programs' attribute: <test definition=kool-untyped.k programs= />
    File: 
    Location: 

1) Make sure error messages never exceed 80 characters.

2) I think your error message misses some articles.  English speakers, please react when you see such things.  How about the message "The "extension" attribute requires a "programs" attribute."

3) Why don't you also output a File and a Location?

Thanks,
Grigore

**Comment by grosu** [comment]
Daejun,

I think you should also report a warning (not error) when people forget to specify a results folder.  Sometimes this is intentional, but most of the time it is because people forget to put one.

**Comment by daejunpark** [comment]
@grosu,

A warning message is now reported as follows:

Single job mode:

```
[Warning] A '--results' option was missed.
```

Batch mode:

```
[Warning] A 'results' attribute was missed: <test definition=imp.k
          programs=. />
```

For the current tests/config.xml,

```
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/1_lambda/lesson_1/lambda.k
          programs=tutorial/1_k/1_lambda/lesson_1 />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/1_lambda/lesson_2/lambda.k
          programs=tutorial/1_k/1_lambda/lesson_1 />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/1_lambda/lesson_3/lambda.k
          programs=tutorial/1_k/1_lambda/lesson_1 />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/1_lambda/lesson_4/lambda.k
          programs=tutorial/1_k/1_lambda/lesson_1 />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/1_lambda/lesson_5/lambda.k
          programs=tutorial/1_k/1_lambda/lesson_1              
          tutorial/1_k/1_lambda/lesson_5 />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/1_lambda/lesson_6/lambda.k
          programs=tutorial/1_k/1_lambda/lesson_1              
          tutorial/1_k/1_lambda/lesson_5              
          tutorial/1_k/1_lambda/lesson_6 />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/1_lambda/lesson_7/lambda.k
          programs=tutorial/1_k/1_lambda />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/1_lambda/lesson_8/lambda.k
          programs=tutorial/1_k/1_lambda />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/1_lambda/lesson_9/lambda.k
          programs=tutorial/1_k/1_lambda />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/3_lambda++/lesson_1/lambda.k
          programs=tutorial/1_k/1_lambda tutorial/1_k/3_lambda++ />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/3_lambda++/lesson_2/lambda.k
          programs=tutorial/1_k/1_lambda/lesson_1 />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/3_lambda++/lesson_3/lambda.k
          programs=tutorial/1_k/1_lambda />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/3_lambda++/lesson_4/lambda.k
          programs=tutorial/1_k/1_lambda tutorial/1_k/3_lambda++ />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/3_lambda++/lesson_5/lambda.k
          programs=tutorial/1_k/1_lambda tutorial/1_k/3_lambda++ />
[Warning] A 'results' attribute was missed: <test
          definition=tutorial/1_k/3_lambda++/lesson_6/lambda.k
          programs=tutorial/1_k/1_lambda tutorial/1_k/3_lambda++ />
[Warning] A 'results' attribute was missed: <test
          definition=tests/regression/issue552/issue.k programs= />
[Warning] A 'results' attribute was missed: <test
          definition=tests/regression/issue529/issue.k programs= />
[Warning] A 'results' attribute was missed: <test
          definition=tests/regression/defaultTerms1/issue.k programs= />
[Warning] A 'results' attribute was missed: <test
          definition=tests/regression/mapitem2klabel/issue.k programs= />
[Warning] A 'results' attribute was missed: <test
          definition=tests/regression/issue403/issue.k programs= />
[Warning] A 'results' attribute was missed: <test
          definition=tests/regression/issue425/issue.k programs= />
[Warning] A 'results' attribute was missed: <test
          definition=tests/regression/issue466/issue.k programs= />
[Warning] A 'results' attribute was missed: <test
          definition=tests/regression/issue482/issue.k programs= />
[Warning] A 'results' attribute was missed: <test
          definition=tests/regression/issue483/issue.k programs= />
```
