### ISSUE TITLE
the check of the cell sorts is too strict

### ISSUE THREAD

**Issue by dlucanu** [kframework/k-legacy#930]
The compilation of the following module

```
module TEST
  syntax ExpA ::= Id | Int | ExpA "+" ExpA
  syntax ExpB ::= ExpA | ExpB "*" ExpB

  syntax Id ::= "a"

  configuration
     <k> $PGM:K </k>
     <mycode> a + 2 </mycode>

  rule <k> E:ExpB => .K ...</k>
       <mycode> _ => E </mycode>

  rule <k> .K </k>
       <mycode> E:ExpB => E * E </mycode>

endmodule
```

reports the following error:

```
$ kompile test.k 
[Error] Critical: Wrong type in cell 'mycode'. Expected sort: ExpA but found
ExpB
    Source: File: /Users/dlucanu/teste-temp-k/sorts-in-config/test.k
    Location: (15,17,15,23)
```

We must decouple the declaration of the cell sort from that of the cell term in the initial configuration.
For instance, the user should be able to specify that the sort of the cell <mycode> is ExpB (or even K) but in the initial configuration this cell includes a term of sort ExpA (or Id, or Int, ...).

Is it a way to do that now?

**Comment by radumereuta** [comment]
That's actually the expected behavior.
You can bypass this check, or refine it, by casting the terms.

In this case you can either type the configuration cell like `<mycode> a + 2 :>ExpB </mycode>`
or bypass the type checking in the rule like `<mycode> (E:ExpB => E * E):>ExpA </mycode>`.
