### ISSUE TITLE
krun lib error?

### ISSUE THREAD

**Issue by andreiarusoaie** [kframework/k-legacy#94]
It seems that krun has some strange behaviors when running programs, namely it returns either an error, either it... works:

$ krun programs/sumn.cink -cIN="ListItem(#symInt(n))" -cPC="true" --search --bound 3
Krun was executed with the following arguments:
syntax_module=CINK
main_module=CINK
compiled_def=/Users/dlucanu/cink/basic/cink-kompiled

Warning: Maude produced warnings or errors.
libc++abi.dylib: terminate called throwing an exception

$ krun programs/sumn.cink -cIN="ListItem(#symInt(n))" -cPC="true" --search --bound 3
Search results:

Solution 1, State 1:
<path-condition>
    (0 <=Int #symInt(n)) ==Bool false
</path-condition>
<T>
    <in>
        ListItem(#buffer ( "\n" ))
    </in>
    <out>
        ListItem(#buffer ( "" ))
    </out>
    <control>
        <k>
            0 ;
        </k>
        <fstack>
            .List
        </fstack>
        <env>
            main |-> #symLoc(1)
        </env>
    </control>
    <genv>
        main |-> #symLoc(1)
    </genv>
    <store>
        #symLoc(1) |-> lambda ( .Decls @ (((((((((int n) ;) ((int i) ;)) 
          ((int sum) ;)) ((cin >> n) ;)) ((sum = 0) ;)) ((i = 0) ;)) (while (
           (i <= n) ) ({ (((sum = (sum + i)) ;) ((i = (i + 1)) ;)) }))) (
          return 0 ;)) )
        #symLoc(2) |-> #symInt(n)
        #symLoc(3) |-> 0
        #symLoc(4) |-> 0
    </store>
</T>

I don't know which one of us should work on this. Who's in charge of krun now?

**Comment by dlucanu** [comment]
I got this error several times after I upgraded the OS on my Mac. 

I am thinking whether the strange behaviour of ktest on the fsl machine has the same cause.

**Comment by dlucanu** [comment]
This error became annoying for me. On my Mac I got it in this afternoon very often, even for programs that in the morning run ok. It seems a problem of resources (memory?) because I moved on the fmse machine and the same examples work fine.

**Comment by ericmikida** [comment]
I'm in charge of krun right now so I'll start looking into this. I haven't experienced it yet myself, but I'll try to reproduce it.

**Comment by ericmikida** [comment]
Has anyone been able to more reliably reproduce the bug? I have not been able to get the bug to show up at all...I talked to @daejunpark who had some methods for getting it to show up on fslexp and none of them seemed to work for me, so maybe it's specific to the certain machines?

**Comment by dlucanu** [comment]
It seems to be specific to certain machines, more precise it is depending on the resource available at the execution time. I say that sometimes repeating the command it works. 
Here are the characteristics of my machine:

Processor  2.4 GHz Intel Core 2 Duo
Memory  4 GB 1067 MHz DDR3
Software  OS X 10.8.5 (12F45

Here is scenario that always produce this error on my machine:
- go to cink-semantics/basic/
- compile cink with the symbolic backend

$ kompile cink --backend=symbolic
- execute krun with the following command:

$ krun programs/sumn.cink -cIN="ListItem(#symInt(n))" -cPC="true" --search --bound 7

Here is the error I get:

Krun was executed with the following arguments:
syntax_module=CINK
main_module=CINK
compiled_def=/Users/dlucanu/cink-semantics/basic/cink-kompiled

Warning: Maude produced warnings or errors.
libc++abi.dylib: terminate called throwing an exception

I hope this help you.
