### ISSUE TITLE
libz3.so requires unnecessarily recent glib

### ISSUE THREAD

**Issue by bmmoore** [kframework/k-legacy#945]
The newest included linux 64-bit libz3.so requires glibc 2.14 - and only because it's somehow linking to a newer symbol version of memcpy. This is too new for the current Debian stable or RHEL 6 (which will be supported for at least six more years). Here's the symbol and a link

```
$ objdump -T libz3.so | grep GLIBC_2.14
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.14  memcpy
```

http://www.win.tue.nl/~aeb/linux/misc/gcc-semibug.html

Where did you get this version? One I built myself doesn't need glibc newer than 2.3.3, so that memcpy is quite an outlier (maybe some of the C++ stuff would give tighter requirements).

**Comment by dwightguth** [comment]
Fixed #947
