### ISSUE TITLE
Separate Cell2DataStructure into Java-backend-specific and non-backend-specific parts

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#952]
This pass is run on all backends, however, it currently has a compile time dependency in the java backend. This needs to change in order to support the modularity of the framework. I need someone to separate this pass into two passes, one which runs on all backends, and one which runs only on the Java backend. The former of these two should not reference anything in the org.kframework.backend.java package.

**Comment by yilongli** [comment]
fixed in https://github.com/kframework/k/pull/960
