### ISSUE TITLE
ktest -- on multiple results folders

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#96]
It is very nice that we allow to pass multiple results folders with the "results" entry in config.xml!  For example:

...
  <test ...
    results="folder1 folder2 folder3"
  ...>
...

However, we currently use those directories as a set, not as a list.  In other words, if you have the same pgm.lang.out file in both folder1 and folder2, ktest will pick one of them randomly when testing pgm.lang.

What we should do here is to only consider the latter.  In other words, we should allow results appearing in latter results folders to override previous results.  This will help with a common case, where we extend or modify a language and we expect different results for the same programs when executed with the extended language.  If we have the above, then all we need to do is to add the new results of the programs which have a different behavior with the new definition and that's it.

Let me be more specific.  SIMPLE's exceptions suck in the definition in the tutorial, in that functions do not declare what exception they can throw (like in Java).  Because of that, when we execute program 

k/dist/tutorial/2_languages/1_simple/2_typed/programs/exceptions/exceptions_02.simple

with the typed version of SIMPLE dynamic, we get the result 7, although the program should get stuck before that, because the program is 

void main() {
  try {
    foo();
  }
  catch(int e) {
    print(e,"\n");  // should print 7
  }
}

void foo() {
  try {
    throw 5;
    print(17);      // should not be printed
  } catch(int e) {
    throw e + 2;    // throws 7
  }
  throw 1;          // should not be reached
}

So exceptions_02.simple.out in the current definition is 7.  However, once one fixes it, e.g. as part of exercise 2, the exceptions_02.simple.out file will be empty.  Naturally, I'd like to test the new definition using the config.xml file:

  <test
      definition="simple-typed-dynamic.k"
      programs="../../../../programs"
      extension="simple"
      results="../../../results ."
      exclude="dekker"
      skip="pdf">
  </test>

So it will run the programs in the original definition and will check the results from there (../../../results", exept for the overridden ones in the current folder "."

**Comment by grosu** [comment]
Daejun, this is still an important enhancement, so please get to it once you fix the bugs.

**Comment by grosu** [comment]
Daejun, I know you are frustrated with that non-deterministic bug of ktest.  However, it would be great if you can find a small break to take care of issue #96.  This would help enormously with creating the configuration files of the languages in the tutorial.  Right now, I'm assuming that #96 is solved and live with the fail reports, but I am afraid I may miss real failures because of this.  Thanks.

**Comment by andreiarusoaie** [comment]
Daejun, this is not that hard to implement; You can take a look at extensions or excluded programs.

**Comment by daejunpark** [comment]
@grosu 

One thing to clarify:

When the last directory has a *.out file but no *.in file, what should ktest do?
- the previous directory is searched.
- no *.in file is considered.

For example,
config.xml:

```
<test ... results="/path1 /path2" ... />
```

directory structure:

```
/path1/pgm.in
/path1/pgm.out

/path2/pgm.out
```

Then, which one should ktest consider? either

```
/path1/pgm.in
/path2/pgm.out
```

or

```
(no *.in)
/path2/pgm.out
```

The current implementation is the former.
Please let me know if you want the latter.

**Comment by andreiarusoaie** [comment]
I find your 'latter' proposal a bit confusing for users. I think that *.in and *.out  files should be always grouped in the same folder, not in different folders. 

However I'm wondering if we want to share *.in or *.out files in the sense that we want to have tests with the same *.in and multiple *.out files (or the reverse).  But again, this may be a bit too advanced for `ktest` users.

**Comment by grosu** [comment]
We definitely want the former!  So have you implemented it already?

Grigore

**Comment by grosu** [comment]
Wonderful, thanks Daejun!  I just tested it on all lessons in tutorial/1_k/1_lambda.  Please go ahead and run ktest/tests/config.xml in each of those lessons, and also take a look at the config.xml files, to see how they evolve as one's language evolves.   Also, this will warm you up for the next step: nested config.xml files :-)

Grigore
