### ISSUE TITLE
A function rule is not applied in pattern-matching backend, especially when using K-FUNCTIONAL-VISITOR

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#976]
@yilongli 

A function rule is not applied in `--pattern-matching` backend.

In the following example, I've used `K-FUNCTIONAL-VISITOR` to replace `Id`s in a given term. It seems that a reducible functional term generated by the replacement is not considered as a function rule evaluation.

Suppose that `a.k` is given as follows: (sorry, but it's my best to minimize the example.)

```
require "modules/k-functional-visitor.k"

module A



imports K-FUNCTIONAL-VISITOR

syntax PseudoCodes ::= PseudoCode PseudoCodes
                     | PseudoCode
syntax PseudoCode  ::= "Let" Id "=" K ";" [seqstrict(2)]
                     | "Return" K ";" [seqstrict(1)]

rule PC:PseudoCode PCs:PseudoCodes => PC ~> PCs

rule Let X:Id = V:KResult; ~> PCs:PseudoCodes 
  => #visit(PCs, '@Replace`(_`,_`), V, '_==K_, X)
//                   
syntax KItem ::= "@Replace" "(" K "," K ")" [function]
rule @Replace(_, K) => K




syntax KResult ::= Val

syntax Exp ::= Val
             | Id

syntax Var ::= String
syntax Val ::= Int

syntax Val ::= "@desc" "(" Map ")"

syntax Exp ::= Exp "." Var [function]
rule @desc(X |-> V:Val _) . X => V



syntax KItem ::= "run"

syntax Id ::= "$desc"
rule run
  => Let $desc = foo;
     Return $desc."x";

syntax KItem ::= "foo"
rule foo => @desc("x" |-> 1 "y" |-> 2)



endmodule

```

Then, the `pattern-matching` backend gets stuck at the reducible functional term: `@desc( "x" |-> 1 "y" |-> 2 ) . "x"`, which should have been reduced to `1`.

```
$ cat 1.a
run

$ krun --pattern-matching 1.a
[7, 32.31 ms]
28.48 ms(mc=3.185 ms, eval=9.411 ms[0.000 ns, 9.304 ms], rew=14.50 ms) + 0.000 ns
870.0 μs
0.000 ns
<k>
    @desc ( 
        "x" |-> 1
        "y" |-> 2 ) . "x" ~> Return HOLE ;
</k>
```

I've tried to find why it happens, but failed. Could you please fix this problem and/or explain why it happens? Thanks in advance!

**Comment by yilongli** [comment]
The problem is that the `BuiltinVisitor` is not very well-tested. It was unable to evaluate `@desc ( "x" |-> 1 "y" |-> 2 ) . x` properly, which is resulted from substituting `$desc` from `$desc."x"` with `@desc ( "x" |-> 1 "y" |-> 2 )`.

**Comment by daejunpark** [comment]
Thanks @yilongli ! But I'm still wondering why this problem happens only in pattern-matching backend, not in unification-based java backend. Is the `BuiltinVisitor` specific for the pattern-matching backend?

**Comment by yilongli** [comment]
No, the `BuiltinVisitor` is not specific to the option `--pattern-matching`. I have no idea why rewriting with unification can succeed without further investigation. If you really want to look into this problem, you can set up a breakpoint in `BuiltinVisitor#visit(Term)` and take a look at the implementation of `PrePostTransformer`. That is all you need to understand this bug.
