### ISSUE TITLE
Java AWT/Swing random activation

### ISSUE THREAD

**Issue by cos** [kframework/k-legacy#982]
Sometimes, when an exception is thrown, some Java AWT/Swing classes activate, i.e., I get the characteristic quick window creation flash. I see this as a bug. The K tool should not activate the Java visual interface when it doesn't need it.

@radumereuta said that this is from some coloring package. Afaik, even one usage of certain AWT/Swing classes trigger visual interface activation. I think we should fix this. It is distracting and it looks unprofessional -- you're in the terminal running the tool and suddenly it changes desktops (on mac) in order to show a window flash.

**Comment by dwightguth** [comment]
Are you running from the IDE or the command line? it should be the case
that the scripts turn on headless mode so that you don't see this. If that
is not happening correctly, I would like to know that.

**Comment by cos** [comment]
I'm running unit tests from an IDE -- but they would behave identically from command line. The unit tests set up the minimal "Context" possible. If there is a default regarding "headless" mode, the default should be "headless". By the way, what is the "head" in "headless"?

**Comment by dwightguth** [comment]
It is a jvm option: -Djava.awt.headless=true. It indicates that the
terminal should not have a display associated with it. We pass it on the
command line to the jvm. The reason AWT initialization is taking place is
because of static initalization of the class java.awt.Color, which is
needed for the coloring of the command line. This isn't really a bug, you
just need to pass this flag to the eclipse run configuration.

**Comment by ciobaca** [comment]
The kompile/krun scripts should already include this switch.

Stefan

**Comment by cos** [comment]
hm... could we do `System.setProperty("java.awt.headless", "true")` instead? It's tiring to mess with java command line options for each unit test in the IDE.

Alternatively, `java.awt.Color` could be loaded by reflection only when the color command line options is activated.

**Comment by dwightguth** [comment]
Where exactly would you put that call though, that it would be picked up by
the unit test?

**Comment by cos** [comment]
Maybe in the static initializer of the class that creates the mess in the first place, i.e., the class that imports `java.awt.Color`.

The reflection option may be even cleaner -- it will then be completely tied to the activation of the color output.

**Comment by dwightguth** [comment]
This is a lot harder of a solution than you think for what it gains us.
Static initialization is not guaranteed to occur in any order, and java.awt
caches the value, so it has to happen /before/ the classloader loads the
awt package. And relying on ensuring that a particular class is always
loaded via reflection leaves the system very sensitive to bugs that affect
production, whereas currently this problem only affects developers and only
if they choose not to pass a flag to the jvm.

If you can come up with a solution that addresses these issues, I'll
listen, but right now I am still of the belief that the existing solution
is the best compromise.

**Comment by cos** [comment]
> This is a lot harder of a solution than you think for what it gains us.
> Static initialization is not guaranteed to occur in any order, and java.awt
> caches the value, so it has to happen /before/ the classloader loads the
> awt package.

Fair point.

> And relying on ensuring that a particular class is always
> loaded via reflection leaves the system very sensitive to bugs that affect
> production

To what kind of bugs? The only situation in which java.awt.Color would not be available is if we decide to use a completely different JVM (i.e., not Oracle), which I guess is very unlikely.

**Comment by dwightguth** [comment]
The bug is if you accidentally load any class that loads java.awt.color
without using reflection, then you get the stutter you talk about.

**Comment by andreistefanescu** [comment]
On my mac this happens during `mvn package`.

**Comment by dwightguth** [comment]
If you make an issue and assign it to me I will fix "mvn package" tomorrow
morning.

**Comment by cos** [comment]
@dwightguth, so you mean the reflection solution is sensitive to somebody using the class in some other place and, on that use, we'll get the window flash again. I agree, but this is essentially saying we shouldn't fix a bug because somebody may introduce another similar bug somewhere else. 

Also, if somebody does use `Color` in some other place, we'll realize it annoyingly quickly.

**Comment by dwightguth** [comment]
Cosmin, in fact it is much more like deciding not to try to fix every
instance of a common class of bug because you are able to fix it once for
all time instead.

**Comment by cos** [comment]
yes, but you cannot fix this one once for all time (very few issues can). passing a jvm flag every time any piece of code in the framework gets executed in order for it not to initialize the java visual interface is not really a fix.

Also, I think the issue might be more on our side. Why is the static class initializer of java.awt.Color even touched when I'm doing something not in any way related to the console. I noticed the window flash happens when an exception is thrown. Is the exception-handling code invoking it somehow? If so, can we wrap the reference to Color in a separate class that only gets instantiated when color is enabled for output. Bottom line, there should be solutions.

In any case, it would be nice if whomever created this in the first place takes a look at it. It is not a show-stopper, but it is annoying.

**Comment by dwightguth** [comment]
@cos please reassign to @k-oncall if this bug is still present.
