### ISSUE TITLE
kompile prints error message with wrong variable in it

### ISSUE THREAD

**Issue by osa1** [kframework/k-legacy#990]
```
➜  issue696 git:(java8) ✗ cat test.k 
module TEST

  syntax KResult ::= Bool

  configuration
    <k> ?A:KResult ==K ?B:KResult </k>

endmodule

➜  issue696 git:(java8) ✗ kompile test.k 
[Error] Critical: In the configuration you can only have external variables,
not: 'A' (starts with '$').
        Source: File: /home/omer/K/k_new_dist/k/issue696/test.k
        Location: (6,9,6,19)
```

I think it should have said `starts with '?'`.

Also, what is "external variable"? Maybe it should have said "you can't have existential variables" or something like that instead.

**Comment by dwightguth** [comment]
No, that's correct. This should not be an error. Assign it to Radu.

**Comment by radumereuta** [comment]
I just asked @andreistefanescu and he is not sure if this is what we want, so @grosu  what do you think?
It's a really easy fix if we want to support something like this.

**Comment by grosu** [comment]
Can you guys be more explicit?  I am not sure what @andreistefanescu  means,  And why is he not answering himself?  We definitely want to be able to start with a symbolic configuration.  And even if we don't, the error message is definitely bad.  I agree with @osa1
