### ISSUE TITLE
Taskify unification of Maude and Java substitution

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#994]
I'd like to create a version of the tutorial that works for both the maude and java backends. To do this, we need a substitution module that is the same for both backends. Essentially, it should have an outer interface mapped to a java hook, and a maude implementation loaded by the maude backend.

I would like Traian to take some time to create a list of tasks needed in order to accomplish this. They should be broken down granularly enough that each can be accomplished in order in order to create a discrete series of steps to be taken to accomplish the refactoring.

**Comment by yilongli** [comment]
same for the pattern-matching module
